- pages/popover/scrollable.page.tsx
- src/popover/__tests__/positions.test.ts
- src/popover/utils/positions.ts
Popovers are not allowed to overflow the viewport and are made scrollable if necessary but only when the property `renderWithPortal` is `true` and not otherwise. This PR unifies the behavior and makes popovers scrollable if necessary regardless of whether using a portal or not.
- Unit tests
- Manually tested. Adapted existing page for manual testing
- Ran through my pipeline. One integration test catches the change and the result is expected (the popover is now cropped)
<details> …
> fix: Make popover scrollable when needed also when not using a portal

- src/table/resizer/styles.scss
The `styles.styles-reset` added after the cursor declaration overrode it with "auto". Moving the mixin on top fixes the issue.
<details> …
> fix: Table column resizer to have expected cursor

- src/property-filter/__tests__/property-filter.test.tsx
- src/property-filter/token-editor.tsx
In a recent change to the property filter component the matching logic was updated to compare filtering properties by reference. That does not work though for the token editor with async options because in the editor the property is cached in React state. Then, if the properties are updated as result of the onLoadItems call - the options can no longer be matched.
ref: AWSUI-24057
The issue is reproducible in the existing `async-loading.integ.page.tsx`.  Without the fix there are no suggestions in the token editor. With the fix all suggestions are available.
<details>
- _Changes are backward-compatible if not indicated, …
> fix: Property filter token editor match by key

- src/popover/__integ__/popover-placement.test.ts
- src/popover/utils/positions.ts
closes #1719
* Locally
* Screenshot tests in my dev pipeline
<details> …
> fix: Improve alignment for popover in extreme right/left positions

- src/date-picker/__tests__/date-picker-calendar.test.tsx
- src/date-picker/__tests__/date-picker.test.tsx
Test utils was updated to do this by default. It is no longer required in our tests.
Existing unit tests still pass.
<details> …
> chore: Remove unnecessary use of act in date picker tests

- src/internal/analytics/__integ__/static-multi-page-create.test.ts
- src/internal/analytics/__integ__/static-single-page-flow.test.ts
- src/internal/analytics/__tests__/hooks/use-funnel-step.test.tsx
- src/internal/analytics/components/analytics-funnel.tsx
- src/internal/analytics/context/analytics-context.ts
- src/internal/analytics/hooks/use-funnel.ts
- src/internal/analytics/interfaces.ts
This PR fixes a bug that occurs in some usages of funnel events.
When the user has the browser focus on an input element in a Wizard and then clicks on the "Next" button, the Wizard proceeds to the next step before emitting the `subStepComplete` event. At that point, the CSS selector that was used to identify the substep's index does not point to valid/useful elements anymore.
With this change, instead of the CSS selectors we use the `subStepConfiguration` for determining the correct substep number, and include that number in the event data. The `subStepConfiguration` is updated every time a substep is mounted or unmounted.
Added an integration test
<details> …
> fix: Include substep number in subStepComplete event

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/app-layout/interfaces.ts
- src/pagination/interfaces.ts
In two of our examples in the inline code comments, the code examples were missing a comma.
n/a
<details> …
> chore: Add missing commas in documentation

- src/form/__tests__/analytics.test.tsx
- src/form/index.tsx
- src/internal/analytics/__integ__/static-single-page-flow.test.ts
A regression was introduced in this [PR](https://github.com/cloudscape-design/components/commit/7fa1db81e78164671003df2c78c02d1b865e7011#diff-cf319f69cf00076c2f61b37cf74d218c8925885695b31a060421fa9cc79c7e13) where I moved the context provider 1 level down. This was a mistake and I don't know why I did it :( 
<details> …
> chore: Fix Form step context not adding step data attribute

- src/i18n/messages/all.de.json
- src/i18n/messages/all.en-GB.json
- src/i18n/messages/all.en.json
- src/i18n/messages/all.es.json
- src/i18n/messages/all.fr.json
- src/i18n/messages/all.id.json
- src/i18n/messages/all.it.json
- src/i18n/messages/all.ja.json
- src/i18n/messages/all.ko.json
- src/i18n/messages/all.pt-BR.json
- src/i18n/messages/all.tr.json
- src/i18n/messages/all.zh-CN.json
- src/i18n/messages/all.zh-TW.json
Fixing the text according to our writing guidelines
Related links, issue #, if available: AWSUI-24340
Locally
<details>
- _If the code …
> fix: Update built-in s3 resource selector i18n strings

- pages/flashbar/interactive.page.tsx
- src/flashbar/__integ__/collapsible.test.ts
- src/flashbar/__integ__/focus-interactions.test.ts
- src/flashbar/__integ__/pages/interactive-page.ts
- src/flashbar/__tests__/flashbar.test.tsx
- src/flashbar/flash.tsx
- src/internal/components/live-region/__tests__/live-region.test.tsx
- src/internal/components/live-region/index.tsx
- src/internal/components/screenreader-only/index.tsx
This fixes a bug where interactive content of the flashbar would be rendered twice, which leads to duplicated tab stops if the content contains interactive elements like links.
Instead of duplicating the content into the LiveRegion, the flashbar now provides references to the existing content.
Related links, issue #, if available: AWSUI-24287
Tested in a dev page, with VoiceOver
<details> …
> fix: Flashbar renders invisible interactive content

- src/anchor-navigation/use-scroll-spy.tsx
- src/table/__integ__/resizable-columns.test.ts
- src/table/__tests__/columns-width.test.tsx
- src/table/__tests__/resizable-columns.test.tsx
- src/table/column-widths-utils.ts
- src/table/internal.tsx
- src/table/sticky-columns/use-sticky-columns.ts
- src/table/thead.tsx
- src/table/use-column-widths.tsx
- src/table/use-sticky-header.ts
Revert because of the issue: AWSUI-24456
Reverts cloudscape-design/components#1718
> revert: Last table resizable column stable width in React 18

- src/table/__tests__/resizable-columns.test.tsx
- src/table/header-cell/index.tsx
- src/table/header-cell/styles.scss
- src/table/header-cell/th-element.tsx
- src/table/resizer/index.tsx
- src/table/resizer/styles.scss
- src/table/thead.tsx
Removing `::before` selectors from table header cell styles because the same is used by the focus-highlight mixin. Assigning different styles for `::before` may produce unexpected results. The change is needed to support the upcoming keyboard navigation feature that makes table body- and header- cells focusable. It also fixes an existing bug: when the resizer is focused with keyboard and then hovered over the styles collide:
https://github.com/cloudscape-design/components/assets/20790937/d5e3438f-0362-45a2-9185-3a834cbca513
* Existing unit tests now cover the presence of the divider;
* Manual testing for sticky cell styles hiding resize separator conditionally;
* Screenshot tests.
<details>
_The following items are to be evaluated by the author(s) and …
> refactor: Update resizer styles to avoid ::before selector

- src/__a11y__/to-validate-a11y.ts
- src/__tests__/test-a11y-validator.test.tsx
Resolving a pending "TODO" comment about `no-redundant-for` in a11y tests:
```
//TODO: revisit 'no-redundant-for' when fixing AWSUI-18968
```
<details> …
> chore: Remove unnecessary 'no-redundant-for' in a11y tests

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/collection-preferences/interfaces.ts
- src/table/interfaces.tsx
The documentation in Table and Collection preferences don't talk much about how `contentDisplay` has replaced `visibleColumns` in table (not cards). To make this clear, we're adding a few more bits of documentation.
Next step: deprecate `visibleContentPreference` in Cards as well.
Related links, issue #, if available: AWSUI-22308
<details> …
> chore: Improve documentation for contentDisplay and visibleColumns

- src/__integ__/themes.test.ts
- src/app-layout/__integ__/app-layout-refresh-content-width.test.ts
- src/app-layout/__integ__/app-layout-refresh-edge-controls.test.ts
- src/app-layout/__integ__/app-layout-refresh-notifications.test.ts
- src/tabs/__integ__/tabs-in-help-panel.test.ts
- src/tabs/__integ__/tabs.test.ts
We already force disabled motion in our browser setup: https://github.com/cloudscape-design/browser-test-tools/blob/cf77d3f913826dd0083eadeef0dd8df6ac6a3ab8/src/browsers/local.ts#L19-L23
No need for the extra query parameter, it does nothing.
PR build
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#brows …
> chore: Remove redundant motion disabled parameters

- src/app-layout/__integ__/app-layout-refresh-content-width.test.ts
- src/app-layout/visual-refresh/layout.scss
This change makes pages that have contentType=“table” or “cards” set on the App Layout take up 100% of the available width. Previously, all pages in VR had a constrained max-width, however we are updating this in response to user feedback via the internal availability program. The change in behavior was also tested and confirmed in the info density usability study conducted this quarter.
Related links, issue #, if available: AWSUI-19992
Ran through my dev pipeline
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md …
> chore: Make table and card content types span full width

- pages/button/performance-marks.page.tsx
- pages/table/performance-marks.page.tsx
- src/button/__integ__/performance-marks.test.ts
- src/button/internal.tsx
- src/internal/hooks/use-performance-marks.ts
- src/table/__integ__/performance-marks.test.ts
- src/table/internal.tsx
This change adds performance marks to the Button and Table component. These marks are created when the component is first rendered, and when properties of the component (e.g. `loading` or `disabled`) change.
Added integration tests. I did not add unit tests, since JSDOM does not support the necessary performance APIs.
<details> …
> chore: Emit performance marks for button and table

- src/internal/components/selectable-item/__tests__/selectable-item.test.tsx
- src/select/parts/multiselect-item.tsx
Before this change, when rendering the dropdown options in src/select/utils/render-options.tsx `highlightType` allowed to pass either `HighlightType` or `HighlightType['type']`. When rendering the Multiselect component, `HighlightType` was set while other components set the HighlightType['type'].
As part of this PR I de-duplicated the item prop interface of `ItemProps` and `MultiselectItem` to make the type checking more strict and highlight such issues.
Before:
https://github.com/cloudscape-design/components/assets/569011/961e882b-dbe2-42eb-8a80-37f113a4eba8
After:
https://github.com/cloudscape-design/components/assets/569011/91bbf8f8-d43b-4ec8-bb90-a4c2c82e443c
Related links, issue #, if available: AWSUI-24820
- Manually tested in supported browsers.
- Open the Select and Multiselect …
> fix: Fix is-keyboard selector in multiselect dropdown

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/button-dropdown/interfaces.ts
- src/button/interfaces.ts
- src/popover/interfaces.ts
- src/select/interfaces.ts
Updated descriptions for aria label properties assigned to controls to be better consistent and better inline with our guidelines.
<details> …
> chore: Use consistent aria label descriptions for API docs

- src/internal/analytics/components/analytics-funnel.tsx
dispatch the event to the top window, because the listener is attached to top window. 
<details> …
> fix: Dispatch create edit flow event to top window

- src/internal/hooks/use-scroll-sync/__tests__/use-scroll-sync.test.tsx
- src/internal/hooks/use-scroll-sync/index.ts
When render a Select in the horizontally scrollable Table, and the Select is vertically scrollable. When scrolling the Select, Table scroll to the left unexpectedly (see screen recording in the ticket). 
It is because the scroll event in the Select Portal is propagated to the Table. 
Using `event.target` takes the scrollLeft of the Dropdown in the Select(which is 0) and assign to Table scrollLeft. It causes the issue. 
The change uses `currentTarget`, which is the element where the event is attached to, in this case should be the Table itself, to calculate the scrollLeft.
Related links, issue #AWSUI-24387
Added unit test, also tested manually with the table. 
<details>
- …
> fix: Scroll child element makes table unexpectedly scroll

- pages/table/resizable-columns.page.tsx
- src/anchor-navigation/use-scroll-spy.tsx
- src/table/__integ__/resizable-columns.test.ts
- src/table/__tests__/columns-width.test.tsx
- src/table/__tests__/resizable-columns.test.tsx
- src/table/column-widths-utils.ts
- src/table/internal.tsx
- src/table/sticky-columns/use-sticky-columns.ts
- src/table/thead.tsx
- src/table/use-column-widths.tsx
- src/table/use-sticky-header.ts
Re-introduction of https://github.com/cloudscape-design/components/pull/1718 but with a fix to default column IDs.
New integration tests to secure regression.
<details> …
> fix: Last table resizable columns stable with React 18 (#2)

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/app-layout/interfaces.ts
- src/app-layout/utils/use-drawers.ts
Create and export `DrawerChangeDetail` type so users could import it from `AppLayoutProps`, also so the type could appear properly on the documentation website instead of `unknown` https://cloudscape.design/components/app-layout/#events 
updated documentation snapshot
<details>
- …
> fix: Export DrawerChangeDetail type from AppLayoutProps

- src/app-layout/visual-refresh/context.tsx
in `AppLayout` when `splitPanel` slot is `null` and `splitPanelOpen` is `true` bottom offset is added to the page, ideally users should provide the component with the proper state however this used to work in the old version of `AppLayout` so for backward compatibility we'll need to support this case in the new `AppLayout`
Related links, issue #, if available: AWSUI-24603
[in this example](https://github.com/cloudscape-design/components/blob/main/pages/app-layout/with-split-panel.page.tsx#L77) set `splitPanel` to `null` and `splitPanelOpen` to `true`
I'm not sure if there is a proper way to test this, it doesn't seem like a case worth adding a screenshot test for
<details>
- …
> fix: Remove bottom offset when there is no SplitPanel in AppLayout and splitPanelOpen is true

- src/internal/components/selectable-item/styles.scss
Fix the issue that the hover state (highlighted) of style was not visible.
<details>
- _If …
> fix: Fix the selected and highlighted state of style

- pages/app-layout/with-one-open-drawer.page.tsx
- src/app-layout/__tests__/drawers.test.tsx
- src/app-layout/drawer/index.tsx
- src/app-layout/drawer/resizable-drawer.tsx
In classic mode aria-controls was pointing to a non-existent id, cause it wasn't passed from parent
Related links, issue #, if available: AWSUI-25664
new unit test added
<details> …
> fix: Add missing drawer id

- src/column-layout/grid-column-layout.tsx
- src/flashbar/collapsible-flashbar.tsx
- src/internal/animate.ts
- src/mixed-line-bar-chart/__tests__/utils.test.ts
- src/mixed-line-bar-chart/bar-series.tsx
- src/mixed-line-bar-chart/utils.ts
- src/table/sticky-columns/__tests__/use-sticky-columns.test.tsx
- src/table/sticky-columns/interfaces.ts
- src/table/sticky-columns/use-sticky-columns.ts
- src/table/sticky-columns/utils.ts
The refactoring is made to prevent issues similar to one occurred recently in table resizable columns: https://github.com/cloudscape-design/components/pull/1745#discussion_r1398860225
The PR covers part of the codebase, related PRs: https://github.com/cloudscape-design/components/pull/1806, https://github.com/cloudscape-design/components/pull/1807, https://github.com/cloudscape-design/components/pull/1808.
Existing tests
<details> …
> refactor: Replace records having numeric keys with maps, part 1

- src/internal/components/masked-input/__tests__/utils/mask-format.test.ts
- src/internal/components/masked-input/utils/mask-format.ts
- src/internal/hooks/use-date-cache/index.ts
The refactoring is made to prevent issues similar to one occurred recently in table resizable columns: https://github.com/cloudscape-design/components/pull/1745#discussion_r1398860225
The PR covers part of the codebase, related PRs: https://github.com/cloudscape-design/components/pull/1801, https://github.com/cloudscape-design/components/pull/1807, https://github.com/cloudscape-design/components/pull/1808.
<details> …
> refactor: Replace records having numeric keys with maps, part 2

- src/table/internal.tsx
- src/table/thead.tsx
- src/table/use-column-widths.tsx
The refactoring is made to prevent issues similar to one occurred recently in table resizable columns: https://github.com/cloudscape-design/components/pull/1745#discussion_r1398860225
The PR covers part of the codebase, related PRs: https://github.com/cloudscape-design/components/pull/1801, https://github.com/cloudscape-design/components/pull/1806, https://github.com/cloudscape-design/components/pull/1808.
<details> …
> refactor: Replace records having numeric keys with maps, part 3

- src/column-layout/grid-column-layout.tsx
- src/flashbar/collapsible-flashbar.tsx
- src/internal/animate.ts
- src/mixed-line-bar-chart/__tests__/utils.test.ts
- src/mixed-line-bar-chart/bar-series.tsx
- src/mixed-line-bar-chart/utils.ts
- src/table/sticky-columns/__tests__/use-sticky-columns.test.tsx
- src/table/sticky-columns/interfaces.ts
- src/table/sticky-columns/use-sticky-columns.ts
- src/table/sticky-columns/utils.ts
This reverts commit 419f2f5bb7bf2a1630a553ffcf1d018871494d66.
There is a regression for this use-case `<ColumnLayout columns="4" />`
n/a
<details> …
> revert: Replace records having numeric keys with maps, part 1 (#1801)"

- src/mixed-line-bar-chart/__integ__/mixed-line-bar-chart.test.ts
An integration test had two errors:
- The text content that it was checking for was incorrect
- The second parameter passed to `test` was a function calling `setupTest` inside, instead of the result of calling `setupTest` directly. This was making the test pass unconditionally because the function is not run, despite the other error above.
Looked for other possible cases like this in the same component, found none.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public- …
> chore: Fix integration test for chart popover focus

- pages/mixed-line-bar-chart/in-modal.page.tsx
- src/mixed-line-bar-chart/__integ__/mixed-line-bar-chart.test.ts
- src/mixed-line-bar-chart/styles.scss
In bar chart the segments were not highlighted with mouse when the chart is rendered inside popover. The root cause is that the condition `event.target === plotRef.current!.svg` in mouse handler was false when hovering over the invisible bar series rects. When the chart is rendered inside modal those act as hover targets despite being invisible.
Rel: AWSUI-25950
New integration test, screenshot tests. Manual testing confirms the issue was only reproducible in the bar chart. The area-, line-, and pie charts are unaffected.
<details> …
> fix: Bar chart to show popover when inside modal

- pages/mixed-line-bar-chart/in-tabs.page.tsx
- src/internal/components/chart-popover/index.tsx
- src/mixed-line-bar-chart/__integ__/mixed-line-bar-chart.test.ts
When charts are rendered inside tabs the blur target resolves to tabs content which is not inside the chart. As result, the chart's state is cleaned up and the popover is closed.
Rel: AWSUI-25756
New integration test.
<details> …
> fix: Fix clicking inside chart popovers when rendered inside tabs

- pages/table-fragments/grid-navigation-custom.page.tsx
- pages/table-fragments/grid-navigation-performance.page.tsx
- src/table/table-role/__tests__/use-grid-navigation.test.tsx
- src/table/table-role/grid-navigation.tsx
- src/table/table-role/index.ts
- src/table/table-role/interfaces.ts
The grid navigation is an upcoming table feature. It is to be reimplemented with React contexts, see: https://github.com/cloudscape-design/components/pull/1760, KtAVARsTM7ko, 5uPHAylzAuFG.
The explicit suppression API is not yet needed and is therefore removed. The code structure is changed to feature render-prop component (provider) instead of the hook. That is to minimise difference when introducing the React context.
<details>
- _Changes …
> refactor: Remove unneeded API from grid navigation and refactor code structure

- src/i18n/messages-types.ts
- src/i18n/messages/all.de.json
- src/i18n/messages/all.en-GB.json
- src/i18n/messages/all.en.json
- src/i18n/messages/all.es.json
- src/i18n/messages/all.fr.json
- src/i18n/messages/all.id.json
- src/i18n/messages/all.it.json
- src/i18n/messages/all.ja.json
- src/i18n/messages/all.ko.json
- src/i18n/messages/all.pt-BR.json
- src/i18n/messages/all.th.json
- src/i18n/messages/all.tr.json
- src/i18n/messages/all.zh-CN.json
- src/i18n/messages/all.zh-TW.json
Synchronizing translation strings. The big change is the introduction of the `all.th.json` file. But there are also other changes included, like fixes for units in date range picker and one new string for the copy to clipboard component.
Related links, issue #, if available: AWSUI-26332
Only copy to clipboard needs new tests, but it's best to bundle that with the component changes.
<details> …
> feat: Add "th" locale

- pages/table-fragments/grid-navigation-custom.page.tsx
- src/table/table-role/__integ__/grid-navigation.test.ts
- src/table/table-role/__integ__/page-object.ts
- src/table/table-role/__tests__/grid-navigation.test.tsx
- src/table/table-role/__tests__/stubs.tsx
- src/table/table-role/__tests__/table-role-helper.test.ts
- src/table/table-role/grid-navigation.tsx
- src/table/table-role/table-role-helper.ts
- src/table/table-role/utils.ts
Use simpler grid navigation implementation (no mutation observer and a single variable to keep focused cell) based on https://github.com/cloudscape-design/components/pull/1750 to prepare for the register-based implementation based on https://github.com/cloudscape-design/components/pull/1760.
New integration tests, reworked unit tests.
<details> …
> refactor: Simpler grid navigation implementation

- src/table/table-role/grid-navigation.tsx
- src/table/table-role/utils.ts
Restructuring code to reduce diff in the upcoming update. The findFocusedCell, getNextFocusable, and ensureSingleFocusable are moved inside the processor to inject a dependency on registered components, see: https://github.com/cloudscape-design/components/pull/1760
Existing tests
<details> …
> refactor: Restructure table grid navigation utils

- src/toggle/styles.scss
Ensure that toggle graphics are visible in forced-color mode. Previously they weren't, because the component relies purely on background color to "draw" the control, and forced-color overrides all background colors.
Related links, issue #, if available: AWSUI-24890
Tested locally by emulating forced-color mode in Chrome
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blo …
> fix: Ensure toggle is visible in high-contrast/forced-color mode

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/app-layout/interfaces.ts
AppLayout API tab did not include specifics around DrawerTrigger or DrawerAriaLabels. This updates the comment so that the API tab shows them.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/a …
> fix: Updates drawer comments so it shows on API tab

- .github/workflows/visuals.yml
With this PR, you can review BackstopJS screenshot test report with one click. See the latest deployment.
This works: https://d21d5uik3ws71m.cloudfront.net/components/ccba6e21aeeac824d9e090aeef3c7108de0b26eb/visual-regressions/index.html
<details> …
> chore: add screenshot tests report deployment

- pages/table/permutations.page.tsx
- src/table/styles.scss
This reverts commit f27444b90511cf402bb59a5fa200ad08dac4f14b.
<details>
- _If the code …
> revert: "fix: Use border radius design token for column headers in sticky header table (#1857)"

- src/container/styles.scss
We discovered that there is a small gap in rounded corner sizes in Container with media variant.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/acces …
> fix: Fixed rounded corner misalignment in media container

- src/tabs/__tests__/tabs.test.tsx
- src/tabs/index.tsx
The Tabs component used its own algorithm for generating IDs, which did not support server-side rendering. This led to inconsistent IDs between the server-generated HTML and the hydrated HTML.
This PR replaces that algorithm with our central hook for generating IDs, which uses React's `useId` hook (when available).
Related links, issue #, if available: https://github.com/cloudscape-design/components/issues/1834
<details> …
> fix: Tabs generates unstable IDs

- src/app-layout/__tests__/drawers.test.tsx
- src/app-layout/__tests__/utils.tsx
- src/app-layout/index.tsx
- src/app-layout/visual-refresh/context.tsx
This is a fallback for a situation when app layout has both tools and drawers set. Tools panel won't be rendered, if drawers are present. The fallback logic of rendering tools content as a drawer already exists (somewhere), but existing focus management logic doesn't work at the moment.  
Related links, issue #, if available: AWSUI-26132
new unit test added
<details> …
> feat: Handle drawers focus when focusTools is fired 

- src/internal/analytics/components/analytics-funnel.tsx
This code should not fire when component is already unmounted. 
The current behavior causes issues in tests for our consumers
Related links, issue #, if available: AWSUI-26406
Is there a way to tear down the document in Jest? I do not think so.
<details> …
> fix: Fix funnel handling when component is already unmounted

- pages/button/show-more.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/button/__tests__/button.test.tsx
- src/button/index.tsx
- src/button/interfaces.ts
- src/button/internal.tsx
Expose `aria-controls` on button.
We already exposed `aria-expanded` (see [PR](https://github.com/cloudscape-design/components/pull/16)), which is often accompanied with `aria-controls` to indicate a relationship between elements.  It'll allow to create a correct markup for custom components.
Related links, issue #, if available: AWSUI-23016
Unit test added
<details> …
> feat: Add aria-controls to Button

- src/internal/components/chart-series-details/index.tsx
- src/internal/components/chart-series-details/styles.scss
- src/pie-chart/pie-chart.tsx
Add space of 4px (`space-scaled-xxs`) between list items in chart popovers for bar, line, mixed and area charts (but not pie and donut charts).
See AWSUI-28805
- Manually verified all affected chart types, including the metric drilldown feature (expandable and non-expandable) when applicable
- Visual regression tests exist
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/ …
> fix: Increase space between chart popover list items

- src/internal/components/chart-plot/__tests__/chart-plot.test.tsx
- src/internal/components/chart-plot/application-controller.tsx
The timeout seems to not be necessary anymore and led to a race condition in Safari, which would cause the area chart popover dismiss button to lose focus after the changes in #1804, which had to be reverted for that reason.
- Manually tested with Firefox, Chrome and Safari.
- Tested VoiceOver+Firefox myself, and @pan-kot kindly tested NVDA+Firefox as well.
- Deployed to my pipeline together with the changes in #1804.
<details> …
> chore: Remove unnecessary timeout in Chart plot application re-attachment logic

- src/bar-chart/__tests__/chart-series-details.test.tsx
- src/internal/components/chart-popover/index.tsx
- src/internal/components/dropdown/dropdown-fit-handler.ts
- src/internal/utils/__tests__/scrollable-containers.test.ts
- src/internal/utils/scrollable-containers.ts
- src/line-chart/__tests__/chart-series-details.test.tsx
- src/mixed-line-bar-chart/__integ__/mixed-line-bar-chart.test.ts
- src/mixed-line-bar-chart/__tests__/chart-series-details.test.tsx
- src/mixed-line-bar-chart/chart-container.tsx
- src/popover/__tests__/positions.test.ts
- src/popover/container.tsx
- src/popover/interfaces.ts
- src/popover/use-popover-position.ts
- src/popover/utils/positions.ts
This is an exact copy of #1804, which had to be reverted because of a race condition that was fixed by #1884.
Ran these changes together with #1884 in my pipeline.
<details> …
> fix: Prevent chart popovers from overflowing horizontally

- src/internal/components/option/__tests__/option.test.tsx
- src/internal/components/option/highlight-match.tsx
Quick fix for a rare case. Imagine pasting a 100,000 character string into the autosuggest component 😨 
Tested manually on Chrome and Firefox as well.
Related links, issue #, if available: P112982985
Added a test case.
<details> …
> fix: Prevent filtering highlighting from crashing when match is too long

- src/internal/analytics/__tests__/components/analytics-funnel.test.tsx
- src/internal/analytics/components/analytics-funnel.tsx
Update logic for better semantics
PR build
<details> …
> chore: Do not call creation-edit-flow-done event when funnel cancels

- src/__tests__/__snapshots__/design-tokens.test.ts.snap
- style-dictionary/visual-refresh/metadata/colors.ts
Recently we added new token for focused states of form inputs. Token that was used to set border color previously is public and themeable, we're adding the same functionality to the new one.
Related links, issue #, if available: -
-
<details> …
> feat: Make color-border-input-focused token themeable

- pages/app/app-context.tsx
- pages/app/index.html
- pages/app/index.tsx
- src/app-layout/visual-refresh/background.tsx
- src/app-layout/visual-refresh/breadcrumbs.tsx
- src/app-layout/visual-refresh/header.tsx
- src/app-layout/visual-refresh/mobile-toolbar.scss
- src/app-layout/visual-refresh/mobile-toolbar.tsx
- src/app-layout/visual-refresh/notifications.tsx
- src/container/internal.tsx
- src/content-layout/internal.tsx
- src/internal/components/dark-ribbon/index.tsx
- src/internal/utils/__tests__/global-flags.test.ts
- src/internal/utils/content-header-utils.ts
- src/internal/utils/global-flags.ts
- src/split-panel/icons/bottom-icon-refresh.tsx
- src/split-panel/icons/side-position-refresh.tsx
- src/table/internal.tsx
- src/wizard/internal.tsx
- src/wizard/wizard-form-header.tsx
- Addition of global flags
- Addition of first global flag to remove high-contrast header
Locally
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._ Yes …
> feat: Introduce flag to remove high-contrast header

- src/internal/context/__tests__/utils.tsx
- src/internal/context/single-tab-stop-navigation-context.tsx
- src/table/table-role/grid-navigation.tsx
- src/table/table-role/interfaces.ts
- src/table/table-role/utils.ts
Refactored grid navigation and single tab stop navigation context for better performance. The main change is that the focusables are registered as elements rather than element references. That makes the overall process simpler and removes the need to iterate over focusables to transform a set of refs into a set of elements.
Existing tests
<details> …
> refactor: Better efficient grid navigation

- src/internal/styles/utils/styles-reset.scss
- src/table/body-cell/styles.scss
This PR sets the `text-align` property to a flow relative value in order to respond to the direction of the document subtree.
> chore: Update the styles reset mixin to use flow relative text alignment

- .github/workflows/bundle-size.yml
When 3rd party dependencies are added or updated the measure-bundle job should use the updated node_modules. The issue was spotted here: https://github.com/cloudscape-design/components/pull/1842
<details> …
> chore: Fix bundle size script to account for new dependencies

- src/app-layout/visual-refresh/mobile-toolbar.scss
Fixed incorrect application of a design token. Follow up for #1896
Locally, it has no changes in our standard themes. It is only an issue when using a custom theme
<details> …
> fix: update design token used in mobile app layout bar

- src/app-layout/visual-refresh/background.tsx
- src/app-layout/visual-refresh/breadcrumbs.tsx
- src/app-layout/visual-refresh/header.tsx
- src/app-layout/visual-refresh/mobile-toolbar.tsx
- src/app-layout/visual-refresh/notifications.tsx
- src/app-layout/visual-refresh/trigger-button.tsx
- src/cards/index.tsx
- src/container/internal.tsx
- src/content-layout/__tests__/content-layout.test.tsx
- src/content-layout/internal.tsx
- src/internal/components/dark-ribbon/index.tsx
- src/internal/utils/content-header-utils.ts
- src/split-panel/icons/bottom-icon-refresh.tsx
- src/split-panel/icons/side-position-refresh.tsx
- src/table/internal.tsx
- src/wizard/internal.tsx
- src/wizard/wizard-form-header.tsx
- src/wizard/wizard-navigation.tsx
Caching the value of the global flag makes its evaluation dependent on the order in which bundles are loaded and evaluated. This change prevents that from happening.
Unit test
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._ No …
> fix: Make removal of high-contrast header independent of bundling

- src/expandable-section/styles.scss
Fixing a bug in expandable section when default focus outline is shown when clicking on expandable header after focusing on it with the keyboard.
Ref: AWSUI-30684
Before:
https://github.com/cloudscape-design/components/assets/20790937/abf0de6c-5c1d-4ee3-a0ef-bc29dcf88232
After:
https://github.com/cloudscape-design/components/assets/20790937/2e248ed6-8699-418c-b51b-42f97e19f65d
<details> …
> fix: Remove native focus outline from expandable section button

- src/button-dropdown/item-element/index.tsx
Fixing a regression from https://github.com/cloudscape-design/components/pull/1902
In Classic the dropdown has no border so relying on the item borders.
<details> …
> fix: Fix button-dropdown bottom border for non-VR

- src/container/styles.scss
Quick fix for a regression introduced in https://github.com/cloudscape-design/components/pull/1896
The new element is preventing header clicks when there is scroll.
https://github.com/cloudscape-design/components/assets/20790937/76c72afe-752e-46c8-b879-cda88cd9ac8c
Ref: AWSUI-31054
Manual testing using `/full-page-table-with-variable-header-height` test page
<details> …
> fix: Fix content header pointer events

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/code-editor/__tests__/code-editor.test.tsx
- src/code-editor/__tests__/preferences-modal.test.tsx
- src/code-editor/index.tsx
- src/code-editor/interfaces.ts
This is something we're supposed to do for all components - this is just one I missed.
Related links, issue #, if available: AWSUI-31051
Unit test. Maybe a little unnecessary, but why not.
<details> …
> fix: Allow i18nStrings for code editor to be partially provided

- .stylelintrc
- src/table/body-cell/styles.scss
- src/table/header-cell/styles.scss
- src/table/resizer/styles.scss
- src/table/selection/styles.scss
- src/table/sticky-scrollbar/styles.scss
- src/table/styles.scss
- src/tabs/styles.scss
- src/tabs/tab-header-bar.scss
- src/text-content/styles.scss
- src/text-filter/styles.scss
- src/textarea/styles.scss
- src/tiles/styles.scss
- src/toggle/styles.scss
- src/token-group/styles.scss
- src/top-navigation/1.0-beta/styles.scss
- src/top-navigation/styles.scss
- src/tutorial-panel/components/tutorial-detail-view/styles.scss
- src/tutorial-panel/components/tutorial-list/styles.scss
- src/tutorial-panel/styles.scss
- src/wizard/styles.scss
This PR is a subset of the changes drafted in https://github.com/cloudscape-design/components/pull/1713 that affect only the subset of components that being with the letters "T/U/V/W/X/Y/Z".
> chore: Migrate "T/U/V/W/X/Y/Z" components to logical properties

- src/calendar/__tests__/calendar.test.tsx
- src/calendar/grid/index.tsx
In the Calendar, the item representing the current day (i.e, today, regardless whether it is selected or not), is labeled with the date (e.g, `February 12, 2024`) and the `todayAriaLabel` (e.g, `Today`), separated by a dot and a space, like this: `February 12, 2024. Today`. However, if the `todayAriaLabel` happens to not be provided, the resulting ARIA label was `February 12, 2024. undefined`.
This change handles this more gracefully by just not appending the second part and leaving the ARIA label as `February 12, 2024` if the `todayAriaLabel` is not provided.
Noticed while working on #1942.
- New unit test. Verified that it failed before the change
- Manually verified by inspecting the element in the `calendar/simple` dev page
<details>
_The following …
> fix: Append `todayAriaLabel` in Calendar only if it is provided

- src/date-range-picker/index.tsx
- src/internal/context/app-layout-context.ts
- src/internal/context/link-default-variant-context.ts
- src/internal/context/reset-contexts-for-modal.tsx
- src/internal/context/single-tab-stop-navigation-context.tsx
- src/modal/__tests__/modal.test.tsx
- src/modal/internal.tsx
- src/popover/internal.tsx
- src/table/__tests__/a11y.test.tsx
This ensures contexts are consistently reset across different modal-type components, both now and hopefully more so in the future.
Amongst other possible edge cases, this fixes a known bug in Table where a Modal in the `header` slot can
override the table's implicit aria label.
Tested locally
<details> …
> fix: Ensure contexts are consistently reset in different modal-type environments

- src/calendar/__tests__/calendar.test.tsx
Moving across months by using the previous month and next month buttons in the Calendar header was not covered by tests.
Added two unit tests, one for navigating to the previous month and one for navigating to the next month.
<details> …
> test: Add unit test coverage for calendar header buttons

- src/autosuggest/__tests__/i18n.test.tsx
- src/autosuggest/internal.tsx
Augments the existing AutoSuggest `enteredTextLabel` check to also check whether the built-in i18n provider is in use so that it no longer provides false positive warnings when using the provider.
Ran into this issue and thought I'd fix it to prevent it from confusing others.
* Fixes #1926
Added two new unit tests for ensuring desired behaviors:
1. The existing warning is ***still*** triggered when `enteredTextLabel` is undefined and the i18n provider is not in use.
2. No warnings are triggered when `enteredTextLabel` is undefined and the i18n provider is in use.
```sh
npx jest -c jest.unit.config.js src/autosuggest/__tests__/i18n.test.tsx
```
<details>
_The following items are to be evaluated by the author(s) …
> fix: Autosuggest warning for undefined enteredTextLabel when using built-in i18n

- src/autosuggest/__tests__/i18n.test.tsx
- src/autosuggest/internal.tsx
Further augments the existing AutoSuggest `enteredTextLabel` check from #1966 to also check whether the built-in i18n provider is in use and configured properly so that it no longer provides false positive warnings when using the provider correctly.
https://github.com/cloudscape-design/components/pull/1966#discussion_r1490853524
Related links, issue #, if available: #1926 
Augmented my previous two new unit tests for ensuring desired behaviors and added two more for testing that the provider is configured properly.
```sh
npx jest -c jest.unit.config.js src/autosuggest/__tests__/i18n.test.tsx
```
<details>
- _Changes are …
> fix: Autosuggest enteredTextLabel required iteration

- src/autosuggest/autosuggest-option.tsx
- src/autosuggest/internal.tsx
- src/autosuggest/options-controller.ts
- src/autosuggest/options-list.tsx
- src/autosuggest/plain-list.tsx
- src/autosuggest/virtual-list.tsx
- src/property-filter/property-filter-autosuggest.tsx
Remove code duplication. Now the warning is printed in the place where the value is actually used
PR build passes. Test for the warning has been already added here: https://github.com/cloudscape-design/components/pull/1966
<details>
- _Changes …
> refactor: Move entered text label check to the actual use

- src/table/table-role/__tests__/table-role-helper.test.ts
- src/table/table-role/table-role-helper.ts
The table wrapper when scrollable must be always focusable.
<details> …
> fix: Table wrapper is scrollable regardless of table role

- src/internal/styles/direction.scss
An [issue is reported in autoprefixer](https://github.com/postcss/autoprefixer/issues/1391) when using the `@supports` query with a pseudo-class. This PR will temporarily remove the use of the `:dir()` pseudo-class in the `with-direction` mixin and instead use on the `dir` attribute selector.
> chore: Temporarily remove @supports query for :dir() pseudo-class.

- src/button/__tests__/internal.test.tsx
- src/button/internal.tsx
- src/button/styles.scss
- src/tabs/__integ__/tabs.test.ts
- src/tabs/tab-header-bar.tsx
After reaching the end of the tabs list, focus ring gets lost, because previous / next button becomes disabled. It's confusing for users, that's why we want to keep the focus ring while still communicating that button is disabled.
Related links, issue #, if available: AWSUI-30507
* Manually with VO+Chrome 
* New unit test for internal button
<details> …
> fix: Keep previous/next button focused when they are disabled

- src/app-layout/__tests__/common.test.tsx
- src/app-layout/__tests__/desktop.test.tsx
- src/app-layout/__tests__/drawers.test.tsx
- src/app-layout/__tests__/mobile.test.tsx
- src/app-layout/__tests__/runtime-drawers.test.tsx
- src/app-layout/__tests__/utils.tsx
- src/app-layout/index.tsx
Still removing beta API from our code. Previous PR: https://github.com/cloudscape-design/components/pull/1955
The source code will be removed in the next batch along with [this dev page](https://github.com/cloudscape-design/components/blob/main/pages/app-layout/with-beta-drawers.page.tsx)
PR build
<details> …
> chore: Remove beta drawer API from app layout unit tests

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/app-layout/interfaces.ts
We do not support this browser in any way, no need for special notes.
Checked all other documentation texts, this is the only one remaining
n/a
<details> …
> chore: remove Internet Explorer mention from the API documentation

- backstop/.puppeteerrc.cjs
- backstop/package-lock.json
- backstop/package.json
Override baseURL for Chrome downloads until BackstopJS updates their dependency version of Puppeteer.
```
npm --prefix backstop install ./backstop
```
<details> …
> chore: Set Puppeteer base download URL for BackstopJS

- src/internal/styles/direction.scss
This PR modifies the change made in #1980 due to an autoprefixer limitation. Direction detection will by implemented exclusively by the `:dir()` pseudo-class without browser support detection.
> chore: Replace dir attribute with dir pseduo-class

- pages/property-filter/common-props.tsx
- pages/property-filter/custom-forms.tsx
- src/internal/components/autosuggest-input/__tests__/autosuggest-input.test.tsx
- src/internal/components/autosuggest-input/index.tsx
- src/internal/components/dropdown/__tests__/dropdown.test.tsx
- src/internal/components/dropdown/index.tsx
- src/internal/utils/__tests__/node-belongs.test.ts
- src/internal/utils/node-belongs.ts
Dropdown and Autosuggest had a bug were they only looked at `element.contains()` on the containers to identify clicks and focus/blur events outside of the dropdown. This broke when the some of the contents of a dropdown were rendered through a portal themselves, which specifically happened for the [PropertyFilter with custom forms](https://cloudscape.design/components/property-filter?tabId=playground&example=with-custom-form) when the custom form contained an informational popover or a Select.
Nested dropdowns are clearly not recommended by Cloudscape, but this seems like a general enough issue to want to address as it seems to be recurring (recently in Charts).
In order to fix this, I simply leveraged the existing `nodeBelongs()` utility which was used to fix the mentioned charts issue, …
> fix: Fix click interactions of dropdown components inside portals

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/code-editor/__tests__/code-editor.test.tsx
- src/code-editor/__tests__/preferences-modal.test.tsx
- src/code-editor/index.tsx
- src/code-editor/interfaces.ts
- src/code-editor/use-editor.tsx
- src/code-editor/util.ts
A follow up from #1951 - because of the way people load themes, we can't really be sure that they'll have the right theme even if it's technically included in an ace version. So we can no longer do version checks to decide whether we support that theme.
Instead, it's now decided through a kind of hidden "flag" of being provided through the `themes` property. So if you explicitly provide `"cloud_editor"` and `"cloud_editor_dark"` in your list of supported themes, you'll get it.
Related links, issue #, if available: AWSUI-29990
Unit testing, as usual.
<details> …
> fix: Make cloud editor themes opt-in using the `themes` property of code editor

- backstop/package-lock.json
- backstop/package.json
This PR downgrades BackstopJS. A [recent BackstopJS upgrade](https://github.com/cloudscape-design/components/pull/2005) introduced errors in visual regression checks.
<details> …
> fix: Downgrade BackstopJS

- src/app-layout/visual-refresh/trigger-button.scss
Fixes #2008 by setting an explicit inline padding of 0 to drawer buttons. Without it, different devices would add a different padding. Since the text is centered, in most cases this did not matter except in iPad where this padding is big enough (14px) for the text not to fit and be brought to the right.
Tested the `app-layout/default` page in an iPad simulator; compared [this version](https://d21d5uik3ws71m.cloudfront.net/components/ed329558ed7accf4b2859d8bba2c0ea1e35366fb/dev-pages/index.html#/light/app-layout/default) with the fix against [another version](https://d21d5uik3ws71m.cloudfront.net/components/7b579408e48b68b3bc2b6dc98b989c9af62a8b87/dev-pages/index.html#/light/) without the fix.
<details> …
> fix: Add explicit inline padding to drawer buttons

- package-lock.json
- package.json
- pages/code-editor/themes.page.tsx
Ongoing discussion internally about themes and testing. Let's just add another dev page, why not
This page will be screenshot tested. One group of themes for light mode, and another group for dark mode.
<details> …
> chore: Add test page for default theme resolution and styling

- src/button/index.tsx
- src/internal/hooks/use-latency-metrics/__tests__/use-latency-metrics.test.tsx
- src/internal/hooks/use-latency-metrics/index.ts
- src/internal/utils/__tests__/panorama.ts
- src/spinner/index.tsx
- src/table/__tests__/header-cell.test.tsx
- src/table/__tests__/interaction-metrics.test.tsx
- src/table/header-cell/index.tsx
- src/table/index.tsx
- src/table/internal.tsx
- src/table/thead.tsx
- src/table/tools-header.tsx
This PR extends the latency metrics for loading states with information about what user action likely caused the loading state. For example, if the user interacts with the pagination of a table, and then the table enters a loading state, the resulting latency metric will include the field `userAction: 'paginate'`.
<details> …
> feat: Include user interaction in latency metrics

- pages/tabs/permutations.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/tabs/index.tsx
- src/tabs/interfaces.ts
- src/tabs/styles.scss
Add a new property to Tabs component to allow the tab content to fit available height (that is, to expand or scroll accordingly)
Related links, issue #, if available: AWSUI-19223
Local testing, including integration in an application that requested this feature. New permutations added
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-supp …
> feat: Add `fitHeight` property to Tabs

- src/alert/index.tsx
- src/area-chart/index.tsx
- src/autosuggest/index.tsx
- src/badge/index.tsx
- src/bar-chart/index.tsx
- src/box/index.tsx
- src/button-dropdown/index.tsx
- src/button/index.tsx
- src/cards/index.tsx
- src/code-editor/index.tsx
- src/column-layout/index.tsx
- src/content-layout/index.tsx
- src/copy-to-clipboard/index.tsx
Follow up for https://github.com/cloudscape-design/components/pull/1956
Related links, issue #, if available: Vg2OAA5ArJn8
n/a
<details> …
> chore: Add props reporting for A-C components

- src/date-picker/__tests__/month-granularity.test.tsx
Mock date in date picker month granularity date to make the test consistent and prevent failures due to changing dates.
Ran the failing test locally.
<details> …
> test: Mock date in date picker test

- src/internal/utils/__tests__/global-flags-ssr.test.ts
- src/internal/utils/__tests__/global-flags.test.ts
- src/internal/utils/global-flags.ts
Make it possible to define feature flags in SSR
```js
// remove dark header
global[Symbol.for('awsui-global-flags')] = { removeHighContrastHeader: true };
```
Added an SSR test suite
<details> …
> chore: Support feature flags in SSR

- src/s3-resource-selector/__integ__/focus-interactions.test.ts
- src/s3-resource-selector/s3-modal/basic-table.tsx
Using table keyboard navigation for S3 resource selector buckets table.
Updated existing integration test, CI integration tests, dry run.
<details> …
> feat: Activate table keyboard nav in s3 resource selector

- build-tools/tasks/typescript.js
Fix source maps base path. This parameter produces `lib/default/....` fictional paths, which do not exist in the system anywhere. This makes it confusing to read stack traces from our customers.
The default behavior works well.
This can be seen in our unit test logs. Before (taken from [this build](https://github.com/cloudscape-design/components/actions/runs/8154960532/job/22289462488)):
```
console.warn
[AwsUi] [PieChart] You provided a `highlightedSegment` prop without an `onHighlightChange` handler. This will render a non-interactive component.
at warn (node_modules/@cloudscape-design/component-toolkit/internal/logging.js:10:21)
at lib/components/internal/hooks/use-controllable/lib/default/internal/hooks/use-controllable/index.ts:65:17
```
Now …
> chore: Fix source maps base path

- pages/table-fragments/grid-navigation-custom.page.tsx
- src/table/table-role/__integ__/grid-navigation.test.ts
- src/table/table-role/grid-navigation.tsx
Updated table keyboard navigation so that column- and element indices are preserved when the user moves vertically with arrow keys or page-up/page-down. This way when the number of interactive elements in the column is inconsistent or there are columns with colspan > 1 the horizontal cursor position is preserved so that the user does not have to start over from column 1.
That colspan > 1 columns are not supported yet but are planned as part of progressive loading, see: eDjiAKchzKda.
https://github.com/cloudscape-design/components/assets/20790937/d80f2854-fb03-4545-bfd4-bd7effe32c50
New integration tests
<details>
- …
> chore: Keyboard nav preserve user index

- src/date-input/index.tsx
- src/date-picker/index.tsx
- src/date-range-picker/index.tsx
- src/expandable-section/index.tsx
- src/file-upload/index.tsx
- src/form-field/index.tsx
- src/form/index.tsx
- src/grid/index.tsx
- src/header/index.tsx
- src/hotspot/index.tsx
- src/icon/index.tsx
- src/input/index.tsx
- src/link/index.tsx
- src/mixed-line-bar-chart/index.tsx
- src/modal/index.tsx
- src/multiselect/index.tsx
- src/pagination/index.tsx
- src/pie-chart/index.tsx
- src/popover/index.tsx
- src/progress-bar/index.tsx
- src/property-filter/index.tsx
Follow up for https://github.com/cloudscape-design/components/pull/2024
Related links, issue #, if available: Vg2OAA5ArJn8
PR build
<details> …
> chore: Add props reporting for D-P components

- src/i18n/messages-types.ts
- src/i18n/messages/all.de.json
- src/i18n/messages/all.en-GB.json
- src/i18n/messages/all.en.json
- src/i18n/messages/all.es.json
- src/i18n/messages/all.fr.json
- src/i18n/messages/all.id.json
- src/i18n/messages/all.it.json
- src/i18n/messages/all.ja.json
- src/i18n/messages/all.ko.json
- src/i18n/messages/all.pt-BR.json
- src/i18n/messages/all.tr.json
- src/i18n/messages/all.zh-CN.json
- src/i18n/messages/all.zh-TW.json
Updated strings based on i18n process doc: `w07VAyVxf86q`
Contains necessary strings for #2036.
Existing tests
<details>
- _If the code …
> chore: Update i18n strings

- src/content-layout/internal.tsx
Remove unused code. This `rootElement` ref does nothing
PR build
<details>
- _If the code …
> chore: Remove unused code from content layout

- src/select/index.tsx
- src/space-between/index.tsx
- src/spinner/index.tsx
- src/split-panel/index.tsx
- src/status-indicator/index.tsx
- src/tabs/index.tsx
- src/tag-editor/index.tsx
- src/textarea/index.tsx
- src/tiles/index.tsx
- src/time-input/index.tsx
- src/token-group/index.tsx
- src/wizard/index.tsx
Follow up for https://github.com/cloudscape-design/components/pull/2046
This is the last PR in that chain.
PR build
<details>
- _If the …
> chore: Add props reporting for S-W components

- pages/table/inline-editor.permutations.page.tsx
Table editable cells styles are to be updated in https://github.com/cloudscape-design/components/pull/2060. 
In this PR I am adding more permutations to compare before and after in screenshots.
The updates made to the test page will be visible in screenshot tests
<details>
- _Changes …
> test: Add permutations for table editable cells

- src/container/styles.scss
Big part of this fix. Looks nicer on Mac, but still need to check Windows (because it has the buttons at the end).
Related links, issue #, if available: AWSUI-35910
Might be tested in screenshot tests? I'll have to look into that next - it looks like we hide scrollbars in screenshot tests, so we're not getting the best coverage for cases where we expect to see scrollbars...
<details> …
> fix: Ensure scrollbars in fit-height containers don't leave rounded corners

- src/area-chart/__tests__/area-chart-use-chart-model.test.tsx
- src/area-chart/model/use-chart-model.ts
- src/mixed-line-bar-chart/__tests__/use-mouse-hover.test.ts
- src/mixed-line-bar-chart/hooks/use-mouse-hover.ts
This PR addresses the issue where an exception was thrown when leaving the popover on a chart by either:
- Focusing another element outside the page (all browsers)
- Right-clicking on a popover (Firefox only)
The root cause was that `event.relatedTarget` pointed to the `window` object in these cases. The `useMouseHover` hook has been updated to account for this scenario.
Related links, issue #, if available: AWSUI-35614
---
Why FF acts differently?
Firefox is firing the `onmousleave` event on a right click, all other browsers don't. Try it on the [mouseleave MDN page's Examples](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event#examples). The [onmouseleave specs](https://w3c.github.io/uievents/#event-type-mouseleave) mentions
> A [user …
> fix: hide popover on line charts when relatedTarget is not a DOM node

- src/select/__tests__/use-native-search.test.ts
- src/select/internal.tsx
- src/select/utils/use-native-search.ts
While browsing the code, I stumbled across two deprecated markers. In the KeyboardEvent details, the charCode property is no longer supported. It may have already been removed from the relevant web standards. Furthermore, React onKeyPress is also marked as deprecated. 
see here https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode
Added missing unit test for hook
<details> …
> chore: changed deprecated charCode with key event property

- src/breadcrumb-group/__integ__/breadcrumb-group.test.ts
- src/breadcrumb-group/__tests__/breadcrumb-item.test.tsx
- src/breadcrumb-group/item/item.tsx
- src/breadcrumb-group/item/styles.scss
- src/internal/components/tooltip/__tests__/tooltip.test.tsx
- src/internal/components/tooltip/index.tsx
- src/internal/components/tooltip/styles.scss
- src/popover/body.tsx
A simple tooltip component, that has the same styles as our Popover component, but not triggered via a click. It is currently used in the Breadcrumb component, and soon to be Slider component. There are also several other discussions around other places to use this component in the future.
The component was simply moved from the Breadcrumb component to our internal folder, for reusability.
I tested using the Breadcrumb testing pages to make sure there was no change.
Only basic tests were added to the component itself since it uses the same internal components as the Popover.
<details>
- _Changes include appropriate documentation …
> feat: Adds internal tooltip component

- src/i18n/messages-types.ts
- src/i18n/messages/all.de.json
- src/i18n/messages/all.en-GB.json
- src/i18n/messages/all.en.json
- src/i18n/messages/all.es.json
- src/i18n/messages/all.fr.json
- src/i18n/messages/all.id.json
- src/i18n/messages/all.it.json
- src/i18n/messages/all.ja.json
- src/i18n/messages/all.ko.json
- src/i18n/messages/all.pt-BR.json
- src/i18n/messages/all.tr.json
- src/i18n/messages/all.zh-CN.json
- src/i18n/messages/all.zh-TW.json
A dependency to https://github.com/cloudscape-design/components/pull/2000
<details> …
> chore: Add i18n for table expandable rows

- src/table/index.tsx
This metric is implemented incorrectly. Only original props should be passed to that object
Reverts cloudscape-design/components#2097
> revert: Add table expandable rows to metrics

- src/anchor-navigation/internal.tsx
This PR updates the component name that is shown in the development warning message of the Anchor Navigation.
<details> …
> chore: Fix anchor navigation warning text

- pages/property-filter/common-props.tsx
- pages/property-filter/hooks.page.tsx
- pages/property-filter/token-editor.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/property-filter/__tests__/controller.test.ts
- src/property-filter/__tests__/property-filter.test.tsx
- src/property-filter/controller.ts
- src/property-filter/index.tsx
- src/property-filter/interfaces.ts
- src/property-filter/token-editor.tsx
- src/property-filter/token.tsx
- src/property-filter/utils.ts
This CR adds the ability to customize free text filtering operators for the Property Filter, just like every other property operator. The corresponding update has already been merged into collection-hooks: https://github.com/cloudscape-design/collection-hooks/commit/59dcd9cd5e46c492e13939e59505f229782c202d.
See: k6RfAb8hHR1t
1. Updated 2 pages in the dev app (general property filter hooks page, and token editor page) and confirmed both worked with the new feature as expected.
2. Ran unit, integ and motion tests.
3. Fully ran visual regression testing because I expected the token-editor page to be part of it, but since it's only the permutations page every one of the 144 tests passed.
Video of various interactions with free text filtering in the dev app: …
> feat: Configurable operators for free text filtering in property filter

- .github/workflows/bundle-size.yml
We use a deprecated version
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache/restore@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Since #2032, the workflow is fast enough, we can simply remove the dependency instead of upgrading
PR build
<details> …
> chore: Remove caching from bundle size workflow

- pages/app-layout/with-split-panel.page.tsx
- src/app-layout/visual-refresh/context.tsx
Fixes the scrollbar position in table when split panel was removed, but `splitPanelOpen` is still `true`
Related links, issue #, if available: AWSUI-36917
Check [this](https://d21d5uik3ws71m.cloudfront.net/components/9e026d15b245a834e065078fd545bde5fc4fdd41/dev-pages/index.html#/light/app-layout/with-split-panel) dev page
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/b …
> fix: Don't include split panel offset when there is no split panel

- src/__tests__/__snapshots__/test-utils-selectors.test.tsx.snap
- src/app-layout/__tests__/drawers.test.tsx
- src/app-layout/drawer/overflow-menu.tsx
- src/app-layout/test-classes/styles.scss
- src/test-utils/dom/app-layout/index.ts
This change adds a new test util function to find the trigger that shows the AppLayout drawers when they overflow.
Related links, issue #, if available: AWSUI-39169
<details> …
> feat: Add findDrawersOverflowTrigger test util

- backstop/package-lock.json
Upgrading the transitive dependencies manually because dependabot was not able to so. The main motivation for doing that was to upgrade `express` to 4.19.2.
Related links, issue #, if available: https://github.com/cloudscape-design/components/security/dependabot/51
<details>
- _Changes …
> chore: Upgrade transitive dependencies in backstop folder

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/internal/components/token-list/index.tsx
- src/internal/components/token-list/interfaces.ts
- src/internal/components/token-list/token-limit-toggle.tsx
- src/multiselect/__tests__/multiselect.test.tsx
- src/multiselect/interfaces.ts
- src/multiselect/internal.tsx
- src/property-filter/__tests__/property-filter.test.tsx
- src/property-filter/index.tsx
- src/property-filter/interfaces.ts
- src/token-group/__tests__/token-group.test.tsx
- src/token-group/interfaces.ts
- src/token-group/internal.tsx
For the [TokenGroup component](https://cloudscape.design/components/token-group/) (used in [Multiselect](https://cloudscape.design/components/multiselect/) and [PropertyFilter](https://cloudscape.design/components/property-filter/?tabId=playground&example=with-hidden-tokens)), we have [writing guidelines](https://cloudscape.design/components/token-group/?tabId=usage) for the show more/show fewer button labels. When multiple TokenGroups/Multiselect/PropertyFilter components are used on one page with identical show more/show fewer button labels, the button’s aria-label should be different to ensure uniqueness across the page. This enables screen reader users to determine the purpose of the button.
- AWSUI-36423
- O2aiARe6YDXL
- added additional unit …
> feat: Add ariaLabels to token group for "Show fewer" and "Show more" buttons

- src/internal/context/__tests__/utils.tsx
- src/internal/context/single-tab-stop-navigation-context.tsx
- src/table/table-role/__tests__/grid-navigation.test.tsx
- src/table/table-role/grid-navigation.tsx
In tables with keyboard nav when a cell does not have interactive elements the cell itself is focused.
When there are interactive elements we always expect one of those to be focused instead of the cell.
The PR fixes the issue when table cell content updates dynamically so that the cell receives interactive element. When the cell is focused the focus must transition to the newly added element.
The problem was originally found as part of https://github.com/cloudscape-design/components/pull/2108 testing. When progressive loading transitions from "load more" to "loading" and back to "load more" the focus should transition between the load-more button and the text-only loading cell.
* New integration test as part of https://github.com/cloudscape-design/components/pull/2108 …
> fix: Table navigation to focus element registered inside focused cell

- src/popover/internal.tsx
There is a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1592017) that causes empty inline elements to have non-zero offsetHeight. This seems to not affect the page layout in most cases, but under certain circumstances it can also cause extra scrollHeight and therefore unexpected overflow to the parent of the parent (see [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1592017#c10)). This is affecting our popover component in closed state when rendering it in a portal, since the popover container has `display: inline` applied and is wrapped inside a div at the end of the body.
The solution applied in this PR is to apply the class `popover-content`, whose sole effect is to apply a CSS rule of `display: inline`, only when the popover is open, i.e, the popover …
> fix: Prevent closed popovers from altering the layout in Firefox

- pages/modal/async-modal-root.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/code-editor/index.tsx
- src/code-editor/interfaces.ts
- src/code-editor/preferences-modal.tsx
- src/collection-preferences/index.tsx
- src/collection-preferences/interfaces.ts
- src/internal/components/portal/__tests__/portal.test.tsx
- src/internal/components/portal/index.tsx
- src/modal/__integ__/modal.test.ts
- src/modal/interfaces.ts
- src/modal/internal.tsx
- src/s3-resource-selector/index.tsx
- src/s3-resource-selector/interfaces.ts
- src/s3-resource-selector/s3-modal/__tests__/utils.ts
- src/s3-resource-selector/s3-modal/index.tsx
Add `getModalRoot`/`removeModalRoot` properties to support lazy-loaded containers.
Related links, issue #, if available: 6M8sAlwBF9g5
1. Locally, on all changed components
2. Added related unit and integration tests
<details> …
> feat: Support async rendering container in modal components

- src/table/__tests__/table.test.tsx
- src/table/body-cell/styles.scss
- src/table/body-cell/td-element.tsx
In table component cell content is rendered directly into the TD elements. All cell styles are also applied to the TD elements, including min width, overflow and other. That is limiting though:
1. In VR tables there are no left/right paddings for the edge cells. As result, the focus outline is smaller than we would like it to be. It is not possible to extend it past the TD edges though because of the `overflow: hidden` style. See https://github.com/cloudscape-design/components/pull/2070.
2. In tables with expandable rows we add expand toggles to the first column. If the same column includes editable content the current solution is to disable the editing for the first column. That is because we cannot make the entire cell clickable while it also includes the clickable toggle element.
3. …
> chore: Add table cell content wrapper element

- src/app-layout/__tests__/widgetized-layout.test.tsx
- src/app-layout/classic.tsx
- src/app-layout/implementation.tsx
- src/app-layout/interfaces.ts
- src/app-layout/visual-refresh/context.tsx
- src/app-layout/visual-refresh/index.tsx
- src/app-layout/widget.tsx
Move separate defaults from Classic and Refresh versions in a single place
PR build + locally, no regressions
<details> …
> refactor: Deduplicate app layout default prop values

- src/top-navigation/__integ__/top-navigation.test.ts
- src/top-navigation/__tests__/top-navigation-overflow-menu.test.tsx
- src/top-navigation/parts/overflow-menu/menu-item.tsx
When rendering the top-navigation in a narrow width (mobile width for example) the top navigation utilities turns into menu dropdown, the items are always rendered as an `a` element.
When the items inside the menu dropdown does not have an `href` they are rendered with a `tabIndex` of 0 and with a `role` of `link`, this leads to an a11y issue where they are not announced and can not be accessed using the keyboard by using tab.
This PR adds a role `button` whenever there is no `href` provided and sets the `tabIndex` to be always 0.
issue: AWSUI-38331
Added unit and integ tests
<details>
- _Changes include appropriate documentation …
> chore: Use `button` role on anchors without `href` in top-navigation menu in mobile

- src/table/table-role/__tests__/grid-navigation.test.tsx
- src/table/table-role/grid-navigation.tsx
- src/table/table-role/utils.ts
A follow-up for https://github.com/cloudscape-design/components/pull/2118#discussion_r1551818397.
Table keyboard navigation must support both TD and TH cells.
* Updated unit tests
<details> …
> fix: Fix table keyboard navigation for TH cells

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/app-layout/__integ__/app-layout-refresh-content-width.test.ts
- src/app-layout/__tests__/widgetized-layout.test.tsx
- src/app-layout/classic.tsx
- src/app-layout/index.tsx
- src/app-layout/interfaces.ts
- src/app-layout/utils/use-resize.tsx
- src/app-layout/visual-refresh/context.tsx
- src/app-layout/visual-refresh/navigation.scss
- src/app-layout/visual-refresh/navigation.tsx
- src/app-layout/visual-refresh/split-panel.tsx
- src/app-layout/visual-refresh/tools.scss
- src/app-layout/visual-refresh/tools.tsx
Consolidate all 280/290 values in a single place
* Locally
* PR build
* Screenshot tests in my pipeline
<details> …
> fix: Unify drawer widths treatment

- pages/popover/inline.page.tsx
- src/popover/internal.tsx
- src/popover/styles.scss
Corrected rework of #2116 (reverted by #2133), but having inline popovers into account. The new corrected logic is to add `display: inline` only if not using a portal.
Issue: AWSUI-40397
- Ran in my pipeline, getting the same expected diffs in the Firefox diffs as in #2116
- Added test page to cover inline popovers. Tested manually and will add a visual regression test.
<details> …
> fix: Do not display popover inline when using portal

- pages/form/with-validation.page.tsx
- src/form-field/__tests__/form-field-rendering.test.tsx
- src/form-field/internal.tsx
Added aria live to form field error messages as part of validation improvements. These changes allow error messages to be announced in form field, attribute editor, tag editor, file upload, etc (components that use FormFieldError component).
Issue: AWSDesignSystem-432
Tested manually (to try yourself; go to pages/form/with-validation, turn on screen reader, type text longer than 4 letters to the input field and click submit)
Also added and ran unit test
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-api …
> feat: Announce form field errors using ARIA live region

- src/app-layout/visual-refresh/layout.scss
- src/content-layout/styles.scss
- src/internal/generated/custom-css-properties/list.js
- src/wizard/styles.scss
Remove inter-dependencies between css-variables in app layout and other components.
This inter-dependency only works when both instances are coming from the same bundle, but we cannot guarantee that in real world
* Screenshot tests in my dev pipeline. There will be differences and they are expected
<details> …
> chore: Remove cross-component css-variables

- pages/table/expandable-rows-test.page.tsx
- pages/table/expandable-rows/expandable-rows-configs.tsx
- pages/table/expandable-rows/expandable-rows-data.ts
An update to a table test page to support https://github.com/cloudscape-design/components/pull/2131
The test page is enhanced with a server mock to imitate server-side data processing. The update is primarily needed for 2131 to ensure progressive loading behaves as expected with both client- and server side resolution.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob …
> chore: Table expandable test page server mock

- pages/visual-contexts/styles.scss
- pages/visual-contexts/top-navigation.page.tsx
- style-dictionary/visual-refresh/colors.ts
The PR does: 
1. Add one page to test Top Nav visual context change, see CR-122397160
2. Separate `colorTextDropdownItemDefault` from `colorTextFormDefault` because we want to update `colorTextFormDefault` color in topnav context but keep `colorTextDropdownItemDefault` as it is. 
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/bl …
> chore: Add page to test top nav visual context change

- src/table/__tests__/body-cell.test.tsx
- src/table/__tests__/header-cell.test.tsx
- src/table/body-cell/td-element.tsx
- src/table/header-cell/index.tsx
- src/table/header-cell/th-element.tsx
- src/table/table-role/grid-navigation.tsx
- src/table/table-role/utils.ts
In tables with keyboard navigation all cells were assigned tabIndex="-1". This way, the cells are still not reachable with Tab navigation, but receive focus upon clicking: when clicking on a cell the focus event is emitted and the cell becomes the active element. In case a cell includes an interactive element such as an expand toggle, that interactive element receives focus instead of the cell. That breaks the browser's text selection behaviour:
1. The user starts selection by clicking and dragging over text content in a cell;
2. The cell receives focus;
3. The focus is dispatched to the first interactive element of the cell (the expand toggle);
4. The text selection is not performed.
The problem is fixed by not assigning the negative tab index to cells unless immediately before issuing …
> fix: Table with mixed cell content and grid navigation to allow text selection

- pages/bar-chart/stacked-permutations.page.tsx
- src/bar-chart/__tests__/bar-chart.test.tsx
- src/mixed-line-bar-chart/data-series.tsx
There was a bug caused by mismatched indexes. In a stacked bar chart if the threshold series come before bar series this results in a miscalculated offsets.
Rel: AWSUI-40910
* New permutations
<details> …
> fix: In stacked bar chart threshold series can be added at any position in the series array

- pages/side-navigation/permutations.page.tsx
Side Navigation component allows any level of items nesting but we don't have any tests for more than 1 level, this PR adds screenshot tests for 4 levels of nesting for the 3 item types that allows nesting: `section`, `link-group` and `expandable-link-group`
Our [API says](https://cloudscape.design/components/side-navigation/?tabId=api):
> Although there is no technical limitation to the nesting level, our UX recommendation is to use only one level.
But it's still possible to use nested items in Side Navigation and we want to avoid any regressions to these untested levels of nesting. 
Related links, issue #, if available: AWSUI-40872
<details> …
> test: Add screenshot tests for nested items in Side Navigation

- pages/table/expandable-rows-test.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/cards/__tests__/cards.test.tsx
- src/cards/index.tsx
- src/cards/interfaces.tsx
- src/table/__tests__/a11y.test.tsx
- src/table/index.tsx
- src/table/interfaces.tsx
- src/table/internal.tsx
In Table and Cards we announce changes to items with `renderAriaLive`. The changes are only announced when the `firstIndex` is defined which we require for when the pagination is used. However, the announcements are relevant in one of the two cases:
1. Page changes (represented by a change of the first index)
2. Filter changes (represented by a change of the total items)
The second case remains uncovered when there is no pagination and the first index is not provided explicitly which is against our recommendation.
When `firstIndex` is not defined it defaults to 1 in both Table and Cards. As result, the live announcement is consistently performed. The `totalItemsCount` can remain undefined though when the actual count is unknown. That is expected to be handled by the `renderAriaLive` which …
> fix: Render live announcements in Table and Cards when no pagination

- pages/bar-chart/stacked-permutations.page.tsx
The random order of threshold series in bar chart permutations affected series order in the legend making the VR tests flaky.
<details> …
> chore: Stable bar chart permutations

- src/mixed-line-bar-chart/__tests__/utils.test.ts
- src/mixed-line-bar-chart/bar-series.tsx
- src/mixed-line-bar-chart/data-series.tsx
- src/mixed-line-bar-chart/utils.ts
Reverting PR https://github.com/cloudscape-design/components/pull/2171 due to unexpected performance impact.
<details> …
> revert: Partially rounded corners for stacked bar charts

- pages/app-layout/fill-content-area.page.tsx
- pages/popover/container-test.page.tsx
- src/app-layout/utils/use-pointer-events.ts
- src/internal/direction.ts
- src/internal/utils/handle-key.ts
- src/table/resizer/index.tsx
- src/tabs/scroll-utils.ts
This is a minor name change to remove conflicts with instances of `isRtl` as a boolean parameter or the necessity to import `isRtl` as `getIsRtl` in functions where the value assignment is used in multiple places.
> chore: Rename isRtl utility function to getIsRtl.

- .gitignore
- pages/theming/integration.page.tsx
- pages/theming/tokens.page.tsx
- src/theming/__integ__/index.test.ts
- src/theming/__integ__/tokens.test.ts
- src/theming/__tests__/index.test.ts
- src/theming/index.ts
Expose `generateThemeStylesheet` API added to `@cloudscape-design/theming-core`:
* https://github.com/cloudscape-design/theming-core/pull/75
* https://github.com/cloudscape-design/theming-core/pull/77
I've tested this API with my application which consumes it, and I've added unit & integration tests.
<details> …
> feat: add generateThemeStylesheet API

- backstop.config.js
Wait for code-editor error state before taking a screenshot.
PR build
<details>
- _If the …
> chore: Fix flaky code-editor screenshot test

- src/area-chart/__integ__/page-objects/area-chart-page.ts
- src/area-chart/__tests__/area-chart-model-utils.test.ts
- src/area-chart/__tests__/area-chart-use-chart-model.test.tsx
- src/area-chart/chart-container.tsx
- src/area-chart/internal.tsx
- src/area-chart/model/compute-chart-props.ts
- src/area-chart/model/index.ts
- src/area-chart/model/use-chart-model.ts
- src/internal/components/cartesian-chart/__tests__/value-labels.test.tsx
- src/internal/components/cartesian-chart/block-end-labels.tsx
- src/internal/components/cartesian-chart/inline-start-labels.tsx
- src/internal/components/cartesian-chart/labels-measure.tsx
- src/internal/components/cartesian-chart/styles.scss
- src/internal/components/cartesian-chart/value-labels.tsx
- src/internal/components/chart-legend/index.tsx
- src/internal/utils/handle-key.ts
- src/mixed-line-bar-chart/chart-container.tsx
Fix area charts rendering issues when page direction is RTL:
* Inverting X domain when RTL;
* Inverting horizontal move direction with keyboard when RTL;
* Alternative X position for value axis.
* Manual testing;
* Screenshot testing.
<details> …
> chore: Add RTL support for area chart

- src/app-layout/visual-refresh/universal-toolbar.scss
Fix drawers from collapsing when they still have room next to breadcrumbs.
Related links, issue #, if available: follow up from  [#2204](https://github.com/cloudscape-design/components/pull/2204)
<details> …
> fix: drawers overflow too soon

- src/__tests__/__snapshots__/design-tokens.test.ts.snap
- style-dictionary/visual-refresh/metadata/colors.ts
These two tokens are used in button dropdowns, which are often themed in contexts. These tokens were previously private, but they pointed to themeable tokens, making them basically implicitly themeable. And when we innocently changed the values of a private token in #2167, it ended up breaking customers.
I was tempted to make all `colorTextDropdownItem*` tokens public and themeable, but I want to leave that for our future validation efforts if/when we check that private tokens don't depend on public tokens like this.
Related links, issue #, if available: AWSUI-41803
Just metadata changes. Updated snapshots.
<details>
- …
> feat: Make colorTextDropdownItemDefault and colorTextDropdownItemDisabled themeable

- src/form-field/__tests__/form-field-rendering.test.tsx
- src/form-field/internal.tsx
Fixed the issue where error icon aria label wasn't being announced unless i18n strings were defined specifically
Related links, issue #, if available: AWSUI-41861
<details> …
> fix: Form field live region error icon aria label

- src/internal/components/responsive-text/__tests__/responsive-text.test.tsx
- src/internal/components/responsive-text/index.tsx
- src/pie-chart/__tests__/responsive-text.test.tsx
- src/pie-chart/responsive-text.tsx
Fix pie charts rendering issues when page direction is RTL:
* Align the labels to the correct side;
* Make labels truncation reversed.
* New unit test for truncation;
* Manual testing;
* Screenshot testing.
<details> …
> chore: Add RTL support for pie chart

- pages/app-layout/with-table-and-sticky-offset.page.tsx
Follow up for https://github.com/cloudscape-design/components/pull/2213 to add a screenshot test. We need to have an AppLayout + stickyHeaderVerticalOffset combination to test
This change is testing
<details> …
> chore: Add stickyHeaderVerticalOffset use-case for screenshot testing

- pages/funnel-analytics/mock-funnel.ts
- pages/funnel-analytics/static-multi-page-flow.page.tsx
- pages/funnel-analytics/static-single-page-flow.page.tsx
- src/alert/index.tsx
- src/container/index.tsx
- src/form-field/index.tsx
- src/form-field/interfaces.ts
- src/form-field/internal.tsx
- src/form/__tests__/analytics.test.tsx
- src/form/index.tsx
- src/form/internal.tsx
- src/internal/analytics/__integ__/static-multi-page-create.test.ts
- src/internal/analytics/__integ__/static-single-page-flow.test.ts
- src/internal/analytics/components/analytics-funnel.tsx
- src/internal/analytics/context/analytics-context.ts
- src/internal/analytics/hooks/use-funnel.ts
- src/internal/analytics/interfaces.ts
- src/internal/base-component/index.ts
- src/link/internal.tsx
- src/wizard/__tests__/analytics.test.tsx
- src/wizard/analytics.ts
- src/wizard/index.tsx
- src/wizard/internal.tsx
- src/wizard/wizard-form.tsx
This separates instance identifiers between funnel, steps and substeps to allow them to be passed in separately in the funnel event functions.
<details> …
> chore: Pass analytics instance identifier for parents down to methods

- src/button/styles.scss
Removed negative margin for inline link variant. Expected visual difference in Button permutations.
Before:
After:
AWSUI-37538
<details> …
> fix: Remove negative margin from Button inline link variant

- pages/autosuggest/simple.page.tsx
- pages/top-navigation/integ.page.tsx
- pages/top-navigation/search.page.tsx
- src/top-navigation/__integ__/top-navigation.test.ts
- src/top-navigation/internal.tsx
In Top navigation all content is rendered twice. The second time the content is rendered as "virtual" - it is invisible and is used to measure content elements widths. That creates potential problems, for example, using the `id` attribute on a content node would result in duplicate IDs present in the DOM. A similar issue was with React refs. The ref callback is called twice and the actual node it gets assigned is the one which comes from the callback executed the last. That means the virtual content must come before the actual content and it can't be rendered in our Portal because the portal content is rendered with a delay.
Rel: AWSUI-42554, https://github.com/cloudscape-design/components/issues/2181
* New integration test
<details>
_The following …
> fix: Make inputs inside top navigation programmatically focusable

- src/slider/__tests__/utils.test.tsx
- src/slider/utils.ts
Fix JS rounding issues when using decimal values for slider `step`
Related links, issue #, if available: AWSUI-42557
Updated unit tests
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessib …
> fix: Better support for decimal steps in slider

- src/tag-editor/__tests__/validation.test.ts
- src/tag-editor/validation.ts
TagEditor allows only for the following characters: `+ - = . _ : / @`. However, our validation allowed for backslash. 
We checked with Tagris team and confirmed with them that backslash is not allowed.
So we're updating the regex.
Related links, issue #, if available: AWSUI-42153
Added a new test to explicitly test for backslash
<details> …
> fix: Exclude backslash from the list of allowed characters in tag editor

- src/input/internal.tsx
Email input types should always use dir='ltr' regardless of the inherited document direction. This PR updates the attribute accordingly.
> chore: Set dir attribute to ltr for email input type.

- pages/app-layout/with-split-panel.page.tsx
- pages/app-layout/with-table-and-split-panel.page.tsx
- src/app-layout/__integ__/app-layout-focus-delegation.test.ts
- src/split-panel/styles.scss
Currently, fixed position elements like an open Popover can "leak" out of a split panel when scrolling (see screenshot). While there is no technical defect, this can be very jarring and users might find it looks broken.
To fix this issue, we're introducing a `clip-path` to the split panel bottom drawer.
Related links, issue #, if available: AWSUI-24345, `CR-126847853`
Tested locally, added a new screenshot test, and tested in a prod environment.
<details>
- …
> fix: Fix popover in split panel leaking outside of the split panel container

- src/table/selection/use-selection.ts
The refactoring is done to facilitate future planned support for grouped selection so that when a parent row is selected (in table with expandable rows) all child rows are automatically selected too. That different selection mechanism requires a different computation which can be substituted to the useSelection.
Existing tests
<details> …
> refactor: Reorganise and document code in table use-selection util

- .github/workflows/bundle-size.yml
- .github/workflows/bundle-size/build.js
- .github/workflows/bundle-size/status-report.js
- Report bundle size on push (not just on pull request). This is so that reports can be associated with commits.
- Extend bundle size report to include dependency versions taken from `packagelock.json`, as `@cloudscape-design` dependencies are not pinned in `package.json`
See:
- [Report on this PR](https://github.com/cloudscape-design/components/actions/runs/9129222860/job/25103251099?pr=2266) (PR workflow)
- [Report on dev branch](https://github.com/cloudscape-design/components/actions/runs/9129510421) (push workflow)
<details> …
> feat: Report bundle size for every commit in main

- pages/property-filter/permutations.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/__tests__/__snapshots__/test-utils-selectors.test.tsx.snap
- src/property-filter/__tests__/property-filter.test.tsx
- src/property-filter/index.tsx
- src/property-filter/interfaces.ts
- src/property-filter/styles.scss
- src/test-utils/dom/property-filter/index.ts
This CR adds the ability to display a constraint text for the Property Filter. This can be used for server-side collections when the capabilities of the Search API do not allow every combination of filters offered by Property Filter: limited number of filter tokens, incompatible tokens, etc.
This change includes a new method to the `PropertyFilterWrapper` test utility, to find the new slot container for the constraint text.
See: mMxbAEGGaa5a
1. Tested by updating the permutations page to display constraint text with and without tokens:
2. Updated unit tests with a straightforward test to confirm the new test utility works and that the constraint text is correctly slotted.
3. Ran all unit, integ, a11y and motion tests. Updated documentation snapshots.
4. Ran visual regression testing. …
> feat: Constraint text for Property Filter

- src/progress-bar/__tests__/progress-bar.test.tsx
- src/progress-bar/index.tsx
- src/progress-bar/internal.tsx
- src/test-utils/dom/progress-bar/index.ts
Introduced `findAdditionalInfo` method for progress bar test utils.
The test utils for the ProgressBar component do not provide a way to get the additionalInfo slot. In v2, customers worked around this by searching for a hardcoded class name, which does not work anymore in v3.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/ …
> feat: findAdditionalInfo method for progress bar test utils

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/table/interfaces.tsx
Fix markdown formatting so lists are correctly nested
Tested output locally 
<details>
- _If …
> fix: Fix markdown format in table docs

- src/form-field/internal.tsx
- src/form-field/styles.scss
This PR removes the top padding from the form field when there is no label present. 
Related links, issue #, if available: AWSUI-43667
Tested manually in the dev pages by removing the label from a form field and inspecting the layout with the dev tools.
<details> …
> fix: Form field has padding even when no label is present

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/progress-bar/__tests__/progress-bar.test.tsx
- src/progress-bar/index.tsx
- src/progress-bar/interfaces.ts
- src/progress-bar/internal.tsx
Before this change screen reader users had difficulty determining which constraints correspond with which field. This change associates the `description`, `additionalInfo` and `ariaDescribedby` with the `<progress />` element if provided. The `ariaDescribedby` property got exposed which allows customization if needed. 
Related links, issue #, if available: AWSUI-40665
- added additional unit tests.
<details> …
> fix: Associate description and additionalInfo with <progress> element

- src/split-panel/icons/resize-handler.tsx
Hide the SVG from being treated as a graphic by screen readers so that they don't call this out as an unlabeled image. In every context that it's used, it's wrapped by a `role="slider"` with a label, so a label on the icon itself is irrelevant. But if we don't remove from the accessibility tree, it's treated as an unlabeled image by automated testing tools.
We do this in the icon component by default but we're not using the icon component here, so it was missed.
Related links, issue #, if available: AWSUI-42858
No new tests here. Adding a test for checking a fixed property feels silly.
<details>
- _Changes are …
> fix: Hide resize handler icon SVG from screen readers

- pages/app-layout/skeleton.page.tsx
- pages/app-layout/utils/skeleton-layout.tsx
- src/app-layout/skeleton/index.tsx
- src/app-layout/skeleton/layout.tsx
- src/app-layout/skeleton/styles.scss
- src/internal/generated/custom-css-properties/list.js
Part of a bigger project to refactor app layout and make it lazy loadable
Added a new dev page. [Click here to preview](https://d21d5uik3ws71m.cloudfront.net/components/0e4d1e6c26686e1e6277556dd28413a9438056a1/dev-pages/index.html#/light/app-layout/skeleton)
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.m …
> chore: Add app layout skeleton internal component

- src/internal/utils/dom.ts
Just getting ahead of any possible future need (container queries 😉). Right now, there's no use-case for it directly in the components itself, but it does bring it closer in line with [native browser layout behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block), should people end up doing container queries on their end.
No tests, just manual messing around. Just getting ahead of potential future changes where we use container queries ourselves and the popover ends up breaking.
<details>
- _Changes are backward-compatible if …
> chore: Treat CSS containment as containing block for positioning

- pages/button/performance-marks-in-modal.page.tsx
- src/button/__integ__/performance-marks.test.ts
- src/internal/hooks/use-performance-marks.ts
This PR updates the logic for emitting performance marks. They will no longer be emitted for components that are located inside Modals.
Related links, issue #, if available: AWSUI-44575
Added a unit test, and manually verified in the new dev page
<details> …
> chore: Do not emit performance marks for buttons inside modals

- package-lock.json
- package.json
- src/code-editor/__tests__/code-editor.test.tsx
- src/code-editor/__tests__/util.tsx
- src/code-editor/use-editor.tsx
Reverts cloudscape-design/components#2282 😢
> revert: Revert "fix: Correctly pass ariaLabel from code editor to underlying ace editor"

- src/area-chart/__tests__/area-chart-initial-state.test.tsx
- src/area-chart/elements/chart-popover.tsx
- src/internal/components/chart-popover/index.tsx
- src/internal/components/chart-popover/motion.scss
- src/internal/components/chart-popover/styles.scss
- src/mixed-line-bar-chart/__tests__/mixed-chart.test.tsx
- src/mixed-line-bar-chart/chart-popover.tsx
- src/mixed-line-bar-chart/motion.scss
- src/pie-chart/pie-chart.tsx
Improve code reuse between chart instances and apply the same transition treatment to all popovers used there
* PR build
* Locally, ensured transition works on all chart instances
<details> …
> refactor: Move transition handling to shared chart popover component

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/link/__integ__/link.test.ts
- src/link/__tests__/index.test.tsx
- src/link/interfaces.ts
- src/link/internal.tsx
Add onClick event for Link component. 
Currently Link has one event: onFollow, which is called when the Link is called without modifier key. Our customer needs an event calls for every onClick to collect metrics. 
Add unit tests 
<details>
- …
> feat: Add onClick event for Link component

- src/internal/context/single-tab-stop-navigation-context.tsx
- src/table/table-role/utils.ts
In a recent bugfix (https://github.com/cloudscape-design/components/pull/2294) to table keyboard navigation for Firefox and Safari the focus lost detection transitioned from listening to focusout event to monitoring focusable element unmounts. That introduced problems in React 18 because there the unmount events come after the focus transition occurred so the check `nodeBelongs(focusable, document.activeElement)` no longer works. This is fixed by updating the single tab stop navigation context subscription to use layout effect instead of effect.
* Manual testing in Chrome, Firefox, and Safari in React 16 and 18;
* Existing unit- and integration tests run with React 16 and 18;
* New behaviour test for Firefox and Safari (React 16, CR-129786127);
* New e2e test for examples/demos (React 18, …
> fix: Fix table grid navigation for React 18

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/form/__tests__/form.test.tsx
- src/form/interfaces.ts
- src/form/internal.tsx
- src/form/styles.scss
With the removal of high-contrast header, the form variant property is no longer needed
dev pipeline
<details>
- _Changes include appropriate documentation updates._ Y
- _If the …
> chore: Deprecate variant property in form component

- src/test-utils/dom/table/index.ts
Unlike in Cards, the updated method to find the header in Table is `findHeaderSlot`, not `findHeader`.
`findHeader` does not exist in Table's test utils.
<details> …
> fix: Fix description of Table findHeaderRegion test util method

- package-lock.json
- package.json
- src/code-editor/__tests__/code-editor.test.tsx
- src/code-editor/__tests__/util.tsx
- src/code-editor/use-editor.tsx
Un-reverts cloudscape-design/components#2288 (when it's time)
> fix: Correctly pass ariaLabel from code editor to underlying ace editor

- .github/workflows/bundle-size.yml
- .github/workflows/bundle-size/status-report.js
The bundle size is calculated for PR commits but also once a commit is merged to main. Thus, rename the output file to not be refer to "pr" and be more generic instead.
Result of PR workflow can be seen in the checks below.
Result of merging to main will be seen once this PR is merged.
<details> …
> chore: Rename bundle size output file

- src/internal/utils/dom.ts
My guess on what's happening here is that CSS [contain](https://caniuse.com/mdn-css_properties_contain) isn't supported on Safari 15.0, 15.1, and 15.3, so calling a property on it causes an error to throw. Treating this as a hotfix for now, but I don't know how best to address this in the long term. Either an audit on whether properties we're calling on `getComputedStyle` exist, or some kind of CSS-like browser-support check?
Related links, issue #, if available: AWSUI-45436
See above.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blo …
> fix: Ensure 'contain' is provided in getComputedStyle before relying on it

- src/app-layout/split-panel/provider.tsx
- src/internal/context/split-panel-context.ts
- src/split-panel/__tests__/helpers.ts
Since https://github.com/cloudscape-design/components/pull/1612 this value is not used inside split panel context
PR build
<details> …
> chore: remove reportSize from split panel context

- src/mixed-line-bar-chart/__integ__/announcements.test.ts
- src/mixed-line-bar-chart/chart-container.tsx
Ensure chart announcements track focus state correctly: previously they would lag one action behind the active selection.
Related links, issue #, if available: AWSUI-42778
Updated integ tests
<details> …
> fix: Ensure chart announcements track focus state correctly

- build-tools/tasks/generate-custom-css-properties.js
```js
import customCssProps from '../../../lib/components/internal/generated/custom-css-properties';
customCssProps.whateverRandom;
// before: no type error
// after: Property whateverRandom does not exist on type ...
```
PR build
<details>
- …
> chore: Fix type definitions for custom css prop names generator

- src/tabs/__tests__/tabs.test.tsx
- src/tabs/tab-header-bar.tsx
Updated keyboard navigation logic in Tabs to use single-tab-stop context.
So far there is a lot of similarities with src/table/table-role/grid-navigation.ts. There is an opportunity to reuse the parts of code that define focusables, focusableHandles, and focusablesState state, but I would prefer to do it in a separate follow-up PR to keep the diff manageable.
The change is supposed to introduce no difference to the current Tabs UX. We do it to support the upcoming feature: https://github.com/cloudscape-design/components/pull/2173 (actions in tabs). The update is proven to work with actions: https://github.com/cloudscape-design/components/pull/2325.
* Existing unit- and integration tests;
* Screenshot tests;
* Dry-run;
* Manual tests.
<details>
_The …
> chore: Tabs use single tab stop navigation mechanism

- src/app-layout/__integ__/app-layout-sticky-elements.test.ts
- src/app-layout/__tests__/sticky-offset.test.ts
- src/app-layout/utils/sticky-offsets.ts
- src/app-layout/visual-refresh/layout.scss
- src/app-layout/visual-refresh/main.tsx
- src/app-layout/visual-refresh/notifications.scss
- src/app-layout/visual-refresh/notifications.tsx
- src/container/__integ__/awsui-legacy-applayout-sticky.test.ts
- src/container/__integ__/header-cover.test.ts
- src/container/__tests__/sticky-header.test.tsx
- src/container/__tests__/sticky-offset.test.ts
- src/container/internal.tsx
- src/container/styles.scss
- src/container/use-sticky-header.ts
- src/table/internal.tsx
No longer needed after the removal of high-contrast header in these components
dev pipeline
<details> …
> chore: Remove usage of overlap hook in container

- pages/popover/text-wrap.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/popover/index.tsx
- src/popover/interfaces.ts
- src/popover/internal.tsx
- src/popover/styles.scss
Added a `wrapTriggerText` property.
Follows the "negative" prop convention we essentially established for button and status indicator components. It has the name `trigger` in it to both follow the pattern with the other props (`triggerType`, `triggerAriaLabel`), and make it clear that this doesn't apply to the body itself. Setting this prop to `false` adds both text wrapping and truncation to the text trigger, and while I messed around with making it default, I've seen enough popovers with "internal" wrapping to realize this is a bad idea (plus it would make it completely unreadable/inaccessible for most cases outside a resizable table).
```typescript
/**
* Specifies if the text trigger content should wrap. If you set it to false, it prevents the text from
* wrapping and truncates it with …
```
> feat: Add wrapTriggerText to popover

- src/internal/context/single-tab-stop-navigation-context.tsx
- src/table/table-role/__tests__/grid-navigation.test.tsx
- src/table/table-role/grid-navigation.tsx
- src/tabs/tab-header-bar.tsx
Reused code between Tabs and Table that now both use single tab stop navigation context.
This change is a follow-up for https://github.com/cloudscape-design/components/pull/2330.
* Existing unit- and integration tests;
* Screenshot and lighthouse tests;
* Dry run to live.
<details>
- …
> refactor: Refactor single tab stop context

- src/button/__integ__/performance-marks.test.ts
- src/button/internal.tsx
- src/internal/hooks/use-performance-marks/__tests__/use-performance-marks.test.tsx
- src/internal/hooks/use-performance-marks/index.ts
- src/internal/hooks/use-unique-id/index.ts
- src/table/__integ__/performance-marks.test.ts
- src/table/internal.tsx
This PR extends the existing performance mark mechanism with a mechanism to identify the corresponding DOM element. Each performance mark already contains an ID (in `detail.instanceIdentifier`) that is tied to the lifetime of the component.
With this PR, this same ID is now attached to a DOM element inside the component (not necessarily the _root_ element), in the data attribute `data-analytics-performance-mark`. Thus, the elements for each performance mark can be found like this:
```js
performance
.getEntriesByType('mark')
.filter(mark => mark.detail?.source === 'awsui')
.map(mark => ({
mark,
element: document.querySelector(
`[data-analytics-performance-mark="${mark.detail.instanceIdentifier}"]`
),
}));
```
<details> …
> chore: Connect performance marks to DOM elements

- pages/table/full-page-variant.page.tsx
- src/table/__integ__/table.test.ts
- src/table/internal.tsx
- src/table/table-role/table-role-helper.ts
Found in Slack and I'm following up with a quick fix, so no ticket. There are two things here that need to be labelled - the table itself (if there are multiple tables) and the focusable scroll wrapper (if the table is horizontally scrollable). Previously, we used to "auto-label" the former from the header slot, but not the latter.
Removed a manual label from a test page and the test should continue to pass. No unit test changes because we can't reliably make the scrollable wrapper show up on unit tests.
<details> …
> fix: Automatically label table's scrollable region using header

- src/internal/styles/forms/mixins.scss
- src/table/body-cell/styles.scss
- src/table/body-cell/td-element.tsx
- src/table/header-cell/styles.scss
This PR mainly changes how paddings are applied to table cells. Previously the paddings were applied to the cell directly (TD or TH element) and now all paddings are applied to the nested content element (the DIV element). The content element also receives the `overflow: none` from the cell. This way, the content DIV does not allow for the content to overflow but the cell element does. As result, we can render the cell focus outline which exceeds the dimensions of the cell on the left.
Because the borders are still applied to the cells and not the content, there is a 1px difference in cell size compared to the previous version. That difference is compensated by subtracting border width from padding, but due to conditional padding application in certain cases there is a small pixel shift …
> fix: Fix table cell focus outline

- src/app-layout/visual-refresh/drawers.scss
Ensure drawer icons are right-aligned when in VR mobile view and there are no breadcrumbs.
Related links, issue #, if available: AWSUI-46715
Tested locally
<details> …
> fix: Ensure drawer icons remain on right in mobile

- pages/table/editable-data.ts
- pages/table/inline-editor.permutations.page.tsx
- src/table/body-cell/inline-editor.tsx
- src/table/body-cell/styles.scss
When using select component with very long option labels in table with inline editing the component expands beyond cell borders.
https://github.com/cloudscape-design/components/assets/20790937/53bc2866-9d01-428c-a700-ec93bc01dfce
Rel: AWSUI-42444
* Updated permutations, the issue is now captured by VR and screenshot tests
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/b …
> fix: Fix select overflow when using in table inline editing

- src/app-layout/__tests__/widgetized-layout.test.tsx
- src/breadcrumb-group/__tests__/widgetized-breadcrumbs.test.tsx
- src/breadcrumb-group/implementation.tsx
- src/breadcrumb-group/interfaces.ts
- src/breadcrumb-group/item/funnel.tsx
- src/breadcrumb-group/item/item.tsx
- src/breadcrumb-group/item/styles.scss
- src/breadcrumb-group/skeleton.tsx
- src/internal/widgets/__tests__/utils.ts
- src/internal/widgets/__tests__/widgets.test.tsx
- src/split-panel/__tests__/widgetized-panel.test.tsx
Render funnel name placeholder while the widget is loading
Added unit tests. Integration tests will be done in the pipeline
<details> …
> chore: Add skeleton state for breadcrumb group widget

- build-tools/tasks/generate-icons.js
- themes/icons/drag-indicator.svg
- themes/icons/resize-area.svg
- themes/icons/send.svg
- themes/icons/subtract-minus.svg
Clean up icons from inline attributes because they conflict with our CSS we apply to the icons: https://github.com/cloudscape-design/components/blob/af1a976051f9de50675d30004475bbe0e3847ffa/src/icon/mixins.scss#L98-L120
Screenshot tests in my dev pipeline
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#b …
> fix: Clean up icons content

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/popover/__tests__/popover.test.tsx
- src/popover/index.tsx
- src/popover/interfaces.ts
- src/popover/internal.tsx
As part of the effort to improve accessibility on the [loading and refreshing](https://cloudscape.design/patterns/general/loading-and-refreshing/) pattern. When the status indicator popover gets added dynamically, we should move focus to the trigger so that assistive technology users are aware.
Unit tests.
<details> …
> feat: Add focus() method to popover ref

- src/code-editor/status-bar.tsx
- src/code-editor/styles.scss
- src/code-editor/tab-button.tsx
This PR migrates the CodeEditor component to using native CSS container queries and removes the need for a virtual status bar measurment.
> chore: Migrate CodeEditor to native CSS container queries.

- src/code-editor/styles.scss
The CodeEditor was upgraded to use container queries with an anticipated degraded experience in Safari 15 for the remainder of the support cycle. A duplicate text occurrence of the count appears in the UI only for this browser and version. This PR adds an additional @supports query to remove this.
> chore: Improve graceful degradation for CodeEditor in Safari 15.

- src/copy-to-clipboard/__tests__/copy-to-clipboard.test.tsx
- src/copy-to-clipboard/internal.tsx
When a page runs in an insecure context (e.g. plain HTTP), the browser's clipboard API is not available. In this case, the CopyToClipboard component used to get stuck in the pending state. With this change, the component shows the error state instead.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#brows …
> fix: CopyToClipboard is stuck in insecure contexts

- src/table/index.tsx
This change adds metadata for two table inline edit features: 1) inline edit in general, 2) disabled inline edit cells.
<details> …
> chore: Add property metrics for table inline edit

- pages/button-dropdown/checkboxes.page.tsx
- src/button-dropdown/item-element/styles.scss
Updating the indentation of the button dropdown items based on a design review with visual design. Originally part of the button checkbox project, but separated due to a contributor owning that part.
Changes:
- Indent with icons: 8px -> 4px
- Indent inside a category: 32px -> 28px
- Indent of checkbox items in a category: 20px -> 28px
Previous:
New:
<details> …
> fix: Updates indents in button dropdowns

- src/breadcrumb-group/implementation.tsx
- src/internal/widgets/index.tsx
- src/side-navigation/implementation.tsx
Fix type issues and remove the need for manual type declarations
PR build
<details>
- _If the …
> chore: Fix automatic type resolution for createWidgetizedComponent function

- src/app-layout/__tests__/common.test.tsx
- src/app-layout/__tests__/desktop.test.tsx
- src/app-layout/__tests__/drawers.test.tsx
- src/app-layout/__tests__/mobile.test.tsx
- src/app-layout/__tests__/runtime-drawers.test.tsx
- src/app-layout/__tests__/split-panel.test.tsx
- src/app-layout/__tests__/utils.tsx
Merge two very similar helpers `describeEachThemeAppLayout` and `describeEachAppLayout` into one
Test only change. PR build passes
<details> …
> chore: Refactor app layout test helpers

- src/app-layout/__tests__/split-panel.test.tsx
Use `describe.each` instead of manual for-of loop. This makes navigation through the tests easier, as they are logically grouped
PR build
<details> …
> chore: Fix app layout + split panel tests structure

- src/container/internal.tsx
- src/container/styles.scss
- src/table/header-cell/styles.scss
- src/table/styles.scss
This PR updates the colour tokens used for the Table header background. It used to use the Container tokens, even if the table was in the `full-page` variant, which does not have a (visible) container. After this PR, the table uses the page-level colour tokens when it is in the `full-page` variant.
Before
After
Manual testing in the dev pages
<details> …
> fix: Full-page table uses container background colours instead of page background colours

- src/internal/components/tooltip/__tests__/tooltip.test.tsx
- src/internal/components/tooltip/index.tsx
Update tooltip to accept html attributes. Avatar will use it to close the tooltip when tooltip is clicked to have consistency across other tooltip usages (slider, breadcrumb, etc.).
<details> …
> chore: Update tooltip to accept html attributes

- src/container/internal.tsx
- src/container/styles.scss
- src/table/header-cell/styles.scss
- src/table/styles.scss
Reverts cloudscape-design/components#2398
> revert: Revert "fix: Full-page table uses container background colours instead of page background colours"

- src/app-layout/visual-refresh-toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/interfaces.ts
- src/app-layout/visual-refresh-toolbar/notifications/index.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
- src/app-layout/visual-refresh/context.tsx
- src/app-layout/visual-refresh/notifications.tsx
Let's remove `useContainerQuery` from the root app layout component and put it down to the components where it is really needed
* Locally, found no issues in rendering
* PR build and screenshot tests will take care of the rest
<details>
- …
> chore: Move resize observers down to the observed nodes

- src/table/__tests__/a11y.test.tsx
- src/table/table-role/table-role-helper.ts
Valid falsy values strike again! `aria-rowcount` was being set to `-1` (indeterminate), even though the items were very determinately 0.
Related links, issue #, if available: AWSUI-48116
Unit test.
<details> …
> fix: Provide aria-rowcount to table even when totalItemsCount is 0

- pages/app-layout/global-breadcrumbs.page.tsx
- src/app-layout/__integ__/global-breadcrumbs.test.ts
- src/app-layout/__tests__/global-breadcrumbs.test.tsx
- src/app-layout/visual-refresh-toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/interfaces.ts
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
- src/breadcrumb-group/index.tsx
- src/internal/plugins/api.ts
- src/internal/plugins/controllers/breadcrumbs.ts
- src/internal/plugins/helpers/use-global-breadcrumbs.ts
Deduplicate multiple `BreadcrumbGroup` instances across the page and render only one inside the respective app layout slot. Only behind `appLayoutWidget` feature flag, not for production use.
```js
<AppLayout
breadcrumbs={null}
content={<>
<BreadcrumbGroup /> // this one will be rendered in the intended place, even if it did not use the slot
</>}
/>
```
See the tests for more details about order resolution and other corner-cases.
Added unit and integration tests
<details> …
> feat: Support breadcrumb instances deduplication

- .github/workflows/release.yml
Reverts cloudscape-design/components#2420
Our release infra does not support slashes
> revert: Allow release workflow for dev branch with slashes

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/top-navigation/1.0-beta/interfaces.ts
- src/top-navigation/interfaces.ts
When we released the latest update to button dropdowns that added support for checkbox items, we kept top navigation out of scope. We need to update the API documentation to indicate this change, to avoid confusing customers.
<details>
- _Changes …
> chore: Updates TopNav API documentation to remove checkbox item support

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/cards/interfaces.tsx
- src/table/interfaces.tsx
There were two descriptions that mention the high-contrast header for Cards and Table, which have been removed.
<details> …
> chore: Remove mentions of high contrast header from descriptions

- src/property-filter/styles.scss
Fixing an issue when in property filter tokens the token part and operation selector have slightly different height.
Rel: AWSUI-50060
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibil …
> fix: Align property filter token light height with operation selector

- src/__tests__/__snapshots__/design-tokens.test.ts.snap
- style-dictionary/visual-refresh/metadata/colors.ts
Making the notification grey design token public.
AWSUI-48766
<details> …
> chore: Make notification grey token public

- pages/top-navigation/utilities.page.tsx
- src/top-navigation/__tests__/top-navigation.test.tsx
- src/top-navigation/internal.tsx
- src/top-navigation/parts/utility.tsx
Prevent checkbox items from rendering in top navigation. They weren't supposed to be supported, and aren't supported in all variants of top navigation (i.e. not in the mobile version) so it's safer to prevent them from working at all.
Local testing, unit tests
<details> …
> fix: Prevent checkbox items from rendering in top navigation

- src/internal/components/filtering-token/styles.scss
- src/property-filter/styles.scss
The fix addresses the issue introduced in https://github.com/cloudscape-design/components/pull/2443. The consistent line height while makes the token size aligned also increases the space between the token text and the popover underline which is unwanted.
A different mitigation is to use the flex stretch alignment. The root container of the filtering token uses items stretch but that can only work if there is no block size. In that particular case the block size 100% does not work well for different zoom levels.
<details>
- _Changes are backward-compatible if …
> fix: Fix filtering token alignment

- src/file-upload/__tests__/file-upload-dropzone.test.tsx
- src/file-upload/dropzone/index.tsx
As reported in https://github.com/cloudscape-design/components/issues/2427:
Previously, the drop area was only displayed if `DataTransfer.items`contained a file of kind 'file'. This worked in Chrome, Edge, and Firefox, however it did not work on Safari, because `DataTransfer.files` is in protected mode during the `dragover` event ([HTML specs reference](https://html.spec.whatwg.org/multipage/dnd.html#dom-datatransfer-files)).
This change now checks `DataTransfer.types` ([HTML spec reference](https://html.spec.whatwg.org/multipage/dnd.html#dom-datatransfer-types)) for the presence of the 'Files' type to display the drop area, ensuring compatibility across all browsers.
⚠️ Changes: With this change, it's now possible to drag multiple files in a non-multiple zone. When doing so, we already …
> fix: Support dropping files to FileUpload in Safari

- src/internal/components/tooltip/__tests__/tooltip.test.tsx
- src/internal/components/tooltip/index.tsx
Added support for arbitrary React nodes in the internal Tooltip. Previously, it only accepted string and number values. It is now possible to distplay tooltips with components like StatusIndicator inside. 
I've added tests to verify that components are displayed in the Tooltip and that the trackKey is set correctly
<details> …
> feat: support for React.ReactNode values in the internal tooltip

- src/app-layout/visual-refresh-toolbar/skeleton/index.tsx
- src/app-layout/visual-refresh-toolbar/skeleton/styles.scss
Fixing a use-case from this page: https://github.com/cloudscape-design/components/blob/main/pages/app-layout/fill-content-area.page.tsx
it works in old app layout, but broke in the new `visual-refresh-toolbar` mode
Tested using that dev page. No visual regression tests for that mode yet
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/compon …
> chore: Fix content area styles

- src/slider/mixins.scss
- src/slider/styles.scss
Follow up the recent release of read-only states.
1. Fix read-only slider size
2. Prevent hover, focus, and active styles from being applied to the disabled state
<details> …
> fix: Read-only slider fixes

- src/table/body-cell/styles.scss
- src/table/body-cell/td-element.tsx
Update table body cell structure so that expand toggle is outside cell content. That is to support a follow-up change to move cell editing styles to from cell to cell content so that both inline edit trigger and expand toggle can be present in a single cell.
Rel: AWSUI-43194
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#brow …
> chore: Table cell expand toggle is outside cell content

- src/tabs/tab-header-bar.scss
- src/tabs/tab-header-bar.tsx
Undoes regression introduced into VR compact mode in #2435
<details> …
> chore: Fixes tab divider height regression in VR compact mode

- src/area-chart/__tests__/area-chart-model-utils.test.ts
- src/area-chart/model/use-chart-model.ts
- src/area-chart/model/utils.ts
- src/internal/utils/__tests__/circle-index.test.ts
- src/internal/utils/circle-index.ts
- src/mixed-line-bar-chart/hooks/use-navigation.ts
- src/tabs/tab-header-bar.tsx
Reduce code duplication by sharing circle-index util from area chart.
<details>
- _If the …
> refactor: Shared circleIndex util

- pages/button-dropdown/disabled-reason.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/button-dropdown/item-element/index.tsx
- src/button-dropdown/item-element/styles.scss
- src/button-dropdown/tooltip.tsx
- src/button/interfaces.ts
Fixed styles for ButtonDropdown selectable items when disabledReason is present. Updated API description for Button interfaces.
<details> …
> fix: Styles for ButtonDropdown and Button API description

- src/prompt-input/styles.scss
a commit was merged after we moved the mixin to component-toolkit  
<details>
- _If the code …
> fix: Use focus-visible from components-toolkit

- src/app-layout/visual-refresh-toolbar/drawer/index.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
- src/container/internal.tsx
- src/container/styles.scss
- src/split-panel/bottom.tsx
- src/split-panel/styles.scss
Miscellaneous fixes in preparation for usability testing beginning next week.
Fixes bugs 20-22 listed in "App layout bug bash findings" quip.
- Removes excess space above full-page table layouts
- Vertically center resize handle in drawers
- Remove scroll away feature for third round of testing
- Remove split panel bottom closed state 
<details> …
> chore: Misc p0 bug fixes for testing

- src/internal/components/dropdown/styles.scss
Remove `unset` of paddings to drop down left and right positioning between directions.
this `unset` is causing the dropdown to go out of page boundaries in RTL
to reproduce: open top left or bottom left dropdown in the following links
Related links, issue #, if available: AWSUI-50831
tested with screenshot tests, the issue currently exist after the change the issue is resolved. 
<details> …
> fix: Keep padding when opening dropdown on right or left

- src/button/__tests__/analytics-metadata.test.tsx
- src/button/analytics-metadata/interfaces.ts
- src/button/analytics-metadata/styles.scss
- src/button/index.tsx
- src/button/internal.tsx
- src/internal/__tests__/analytics-metadata-test-utils.ts
First implementation of analytics instrumentation
<details> …
> feat: Decorate button component with analytics metadata

- src/internal/context/single-tab-stop-navigation-context.tsx
- src/table/table-role/grid-navigation.tsx
- src/tabs/tab-header-bar.tsx
A small improvement for single tab stop navigation context. To be also consumed here by the new button group component: https://github.com/cloudscape-design/components/pull/2469
* Existing unit- and integration tests
* Manual tests
<details>
- …
> refactor: Single tab stop navigation simpler unregistering

- pages/annotation-context/with-switching-pages.page.tsx
- src/annotation-context/__integ__/switching-pages.test.ts
- src/annotation-context/index.tsx
AWSUI-51612
**Problem**
When 2 pages have connected hotspots and loading states for transition between them, after loading a new page, the next hotspot in not automatically shown.
**Root cause**
[useEffect](https://github.com/cloudscape-design/components/blob/main/src/annotation-context/index.tsx#L87) responsible for opening the next hotspot is called before the next hotspot is registered on the page, so [this object](https://github.com/cloudscape-design/components/blob/main/src/annotation-context/index.tsx#L95) would be empty.
**Solution**
Added `availableHotspots` to the `useEffect` dependency array to ensure the useEffect picks up the latest changes from newly registered hotspot. Adding `availableHotspots` to the dependency array does not causing infinite loop, because they are not …
> fix: Problem with hotspot component within annotation context

- pages/button-group/item-permutations.page.tsx
- pages/button-group/permutations.page.tsx
- pages/button-group/test.page.tsx
- src/button-group/__integ__/button-group.test.ts
- src/button-group/__tests__/button-group.test.tsx
- src/button-group/icon-button-item.tsx
- src/button-group/item-element.tsx
- src/button-group/menu-dropdown-item.tsx
> fix: Button group tooltip fix for items w/o popover, loading and disabled items

- src/button-dropdown/internal.tsx
- src/button-dropdown/styles.scss
There was an unwanted gap in drop down button which was only visible in "normal" variant.
**This PR removes the gap.**
Related links, issue #, if available: AWSUI-48343
Tested and verified using the dev run with Chrome, Firefox and Safari.
<details> …
> fix: Removed gap from the normal variant of the button-dropdown

- .eslintrc.js
- build-tools/stylelint/__tests__/license-headers.test.js
- build-tools/stylelint/__tests__/no-implicit-descendant.test.js
- build-tools/stylelint/__tests__/no-motion-outside-of-mixin.test.js
- build-tools/stylelint/index.js
- pages/app-layout/multi-layout-iframe.page.tsx
- pages/app-layout/multi-layout-simple.page.tsx
- src/app-layout/__integ__/multi-app-layout.test.ts
- src/app-layout/__tests__/background-overlap.test.tsx
- src/app-layout/__tests__/common.test.tsx
- src/app-layout/__tests__/desktop.test.tsx
- src/app-layout/__tests__/drawers.test.tsx
- src/app-layout/__tests__/global-breadcrumbs.test.tsx
- src/app-layout/__tests__/header-variant.test.tsx
- src/app-layout/__tests__/i18n.test.tsx
- src/app-layout/__tests__/main.test.tsx
- src/app-layout/__tests__/mobile.test.tsx
- src/app-layout/__tests__/runtime-drawers.test.tsx
- src/app-layout/__tests__/slots.test.tsx
- src/app-layout/__tests__/split-panel-provider.test.tsx
- src/app-layout/__tests__/split-panel.test.tsx
- src/app-layout/__tests__/tools.test.tsx
- src/app-layout/__tests__/warnings.test.tsx
Disable eslint import sort rule for app-layout tests because of a circular dependencies, which breaks the tests.
Raised eslint import sort rule to error.
<details> …
> fix: Disable import sort rule for app-layout tests 

- src/drawer/implementation.tsx
- src/help-panel/implementation.tsx
- src/side-navigation/implementation.tsx
- src/split-panel/implementation.tsx
- src/split-panel/side.tsx
Fix a merge conflict between https://github.com/cloudscape-design/components/pull/2497 and https://github.com/cloudscape-design/components/pull/2482
PR build is green now 
* `Measure bundle size / measure` fails because it cannot load the baseline data from the mainline
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CO …
> chore: Fix build

- src/app-layout/visual-refresh-toolbar/skeleton/styles.scss
Usage of wrong grid area names led to very unfortunate layouts on mobile.
Locally
Mobile grid layout order should appear as indicated in the template.
```
<toolbar>
<notifications>
<main>
```
<details> …
> fix: Toolbar mobile grid layout

- pages/table/permutations.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/table/__tests__/body-cell.test.tsx
- src/table/body-cell/styles.scss
- src/table/body-cell/td-element.tsx
- src/table/interfaces.tsx
- src/table/internal.tsx
This PR adds a small property to table cells that allows the content to be aligned vertically.
Part of the track two tickets for the P&C squad in Q3.
<details> …
> feat: Adds verticalAlign property to table cells

- pages/progress-bar/permutations-flash.page.tsx
- src/progress-bar/styles.scss
- style-dictionary/utils/token-names.ts
- style-dictionary/visual-refresh/colors.ts
- style-dictionary/visual-refresh/contexts/flashbar-warning.ts
Reverts cloudscape-design/components#2480
Progress bar color styling was no longer being applied in Chrome for some reason. My working guess is that it's now defined in the same rule next to the -moz- styling, and that breaks it somehow? Reverting to unblock our releases.
> revert: Revert "fix: Improve progress bar color contrast in warning flash message"

- pages/app-layout/multi-layout-simple.page.tsx
- src/app-layout/__tests__/global-breadcrumbs.test.tsx
- src/app-layout/__tests__/multi-layout.test.tsx
- src/app-layout/visual-refresh-toolbar/compute-layout.ts
- src/app-layout/visual-refresh-toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/multi-layout.ts
- src/app-layout/visual-refresh-toolbar/navigation/index.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/drawer-triggers.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
- src/internal/plugins/api.ts
- src/internal/plugins/controllers/__tests__/app-layout-widget.test.ts
- src/internal/plugins/controllers/app-layout-widget.ts
- src/internal/plugins/helpers/use-global-breadcrumbs.ts
Allow multiple app layouts to collaborate and render a single UI
1. Added unit tests
2. Integration tests are done on these dev pages: https://github.com/cloudscape-design/components/pull/2486
<details> …
> feat: Allow multiple app layouts rendered on a page (feature-flag only)

- src/pie-chart/__integ__/pie-chart.test.ts
- src/pie-chart/__tests__/pie-chart.test.tsx
- src/pie-chart/pie-chart.tsx
- src/pie-chart/segments.tsx
Ensure that touches/taps always fully open the popover, and don't leave it in "hover"-style state if the touch
is somehow interrupted.
Related links, issue #, if available: AWSUI-46115
Tested locally. Due to the combination of this only happening on touch devices, and only when tapping certain parts of certain segments, it's not easy to test in any of our existing integration or visual regression test suites.
<details> …
> fix: Improve touch handling in pie-chart

- pages/key-value-pairs/text-wrap.page.tsx
- src/column-layout/__tests__/with-css.test.tsx
- src/column-layout/flexible-column-layout/index.tsx
AWSUI-52998
Replaced `1fr` with `minmax(0, 1fr)` in layout columns, because `1ft` is equivalent to `minmax(auto, 1fr)` that prevents proper text-wrapping. 
<details> …
> fix: Column layout text wrapping

- src/app-layout/__tests__/multi-layout.test.tsx
- src/app-layout/__tests__/toolbar.test.tsx
- src/app-layout/visual-refresh-toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/multi-layout.ts
- src/app-layout/visual-refresh-toolbar/toolbar/drawer-triggers.tsx
Fix some bugs, follow up for https://github.com/cloudscape-design/components/pull/2429
1. `navigationHide` is not respected
2. When there are no features, empty toolbar is rendered
* Locally
* Screenshot tests in my dev-pipeline (where all of these were found)
<details> …
> chore: Fix app layout toolbar bugs

- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
Fixed a widgetization issue. `AppLayoutToolbarImplementation` and `AppLayoutVisualRefreshToolbar` components may be coming from different versions, in which case `toolbarProps` is undefined
Not testable in a single-version dev page
<details>
- …
> chore: Allow toolbar props to be empty in visual-refresh-toolbar app layout

- pages/s3-resource-selector/data/i18n-strings.ts
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/s3-resource-selector/__tests__/fixtures.ts
- src/s3-resource-selector/__tests__/main.test.tsx
- src/s3-resource-selector/interfaces.ts
- src/s3-resource-selector/s3-modal/__tests__/fetching.test.tsx
- src/s3-resource-selector/s3-modal/basic-table.tsx
- src/s3-resource-selector/s3-modal/styles.scss
Adds `Last Updated` to the S3 resource selector modal.
The addition of this text should help the screen readers to inform the users once the fetch process is finished.
Related links, issue #, if available: AWSUI-41521
Manually tested on Chrome, Firefox & Safari.
Automated testing _in progress_.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#bro …
> feat: add loading a11y to s3 selectors for screen readers

- pages/app/index.tsx
- src/app-layout/__tests__/app-layout.ssr.test.tsx
- src/app-layout/internal.tsx
- src/app-layout/utils/feature-flags.ts
- src/drawer/implementation.tsx
- src/internal/plugins/helpers/use-global-breadcrumbs.ts
- src/side-navigation/implementation.tsx
- src/split-panel/bottom.tsx
- src/split-panel/implementation.tsx
- src/split-panel/side.tsx
Support activating app layout toolbar UI only, without the widgetization.
Ran locally, works.
The PR build will pass after this change is released: https://github.com/cloudscape-design/component-toolkit/pull/86
<details> …
> chore: Support appLayoutToolbar feature flag

- src/split-panel/implementation.tsx
- src/split-panel/index.tsx
Move i18n provider resolution from `src/split-panel/implementation.tsx` to `src/split-panel/index.tsx`.
This is needed to resolve i18n strings inside the application context, instead of widget
PR build passes. No functional changes for the non-widget mode
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#b …
> chore: Resolve split panel i18n strings in the public component part

- src/button-dropdown/styles.scss
Fixes the issue with drop down button arrow going behind container's background.
Related links, issue #, if available: AWSUI-53531
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility …
> fix: fixes the z-index offset.

- src/code-editor/resizable-box/styles.scss
Mirror resize icon of Code Editor when viewed in a RTL document.
Related links, issue #, if available: AWSUI-53401
Before
After
Viewable on dev page locally. Seems our [deployed dev pages](https://d21d5uik3ws71m.cloudfront.net/components/dea4ef812982c3fa6ad84b48d6aac6ec547ba84a/dev-pages/index.html#/light/code-editor/simple?direction=rtl) CSP do not allow the icon to be viewed. …
> chore: Fix resize icon of Code Editor for RTL

- src/__tests__/__snapshots__/test-utils-selectors.test.tsx.snap
- src/property-filter/__tests__/property-filter-token-editor.test.tsx
- src/property-filter/token-editor.tsx
- src/test-utils/dom/property-filter/index.ts
AWSUI-22585
Turned token editor popover into `form` and make it submit on `onSubmit` event.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibil …
> feat: Make token editor form submit on onSubmit event

- pages/app-layout/runtime-drawers-with-updates.page.tsx
- src/app-layout/__integ__/runtime-drawers-with-updates.test.ts
- src/app-layout/__tests__/runtime-drawers.test.tsx
- src/internal/plugins/__tests__/api.test.ts
- src/internal/plugins/controllers/__tests__/drawers.test.ts
- src/internal/plugins/controllers/drawers.ts
Support `updateDrawer` in AppLayout plugins API
Currently, there is only option to register a Drawer, there is no support to update a registered drawer. Such updates includes badge, resizable, orderPriority, and others
Related links
- Linked to previous [pull request](https://github.com/cloudscape-design/components/pull/2476).
<details> …
> feat: support updateDrawer in AppLayout plugins API

- src/pagination/__tests__/pagination.test.tsx
- src/test-utils/dom/pagination/index.ts
AWSUI-53414
Added `isDisabled` method for pagination test-utils.
<details>
- _If the code …
> feat: isDisabled method for pagination test-utils

- pages/toggle-button/test-hover.page.tsx
Added a new page for the toggle button with test IDs that reflect the button's states to test hover behavior in screenshot tests.
<details> …
> chore: Add a page for the toggle button to test hover styles

- src/internal/components/token-list/styles.scss
Safari flexbox quirks does not calculate the height of the parent correctly.
Related links, issue #, if available: https://github.com/cloudscape-design/components/issues/2433
<details> …
> fix: Safari token gap in FileUpload with multiple files

- src/table/__integ__/keyboard-scroll.test.ts
Fixing a flaky integ test in a table that started to fail with an update of chromedriver.
<details> …
> chore: Fix flaky table keyboard scroll test

- src/property-filter/__tests__/property-filter-token-list.test.tsx
- src/property-filter/token.tsx
Reverts an accidental change from https://github.com/cloudscape-design/components/pull/2510 that made all properties label visible in the token. Use an empty string for that case instead.
<details> …
> fix: Revert change to visible all properties label

- src/__tests__/__snapshots__/test-utils-selectors.test.tsx.snap
- src/tabs/__tests__/tabs.test.tsx
- src/tabs/tab-header-bar.scss
- src/tabs/tab-header-bar.tsx
- src/tabs/test-classes/styles.scss
- src/test-utils/dom/tabs/index.ts
Fixing tabs test utils for dismiss button so that the selectors return the button and not its wrapper.
Rel: [AWSUI-54108]
* Updated existing unit tests
* Dry-run to live
<details> …
> fix: Fix tabs dismiss button test-utils

- src/button-group/__integ__/button-group.test.ts
- src/button-group/item-element.tsx
Fixing an issue when tooltip is shown after a menu closes with mouse click, keyboard select, or Escape keypress.
* New integration tests
<details> …
> fix: Button group show no tooltip when menu closes

- src/area-chart/chart-container.tsx
- src/area-chart/internal.tsx
- src/internal/components/cartesian-chart/block-end-labels.tsx
- src/mixed-line-bar-chart/chart-container.tsx
X-axis labels in mixed line-bar chart didn't respect document's direction. This PR fixes it.
Bonus: Area-chart fix
Related links, issue #, if available: AWSUI-53402
- manually
- dev-pipeline - IN-PROGRESS
<details> …
> fix: Adjust inline offset in chart X-axis based on direction

- src/internal/utils/__tests__/dom.test.ts
- src/internal/utils/dom.ts
- src/internal/utils/handle-key.ts
- src/internal/utils/node-belongs.ts
Fixing an issue when element instanceof Node/HTMLElement/SVGElement would not work when the window of the element is different from the window of the respective type.
Similar fix: https://github.com/cloudscape-design/component-toolkit/pull/44
Rel: [AWSUI-53831]
* Manual testing in an environment with an iframe
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CON …
> fix: Fix nodeBelongs utility for iframes

- src/app-layout/__tests__/widget-compatibility.test.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
The main `<AppLayout>` component and its `<AppLayoutToolbarImplementation />` may come from different versions.
Support some backward compatibility via providing some aliases for props
Added some tests
<details> …
> chore: Add cross-version compatbility in app layout internals

- src/app-layout/visual-refresh-toolbar/skeleton/styles.scss
Fixed a style issue caused by `.unfocusable-mobile * { visibility: visible; }` apply to broad. This rule appeared to be more specific than this one, for example: https://github.com/cloudscape-design/components/blob/054641066605387c974d0fde8d5cb096743a3618/src/internal/components/cartesian-chart/styles.scss#L73-L74
Related links, issue #, if available: AWSUI-53899
Screenshot tests in my dev pipeline. [This demo](https://github.com/cloudscape-design/demos/tree/main/src/pages/configurable-dashboard) reproduces the issue.
<details> …
> fix: Fix visibility styles for mobile mode in toolbar app layout

- pages/autosuggest/events.page.tsx
- src/autosuggest/__integ__/events-autosuggest.test.ts
- src/autosuggest/__tests__/options-controller.test.ts
- src/autosuggest/options-controller.ts
- src/property-filter/index.tsx
Fixing an inconsistency in the events handling
1. When the input field is focused, pressing enter closes the dropdown, but no `onSelect` event fired
2. When the "Use current value" option is focused, the dropdown closes, with an `onSelect` event
Both interactions are the same for the end user – the dropdown closes while keeping the current value, so they should produce the same event.
For the context, this is a long way to fix AWSUI-53412. In that issue on our website there is a bug with the search autosuggest. It uses a workaround for the missing event. After this event is added, we can remove the workaround
Locally + updated existing events test to include the new events.
Dry-runs if anybody relied on the broken behavior: 6982713945, 6982715033, …
> fix: Consistently fire onSelect even when closing the dropdown

- pages/select/generate-options.ts
- pages/select/item.permutations.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/internal/components/option/interfaces.ts
- src/multiselect/__tests__/i18n.test.tsx
- src/multiselect/__tests__/multiselect.test.tsx
- src/select/__tests__/select.test.tsx
- src/select/interfaces.ts
- src/select/parts/item.tsx
- src/select/parts/multiselect-item.tsx
Enhancing Select and Multiselect option group type with features such as description, tags, labelTag and more.
Rel:
* AWSUI-54638
* [1YVQAGeLk8iH]
* Unit tests
<details> …
> feat: Support for option group features in Select and Multiselect

- pages/table/permutations.page.tsx
- src/table/styles.scss
When a table has a sticky header and doesn't have anything in the header slot, the table top border doesn't have the right border radius.
in this PR I used the border radius design token instead of the previous 0 value.
- added a new permutation to cover the case
- ran visual regression tests in dev pipeline.
<details> …
> fix: Use border radius design token for column headers in sticky header table

- src/table/body-cell/styles.scss
Fixing table cell spacing to give space for the focus outlines of the cell content.
The cell can include various focusable content such as links, buttons, button dropdown, popover trigger and more. The cells are also focusable when keyboard navigation is on or when editable.
The cell content includes overflow hidden to prevent cell content to exceed cell boundaries and the inline content is truncated with ellipsis (...). However, that style also makes the focus outline of the content being cut off as we add it with an absolute position and some negative offset to render around the element within some distance.
Before:
After:
Rel: AWSUI-53403
* Manual testing
* Existing and new screenshot tests [CR-143543797]
<details> …
> fix: Fixed table cell overflow

- src/button-dropdown/__tests__/analytics-metadata.test.tsx
- src/button-dropdown/analytics-metadata/interfaces.ts
- src/button-dropdown/item-element/index.tsx
Additional property, needed, for example, for Breadcrumb Group
<details> …
> feat: Add href in analytics metadata of button-dropdown

- pages/copy-to-clipboard/simple.page.tsx
- src/copy-to-clipboard/internal.tsx
- src/copy-to-clipboard/styles.scss
Prevent copy-to-clipboard trigger text from wrapping to a separate line in tables
Related links, issue #, if available: AWSUI-54773
- In my dev pipeline
- new screenshot test added
<details> …
> fix: Do not wrap text after icon in copy-to-clipboard

- src/app-layout/__tests__/global-breadcrumbs.test.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
- src/breadcrumb-group/__tests__/analytics-metadata.test.tsx
- src/breadcrumb-group/analytics-metadata/interfaces.ts
- src/breadcrumb-group/analytics-metadata/styles.scss
- src/breadcrumb-group/implementation.tsx
- src/breadcrumb-group/index.tsx
- src/breadcrumb-group/interfaces.ts
- src/breadcrumb-group/item/funnel.tsx
- src/button-dropdown/__tests__/analytics-metadata.test.tsx
- src/button-dropdown/interfaces.ts
- src/button-dropdown/internal.tsx
- src/button-dropdown/item-element/index.tsx
- src/button-dropdown/items-list.tsx
Similar to https://github.com/cloudscape-design/components/commit/dde24620bceb97c2fd3e59aa45b0e95af8402313, however it required to add properties to other components including:
- Button dropdown
- to surface the right information from custom triggers
- to process analytics properties set by the button dropdown, which do not make sense for Breadcrumbs
- App layout, to test that widgetized breadcrumbs are also decorated with analytics information
<details> …
> feat: Add analytics metadata to BreadcrumbGroup

- pages/property-filter/common-props.tsx
- pages/property-filter/custom-forms.tsx
- pages/property-filter/property-filter-editor-permutations.page.tsx
- pages/property-filter/property-filter-tokens-permutations.page.tsx
- pages/property-filter/token-editor.page.tsx
- src/popover/container.scss
- src/popover/container.tsx
- src/popover/internal.tsx
- src/property-filter/__tests__/property-filter-token-editor.test.tsx
- src/property-filter/filtering-token/__tests__/filtering-token.test.tsx
- src/property-filter/filtering-token/index.tsx
- src/property-filter/index.tsx
- src/property-filter/internal.tsx
- src/property-filter/styles.scss
- src/property-filter/token-editor.tsx
- src/property-filter/token.tsx
Pass internal token editor props via property filter internal to feature the new editor in the editor test page.
Added a change to popover internal to allow no size setting: that is something we implicitly support as passing a size not matching small, medium or large does the same.
* New test page asset
* Existing token editor permutations
* Existing unit- and integration tests
<details> …
> chore: Property filter token editor integration

- src/internal/components/tooltip/index.tsx
Reuse Popover arrow component for internal tooltip to make borders consistent
Related links, issue #, if available: AWSUI-55554
* Dev pipeline 
<details> …
> fix: Align border width of the popover arrow between components

- src/app-layout/__integ__/global-breadcrumbs.test.ts
- src/app-layout/internal.tsx
- src/app-layout/utils/feature-flags.ts
- src/drawer/implementation.tsx
- src/help-panel/implementation.tsx
- src/internal/plugins/helpers/use-global-breadcrumbs.ts
- src/side-navigation/implementation.tsx
- src/split-panel/bottom.tsx
- src/split-panel/implementation.tsx
- src/split-panel/side.tsx
Fixed a bug where some toolbar-only changes could leak into the classic design
Added an integration test
<details> …
> fix: Fix toolbar feature flag detection to only apply in visual refresh mode

- pages/table/permutations.page.tsx
- src/app-layout/classic.tsx
When the split panel is positioned at the bottom, it does not calculate correctly its available horizontal space in Classic if a drawer is active which has a `defaultSize` such that it won't fit into the available space for the drawers. (The drawer itself will narrow itself down as expected, but the bottom split panel will not calculate that narrowing, resulting in empty space between the split panel and the drawer).
Issue #: AWSUI-55244
- Manually by following the steps in the aforementioned ticket
- I am adding a test in the pipeline (CR-144062151)
<details> …
> fix: Use correct width for bottom split panel when drawer is present

- pages/table/permutations.page.tsx
Issue: AWSUI-56245
Also related: AWSUI-56256
Manually tested by following these steps:
- Open the page in two tabs and simulate a 500px-wide device in each using the browser's built-in device simulator
- Reload the page only for one of the tabs
- Switch tabs and check for the difference in the table header of the last table
The steps above made the issue reproducible before the changes and not after the changes.
We will be able to verify that the test works without flakiness once the updated test page is deployed on both stages.
<details> …
> chore: Make column widths fixed to workaround flaky test

- src/table/__integ__/sticky-header.test.ts
- src/table/__tests__/resizable-columns.test.tsx
- src/table/use-column-widths.tsx
- src/table/use-sticky-header.ts
Applied two updates to table sticky header width sync:
1. Use bounding client rect width instead of overflow width to remove error caused by rounding
2. Use request animation frame when sync width with observer to give browser more time to settle column widths
Rel: AWSUI-56256
* Manual checks
* Updated integ test
<details> …
> fix: Resolved table sticky header misalignment

- src/app-layout/visual-refresh-toolbar/toolbar/styles.scss
fixing the focus indicatory styling on the visual refresh toolbar  where the indicator styling was being cur off by parent elements. 
Here the parent elements all have a height adjusted to 100% of the toolbar and the items aligned to the center, which allows for the indicator styling on the top and the bottom to be seen like such
Also in this PR, the horizontal padding of the toolbar is set in two different elements. The left side remains in the `.universal-toolbar` with the right padding set as zero and the matching right padding is set in its child element with `.drawers-desktop-triggers-container, .drawers-mobile-triggers-container`. This allows for the right side styling of the focus indicator on the last item to show correctly
This bug has …
> fix: fix focus indicator styling issue (vr-toolbar flag only) 

- src/collection-preferences/index.tsx
- src/internal/context/collection-preferences-metadata-context.ts
- src/table/index.tsx
Supporting an automated internal use of the component metrics. We can use these metrics to find more complex components/patterns that don't match up with our usage guidelines and UX best practices (like uses of sticky headers, or not allowing disabling table features enabled by default). Keeping details out of this public PR, but feel free to reach out. Adding another context felt safe because it's only used internally, there isn't a wide gap between the components (as in, unlikely to be split across bundles), and it doesn't break any end-user experience if it doesn't match up. Maybe long-term, this could be "generified" into a linting context or something, but not for now.
No coded test, just manually made sure the shape/values align with …
> chore: Add additional metadata metrics to table and collection preferences

- pages/dropdown/expandable.page.tsx
- pages/property-filter/async-loading.integ.page.tsx
- pages/property-filter/common-props.tsx
- pages/property-filter/hooks.page.tsx
- pages/property-filter/permutations.page.tsx
- pages/property-filter/split-panel-app-layout-integration.page.tsx
- pages/property-filter/token-editor.page.tsx
- pages/table/permutations.page.tsx
Remove usage of deprecated labels and add i18n provider to one of the property filter test pages
* Manual check
* Existing a11y tests
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibil …
> refactor: Replace deprecated i18n strings with labels

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/i18n/messages-types.ts
- src/property-filter/__tests__/property-filter-i18n.test.tsx
- src/property-filter/i18n-utils.ts
- src/property-filter/interfaces.ts
- src/property-filter/internal.tsx
- src/property-filter/token.tsx
Introducing new i18n string for property filter. The related i18n messages will come later, but before the messages are available the string `{propertyLabel} {operator} {value}` is used as default which is the same label that is used currently.
Rel: [tB42A7nNaXZN]
* Updated unit test
* Manual checks with and without i18n provider
<details> …
> feat: New property filter i18n.formatToken function

- src/button-dropdown/__tests__/button-dropdown.test.tsx
- src/button-dropdown/internal.tsx
Fixes a bug when button dropdown ARIA label is not assigned when external icon is not set.
The bug was discovered when implementing: https://github.com/cloudscape-design/components/pull/2603
<details> …
> fix: Fixes button dropdown main action aria label

- CONTRIBUTING.md
- build-tools/tasks/integ.js
- build-tools/tasks/motion.js
Adjust NodeJS config so that jest tests can cope with ESM (see https://jestjs.io/docs/ecmascript-modules). This is so that we can upgrade webdriverio, which is distributed as ESM in recent versions.
Related links, issue #, if available: AWSUI-51276
Tested in local workspace with upgraded version of webdriverio (https://github.com/cloudscape-design/browser-test-tools/pull/86)
<details> …
> chore: Add support for ESM in jest

- src/app-layout/__tests__/multi-layout.test.tsx
- src/app-layout/__tests__/toolbar.test.tsx
- src/app-layout/test-classes/styles.scss
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
This will be used in integration tests to detect which app layout version is currently running.
Not exposed as a public test util, because which app layout design is used is still our internal implementation detail (may change in the future)
Updated related unit tests which currently use an unreliable class name
<details> …
> chore: Add deterministic app layout toolbar selector

- src/property-filter/controller.ts
- src/property-filter/internal.tsx
- src/property-filter/property-editor.tsx
- src/property-filter/token.tsx
Refactor property filter controller so that:
* Focusing logic is moved to the component;
* Match tokens logic is consolidated in the controller (the controller operates internal objects and transforms to external).
<details> …
> refactor: Property filter controller operates internal objects

- src/app-layout/__tests__/toolbar.test.tsx
- src/app-layout/resize/styles.scss
- src/app-layout/visual-refresh-toolbar/compute-layout.ts
- src/app-layout/visual-refresh-toolbar/drawer/index.tsx
- src/app-layout/visual-refresh-toolbar/drawer/styles.scss
- src/app-layout/visual-refresh-toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/navigation/index.tsx
- src/app-layout/visual-refresh-toolbar/navigation/styles.scss
- src/app-layout/visual-refresh-toolbar/skeleton/index.tsx
- src/app-layout/visual-refresh-toolbar/skeleton/styles.scss
- src/app-layout/visual-refresh-toolbar/toolbar/drawer-triggers.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/styles.scss
Adjust the orientation of the toolbar so it is positioned above the drawers to support the asks from Sidecar team.
This commit also adds a divider between the split panel and the other drawers.
<details> …
> feat: Update toolbar layout so it spans full page width (non-deduplicated)

- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
Fixing widgetization issue. `breadcrumb-group/implementation` contains the pure (non-widgetized) component. Using `breadcrumb-group/internal` loaded the widgetized breadcrumbs which were running another loop of widgetization inside the already widgetized app layout toolbar.
Fixing the import removes some unnecessary side effects
PR build. [This test suite](https://github.com/cloudscape-design/components/blob/main/src/app-layout/__tests__/global-breadcrumbs.test.tsx) will capture possible issues
<details> …
> chore: Fix incorrect import

- src/app-layout/__integ__/app-layout-focus-delegation.test.ts
- src/app-layout/visual-refresh-toolbar/index.tsx
- Manages the focus from the toolbar trigger button to inside the drawers when opened and returns that focus to the toolbar trigger when closed 
- This only applies focus changes for the drawers, not split panel. That will come in a follow up
- Here we also tests for the focus delegation for the AppLayout component. We skip the tests with known issues that will be addressed in follups pull request
Test added and skipped where needed
Go to https://d21d5uik3ws71m.cloudfront.net/components/42a4e8c5a4fa120648dc84733850516790b93a18/dev-pages/index.html?visualRefresh=true&appLayoutWidget=true#/light/app-layout/with-drawers?visualRefresh=true&appLayoutWidget=true
- click a drawer trigger (any button in the toolbar except the first (that opens a split …
> chore: updating toolbar focus to inside the drawers and enhance focus delegation test for app layout to include appLayoutWidget param

- src/container/index.tsx
- src/expandable-section/index.tsx
- src/form-field/index.tsx
- src/form/index.tsx
- src/table/index.tsx
- src/wizard/index.tsx
Add analytics metadata properties to be logged on render to better capture adoption.
<details> …
> chore: Log analyticsMetadata properties

- src/app-layout/__tests__/drawers.test.tsx
- src/app-layout/__tests__/trigger-button.test.tsx
- src/app-layout/visual-refresh/drawers.tsx
Uses the selected prop in the TriggerButton for visual refresh.  
Added unit tests so this will be detected before making it to visual tests
This fixes the issue the visual tests have detected, and they will pass. Follow up to https://github.com/cloudscape-design/components/pull/2594
- On local host, visually
- adding unit tests for trigger-button
- adding unit tests for drawers
<details> …
> chore: adding selected prop to drawers and unit tests

- pages/table/sticky-columns.page.tsx
- src/table/body-cell/styles.scss
- src/table/header-cell/styles.scss
Fixing a bug when first sticky column padding is missing in VR
Rel: AWSUI-57462
* Manual tests in Classic, VR, with compact mode, with striped rows
* New screenshot tests, see: CR-146133400
<details> …
> fix: Fixes table sticky col padding in vr

- src/app-layout/__tests__/global-breadcrumbs.test.tsx
- src/app-layout/__tests__/multi-layout.test.tsx
- src/internal/plugins/controllers/__tests__/app-layout-widget.test.ts
- src/internal/plugins/controllers/app-layout-widget.ts
Follow up for https://github.com/cloudscape-design/components/pull/2624
After the design changes, we need to render the toolbar on the first app layout in the stack, not last
Updated related unit tests to reflect the new behavior
<details>
- …
> chore: Update app layout deduplication order

- pages/button-dropdown/main-action.page.tsx
- src/button-dropdown/__integ__/performance-marks.test.ts
- src/button-dropdown/internal.tsx
- src/button/internal.tsx
All primary buttons (including the button dropdown) emit a performance mark when they are rendered, to allow for measuring the page load performance. When a button dropdown had a primary action, there was a bug: it emits _two_ performance marks (one for the main action, and one for the dropdown trigger), while it should emit only one.
This PR fixes that bug, by suppressing any performance marks in the dropdown trigger.
Related links, issue #, if available: AWSUI-57722
Added a new integration test. The test is mostly copied from the same test for the Button component ([button/\_\_integ\_\_/performance-marks.test.ts](https://github.com/cloudscape-design/components/blob/main/src/button/__integ__/performance-marks.test.ts)).
<details>
_The following items …
> fix: Button dropdown with main action creates duplicate performance mark

- pages/button-dropdown/permutations-main-action.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/button-dropdown/interfaces.ts
- src/button-dropdown/internal.tsx
- src/button-dropdown/styles.scss
- make `text` property in `mainAction` optional
- remove extra padding when there is no text in main action using the same padding as dropdown trigger
Related links, issue #, if available: HgxDAw1K2GBU
added new permutations
<details> …
> feat: Support icon only main action in button dropdown

- pages/property-filter/common-props.tsx
- pages/property-filter/custom-forms.tsx
- pages/property-filter/property-filter-editor-permutations.page.tsx
- pages/property-filter/split-panel-app-layout-integration.page.tsx
- pages/property-filter/token-editor.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/autosuggest/options-controller.ts
- src/property-filter/__tests__/common.tsx
- src/property-filter/__tests__/property-filter-i18n.test.tsx
- src/property-filter/__tests__/property-filter-token-editor.test.tsx
- src/property-filter/__tests__/property-filter-token-list.test.tsx
- src/property-filter/controller.ts
- src/property-filter/filtering-token/__tests__/filtering-token.test.tsx
- src/property-filter/i18n-utils.ts
- src/property-filter/interfaces.ts
- src/property-filter/internal.tsx
- src/property-filter/styles.scss
- src/property-filter/token-editor.tsx
- src/property-filter/token.tsx
- src/property-filter/utils.ts
- src/test-utils/dom/property-filter/index.ts
Introducing property filter token groups as an internal feature first.
Depends on https://github.com/cloudscape-design/collection-hooks/pull/74
Rel: [qUFhApKfmWEg]
* Manual testing
* Bug bash
<details> …
> chore: Property filter token groups internal feature

- src/autosuggest/autosuggest-option.tsx
- src/internal/__tests__/analytics-metadata-test-utils.ts
- src/internal/components/option/analytics-metadata/styles.scss
- src/internal/components/option/option-parts.tsx
- src/internal/components/selectable-item/__tests__/analytics-metadata.test.tsx
- src/internal/components/selectable-item/analytics-metadata/interfaces.ts
- src/internal/components/selectable-item/analytics-metadata/styles.scss
- src/internal/components/selectable-item/analytics-metadata/utils.ts
- src/internal/components/selectable-item/index.tsx
- src/internal/components/selectable-item/interfaces.ts
- src/select/parts/item.tsx
- src/select/parts/multiselect-item.tsx
Needed to introduce analytics metadata for Select, Multiselect, Autosuggest, Property filter.
Note that it depends on https://github.com/cloudscape-design/component-toolkit/pull/94
<details> …
> feat: Add analytics metadata to internal Selectable item component

- package-lock.json
- pages/expandable-section/permutations.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/expandable-section/__tests__/expandable-section.test.tsx
- src/expandable-section/expandable-section-header.tsx
- src/expandable-section/interfaces.ts
- src/expandable-section/styles.scss
- src/expandable-section/utils.ts
Add `disablePaddings` property to ExpandableSection to allow removing padding from `default` and `footer` variants.
This allows the component to be used more flexibly in different scenarios (e.g. within an Alert)
Added new permutations.
<details> …
> feat: Add new expandable-section 'inline' variant

- src/collection-preferences/__integ__/collection-preferences.test.ts
- src/collection-preferences/__integ__/pages/collection-preferences-page.ts
- src/collection-preferences/content-display/__integ__/content-reordering.test.ts
- src/collection-preferences/content-display/__integ__/pages/content-display-page.ts
- src/mixed-line-bar-chart/__integ__/mixed-line-bar-chart.test.ts
- src/table/__integ__/sticky-scrollbar.test.ts
Related to https://github.com/cloudscape-design/browser-test-tools/pull/105 (see dry-run test failures).
Switching to Chromium --headless=new causes failures to our tests that depend on screen size. The refactoring fixes the issue for some of the app layout tests to either remove the dependency completely or make assertions depend on the measured viewport height.
Previous PR: https://github.com/cloudscape-design/components/pull/2657
* Verified the tests work with old and new headless mode
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/ …
> refactor: Update integration tests to resolve chromium upgrade 2

- src/i18n/messages/all.ar.json
- src/i18n/messages/all.de.json
- src/i18n/messages/all.en-GB.json
- src/i18n/messages/all.es.json
- src/i18n/messages/all.fr.json
- src/i18n/messages/all.id.json
- src/i18n/messages/all.it.json
- src/i18n/messages/all.ja.json
- src/i18n/messages/all.ko.json
- src/i18n/messages/all.pt-BR.json
- src/i18n/messages/all.tr.json
- src/i18n/messages/all.zh-CN.json
- src/i18n/messages/all.zh-TW.json
New i18n messages for property filter
<details> …
> chore: I18n messages for property filter groups

- src/app-layout/__tests__/global-breadcrumbs.test.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
Replacement for this PR: https://github.com/cloudscape-design/components/pull/2666
Build passes
<details> …
> fix: Fix flaky global breadcrumbs test

- src/app-layout/__integ__/app-layout-split-panel.test.ts
Related to https://github.com/cloudscape-design/browser-test-tools/pull/105 (see dry-run test failures).
Switching to Chromium --headless=new causes failures to our tests that depend on screen size. The refactoring fixes the issue for some of the app layout tests to either remove the dependency completely or make assertions depend on the measured viewport height.
Previous PR: https://github.com/cloudscape-design/components/pull/2660
* Verified the tests work with old and new headless mode
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/ …
> refactor: Update integration tests to resolve chromium upgrade 3

- src/autosuggest/__tests__/analytics-metadata.test.tsx
- src/autosuggest/analytics-metadata/interfaces.ts
- src/autosuggest/index.tsx
- src/input/__tests__/analytics-metadata.test.tsx
- src/input/analytics-metadata/interfaces.ts
- src/input/internal.tsx
Similar to https://github.com/cloudscape-design/components/commit/dde24620bceb97c2fd3e59aa45b0e95af8402313
<details>
- _If the code …
> feat: Add analytics metadata to Autosuggest component

- pages/button-dropdown/permutations-main-action.page.tsx
- src/button-dropdown/internal.tsx
Currently the children slot passed to DropDown component is ignored when `mainAction` is used, this change supports this feature. 
added new permutations 
<details> …
> feat: Support using text in main action dropdown tigger

- src/property-filter/__tests__/common.tsx
- src/property-filter/__tests__/property-filter-i18n.test.tsx
- src/property-filter/__tests__/property-filter-token-editor.test.tsx
- src/property-filter/filtering-token/index.tsx
- src/property-filter/token-editor-inputs.tsx
- src/property-filter/token.tsx
Some i18n labels are not defined in property filter i18n messages but are expected to come from the internally used components: input, autosuggest, and popover. For it to work the labels must not use fallbacks when passed to the respective components.
<details>
- …
> fix: Fixes property filter i18n labels derived from other components

- pages/app/components/page-view.scss
- pages/app/components/page-view.tsx
Setting negative `z-index` values causes the element to go behind its container element's background.
This effect is not visible in the dev pages and consequently in the visual tests. This PR adds a white background color to the page container in to make the effects of `z-index: -1` visible.
Related links, issue #, if available: `AWSUI-55591`
Setting the same `z-index` issue caused by #2550: Verified in Chrome, Firefox and Safari that the change in this PR can reveal the issue it in the component pages.
<details> …
> chore: Adds background color to page and permutation containers

- src/flashbar/__tests__/analytics.test.tsx
- src/flashbar/__tests__/flashbar.test.tsx
1. Fixing the tests to make them compatible with this change: https://github.com/cloudscape-design/component-toolkit/pull/96
2. Extracted analytics tests in a separate file. Previously, one-time metrics were not captured, because they happened in unrelated unit tests
1. PR build passes
2. Ran tests locally using the changes from the other PR (https://github.com/cloudscape-design/component-toolkit/pull/96), they pass too
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#pu …
> chore: Tolerate other analytics events in flashbar analytics tests

- pages/progress-bar/permutations-flash.page.tsx
- src/progress-bar/styles.scss
- style-dictionary/utils/token-names.ts
- style-dictionary/visual-refresh/colors.ts
- style-dictionary/visual-refresh/contexts/flashbar-warning.ts
We had to revert this PR because Firefox didn't like it. Now fixed (see second commit) and tested in my dev pipeline, so we're good to go.
+ Reverts cloudscape-design/components#2518
+ Refactors the CSS to make it work with Firefox (split the -moz and -webkit rules into separate CSS declarations)
> fix: Improve progress bar color contrast in warning flash message

- src/link/internal.tsx
Found in Slack, didn't bother creating a ticket for this one. A blank aria-labelledby overrides aria-label, so if there's no aria-labelledby, it should be undefined rather than an empty string.
<details> …
> fix: Don't set aria-labelledby on link to empty string by default

- src/table/expandable-rows/expand-toggle-button.tsx
A plain `<button>` will submit the closest surrounding form. Need to add `type="button"` for non-form buttons like expand toggles.
No test for this specifically - we'd just be testing that a static attribute exists. That said, we do have a generic test, but it looks like it's getting less and less applicable as our components get more complex, so...
<details> …
> fix: Prevent expandable table expand buttons from submitting forms

- src/flashbar/__tests__/analytics-metadata.test.tsx
- src/flashbar/analytics-metadata/interfaces.ts
- src/flashbar/analytics-metadata/styles.scss
- src/flashbar/analytics-metadata/utils.ts
- src/flashbar/collapsible-flashbar.tsx
- src/flashbar/flash.tsx
- src/flashbar/non-collapsible-flashbar.tsx
Similar to https://github.com/cloudscape-design/components/commit/9c1752711f80122519564dbbe65249f15ca1da1c
<details>
- _If the code …
> feat: Add analytics metadata to Flashbar

- src/app-layout/visual-refresh-toolbar/toolbar/styles.scss
With the latest changes for breadcrumbs (https://github.com/cloudscape-design/components/commit/d9a5f98307ffdf94d310ad9cd8a70bb8b4f45ce4), they are currently always collapsed when used with toolbar. This change creates a better balance between breadcrumbs and drawers triggers area.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support …
> fix: Breadcrumbs display in toolbar

- src/app-layout/visual-refresh-toolbar/toolbar/styles.scss
The wrapper for the toolbar trigger buttons does not fit their current minimum size of 140px. This PR addresses the issue by setting their minimum width to `auto`. You can see the problem demonstrated in the video below.
https://github.com/user-attachments/assets/42f79532-8d3e-4f0a-aaf7-921dc0ff2c76
<details> …
> fix: Toolbar triggers size

- src/property-filter/styles.scss
Removing user-select: text style from property filter editor that makes cursor look different when hovering above property and operator selects. There is seemingly no value in keeping the style.
Resolves feedback from [HJhfABYOa8OE]
* Manual tests with custom forms
<details>
- _Changes …
> fix: Remove user-select text style from property filter editor

- src/popover/__integ__/popover-placement.test.ts
- src/popover/container.scss
Turns out the 2px border in visual refresh is _just_ enough to force an inner column layout inside the popover to break to a single column. Talk about pixel perfect. Rather than any fancy calculations, it's just easier to add a couple of pixels to the large popover; it's not worth the complexity of making it conditional on the theme either IMO.
Related links, issue #, if available: AWSUI-59615
Permutation tests, I assume.
<details> …
> fix: Allow column layout to extend to two columns inside large full-width popover in refresh

- pages/property-filter/common-props.tsx
- pages/property-filter/split-panel-app-layout-integration.page.tsx
- pages/property-filter/token-editor.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/property-filter/__tests__/common.tsx
- src/property-filter/__tests__/property-filter-i18n.test.tsx
- src/property-filter/__tests__/property-filter-token-editor.test.tsx
- src/property-filter/__tests__/property-filter-token-list.test.tsx
- src/property-filter/__tests__/property-filter.test.tsx
- src/property-filter/filtering-token/__tests__/filtering-token.test.tsx
- src/property-filter/filtering-token/index.tsx
- src/property-filter/filtering-token/styles.scss
- src/property-filter/i18n-utils.ts
- src/property-filter/index.tsx
- src/property-filter/interfaces.ts
- src/property-filter/internal.tsx
- src/test-utils/dom/property-filter/index.ts
Making property filter token groups API public. The PR also includes small changes to default popover position, alignment and border radius of nested tokens, dev-warning for hide-tokens.
Rel: [HJhfABYOa8OE]
<details> …
> feat: Property filter token groups

- src/file-upload/internal.tsx
- src/internal/hooks/use-list-focus-controller.tsx
- src/property-filter/__tests__/property-filter-token-list.test.tsx
- src/property-filter/filtering-token/index.tsx
- src/property-filter/internal.tsx
- src/property-filter/token-editor.tsx
- src/token-group/internal.tsx
In property filter when the focus comes back to input after the last token is removed the dropdown must stay closed.
* Enhanced existing unit test
<details> …
> fix: Property filter keeps dropdown closed on autofocus

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/internal/components/button-trigger/index.tsx
- src/internal/components/button-trigger/styles.scss
- src/property-filter/filtering-token/index.tsx
- src/property-filter/interfaces.ts
- src/select/internal.tsx
- src/select/parts/trigger.tsx
Fixing nested token radius on the left side when operation selector is present.
Additionally, there are small improvements to the api docs.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/acce …
> fix: Fixes border radius in property filter nested tokens

- pages/breadcrumb-group/events.page.tsx
- src/breadcrumb-group/__integ__/breadcrumb-group.test.ts
- src/breadcrumb-group/__tests__/analytics-metadata.test.tsx
- src/breadcrumb-group/__tests__/breadcrumb-group.test.tsx
- src/breadcrumb-group/__tests__/breadcrumb-item.test.tsx
- src/breadcrumb-group/__tests__/utils.test.ts
- src/breadcrumb-group/implementation.tsx
- src/breadcrumb-group/interfaces.ts
- src/breadcrumb-group/item/funnel.tsx
- src/breadcrumb-group/item/item.tsx
- src/breadcrumb-group/item/styles.scss
- src/breadcrumb-group/styles.scss
- src/breadcrumb-group/utils.ts
This PR reverts the partial revert of responsive breadcrumbs (https://github.com/cloudscape-design/components/commit/a1f027553b7b1c43a8cda5f675bb67e0ba3991e1) and introduces a small performance improvement.
<details> …
> feat: Re-introduce responsive breadcrumb group

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/internal/analytics/index.ts
- src/internal/analytics/interfaces.ts
- src/internal/hooks/use-component-analytics/__tests__/use-component-analytics.test.tsx
- src/internal/hooks/use-component-analytics/index.ts
- src/table/interfaces.tsx
- src/table/internal.tsx
Adds a Component Metric hook that will be used to support the funnel metrics through pattern identification. In this revision Table has been instrumented to emit a metric on render with some additional metadata.
<details> …
> chore: Add component render metric hook

- src/app-layout/__tests__/tools.test.tsx
- src/app-layout/__tests__/utils.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
When the toolbar is displayed, `appLayoutTestWrapper.findTools()` returns null if the tool panel is closed. This happens also without the toolbar, but only when more drawers are present. this change allows to ascertain if a drawer is closed both when it has the `drawer-closed` className, and when it is null. 
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONT …
> chore: Extend applayout tools test to toolbar

- src/date-picker/__tests__/common.tsx
- src/date-picker/__tests__/date-picker-calendar.test.tsx
- src/internal/components/dropdown/index.tsx
Inside click detection in dropdowns is broken because we couldn't determine whether an element belonged to a dropdown inside a shadow DOM context. This is essentially the same root cause as in #781, manifesting in a different component.
Related links, issue #, if available: AWSUI-59038
Added tests. We had a case previously where we had to revert because some packages had older JSDOMs didn't support composedPath, but enough time has passed that we should just ask them to upgrade if they hit this issue.
<details> …
> fix: Fix dropdown click handling inside shadow DOM context

- src/app-layout/__integ__/app-layout-sticky-elements.test.ts
- src/app-layout/__tests__/mobile.test.tsx
- src/app-layout/visual-refresh-toolbar/multi-layout.ts
- src/app-layout/visual-refresh-toolbar/toolbar/drawer-triggers.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
1 - Disable trigger buttons in mobile view
2 - Display toolbar even if it only has breadcrumbs
3 - activate many of the mobile tests
<details> …
> fix: Toolbar disabled buttons in mobile and display of breadcrumbs

- jest.integ.config.js
- jest.motion.config.js
- jest.unit.config.js
Cleanup after https://github.com/cloudscape-design/components/pull/2718
* Build passes
* Tested locally that typescript errors fail the build
<details> …
> chore: Fix jest deprecation warnings

- src/app-layout/__integ__/app-layout-split-panel.test.ts
- src/app-layout/visual-refresh-toolbar/split-panel/index.tsx
We already do that for the navigation and tools panel, but not the split panel
https://github.com/cloudscape-design/components/blob/8ca4c6a55dd13eb572df364cb420527fa1366035/src/app-layout/visual-refresh-toolbar/navigation/index.tsx#L31
1. Manually
2. Added an integration test
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/m …
> fix: Fix split panel vertical offset calculation

- build-tools/tasks/a11y.js
- src/button-dropdown/__integ__/performance-marks.test.ts
- src/button/__integ__/performance-marks.test.ts
A follow-up for https://github.com/cloudscape-design/components/pull/2735, fixing more failures from the dry run of https://github.com/cloudscape-design/browser-test-tools/pull/109
<details> …
> chore: Supporting webdriverio v9 migration 2

- src/__tests__/__snapshots__/design-tokens.test.ts.snap
- src/app-layout/drawer/index.tsx
- style-dictionary/classic/contexts/tools-drawer-trigger.ts
- style-dictionary/classic/index.ts
- style-dictionary/utils/contexts.ts
Adjust color contrast for the active runtime drawer trigger buttons.
The color contrast (Button background color vs focus ring color) changed:
- light mode:
-  1:1 before this change
-  4.82:1 after this change
Before/after this change:
|<img width="208" alt="pr-2708-before-light" src="https://github.com/user-attachments/assets/21b57896-f1fb-4817-96fe-4b5ffccf066a">   |<img width="208" alt="pr-2708-after-light" src="https://github.com/user-attachments/assets/a2de6d96-2882-49a7-ae9d-d74be2dc7a1e">   |
|---|---|
- dark mode: 
-  1.31:1 before this change
-  5.95:1 after this change
Before/after this change:
|<img width="208" alt="pr-2708-before-dark" src="https://github.com/user-attachments/assets/9c6c5ef7-79cc-4553-8b78-d03bec891d94">   |<img width="208" alt="pr-2708-after-dark" …
> fix: Focus color contrast on active runtime drawer trigger

- src/date-range-picker/__tests__/date-range-picker.test.tsx
- src/date-range-picker/dropdown.tsx
- src/date-range-picker/index.tsx
Obviously trying to break the record for oldest PR merged into the repo here - but let me get this merged once and for all!
The title explains the PR pretty well - but the bigger question is whether it'll break anyone. Sending it through my pipeline to check.
Related links, issue #, if available: AWSUI-18012
<details> …
> fix: Only provide date strings to isValidRange when date range picker is set to dateOnly

- src/app-layout/__integ__/app-layout-focus-delegation.test.ts
- src/app-layout/visual-refresh-toolbar/index.tsx
Currently, in the toolbar variant of AppLayout, when a drawer is opened by a custom button (vs it's trigger) the focus is not restored when that drawer is closed on mobile. This returns that focus. It also asserts this functionality is working on an integ test that was skipped before.
To view bug, go to https://d81a4az09pn2q.cloudfront.net/polaris/index.html#/light/app-layout/with-drawers/?visualRefresh=true&appLayoutWidget=true&splitPanelPosition=side on mobile width, open drawer via button in the content, close drawer and note the focus is not back on the button in content.
Compare with https://d21d5uik3ws71m.cloudfront.net/components/48328fe77949ce9cabbf48dfb532bfcff3d17531/dev-pages/index.html#/light/app-layout/with-drawers/?visualRefresh=true&appLayoutWidget=true&splitPanelPosition=si …
> fix: restoring focus to button on dom that opened panel once panel closed on mobile

- src/alert/index.tsx
- src/button/internal.tsx
- src/form-field/internal.tsx
- src/internal/analytics/__integ__/static-multi-page-create.test.ts
- src/internal/analytics/__integ__/static-single-page-flow.test.ts
- src/internal/analytics/components/analytics-funnel.tsx
- src/internal/analytics/hooks/use-funnel.ts
- src/internal/analytics/interfaces.ts
- src/internal/analytics/selectors.ts
- src/link/internal.tsx
- src/wizard/internal.tsx
As part of the resource creation funnel we can infer the type of resource from the breadcrumb. Based on our initial investigation this is always the second breadcrumb item. This value is then sent along with the funnelStart event.
Quip ref: [jWVWAxBtMgkK]
Existing tests updated. …
> chore: Infer resource type from breadcrumbs

- src/table/__integ__/table-interaction-metrics.test.ts
This PR fixes a flakiness in the test for table interaction metrics, by increasing the allowed value.
See e.g. https://github.com/cloudscape-design/components/actions/runs/11035103239/job/30650763031#step:5:2193
n/a
<details> …
> chore: Fix flakiness of table interaction metrics test

- src/button-dropdown/__integ__/performance-marks.test.ts
- src/button/__integ__/performance-marks.test.ts
- src/collection-preferences/content-display/__integ__/pages/content-display-page.ts
- src/container/__integ__/header-cover.test.ts
- src/table/__integ__/performance-marks.test.ts
- src/theming/__integ__/index.test.ts
This fixes remaining incompatibility issues. The PR is a follow-up for: https://github.com/cloudscape-design/components/pull/2753
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/ …
> chore: Supporting webdriverio v9 migration 3

- src/button/__tests__/analytics-metadata.test.tsx
- src/button/analytics-metadata/interfaces.ts
- src/button/internal.tsx
Needed for Collection Preferences instrumentation: in [this file](https://github.com/cloudscape-design/components/blob/main/src/collection-preferences/index.tsx#L146) we have buttons whose action needs to be more specific than clicking.
The property will remove the need to add artificial spans, as we did in [property filter](https://github.com/cloudscape-design/components/blob/main/src/property-filter/token-editor.tsx#L210), which caused visual changes. A follow-up PR will adopt the new Button property in Property filter component.
<details> …
> feat: Allow to override analytics action in Internal button

- pages/utils/iframe-wrapper.tsx
Without this fix, the doctype inside the iframe is not set. Our components only work with html5 doctype.
Locally, by checking `document.doctype` value
<details> …
> chore: Fix doctype setup for iframe dev pages

- src/date-range-picker/index.tsx
- src/date-range-picker/styles.scss
Spot the issue.
In small screens, the date range picker blows past the screen width. The dropdown does as well (the trigger is designed to match the min-width of the dropdown), but let's just focus on the trigger for now. The design options for the dropdown itself are a little ambiguous for now.
Related links, issue #, if available: AWSUI-59654
Screenshot tests. Actually, this doesn't fail anything, though it should. We could add a constrained width test on the simple or "small viewport" pages on the internal package rather than making a new dev page. Internal CR will follow after this merges.
<details>
- _Changes are …
> fix: Remove min-width from date range picker trigger

- pages/app-layout/multi-layout-iframe.page.tsx
- pages/app-layout/multi-layout-simple.page.tsx
The external link icon position is off until this fix is added: https://github.com/cloudscape-design/components/pull/2783
<details> …
> chore: Adds external link to a dev test page with an iframe

- src/internal/analytics/interfaces.ts
- src/internal/hooks/use-component-analytics/__tests__/use-component-analytics.test.tsx
- src/internal/hooks/use-component-analytics/index.ts
- src/table/internal.tsx
As part of a component mount we generate a new task interaction id that can be attached to the dom reference and subsequently picked up at a later time.
<details> …
> chore: Attach task interaction id to table instance

- src/flashbar/styles.scss
Adds a stacking context around the flash-list to prevent the box shadow disappearing behind the parent element's background.
This has been blocking #2655 
Related links, issue #, if available: AWSUI-59453
- Automated visual tests.
- For manual testing, run the project locally, go to the flashbar page and set a background color to any parent `<div />` element. Verify that the flashbar shadow is not disappearing.
<details> …
> fix: Flashbar box shadow disappearing behind parent background

- src/app-layout/visual-refresh-toolbar/skeleton/styles.scss
When using the new app layout with the old widgets, the tools panel doesn't adjust to the correct size. This PR fixes that issue.
<details> …
> fix: New app-layout and old widgets

- pages/prompt-input/permutations.page.tsx
- pages/prompt-input/simple.page.tsx
- pages/utils/permutations-view.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/__tests__/__snapshots__/test-utils-selectors.test.tsx.snap
- src/internal/styles/forms/mixins.scss
- src/prompt-input/__integ__/prompt-input.test.ts
- src/prompt-input/__tests__/prompt-input.test.tsx
- src/prompt-input/interfaces.ts
- src/prompt-input/internal.tsx
- src/prompt-input/styles.scss
- src/prompt-input/test-classes/styles.scss
- src/test-utils/dom/prompt-input/index.ts
This reverts commit 680ece35b6a6b57f22a4f54835bdfcb0f47e01f5.
Reverts https://github.com/cloudscape-design/components/commit/680ece35b6a6b57f22a4f54835bdfcb0f47e01f5 as it is rendering two `aria-labels` and this result in tests that looks for labels to return multiple elements and fail.
related build: 7045624283
<details> …
> revert: "feat: Prompt input secondary actions and content slots (#2720)"

- pages/multiselect/disabled-reason.page.tsx
- pages/select/disabled-reason.page.tsx
- src/internal/components/tooltip/index.tsx
- src/popover/__tests__/positions.test.ts
- src/popover/container.tsx
- src/popover/interfaces.ts
- src/popover/use-popover-position.ts
- src/popover/utils/positions.ts
- src/select/__integ__/disabled-reason.test.ts
- src/select/__tests__/common.ts
- src/select/__tests__/disabled.test.tsx
- src/select/__tests__/select.test.tsx
- src/select/parts/item.tsx
- src/select/parts/multiselect-item.tsx
Before:
https://github.com/user-attachments/assets/335704df-4366-4f08-a12b-dbd5c2906b69
After:
https://github.com/user-attachments/assets/80600dc7-3970-46b1-a28a-7815e77fc0cf
Issue: AWSUI-55390
- Manually
- Added integration tests
- Added one unit test
<details> …
> fix: Hide disabled reason tooltip when the option is scrolled away

- src/__tests__/__snapshots__/test-utils-selectors.test.tsx.snap
- src/app-layout/__integ__/app-layout-drawers.test.ts
- src/app-layout/__integ__/app-layout-focus-delegation.test.ts
- src/app-layout/__integ__/app-layout-split-panel.test.ts
- src/app-layout/__integ__/app-layout-toolbar-tooltips.test.ts
- src/app-layout/__integ__/constants.ts
- src/app-layout/__integ__/global-breadcrumbs.test.ts
- src/app-layout/__integ__/runtime-drawers-controllability.test.ts
- src/app-layout/__integ__/runtime-drawers.test.ts
- src/app-layout/__integ__/toolbar-tooltips/app-layout-toolbar-drawer-trigger-tooltip.test.ts
- src/app-layout/__integ__/toolbar-tooltips/app-layout-toolbar-drawer-trigger-tooltip.test.tsx
- src/app-layout/__integ__/toolbar-tooltips/app-layout-toolbar-no-tooltips.test.ts
- src/app-layout/__integ__/toolbar-tooltips/app-layout-toolbar-split-panel-trigger-tooltip.test.ts
- src/app-layout/__integ__/utils.ts
- src/app-layout/__tests__/drawers.test.tsx
- src/app-layout/__tests__/split-panel.test.tsx
- src/app-layout/__tests__/toolbar.test.tsx
- src/app-layout/__tests__/trigger-button.test.tsx
- src/app-layout/test-classes/styles.scss
- src/app-layout/visual-refresh-toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/drawer-triggers.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/trigger-button/index.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/trigger-button/styles.scss
- src/app-layout/visual-refresh/drawers.tsx
- src/split-panel/implementation.tsx
- src/split-panel/side.tsx
- src/split-panel/styles.scss
- src/test-utils/dom/app-layout/index.ts
- works for both spit panel positions
- set focus to split panel resize button when split panel opened via toolbar trigger button
- set focus back to split panel trigger button on the toolbar once it is closed from the close button on the split panel
-  returns split panel interactions in integ tests
- update to app layout integ tests where:
- removed redundant classes
- moved test added testutil functions and updated the tests to use those util functions
- separated tooltip tests into multiple files with a util
got to deployment with the following path & params - /light/app-layout/with-split-panel?appLayoutWidget=true
- open split panel via the first button in the toolbar
- close split panel via its close button
- note the focus
Confirm …
> fix: restore focus delegation to split panel in visual-refresh-toolbar

- src/app-layout/visual-refresh-toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/split-panel/styles.scss
This issue occurs when the 'Show scroll bars' option is set to 'Always' in the macOS Appearance System preferences. 
The problem arises when the side split panel is opened at desktop screen size, causing the scroll bar to appear briefly and then hide because of the animation. This problem is fixed via setting `overflow: hidden` to side-panel's parent element.
<details> …
> fix: Shaking split panel

- pages/area-chart/loading.page.tsx
- src/area-chart/__integ__/area-chart.test.ts
- src/area-chart/__tests__/area-chart-use-chart-model.test.tsx
- src/area-chart/internal.tsx
- src/area-chart/model/use-chart-model.ts
When an area-chart is rendered with `fitHeight` true and has an initial `statusType` of loading then transitions to `finished` the height of the chart becomes zero.
We calculate the chart height given its ref to `useHeightMeasure` and some deps, this is solved by also passing to it the `statusType` as a dependency.
<details> …
> fix: Fix area-chart zero height when statusType is loading then finished with  true

- src/property-filter/__tests__/property-filter.filtering-input.test.tsx
- src/property-filter/internal.tsx
> fix: Fixes property filter count text when token groups are used

- src/app-layout/__tests__/tools.test.tsx
- src/app-layout/utils/use-drawers.ts
- src/app-layout/visual-refresh-toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/interfaces.ts
- src/app-layout/visual-refresh-toolbar/toolbar/drawer-triggers.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
Aligned controllable tools behavior for the app layout toolbar theme with the refresh-layout theme. If tools are partially controllable (where either `toolsOpen` or `onToolsChange` is provided, but not both), the tools will not be activated when clicking on the corresponding trigger button
<details> …
> fix: Partially controllable tools

- src/table/resizer/styles.scss
Before this change, the resizer button was relatively positioned when focused. This caused the resizable button change it's position when focused (see screen recording below). The relative position was coming from the `focus-highlight` mixin. This regression was introduced when fixing sass deprecation warnings (#2638).
Wrapping the absolute position in `& {}` creates a separate rule which takes precedence because of the rule declaration order.
Screen recording of the issue (left tab before, right tab after):
https://github.com/user-attachments/assets/04c1b2ac-0083-4283-a2e4-b689a4403dff
Related links, issue #, if available: AWSUI-59724
- Manually tested in supported browsers on Mac.
- Added additional screenshot test (WIP in my pipeline).
- Can be tested by opening a the [table resizable …
> fix: Resizable column focus ring positioning

- src/container/__tests__/sticky-header.test.tsx
- src/container/use-sticky-header.ts
Related links, issue #, if available: AWSUI-59633
- Added a unit test
- Just in case, manually verified that the sticky header behavior keeps working when reloading a page in scrolled state. The browser generates a trusted scroll event in this case
<details> …
> fix: Let sticky header react only to user-generated resize events

- src/app-layout/__tests__/split-panel.test.tsx
- src/split-panel/implementation.tsx
Deactivated split panel should not appear. It works as expected in classic and VR, but visual-refresh-toolbar.
<details> …
> fix: Split panel appearance based on splitPanel prop

- src/autosuggest/internal.tsx
- src/internal/components/dropdown-status/index.tsx
- src/internal/components/tab-trap/index.tsx
- src/internal/components/tab-trap/styles.scss
- src/property-filter/__tests__/property-filter-autosuggest.test.tsx
- src/property-filter/property-filter-autosuggest.tsx
The tab stop inside property filter and autosuggest dropdown is used to loop focus when there are interactive elements in the dropdown such as the recovery button or custom form. When there are no interactive element the tab stop must be disabled as otherwise it does not forward the focus requiring an extra Tab press to exit the dropdown.
<details> …
> fix: Removes unneeded tab stop from property filter

- src/property-filter/__tests__/property-filter-autosuggest.test.tsx
- src/property-filter/__tests__/property-filter-extended-operators.test.tsx
- src/property-filter/internal.tsx
- src/property-filter/property-editor.tsx
- src/property-filter/property-filter-autosuggest.tsx
- src/property-filter/styles.scss
This PR changes the way custom forms are rendered in the property filter. Now, the form footer is rendered to the dropdown footer which makes it sticky in case the custom form is large.
* Dry-run
<details> …
> chore: Property filter custom form footer

- src/app-layout/visual-refresh-toolbar/drawer/styles.scss
- src/app-layout/visual-refresh-toolbar/skeleton/index.tsx
This commit fixes two issues caused by nested app layouts with iframes. Because the outer app layout imposes boundaries on the inner app layout that the inner app layout is not aware of, the mobile breakpoint gets unintentionally activated on the inner layout too soon, causing a few side effects which can be seen in the video below:
https://github.com/user-attachments/assets/cb2eb1d8-ac28-4d5e-b8f8-516e9b6ca92f
Mitigations for these bugs: 
1. Drawer width should be 100% when mobile breakpoint is activated.
2. The inner layout's content should still be focusable when a panel on the outer app layout is open, and the inner layout is smaller than the mobile breakpoint.
<details> …
> fix: Toolbar with multi-layout nested iframe bugs

- pages/property-filter/custom-forms.scss
- pages/property-filter/custom-forms.tsx
- src/multiselect/embedded.tsx
- src/property-filter/__tests__/property-filter-extended-operators.test.tsx
- src/property-filter/property-editor.tsx
- src/property-filter/styles.scss
Replacing internal form field header with a custom header. That is needed to unblock https://github.com/cloudscape-design/components/pull/2739, where the header and the form body to use different paddings.
Similar to: https://github.com/cloudscape-design/components/pull/2818
* New unit test to secure custom form label assignment
<details> …
> chore: Property filter custom form header improvement

- src/app-layout/__integ__/runtime-drawers-controllability.test.ts
The latest PR https://github.com/cloudscape-design/components/pull/2828 that preserved tools inner now allows tests to pass for the toolbar variant of AppLayout against the `runtime-drawers-imperative` path, thus the tests no longer need to be be skipped
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#br …
> chore: enabling toolbar in integ tests for runtime drawers controllability in AppLayout

- pages/select/screenshot.page.tsx
- src/select/__tests__/use-select.test.ts
- src/select/utils/use-select.ts
The Select component groups are not supposed to be selectable. However, as the useSelect util is reused between Select and Multiselect, there was logic that made groups selected if all children are selected that affected Select components having a single options inside a group.
Before:
https://github.com/user-attachments/assets/d3b8c9a8-f3fa-46b4-92e9-e05b5ba06ec5
After:
https://github.com/user-attachments/assets/e51fa5bf-6700-43d8-b831-690e8ed2cef3
Rel: AWSUI-59650
<details> …
> fix: Removes group highlight state from Select

- src/property-filter/internal.tsx
- src/property-filter/styles.scss
Apply the max width only to the filtering input (and count text), not to additional custom controls,
so that custom controls don't result in an overly small filtering input.
Related links, issue #, if available: AWSUI-59729
Checked for expected diffs in screenshot tests.
<details>
- …
> fix: Apply property filter max width only to filtering input

- src/date-range-picker/__tests__/date-range-picker-relative.test.tsx
- src/date-range-picker/relative-range/index.tsx
Ensure date picker relative unit select has valid default value (previously it always used "days" or "minutes", even if that was not a valid unit)
New unit test
<details> …
> fix: Ensure date picker relative unit select has valid default value

- src/app-layout/__integ__/multi-app-layout.test.ts
Enables the remaining integ test in app layout toolbar for nested app layouts.
<details>
- …
> chore: Enable rest of multi-layout integ tests for toolbar

- src/app-layout/__tests__/trigger-button.test.tsx
- src/area-chart/__tests__/area-chart-initial-state.test.tsx
- src/collection-preferences/content-display/content-display-option.tsx
- src/date-input/__tests__/date-input.test.tsx
- src/expandable-section/__tests__/interactions.test.tsx
- src/internal/components/chart-legend/__tests__/chart-legend.test.tsx
- src/internal/components/chart-plot/__tests__/chart-plot.test.tsx
- src/internal/components/drag-handle/index.tsx
- src/internal/components/masked-input/__tests__/masked-input.test.tsx
- src/link/__tests__/index.test.tsx
- src/mixed-line-bar-chart/__tests__/mixed-chart.test.tsx
- src/mixed-line-bar-chart/__tests__/use-navigation.test.tsx
- src/pie-chart/__tests__/pie-chart.test.tsx
- src/popover/__tests__/popover.test.tsx
- src/property-filter/__tests__/property-filter-extended-operators.test.tsx
- src/property-filter/__tests__/property-filter.filtering-input.test.tsx
- src/property-filter/__tests__/property-filter.test.tsx
- src/split-panel/__tests__/split-panel.test.tsx
- src/table/__tests__/interaction-metrics.test.tsx
- src/table/__tests__/resizable-columns.test.tsx
- src/table/__tests__/selection.test.tsx
- src/table/__tests__/sorting.test.tsx
- src/tabs/__tests__/tabs.test.tsx
- src/time-input/__tests__/time-input.test.tsx
Remove usage of internal imports
* `@cloudscape-design/test-utils-core/dist/utils` -> `@cloudscape-design/test-utils-core/utils`
*  `@dnd-kit/core/dist/hooks/utilities` -> replace with our own type, because that one is not public
Typescript complies fine afterwards
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIB …
> chore: Remove internal imports

- pages/common/options-loader.ts
- pages/dropdown/expandable.page.tsx
- pages/multiselect/multiselect.async.example.page.tsx
- pages/property-filter/async-loading.integ.page.tsx
- pages/property-filter/common-props.tsx
- pages/property-filter/split-panel-app-layout-integration.page.tsx
- src/multiselect/styles.scss
- src/property-filter/__integ__/async-loading.test.ts
- src/property-filter/__tests__/property-filter.filtering-input.test.tsx
- src/property-filter/__tests__/property-filter.test.tsx
- src/property-filter/token-editor-inputs.tsx
This fixes an issue when load items detail from token editor does not include info of selected operator and filtering text, which makes it inconsistent with the same event issued on token creation.
<details> …
> fix: Property filter editor async props

- src/__tests__/__snapshots__/test-utils-selectors.test.tsx.snap
- src/property-filter/__tests__/property-filter-extended-operators.test.tsx
- src/property-filter/property-editor.tsx
- src/property-filter/styles.scss
- src/property-filter/test-classes/styles.scss
- src/test-utils/dom/property-filter/index.ts
Adding test util methods to find the Cancel and Submit buttons in the property filter custom form. The same methods are to be reused for multi-choice forms implemented here: https://github.com/cloudscape-design/components/pull/2739.
The new methods can be used as follows:
```
createWrapper().findPropertyFilter().findPropertyCancelButton().click()
createWrapper().findPropertyFilter().findPropertySubmitButton({ expandToViewport: true }).click()
```
That is similar to existing:
```
createWrapper().findPropertyFilter().findErrorRecoveryButton({ expandToViewport: true }).click()
```
* Updated existing unit tests
<details>
- …
> feat: Adds property filter custom form actions test utils selectors

- src/internal/components/dropdown/index.tsx
even though `event.composedPath` has a wide browser support, it's not supported in old jest versions, this CR adds a fallback to avoid breaking customers unit tests.
<details> …
> fix: Add fallback for event.composedPath in dropdown

- src/checkbox/index.tsx
- src/multiselect/index.tsx
- src/radio-group/index.tsx
- src/select/index.tsx
- src/slider/index.tsx
- src/tiles/index.tsx
- src/toggle/index.tsx
- src/token-group/index.tsx
We have recently added `readOnly` to more components. This change adds the metrics for this.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibi …
> chore: Add metrics for new `readOnly` prop additions

- .github/workflows/release.yml
Using the same setup as in https://github.com/cloudscape-design/actions/blob/main/.github/workflows/dry-run.yml
The setup requires all integ/a11y shards to complete before release is allowed.
<details> …
> fix: Fixes release workflow with shards

- src/internal/components/cartesian-chart/styles.scss
Small fix for a styling regression introduced in #2853
Tested locally
<details>
- _If the …
> chore: Fix accidental margin on non-fit-height charts

- src/app-layout/__integ__/app-layout-focus-delegation.test.ts
- src/app-layout/visual-refresh-toolbar/toolbar/drawer-triggers.tsx
- src/app-layout/visual-refresh/drawers.tsx
- Removed duplicated tests
- Removed unnecessary test id
- Edited and enabled remaining toolbar test. The tab order is different in vr-toolbar on split panel blur because the tab order follows DOM reading order, and toolbar comes before the main content in the toolbar version, thus focus should not go back to tools trigger.
<details> …
> chore: Cleanup and enable remaining toolbar app layout focus delegation tests 

- src/file-upload/__tests__/file-upload.test.tsx
- src/file-upload/internal.tsx
Ensure that, if `multiple` is not set, only one file can be dragged into the dropzone.
Related links, issue #, if available: AWSUI-21885
New unit tests
<details> …
> fix: Ensure single fileupload dropzone only accepts single files

- pages/common/flush-response.ts
- pages/dropdown/width.page.tsx
- src/__integ__/page-objects/async-response-page.ts
- src/internal/components/dropdown/__integ__/width.test.ts
Removing dependency on test page timeout in dropdown width integ tests.
Similar fix: https://github.com/cloudscape-design/components/pull/2882
* Validated by running the test over 100 times in GitHub actions
<details> …
> chore: Fixes flakiness in dropdown width test

- src/internal/widgets/__tests__/widgets.test.tsx
- src/internal/widgets/index.tsx
- src/split-panel/__tests__/widgetized-panel.test.tsx
- src/split-panel/implementation.tsx
- src/split-panel/index.tsx
Replace forwardRef with a plain component to fix this React warning:
```
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()
```
Locally, because it is only a warning
<details>
- …
> fix: Fix forwardRef warning in split panel

- pages/table/expandable-rows-test.page.tsx
- src/table/__integ__/expandable-rows.test.ts
Removing dependency on test page timeout in expandable rows integ tests.
Similar fix: https://github.com/cloudscape-design/components/pull/2883
* Validated by running the test over 100 times in GitHub actions
<details> …
> chore: Fixes flakiness in expandable rows integ test

- src/collection-preferences/content-display/__tests__/content-display.test.tsx
- src/collection-preferences/content-display/index.tsx
- src/collection-preferences/content-display/utils.ts
Option labels in collection prefs must be strings but it is technically possible to use React nodes.
The PR fixes component rendering for this case but only when the filtering feature is not activated.
Rel: AWSUI-59826
* Updated unit test
<details> …
> fix: Fixes collection prefs filtering when column labels are not strings and filtering is disabled

- src/app-layout/constants.scss
- src/app-layout/mobile-toolbar/styles.scss
- src/app-layout/visual-refresh-toolbar/toolbar/styles.scss
- src/app-layout/visual-refresh/mobile-toolbar.scss
Reset the toolbar z-index to the same that was used in vr and classic to make it backward compatible.
This is to prevent breaking anyone who relied on the old z-indexes. For example, it broke a page in Systems Manager which implemented a custom scroll area which set `z-index: 999`.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/ …
> chore: Make toolbar z-index the same that it was in vr and classic

- pages/funnel-analytics/modal.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/alert/__tests__/alert-analytics.test.tsx
- src/form-field/__tests__/form-field-analytics.test.tsx
- src/form/__tests__/analytics.test.tsx
- src/form/index.tsx
- src/internal/analytics/__integ__/static-multi-page-create.test.ts
- src/internal/analytics/__integ__/static-single-page-flow.test.ts
- src/internal/analytics/__tests__/mocks.ts
- src/internal/analytics/components/analytics-funnel.tsx
- src/internal/analytics/hooks/use-funnel.ts
- src/internal/analytics/interfaces.ts
- src/modal/__tests__/analytics.test.tsx
- src/modal/index.tsx
- src/modal/interfaces.ts
- src/modal/internal.tsx
- src/wizard/__tests__/analytics.test.tsx
This change adds funnel support for the Modal component. This allows the potential collection of user interactions through deletion flows within Modals.
Quip: tiy2A6a3X2qu
- Adds funnel instrumentation to Modals
- Add analyticsMetadata with `delete` type to Modal
- Unit tests added for Modals …
> chore: Instrument modal for funnels

- pages/app-layout/controlled-navigation.page.tsx
Problem can be seen on path `/light/app-layout/controlled-navigation/?appLayoutToolbar=true&navigationHide=false&applyNavOpenOverride=true&navOpenOverrideValue=false`
on deployment. Go to https://d21d5uik3ws71m.cloudfront.net/components/b77b2547c6b1210f0de973956d6efb31ae58c212/dev-pages/index.html#/light/app-layout/controlled-navigation/?appLayoutToolbar=true&navigationHide=false&applyNavOpenOverride=true&navOpenOverrideValue=false
and refresh the page.
This is needed so a regression test can be completed
<details> …
> chore: adding page with reproducible problem

- pages/button-dropdown/main-action.page.tsx
- src/button-dropdown/__integ__/button-dropdown-events.test.ts
- src/button-dropdown/internal.tsx
When a button dropdown is rendered with main action only (for test utils consistency) the main action wasn't clickable with enter. The PR fixes that.
Rel: [baiAA7LWUcov]
* New integration test
<details> …
> fix: Makes button dropdown main action clickable with Enter

- pages/table/sticky-scrollbar-in-container.page.tsx
- src/container/styles.scss
- src/table/__integ__/sticky-scrollbar.test.ts
Fixes scrollable area in container which affects the placement of table sticky scrollbar.
Rel: AWSUI-54814
* New integ test
* Dry-run
<details> …
> fix: Container overflow constrained to the content slot

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/text-filter/__tests__/text-filter.test.tsx
- src/text-filter/index.tsx
- src/text-filter/interfaces.ts
- src/text-filter/internal.tsx
To align with other input components
Related links, issue #, if available: fixes #2820
<details> …
> feat: Add disableBrowserAutocorrect prop to TextFilter

- build-tools/tasks/index.js
- build-tools/tasks/size-limit.js
- gulpfile.js
- package-lock.json
- package.json
Add size-limit check for `/internal/plugins` export 
Checked the build logs, there is a size-limit step now
<details> …
> chore: Add size-limit check for runtime API

- package-lock.json
- package.json
- pages/alert/runtime-content.page.tsx
- pages/flashbar/runtime-content.page.tsx
- src/alert/__integ__/runtime-content.test.ts
- src/alert/__tests__/runtime-content-initial.test.tsx
- src/alert/internal.tsx
- src/alert/styles.scss
- src/flashbar/__tests__/runtime-content-initial.test.tsx
- src/flashbar/flash.tsx
- src/flashbar/styles.scss
- src/internal/plugins/controllers/alert-flash-content.ts
- src/internal/plugins/helpers/use-discovered-content.tsx
Add capability to conditionally hide the initial render of alerts and flashes. This reduces the layout shift
that occurs when the alert/flash content is then replaced via runtime API.
New unit tests.
<details> …
> chore: Add `initialCheck` capability to alert/flash content API

- pages/app/styles.scss
- src/flashbar/collapsible.scss
- src/flashbar/styles.scss
Reopens #2813 and #2767 after being reverted at #2876, with the following fix:
Flashbar items use `box-shadow` on the element itself rather than the pseudo element with `z-index: -1`. 
<details> …
> fix: Flashbar shadow z-index issue and pages background

- pages/table/sticky-scrollbar-in-container.page.tsx
- src/container/styles.scss
- src/table/__integ__/sticky-scrollbar.test.ts
This reverts commit 11df6c3e9a129851193a39d46fa02357ad35c54c.
Reverting because of impact on the dashboard demos that need to be resolved first.
<details> …
> revert: Container overflow constrained to the content slot (#2864)

- pages/table/sticky-scrollbar-in-container.page.tsx
- src/table/__tests__/resizable-columns.test.tsx
- src/table/use-column-widths.tsx
Fixes table column width definition. Before, when only table column width is set and it is less than 120px - the min width is then set to 120px. That creates an unexpected effect when the column is resized: it immediately becomes 120px and cannot be resized below that.
Before:
https://github.com/user-attachments/assets/4f879d3a-aed5-4dd5-aa6a-0f3c70d629fa
After:
https://github.com/user-attachments/assets/f87040f7-6207-4ac3-9f99-9050e919a770
* Manual testing in the updated test page
<details> …
> fix: Fixes table column min width when only width is set

- pages/property-filter/common-props.tsx
- pages/property-filter/custom-forms.tsx
- pages/property-filter/property-filter-editor-permutations.page.tsx
- pages/property-filter/split-panel-app-layout-integration.page.tsx
- pages/property-filter/token-editor.page.tsx
- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/multiselect/__tests__/multiselect-embedded.test.tsx
- src/multiselect/embedded.tsx
- src/multiselect/use-multiselect.tsx
- src/property-filter/__tests__/common.tsx
- src/property-filter/__tests__/property-filter-enum-tokens.test.tsx
- src/property-filter/__tests__/property-filter.test.tsx
- src/property-filter/i18n-utils.ts
- src/property-filter/index.tsx
- src/property-filter/interfaces.ts
- src/property-filter/internal.tsx
- src/property-filter/property-editor.tsx
- src/property-filter/styles.scss
- src/property-filter/token-editor-inputs.tsx
- src/property-filter/token-editor.tsx
- src/property-filter/utils.ts
Adds first-class support for multi-choice (enum) tokens in property filter.
Rel: [Tz3OAr3i2ni1], [0aVwAjMOimcN]
Depends on:
* https://github.com/cloudscape-design/collection-hooks/pull/85
* https://github.com/cloudscape-design/components/pull/2789
* https://github.com/cloudscape-design/components/pull/2818
* https://github.com/cloudscape-design/components/pull/2835
* https://github.com/cloudscape-design/components/pull/2840
* https://github.com/cloudscape-design/components/pull/2841
* https://github.com/cloudscape-design/components/pull/2896
* https://github.com/cloudscape-design/components/pull/2897
<details> …
> feat: Property filter enum tokens

- src/internal/components/portal/__tests__/portal.test.tsx
Add a test to confirm this behavior is supported
Related links, issue #, if available: AWSUI-59828
This whole PR is a test
<details>
- …
> chore: Add test to demonstrate cross-iframe getModalRoot usage

- src/internal/utils/dom.ts
- src/pie-chart/__tests__/pie-chart-ssr.test.tsx
Checking for window in parseCssVariable util to resolve errors when charts are rendered with NextJS.
Rel: AWSUI-59858
Closes https://github.com/cloudscape-design/components/issues/2804
<details> …
> fix: Fixes charts for SSR

- .github/workflows/build-lint-test.yml
This job is already run as part of the [shared build-lint-test workflow](https://github.com/cloudscape-design/actions/blob/main/.github/workflows/build-lint-test.yml#L35). Removing as it does not need to run twice
<details> …
> chore: Remove additional git-secrets job from actions

- src/property-filter/__tests__/property-filter-token-editor.test.tsx
- src/property-filter/token-editor.tsx
When a new filter is added to the group is now takes the same property as the last filter in the group. That improves the UX and fixes a bug when the added filter is always a free-text one which should not happen when free text is disabled.
Rel: AWSUI-59876
<details>
- …
> fix: Fixes property filter group editor when free text is disabled

- src/app-layout/__tests__/multi-layout.test.tsx
- src/app-layout/visual-refresh-toolbar/multi-layout.ts
Added two new `forceDeduplicationType` modes
1. `suspended` – temporary remove from deduplication, but without losing state. Already existed built-in via IntersectionObserver since #2906, but now it is possible to manually override this, if IntersectionObserver fails to detect for some reason
2. `off` – completely turn off deduplication. This instance won't communicate to other app layouts at all
Added unit tests for new modes
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTIN …
> chore: Allow more granular app layout deduplication control

- pages/app-layout/runtime-drawers.page.tsx
- pages/app-layout/styles.scss
- pages/app-layout/utils/content-blocks.tsx
- pages/app-layout/utils/external-widget.tsx
- src/app-layout/__integ__/runtime-drawers.test.ts
- src/app-layout/drawer/index.tsx
- src/app-layout/resize/styles.scss
- src/app-layout/visual-refresh-toolbar/compute-layout.ts
- src/app-layout/visual-refresh-toolbar/drawer/global-drawer.tsx
- src/app-layout/visual-refresh-toolbar/drawer/local-drawer.tsx
- src/app-layout/visual-refresh-toolbar/navigation/index.tsx
- src/app-layout/visual-refresh-toolbar/split-panel/index.tsx
- src/app-layout/visual-refresh/drawers.scss
- src/internal/plugins/helpers/runtime-content-wrapper.tsx
- src/internal/plugins/helpers/styles.scss
- Addresses double scrollbar issue in Q chat panel (AWSUI-59823). 
- This also fixes the flickering scrollbar issue at page load or when resizing vertically, due to motion being applied to height changes.
With this change, drawer children should be able to set height to 100% and fill the entire panel content height. This will still require an adjustment to the Q package to remove their custom calculation code. But I manually tested in Chrome and Safari that this change will not have any adverse affect until then, so it is safe to merge beforehand.
Related links, issue #, if available: AWSUI-59823, TT: V1549419424, TT: D169004346
Running through dev pipeline (wip). Tested the change manually in Q in the console. Fixing failing tests (wip).
<details>
_The …
> fix: Extra scrollbars in drawers

- src/__tests__/__snapshots__/documenter.test.ts.snap
- src/button-dropdown/index.tsx
- src/button-dropdown/utils/utils.ts
- src/button/index.tsx
- src/calendar/index.tsx
- src/date-picker/index.tsx
- src/date-range-picker/dropdown.tsx
- src/date-range-picker/index.tsx
- src/multiselect/index.tsx
- src/segmented-control/index.tsx
- src/select/index.tsx
- src/toggle-button/index.tsx
Adds missing metrics to new additions of disabled reason properties in some components.
Note on the naming: I've used `hasDisabledReason` for components that can only have a singular disabled reason (e.g., button), and `hasDisabledReasons` (plural) for components that can have multiple (e.g., date picker). This aligns with the previous addition of `hasDisabledReasons` for tabs: https://github.com/cloudscape-design/components/pull/2692/files.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/m …
> chore: Add missing metrics for new disabled reason properties

- pages/button/disabled-reason.page.tsx
- src/button/__tests__/button.test.tsx
- src/button/internal.tsx
- src/button/styles.scss
This PR addresses an issue with showing disabled reason tooltip for primary/normal button with `href` prop.
AWSUI-59893
<details> …
> fix: Button with disabled reason and href prop

- pages/button-group/test.page.tsx
- src/button-group/__integ__/button-group.test.ts
- src/button-group/__tests__/button-group.test.tsx
- src/button-group/icon-button-item.tsx
- src/button-group/item-element.tsx
- src/button-group/menu-dropdown-item.tsx
The PR includes the following fixes:
1. Menu items can be set as loading or disabled
2. Popover feedback can be shown for disabled and loading items
* Improved test page and adjusted integ tests
<details> …
> fix: Fixes button group item states

- src/app-layout/resize/styles.scss
- src/app-layout/utils/interfaces.ts
- src/app-layout/utils/use-pointer-events.ts
- src/app-layout/utils/use-resize.tsx
- src/app-layout/visual-refresh-toolbar/drawer/global-drawer.tsx
- src/app-layout/visual-refresh-toolbar/drawer/local-drawer.tsx
- src/app-layout/visual-refresh-toolbar/drawer/use-resize.ts
- src/app-layout/visual-refresh-toolbar/navigation/index.tsx
- src/app-layout/visual-refresh-toolbar/skeleton/index.tsx
- src/split-panel/bottom.tsx
- src/split-panel/implementation.tsx
- src/split-panel/side.tsx
Fixing this issue: AWSUI-59756
On initial load, there are some unexpected transitions playing. Fixed it by splitting up the animated properties 1) `inline-size` aka `width` for side panels (navigation, tools, side split panel, and others) 2) `block-size` aka `height` for bottom split panel
Related links, issue #, if available: AWSUI-59756
* Manually tested all 3 app layout designs, all transitions work as expected (and nothing is animated on classic app layout as expected too)
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CO …
> fix: remove unexpected transitions in app layout panels

- pages/app/index.tsx
- pages/prompt-input/simple.page.tsx
- src/prompt-input/__integ__/prompt-input.test.ts
- src/prompt-input/internal.tsx
Fix Prompt input has incorrect height on first render when expanding split panel. It is because the height is set to scrollHeight of the textarea Ref, but it can be 0 when it is in collapsed Split panel. The fix uses the 1 row height of textarea (1 line height + top&bottom padding) as the min height.
Related links, issue AWSUI-56326
Added integration test and run the fix though dev pipeline.
<details> …
> fix: Prompt input has incorrect height on first render when expanding split panel

- pages/funnel-analytics/table.page.tsx
- src/table/__integ__/component-metrics.test.ts
- src/table/__tests__/component-metrics.test.tsx
- src/table/internal.tsx
- Move table task interaction id to root of component to allow components in table actions slots to be aware of this id
- Added an additional integ test to check the information received from the table mount event
- Added additional unit test for data attribute
- Added additional integ test for taskName value
<details> …
> chore: Move table task interaction id to root of component

- src/table/__tests__/analytics-metadata.test.tsx
Add a test to cover use case from this [PR](https://github.com/cloudscape-design/component-toolkit/pull/105).
Related links, issue #, if available: AWSUI-59898
locally
<details> …
> chore: Test analytics metadata in a table with empty header

- src/app-layout/visual-refresh-toolbar/toolbar/styles.scss
This PR addresses an issue with first drawer focus indicator on mobile view (see the screenshot attached)
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-princip …
> fix: Drawer trigger focus indicator

- pages/prompt-input/simple.page.tsx
- src/prompt-input/styles.scss
Previously, the top and end paddings of the prompt input secondary content area were not equal. This created tense layouts that were exacerbated by the current file upload work. This makes the paddings equal on all sides, as well as placing a component without built-in paddings on the test page so that it is easy to tell.
<details> …
> fix: Makes paddings equal on all sides in prompt input

- src/app-layout/constants.scss
- src/drawer/implementation.tsx
- src/drawer/styles.scss
- src/help-panel/implementation.tsx
- src/help-panel/styles.scss
- src/side-navigation/styles.scss
Adjusts the panel header padding to match original VR, in order to fix the misalignment of the Q settings icon and the panel close button. Originally the panel header height was reduced for the toolbar so that the headers and close icons could be aligned with the content in the toolbar. This was when the placement of the toolbar was between the panels, which is not the case anymore. This resets the headers to align with the rest of the elements on the page (flashbars, page headers, table headers, etc).
This change also reduces the space below panel headers so it is more uniform, which fixes a visual bug in side nav where control item had too much space around it and sections that were first in the nav list had too much space above them (in both VR and toolbar).
Related links, issue #, if …
> chore: Reset panel header spacing and fix make content alignment more consistent

- pages/app-layout/multi-layout-global-drawer-child-layout.page.tsx
- src/app-layout/__integ__/multi-app-layout-global-drawer-child.test.ts
- src/app-layout/__tests__/multi-layout-props.test.tsx
- src/app-layout/visual-refresh-toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/multi-layout.ts
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
This PR addresses an issue when a global drawer is registered, but its associated trigger button is not displayed in the toolbar
<details> …
> fix: Pass global drawers' data to toolbar via dedupe api

- src/side-navigation/parts.tsx
- src/side-navigation/styles.scss
There is a [known issue in autoprefixer](https://github.com/postcss/autoprefixer/issues/1391) when using the `@supports` css query with a pseudo-class. It has since been fixed, but many internal teams are using post css autoprefixer older than 10.2.5. This PR removes the use of the `:has()` pseudo-class in the side nav to unblock the pipeline.
Ran through dev pipeline
<details> …
> chore: Remove @supports query for :has() pseudo-class in side nav

- src/__tests__/__snapshots__/test-utils-selectors.test.tsx.snap
- src/s3-resource-selector/s3-modal/index.tsx
- src/s3-resource-selector/s3-modal/styles.scss
- src/s3-resource-selector/test-classes/styles.scss
- src/test-utils/dom/s3-resource-selector/index.ts
When rendering an S3 Resource Selector with a regular Modal using the visible property set to false the test util selector would return the first Modal it finds. This change makes the test util selector more specific to be able to find the associated S3 Modal.
E.g.
```
<Modal visible={false} />
<S3ResourceSelector {...s3ResourceSelectorProps} />
```
Modified a dev page to include a Modal and checked before and after the change. Since its just a once off fix, it does not make sense to add this in as a regression test. This can better be tested in a package like demos where various components are tested together and the test utils are used from a customer's perspective.
<details> …
> fix: S3 resource selector findModal selector test util returning incorrect modal

- src/app-layout/__tests__/runtime-drawers.test.tsx
- src/app-layout/utils/use-drawers.ts
Currently, if we have controllable tools and runtime drawers, after clicking on the trigger of the info panel, it ignores updates to the `toolsOpen` value. That happens because `activeDrawerId` is controlled separately and it still points to the tools drawer.
Related links, issue #, if available: AWSUI-57748
- new unit test added
<details> …
> fix: Respect toolsOpen after opening Tools via drawer

- pages/app-layout/utils/external-widget.tsx
- src/app-layout/__integ__/runtime-drawers.test.ts
- src/app-layout/visual-refresh-toolbar/drawer/global-drawer.tsx
- src/app-layout/visual-refresh-toolbar/drawer/styles.scss
This PR resolves an issue with global drawer content not scrolling when it exceeds the drawer container height and should be scrollable by user
https://github.com/user-attachments/assets/5866df39-7d8a-49c1-bc47-0866bf0f0019
action. 
<details>
- …
> fix: Scroll inside global drawers

- pages/app-layout/utils/drawers.tsx
- src/app-layout/__integ__/app-layout-drawers.test.ts
- src/app-layout/visual-refresh-toolbar/drawer/styles.scss
Current styling stretches this elements vertical height to fill the page height. Given its z-index it can block elements below.
<details> …
> fix: Toolbar close button height extending full height of page

- src/app-layout/__integ__/runtime-drawers.test.ts
For more reliable test coverage, this separates mobile and desktop scroll tests for #2987 fix.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessi …
> test: Separate mobile and desktop tests for recent scroll fix

- pages/app-layout/runtime-drawers.page.tsx
- pages/app-layout/styles.scss
- pages/app-layout/utils/content-blocks.tsx
- pages/app-layout/utils/external-widget.tsx
- pages/app-layout/with-drawers-scrollable.page.tsx
- src/app-layout/__integ__/awsui-applayout.test.ts
- src/app-layout/__integ__/runtime-drawers.test.ts
- src/app-layout/drawer/index.tsx
- src/app-layout/drawer/styles.scss
- src/app-layout/visual-refresh-toolbar/compute-layout.ts
- src/app-layout/visual-refresh-toolbar/drawer/global-drawer.tsx
- src/app-layout/visual-refresh-toolbar/drawer/local-drawer.tsx
- src/app-layout/visual-refresh-toolbar/navigation/index.tsx
- src/app-layout/visual-refresh-toolbar/navigation/styles.scss
- src/app-layout/visual-refresh-toolbar/split-panel/index.tsx
- src/app-layout/visual-refresh/drawers.scss
- src/app-layout/visual-refresh/navigation.scss
- src/app-layout/visual-refresh/navigation.tsx
This is a follow up from https://github.com/cloudscape-design/components/pull/2924 that addresses double scrollbar issue in Q chat panel (AWSUI-59823).
It also addresses an issue in Firefox where side nav would have a scrollbar when there was no side nav header present, the original reason for revert. The other issue regarding flashing scrollbar has been extracted from this PR.
Related links, issue #, if available: AWSUI-59823, TT: V1549419424, TT: D169004346, 
Related screenshot tests added in CR-158701022
Ran through dev pipeline screenshot approvals: 
- 1st: 833b9bfc-f87e-462e-b8e9-3d6f48d73c2a
- 2nd: 42b2f287-623e-4d54-ba8d-29edf66bea4d
<details> …
> chore: Allow drawer content to use full height

- src/__tests__/snapshot-tests/__snapshots__/test-utils-selectors.test.tsx.snap
- src/flashbar/__tests__/collapsible.test.tsx
- src/flashbar/__tests__/flashbar.test.tsx
- src/flashbar/collapsible-flashbar.tsx
- src/flashbar/flash.tsx
- src/flashbar/interfaces.ts
- src/flashbar/non-collapsible-flashbar.tsx
- src/test-utils/dom/anchor-navigation/index.ts
- src/test-utils/dom/flashbar/index.ts
Adds `testId` prop to flash items inside the flashbar component.
<details> …
> feat: Adds test id to flashbar dom selector

- pages/app-layout/refresh-content-width.page.tsx
- pages/app-layout/with-drawers.page.tsx
- pages/app-layout/with-one-open-drawer.page.tsx
- src/alert/__integ__/runtime-content.test.ts
- src/annotation-context/__integ__/annotation-scroll.test.ts
- src/app-layout/__integ__/app-layout-drawers.test.ts
- src/app-layout/__integ__/app-layout-focus-delegation.test.ts
- src/app-layout/__integ__/app-layout-refresh-content-width.test.ts
- src/app-layout/__integ__/app-layout-split-panel.test.ts
- src/app-layout/__integ__/app-layout-sticky-elements.test.ts
- src/app-layout/__integ__/runtime-drawers-with-updates.test.ts
- src/autosuggest/__integ__/form-submit.test.ts
- src/button-dropdown/__integ__/button-dropdown-disabled-reason.test.ts
- src/button-dropdown/__integ__/button-dropdown-events.test.ts
- src/button-group/__integ__/button-group.test.ts
- src/button/__tests__/internal.test.tsx
- src/form-field/__tests__/form-field-control-id.test.tsx
- src/form/__tests__/analytics.test.tsx
- src/internal/analytics/__integ__/static-multi-page-create.test.ts
- src/internal/analytics/__integ__/static-single-page-flow.test.ts
- src/modal/__tests__/analytics.test.tsx
- src/table/__integ__/inline-actions.test.ts
- src/table/__integ__/keyboard-scroll.test.ts
Adds the usage of the newly added selectors in [this PR](https://github.com/cloudscape-design/components/pull/2932) to the existing tests.
Depends on: https://github.com/cloudscape-design/components/pull/2932
Related links, issue #, if available: **Test utils API improvements project**
N/A
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers …
> chore: Uses the new selectors inside existing tests

- src/app-layout/__tests__/runtime-drawers.test.tsx
This PR adds a unit test for global drawers to ensure that classes overridden in another package remain as is. The goal of this test is to avoid any unnoticed modifications to these classes.
<details> …
> chore: U test for checking overridden classes

- package.json
Make the build fail, if assets to bundle in app layout widget grow too high
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibil …
> chore: Add size-limit check for app layout widget entry points

- src/property-filter/__tests__/property-filter-token-editor.test.tsx
- src/property-filter/token-editor-inputs.tsx
The PR addresses `.toLowerCase() is not a function` error thrown from the token editor in case token value is numeric (possible when a query is created programmatically).
Rel: AWSUI-59929
<details> …
> fix: Tolerates numeric token values in default forms

- src/breadcrumb-group/__tests__/breadcrumb-group.test.tsx
- src/breadcrumb-group/interfaces.ts
- src/breadcrumb-group/item/item.tsx
- src/test-utils/dom/breadcrumb-group/index.ts
Adds `testId` prop to breadcrumb items inside the breadcrumb group component.
<details> …
> feat: Adds test id to breadcrumb items

- src/app-layout/__tests__/global-breadcrumbs.test.tsx
- src/app-layout/__tests__/skeleton.test.tsx
- src/app-layout/visual-refresh-toolbar/navigation/index.tsx
- src/app-layout/visual-refresh-toolbar/notifications/index.tsx
- src/app-layout/visual-refresh-toolbar/skeleton/breadcrumbs/index.tsx
- src/app-layout/visual-refresh-toolbar/skeleton/breadcrumbs/styles.scss
- src/app-layout/visual-refresh-toolbar/skeleton/slot-skeletons.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/styles.scss
- src/breadcrumb-group/__tests__/breadcrumb-group.test.tsx
- src/breadcrumb-group/__tests__/breadcrumb-item.test.tsx
- src/breadcrumb-group/__tests__/widgetized-breadcrumbs.test.tsx
- src/breadcrumb-group/implementation.tsx
- src/breadcrumb-group/index.tsx
- src/breadcrumb-group/interfaces.ts
- src/breadcrumb-group/item/funnel.tsx
- src/breadcrumb-group/item/item.tsx
- src/breadcrumb-group/item/styles.scss
- src/breadcrumb-group/skeleton.tsx
- src/breadcrumb-group/styles.scss
- src/internal/analytics/components/analytics-funnel.tsx
- src/internal/analytics/selectors.ts
- src/internal/widgets/index.tsx
- src/wizard/internal.tsx
Make breadcrumbs slot rendered even when the app layout widget is in the loading state, because it is important for funnel metrics tracking
* Added extra unit tests
* Also tested end-to-end in my dev pipeline
<details> …
> chore: Render breadcrumbs slot in the skeleton state

- pages/app-layout/runtime-drawers-with-only-global.page.tsx
- src/app-layout/__tests__/runtime-drawers.test.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/drawer-triggers.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
When only global drawers are present, the panel still should render
Related links, issue #, if available: AWSUI-59981
Locally. More tests later
<details> …
> fix: Render drawers bar if only global drawers are present

- pages/file-token-group/permutations.page.tsx
The permutations page includes a spinner, which we need to pause for screenshot tests.
<details> …
> fix: Disables animations on file token group permutations page

- src/radio-group/__tests__/radio-group.test.tsx
- src/radio-group/interfaces.ts
- src/radio-group/internal.tsx
- src/radio-group/radio-button.tsx
- src/test-utils/dom/radio-group/index.ts
Adds `testId` to radio group items.
<details> …
> feat: Adds test id to radio group buttons

- src/cards/__tests__/cards.test.tsx
- src/cards/index.tsx
- src/cards/interfaces.tsx
- src/test-utils/dom/cards/index.ts
Adds `testId` extractor function to cards inside the card component. Unlike other components, cards can't have a single `testId` prop as the `items` are generic with no base types. For this reason we use a function to extract test id for every individual item.
<details>
- _Changes do …
> feat: Adds test id to cards

- src/wizard/__integ__/wizard.test.ts
- src/wizard/wizard-form.tsx
As the focus is there to alert users of content change, focusing the header on the first render is not necessary. This change will only attempt to focus on the header on subsequent active index changes within the wizard.
Related links, issue #, if available: AWSUI-59850
- Added additional integ test. …
> chore: Do not focus Wizard header on initial render

- pages/app-layout/navigation-with-scrollbar.page.tsx
- src/__integ__/use-browser-with-scrollbars.ts
- src/app-layout/__integ__/navigation.test.ts
- src/app-layout/visual-refresh-toolbar/navigation/index.tsx
- src/app-layout/visual-refresh-toolbar/navigation/styles.scss
Ticket: AWSUI-59956
Before (navigation content is too wide, and part of its padding is being overlapped by the scrollbar):
After (navigation content respects the available space excluding the scrollbar):
- Manually tested on Chrome, Firefox and Safari
- Added an integration test
- Ran in my pipeline
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.m …
> fix: Prevent scrollbar from overlapping side navigation content

- src/autosuggest/__tests__/autosuggest.test.tsx
- src/internal/components/option/index.tsx
- src/internal/components/option/interfaces.ts
- src/multiselect/__tests__/multiselect.test.tsx
- src/multiselect/__tests__/test-utils.test.tsx
- src/select/__tests__/common.ts
- src/select/__tests__/select.test.tsx
- src/select/__tests__/test-utils.test.tsx
- src/test-utils/dom/autosuggest/index.ts
- src/test-utils/dom/internal/dropdown-host.ts
Adds `testId` prop to option component.
The change will be reflected in select, multi-select, autosuggest and property filter components.
Since `Option` is being used in several components, this PR adds test id to:
* Select
* Multiselect
* Autosuggest
<details>
- _Changes do not …
> feat: Adds test id to select items 

- src/modal/__integ__/modal.test.ts
- src/modal/internal.tsx
Description
The change involves adding modal header text as Component identifier to modal metric - timeToContentReadyInModal when a modal is loaded.
How has this been tested?
manually tested the change
integration test updated to verify component header text.
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#b …
> chore: Update modal performance data to include modal header

- pages/file-token-group/permutations.page.tsx
- pages/file-upload/scenario-standalone.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/file-token-group/__tests__/file-token-group.test.tsx
- src/file-token-group/file-token.tsx
- src/file-token-group/interfaces.ts
- src/file-token-group/internal.tsx
- src/file-upload/__tests__/file-upload.test.tsx
- src/file-upload/interfaces.ts
- src/file-upload/internal.tsx
- src/i18n/messages-types.ts
- src/i18n/messages/all.ar.json
- src/i18n/messages/all.de.json
- src/i18n/messages/all.en-GB.json
- src/i18n/messages/all.en.json
- src/i18n/messages/all.es.json
- src/i18n/messages/all.fr.json
- src/i18n/messages/all.id.json
- src/i18n/messages/all.it.json
- src/i18n/messages/all.ja.json
- src/i18n/messages/all.ko.json
- src/i18n/messages/all.pt-BR.json
- src/i18n/messages/all.tr.json
- src/i18n/messages/all.zh-CN.json
- src/i18n/messages/all.zh-TW.json
This adds default provided strings from the i18nStrings messages to file token group and file upload, and in turn makes those properties optional instead of required.
<details> …
> feat: Adds i18n provider to file upload and file token group

- pages/file-token-group/permutations.page.tsx
Screenshot tests were failing due to the `lastModifiedDate` on file tokens changing dynamically. This adds a formatter so that the date is a constant.
<details> …
> fix: Fixes date changing on file token group page

- pages/container/content-overflow.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/test-utils-selectors.test.tsx.snap
- src/container/internal.tsx
- src/container/styles.scss
- src/container/test-classes/styles.scss
- src/test-utils/dom/expandable-section/index.ts
The PR fixes an issue when the container padding caused table scrollbar to display incorrectly. It also improves the handling of fit-height charts that do not fit the container.
Rel: AWSUI-54814
Before:
https://github.com/user-attachments/assets/10c1fd07-8be4-4bea-9f2f-9be3f21be495
After:
https://github.com/user-attachments/assets/358fe6f2-1a43-47c1-8d94-84a3e4def387
<details> …
> fix: Fixes container overflow padding

- pages/table/cell-permutations.page.tsx
- src/table/__tests__/header-cell.test.tsx
- src/table/__tests__/progressive-loading.test.tsx
- src/table/body-cell/disabled-inline-editor.tsx
- src/table/body-cell/index.tsx
- src/table/body-cell/td-element.tsx
- src/table/header-cell/index.tsx
- src/table/header-cell/th-element.tsx
- src/table/internal.tsx
- src/table/no-data-cell.tsx
- src/table/progressive-loading/items-loader.tsx
- src/table/progressive-loading/loader-cell.tsx
- src/table/selection/selection-cell.tsx
- src/table/thead.tsx
In the PR I am creating components for all types of table cells, including selection header cell, selection body cell, loader cell. This helps ensure the styles are consistently assigned and not propagated from the outside as className or style.
* Screenshot tests (no changes expected);
* New permutations page that reproduces all available header and body cell styles.
<details> …
> refactor: Componentizes table cell types and adds permutations

- src/tabs/__integ__/tabs.test.ts
- src/tabs/__tests__/smooth-scroll.test.tsx
- src/tabs/native-smooth-scroll-supported.ts
- src/tabs/smooth-scroll.ts
- src/tabs/tab-header-bar.scss
This reverts commit 8c1bdca73f5f4fa7d5603796824ef3bcc9c6b237.
For some reason on Firefox the tabs don't initialize in the expected scroll position when the fourth tab is the active one.
<details> …
> revert: Revert "feat: Add scroll snapping to responsive tabs (#2899)"

- pages/table/cell-permutations.page.tsx
- src/table/__tests__/header-cell.test.tsx
- src/table/__tests__/progressive-loading.test.tsx
- src/table/body-cell/disabled-inline-editor.tsx
- src/table/body-cell/index.tsx
- src/table/body-cell/td-element.tsx
- src/table/header-cell/index.tsx
- src/table/header-cell/th-element.tsx
- src/table/internal.tsx
- src/table/progressive-loading/items-loader.tsx
- src/table/progressive-loading/loader-cell.tsx
- src/table/selection/selection-cell.tsx
- src/table/thead.tsx
This reverts commit 6d25f884cdeef43872b087c8eb8e933a3088559e to re-introduce https://github.com/cloudscape-design/components/pull/3017
<details> …
> revert: Reintroduces table cell types permutations and refactoring

- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/cards/index.tsx
- src/collection-preferences/index.tsx
- src/collection-preferences/interfaces.ts
- src/table/index.tsx
Adds additional metrics for collection preferences, table, and cards. Updates collection preferences API docs to reflect the expected usage of visible content and content display better.
Rel: [g7eCAnu4xJMH]
<details> …
> chore: Adds metadata metrics for collection preferences

- src/table/body-cell/index.tsx
Fixes a regression introduced in this commit: https://github.com/cloudscape-design/components/pull/3017/commits/3b2bdd646c1bcceeb6037ee996f799fc0cc7ff43
Explanation: a cell can be set as editable but we currently disable it if the cell is also expandable. For that reason it is necessary to explicitly pass isEditable={false} as otherwise the editable styles still apply.
<details> …
> fix: Removes editable styles from expandable cells

- src/wizard/styles.scss
Ticket: AWSUI-60000
The background of the wizard navigation is not correct and not necessary. This is not noticeable without theming because in Visual Refresh, `$color-background-container-content` and `$color-background-layout-main` have the same value, but the issue becomes apparent once they are themed to different values.
Ran through my pipeline and caught the difference in a test for themed components. The new state is the correct one. Coverage already exists.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.m …
> fix: Remove unnecessary background color from wizard navigation

- src/app-layout/__tests__/common.test.tsx
- src/app-layout/__tests__/runtime-drawers.test.tsx
Ensure `findTools` and `findActiveDrawer` test utils always work as expected
Related links, issue #, if available: AWSUI-59987
Test only change
<details> …
> chore: Add extra tests on tools/drawer alias behavior

- src/app-layout/__tests__/runtime-drawers.test.tsx
Make sure this case has a test
Related links, issue #, if available: P165315773
This is a test
<details> …
> chore: Test that unmountContent is called when app layout is unmounted

- src/attribute-editor/__tests__/attribute-editor.test.tsx
- src/attribute-editor/internal.tsx
- src/tag-editor/__tests__/tag-editor.test.tsx
The original issue was that the focus wasn't being moved to the add button when `tagLimit={1}` and the user removes the only row. What was happening was that we would try to move focus imperatively in the remove handler, but at that moment, the add button is still disabled. It becomes enabled when the attribute editor rerenders after the row is removed.
We could solve this by "storing" the focus move and acting on it in the next render (in fact, we do something like this in the tag editor), but that is complex and hard to maintain. So why not just make it focusable (`aria-disabled` + `tabindex="-1"`)?
Related links, issue #, if available: AWSUI-59916
Unit tests and manual checking in the dev pages.
<details>
_The following items are to be evaluated by …
> fix: Move focus to the attribute editor add button even if currently disabled

- pages/column-layout/alignment.page.tsx
- src/column-layout/flexible-column-layout/styles.scss
In the Key-Value-Pair component, the border between the columns was positioned with a slight horizontal offset. This happened because the border was placed at the left edge of a column.
This code change moves the border, so that it is positioned exactly in the middle of the two columns.
Related links, issue #, if available: AWSUI-59957
Tested manually in the browser. Added a new dev page where the alignment of the border can be checked.
<details>
- _Changes …
> fix: Key-value pair border not center-aligned

- src/copy-to-clipboard/__tests__/copy-to-clipboard.test.tsx
- src/copy-to-clipboard/internal.tsx
AWSUI-60050
The root of this issue is that we have two trigger handlers for the copy-to-clipboard component: one attached to a custom trigger wrapper (within the popover component) and another to the trigger itself. Since these triggers have slightly different visual layouts - the outer wrapper lacks a border radius while the inner trigger has one, clicking just outside the inner button corners opens the popover but does not activate the copy-to-clipboard handler. This behavior led to the issue described in the ticket.  
This PR resolves the issue by attaching the existing copy-to-clipboard handler to the popover trigger event.
<details>
_The following items are to be evaluated by the author(s) and the …
> fix: Copy to clipboard misleading popover when clicking outside the corner

- src/attribute-editor/__tests__/attribute-editor.test.tsx
- src/attribute-editor/internal.tsx
- src/tag-editor/__tests__/tag-editor.test.tsx
Reverts cloudscape-design/components#3035. Looks like we have tests that check for the add button to be disabled that I couldn't find with a code search after all. Reverting "pessimistically" to have a clean path to merge.
Looks like I'll have to go with a less ideal "queued" focus effect logic.
> revert: Revert "fix: Move focus to the attribute editor add button even if currently disabled"

- pages/app-layout/multi-layout-iframe.page.tsx
- src/date-picker/index.tsx
- src/date-range-picker/dropdown.tsx
- src/modal/internal.tsx
- src/popover/__tests__/popover.test.tsx
- src/popover/body.tsx
Ticket V1595368753
A page crashes on chrome 131 when closing popover by clicking on close button. Closing via keyboard (by pressing enter on close button) or clicking outside of popover does not cause such a crash.
The issue occurs when both `aria-modal="true"` and `role="dialog"` are present. Removing either of them resolves the problem.
I wasn’t able to reproduce this issue in the integration test environment, so no tests are available for it.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/bl …
> fix: Page crash on closing popover

- src/app-layout/__integ__/app-layout-refresh-content-width.test.ts
- src/app-layout/visual-refresh-toolbar/skeleton/styles.scss
Avoid this content jump when resizing the screen
https://github.com/user-attachments/assets/53e6ab70-3d0c-46f8-bb28-8a486cfef4a3
* Locally, no jump anymore
* Screenshot tests in my dev pipeline for unexpected regressions
<details> …
> fix: Avoid width jump when resizing app layout (toolbar mode only)

- .github/workflows/build-lint-test.yml
- pages/webpack.config.base.js
- pages/webpack.config.js
Moves the build artifacts of the pages outside of the root lib and into the `/pages/lib`.  Everything inside the root lib is considered a releasable artifact but we do not need to release the dev pages and so they can be removed.
<details>
- …
> chore: Move dev pages build artifacts outside of lib

- pages/funnel-analytics/modal.page.tsx
- src/form/__tests__/analytics.test.tsx
- src/internal/analytics/selectors.ts
- src/modal/__tests__/analytics.test.tsx
- src/modal/index.tsx
Currently the funnel name selector was resolving to the first modal header it could find. If there are multiple modals on the page, even if the modal is not visible its header could still be found in the dom. This change adds a unique id for each modal associated with a funnel for the selector to resolve correctly.
Added unit test
<details> …
> chore: Fix multi modal funnel support

- src/tabs/__integ__/tabs.test.ts
- src/tabs/__tests__/smooth-scroll.test.tsx
- src/tabs/native-smooth-scroll-supported.ts
- src/tabs/scroll-utils.ts
- src/tabs/smooth-scroll.ts
- src/tabs/tab-header-bar.scss
- src/tabs/tab-header-bar.tsx
This reverts commit 7948389b3dea282bfb37abcc9aa0bfa6e0abc43f.
It had unexpected effects on vertical scrolling (clicking on a tab would scroll down by certain amount).
<details> …
> revert: Revert "feat: Introduce scroll snapping to responsive tabs (#3088)"

- pages/table/expandable-rows-test.page.tsx
- pages/table/expandable-rows.permutations.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/table/__tests__/progressive-loading.test.tsx
- src/table/interfaces.tsx
- src/table/internal.tsx
- src/table/progressive-loading/items-loader.tsx
- src/table/progressive-loading/loader-cell.tsx
- src/table/progressive-loading/progressive-loading-utils.ts
Adds empty state to currently existing pending, loading, error, and finished states of the table progressive loading. That is to support async row expand that results in an empty array of nested items.
Rel: [yCGlAk8AlAO9]
* Enhanced unit tests
* Manual testing on the updated test page
* Dry run to ensure no TS issues caused by the type extension
<details> …
> feat: Adds table progressive loading empty state

- pages/button/permutations.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/button/__tests__/button.test.tsx
- src/button/index.tsx
- src/button/interfaces.ts
- src/button/internal.tsx
- src/button/test-classes/styles.scss
- src/i18n/messages-types.ts
- src/i18n/messages/all.ar.json
- src/i18n/messages/all.de.json
- src/i18n/messages/all.en-GB.json
- src/i18n/messages/all.en.json
- src/i18n/messages/all.es.json
- src/i18n/messages/all.fr.json
- src/i18n/messages/all.id.json
- src/i18n/messages/all.it.json
- src/i18n/messages/all.ja.json
- src/i18n/messages/all.ko.json
- src/i18n/messages/all.pt-BR.json
- src/i18n/messages/all.th.json
- src/i18n/messages/all.tr.json
- src/i18n/messages/all.zh-CN.json
- src/i18n/messages/all.zh-TW.json
Added an external icon so that the icon label itself can be more easily provided by us through the I18nProvider.
~~The strings aren't included in this PR yet, waiting for a handover from the translators. Should take a few days, but with re:Invent, who knows.~~ In the meantime, I've included the strings we expect to get back (based on the link external icon strings) for review purposes.
Related links, issue #, if available: AWSUI-22607, [OdqSAkZmdBS7]
Updated the permutations page and added unit tests.
<details> …
> feat: Add `external` property to button

- src/internal/components/options-list/utils/use-keyboard.ts
- src/multiselect/__integ__/multiselect.test.ts
- src/select/__integ__/select.test.ts
- src/select/__tests__/use-select.test.ts
- src/select/utils/use-select.ts
We received a number of complaints that multiselect with filtering doesn't let you select options using the Space key (which is something you might expect to be able to do since you see a checkbox affordance). But... it also makes sense that you can't, because the focus is on the input - so we need the space key so that you can type in a space. But to split the difference, we can have it so that space selects an option, but only if you navigated to it with the keyboard or mouse (and presumably finished typing). Typing any other character resets that and lets you type in spaces again.
Related links, issue #, if available: AWSUI-19497
Integ tests and manual playing around. Try it yourself!
<details> …
> fix: Allow space key to select an option inside select/multiselect with filtering

- pages/button-group/test.page.tsx
- pages/file-input/simple.page.tsx
- pages/prompt-input/simple.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/button-group/__integ__/button-group.test.ts
- src/button-group/__tests__/button-group-dev.test.tsx
- src/button-group/__tests__/button-group-focus.test.tsx
- src/button-group/__tests__/button-group-keyboard.test.tsx
- src/button-group/__tests__/button-group-states.test.tsx
- src/button-group/__tests__/button-group-tooltips.test.tsx
- src/button-group/file-input-item.tsx
- src/button-group/interfaces.ts
- src/button-group/internal.tsx
- src/button-group/item-element.tsx
- src/file-input/__tests__/file-input.test.tsx
- src/file-input/internal.tsx
- src/file-input/styles.scss
- src/test-utils/dom/button-group/index.ts
Adds file-input to the button group component.
<details> …
> feat: Adds file input type to button group component

- src/top-navigation/parts/overflow-menu/menu-item.tsx
Recent refactoring (#3025) caused top nav button to be reversed, this fixes that regression.
Local testing.
<details> …
> fix: Top navigation icon direction

- src/modal/index.tsx
`CSS.escape` is not available in jsdom or SSR. This component is not SSR friendly anyway but including an optional chaining here can at least prevent it from breaking.
<details> …
> chore: Only use CSS escape if available for modal funnel name

- build-tools/jest/setup.js
- src/__tests__/functional-tests/ssr.test.ts
These imports have side-effects which we do not want when running SSR compatibility tests
Updated an SSR test to ensure the CSS.escape polyfill is not loaded
<details> …
> chore: Do not load testing-library and jest-dom helpers in SSR enviroment

- pages/property-filter/async-loading.integ.page.tsx
- src/autosuggest/__tests__/load-more-controller.test.ts
- src/autosuggest/load-more-controller.ts
- src/property-filter/__integ__/async-loading.test.ts
- src/property-filter/__tests__/property-filter.test.tsx
Currently, in the Property Filter there is a specific corner case: with `asyncProperties === true` when moving focus away from the input and then clicking on Clear button, `onLoadItems` is invoked with only previous `filteringText` value. That means, callback for `onLoadItems` won't load items for a new, empty string. The issue happens when filter by free text, not when specific property was detected
This is not expected and different from similar behaviour in autosuggest.
With this fix, there will be multiple subsequent `onLoadItems` calls:
1. with the previous `filteringText` value on input focus, which happens before Clear button callback is invoked;
2. with empty `filteringText`
Related links, issue #, if available: AWSUI-59621
* update unit test to move focus away before clicking on …
> fix: Pass empty string to onLoadItems after clicking Clear button

- src/tabs/__integ__/tabs.test.ts
- src/tabs/tab-header-bar.scss
Reintroduced tabs scroll snapping reverted in [this commit](https://github.com/cloudscape-design/components/pull/3110)
The main problem with the previous implementation was related to `scrollIntoView` usage, that causes undesired side effects (vertical page scrolling). I left the custom scrolling implementation as is and covered this cause with an integration test.
To check if the new integ test actually covers this scenario, replace [this line](https://github.com/cloudscape-design/components/blob/main/src/tabs/tab-header-bar.tsx#L137) with the following code:
```javascript
activeTabRef?.scrollIntoView?.({ behavior: smooth ? 'smooth' : 'auto', inline: 'center' });
```
and then run:
```
npx jest -c jest.integ.config.js src/tabs/__integ__/tabs.test.ts;
```
Related links, issue #, if …
> feat: Tabs scroll snapping

- pages/utils/permutations-view.tsx
Issue: `AWSUI-60140`
When the number of permutations exceeds the established maximum, an error will be thrown, which will be shown instead of the page content:
In the first commit of this PR, the maximum was tentatively set to 200 and a few views showed the error which caused existing tests to fail: https://github.com/cloudscape-design/components/actions/runs/12263978366
[Example dev page](https://d21d5uik3ws71m.cloudfront.net/components/ff71362d9ed7554551cfa01fcf0c5318d707c384/dev-pages/index.html#/light/slider/permutations) from the first deployment.
The highest number of permutations we currently have in a dev page is 276, so using that as the maximum.
<details>
- …
> chore: Set limit to number of permutations

- package.json
- src/internal/widget-exports.ts
1. Use the uncompressed number, because we have a downstream requirement of maintaining 
2. Introduce `widget-exports.js` because when `path` config is an array, it bundles every item individually and duplicates dependencies in the sum
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#brows …
> chore: update size-limit config

- src/modal/index.tsx
Global CSS is undefined in JSDOM. See https://github.com/cloudscape-design/components/pull/3120#discussion_r1877957379
<details>
- _If …
> chore: Check existence of window object when referring to global CSS interface

- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/wizard/interfaces.ts
Updated wizard's i18nStrings.submitButton description to clarify that this value is not supported in Cloudscape's i18nProvider.
Related links, issue #, if available: AWSUI-60108
<details> …
> fix: Update wizard's i18nStrings.submitButton description

- src/s3-resource-selector/s3-modal/__tests__/buckets-table.test.tsx
- src/s3-resource-selector/s3-modal/buckets-table.tsx
Reorder columns in table so Region comes before the date. This is in preparation for a new article about Region formatting in the console. This also matches more closely what is displayed in s3 and in the s3 selector widget.
Ran through dev pipeline.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browse …
> chore: Re-order s3 resource selector bucket Regions column

- src/app-layout/__integ__/app-layout-split-panel.test.ts
- src/app-layout/visual-refresh-toolbar/index.tsx
- src/internal/context/split-panel-context.ts
- src/split-panel/bottom.tsx
When the split panel is collapsed, it should not cover the main content. We achieve this by adding extra padding to the main content, similar to the non-toolbar design: https://github.com/cloudscape-design/components/blob/468db9e5e4f940ceff4c1289f8800121ca1f9cc5/src/app-layout/visual-refresh/main.scss#L20-L22
- Added integration test, which failed before the fix and passes after
- Manually tested. Compared result with non-toolbar design
<details>
- _Changes …
> fix: Prevent collapsed bottom split panel from covering content

- pages/autosuggest/simple.page.tsx
- src/__a11y__/to-validate-a11y.ts
- src/autosuggest/__tests__/autosuggest-dropdown-states.test.tsx
- src/autosuggest/__tests__/autosuggest.test.tsx
- src/autosuggest/internal.tsx
Currently, the aria-expanded on autosuggest input is set to false when the dropdown has only entered text value option. That is inconsistent to states when the dropdown only shows a status like "finished" or "loading". The PR makes it so the ARIA expanded is added whenever the dropdown is visible.
Additionally, the PR refactors autosuggest dropdown states tests mainly to include the filtering results text feature that does not have a single in the main.
Rel: [A2f2AlIalxx9]
* Updated unit tests to secure the aria-expanded is set to true for all dropdown states.
<details> …
> fix: Makes autosuggest input use aria-expanded every time the dropdown is shown

- src/mixed-line-bar-chart/chart-container.tsx
Prevents an error when the underlying data set changes while a segment is hovered.
<details> …
> chore: More defensive coding in charts

- src/table/body-cell/styles.scss
The PR includes two small fixes and minor refactoring for editable table cell styles:
1. Improved editor vertical alignment;
2. Correct editable cell padding in sticky column.
Before:
https://github.com/user-attachments/assets/cc480f20-3953-44e6-81c1-53d17d9cda01
After:
https://github.com/user-attachments/assets/57ccf36c-2152-432e-be90-04ca496532bc
* Manual testing on "cell-permutations" and "editable" test pages.
* Screenshot tests.
<details>
- _Changes do …
> fix: Fixes editable table cell paddings for certain corner cases

- package-lock.json
- package.json
In v 1.37 of `ace-builds` there are breaking changes. Pinning this for now to unblock the pipeline
Related links, issue #, if available: -
- dry-run build 7167165402 to live is green
- dev pipeline successfully merged from live
<details> …
> chore: Pin ace-builds version

- .stylelintrc
Adds the `z-index-value-constraint` stylelint rule to this repo.
The rule itself was added in [this PR](https://github.com/cloudscape-design/build-tools/pull/4).
Related links, issue #, if available: AWSUI-55594
<details> …
> chore: Adds the z-index-constraint rule to stylelint

- src/button-dropdown/internal.tsx
- src/button-dropdown/styles.scss
In ButtonDropdown component with main action and full width props, the css style to align text to the center gets overriden sometimes by `Button` component default styles due to not having enough specificity.
in this commit, passing `fullWidth` prop to internal button ensures that the `text-align` style is applied with a specificity that doesn't get overriden by default styles.
<details> …
> fix: Add more css specificity to center text in full width button dropdown main action

- package-lock.json
- package.json
Issue: `AWSUI-60096`
Also see #3080
- Dry run
<details> …
> chore: Upgrade react-keyed-flatten-children to v2.2.1

- src/__tests__/functional-tests/ssr.test.ts
Some people rely on modal not throwing in SSR, so we will include this into our SSR test suite, even if the expected result is an empty string
Test-only change
<details> …
> chore: Un-skip modal in ssr tests

- pages/table/stacked-and-container-variant.page.tsx
- src/table/styles.scss
Added bottom padding to stacked table. Previously when the last item was selected, there would be no space between the selected item and table border whereas container variant table had space.
Related links, issue #, if available: AWSUI-60100
<details> …
> fix: Bottom padding in stacked table

- build-tools/tasks/package-json.js
Allow this export to be used in the widget bundle build without hacks
There is a test that all public exports work: https://github.com/cloudscape-design/components/blob/main/src/__tests__/functional-tests/public-exports.test.ts
<details>
- …
> chore: add widget-exports file to export map

- src/code-editor/styles.scss
I don't think it's supposed to do that:
Not sure when it happened, but we are colliding with ace's wrapper div for styling here. I assume the intent was always to have `position: absolute`, but I don't know if it ever worked with the mixin's `position: relative` overriding that anyway. So I moved those declarations to after the mixin.
Related links, issue #, if available: AWSUI-60262
Local testing, but I suppose a screenshot test is in order.
<details>
- …
> fix: Fix code editor becoming hidden when the group is focused

- pages/drag-handle/permutations.page.tsx
- src/app-layout/__tests__/split-panel-provider.test.tsx
- src/app-layout/drawer/resizable-drawer.tsx
- src/app-layout/utils/use-focus-control.ts
- src/app-layout/utils/use-resize.tsx
- src/app-layout/utils/use-split-panel-focus-control.ts
- src/app-layout/visual-refresh-toolbar/drawer/global-drawer.tsx
- src/app-layout/visual-refresh-toolbar/drawer/local-drawer.tsx
- src/collection-preferences/content-display/content-display-option.scss
- src/collection-preferences/content-display/content-display-option.tsx
- src/internal/components/drag-handle/__tests__/drag-handle.test.tsx
- src/internal/components/drag-handle/index.tsx
- src/internal/components/drag-handle/interfaces.ts
- src/internal/components/drag-handle/resize-icon.tsx
- src/internal/components/drag-handle/styles.scss
- src/internal/components/options-list/index.tsx
- src/internal/components/panel-resize-handle/index.tsx
- src/internal/components/panel-resize-handle/styles.scss
- src/internal/events/index.ts
- src/prompt-input/internal.tsx
- src/split-panel/__tests__/helpers.ts
- src/split-panel/implementation.tsx
Reusing drag handle between collection prefs, split panel, and drawers with potential future extension to board components, see: [a3UOAhaNX7KH].
* New unit tests for drag handle
<details> …
> refactor: Reusable internal drag handle

- pages/tabs/actions.page.tsx
- src/tabs/__integ__/tabs-actions.test.ts
- src/tabs/tab-header-bar.scss
This PR addressed the bug https://github.com/cloudscape-design/components/issues/3159
The root cause is that the tab element has a `:before` element to represent the left border, which is absolutely positioned, so it overlaps the `action` within the tab. Setting `position: relative` for tabs' actions solves the problem. 
<details> …
> fix: Unclickable actions in tabs

- pages/app/index.tsx
- pages/app/styles.scss
Removing unnecessary code as it is not really having any effect on visual regression tests, and it is confusing to manual inspection because:
- scrollbars being hidden might not be expected at all
- it hides some scrollbars (the ones in the body) but not others (the page-level ones)
Ran in my pipeline. Specifically verified that visual regression tests are green for the Safari tests, both for components and demos. And as I expected, scrollbars are still not shown in the screenshots anyway even after this change.
<details> …
> chore: Do not hide scrollbars in dev pages in Mac OS

- package-lock.json
- package.json
This reverts commit 1e11f46fcfed3aa1c0bf67e74dad8f8cd6977eda.
Un-pin ace-builds after the breaking changes in the type definitions of version 1.37.1 were fixed in 1.37.4.
I will merge this only once ace-builds 1.37.4 is available internally.
Issue: `AWSUI-60195`
Locally:
```
rm -f node_modules
npm i
npm run build
```
With the changes in this PR, the commands above were failing before ace-builds 1.37.4 was published and they succeed now.
<details>
- _Changes …
> chore: un-pin ace-builds version

- src/date-picker/index.tsx
- src/date-range-picker/styles.scss
- src/internal/components/dropdown/styles.scss
- src/internal/components/options-list/styles.scss
Issue: `AWSUI-60182`
In the case of dropdowns that contain only a list of selectable options (autosuggest, button dropdown, multiselect, select) it makes sense to disable text selection, but not necessarily for anything that the dropdown may contain, and in particular not for date pickers and date range pickers, where this is having undesired side effects. Therefore moving `user-select: none` from the dropdown component down to the options list component.
- Preparing visual regression tests
- Manually tested:
- Text is selectable in date picker and date ranger picker
- Double-clicking previous and next buttons in date picker or date range picker does not have unexpected side effects
- Text is _not_ selectable in autosuggest, button dropdown, multiselect, select
<details> …
> fix: Allow text selection in date picker and date range picker

- src/table/table-role/utils.ts
Fixes a hard to reproduce issue causing the table to become non-focusable when keyboard nav is on. If moving focus using arrow keys quickly then after moving the focus outside the table it might not be possible to bring it back unless reloading the page. This can only happen on table cells and was caused by explicitly setting the tabIndex=-1 to cells that can sometimes override the tabIndex=0 set by the single tab stop navigation mechanism.
Rel: AWSUI-60269
* Manual tests
* Dry run and screenshot tests
<details> …
> fix: Fixes table with keyboard nav losing focus at times

- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/button-group/__tests__/button-group-dev.test.tsx
- src/button-group/index.tsx
- src/button-group/interfaces.ts
> chore: Adds feature metrics for collection prefs and button group

- src/app-layout/__tests__/split-panel-provider.test.tsx
- src/app-layout/drawer/resizable-drawer.tsx
- src/app-layout/utils/use-focus-control.ts
- src/app-layout/utils/use-resize.tsx
- src/app-layout/utils/use-split-panel-focus-control.ts
- src/app-layout/visual-refresh-toolbar/drawer/global-drawer.tsx
- src/app-layout/visual-refresh-toolbar/drawer/local-drawer.tsx
- src/internal/components/panel-resize-handle/icon.tsx
- src/internal/components/panel-resize-handle/index.tsx
- src/internal/components/panel-resize-handle/styles.scss
- src/split-panel/__tests__/helpers.ts
- src/split-panel/implementation.tsx
This reverts commit cf9b42c79e0fdbde2adfbc6744949c2892cdfa01.
<details>
- _If the code …
> revert: Reusable internal drag handle (#3152)

- src/collection-preferences/content-display/index.tsx
Fixing a small visual regression introduced in: https://github.com/cloudscape-design/components/pull/3195
The `<li>` styles include borders that overlay the focus outline added when the item is active.
<details> …
> fix: Fixes collection preferences active item style

- src/container/styles.scss
- src/table/header-cell/styles.scss
Removing background color of embedded table only in VR.
<details> …
> fix: Remove background color of embedded table only in VR

- pages/property-filter/custom-forms.scss
- src/form-field/styles.scss
Applies the font smoothing setting to to the label field.
Related links, issue #, if available: AWSUI-55624
<details>
- _If the code …
> chore: Adds font smoothing to the form field's text like slots

- build-tools/tasks/test-utils.js
- src/__tests__/snapshot-tests/__snapshots__/test-utils-wrappers.test.tsx.snap
We moved the test utils generation code to the `test-utils` repo [here](https://github.com/cloudscape-design/test-utils/pull/77). This PR removes the redundant code and reuses the utils exported from the `test-utils` repo.
No functional changes are expected. The snapshot diffs must be only spacings/ordering. 
Similar to: https://github.com/cloudscape-design/code-view/pull/54, https://github.com/cloudscape-design/board-components/pull/332, https://github.com/cloudscape-design/chat-components/pull/35
We have already implemented functional tests both in the `test-utils` repo and `components` repo which generates actual test utils and tries to query dom with the generated test utils.
- Unit tests for test utils.
- Unit tests for components.
- _Changes include appropriate documentation …
> chore: Replaces the test utils generation with centralized code from test-utils package

- pages/attribute-editor/buttons.page.tsx
- pages/attribute-editor/form-field-label.page.tsx
- pages/attribute-editor/permutations.page.tsx
- pages/attribute-editor/simple-grid.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/__tests__/snapshot-tests/__snapshots__/test-utils-selectors.test.tsx.snap
- src/attribute-editor/__tests__/attribute-editor.test.tsx
- src/attribute-editor/__tests__/grid-defaults.test.ts
- src/attribute-editor/__tests__/utils.test.ts
- src/attribute-editor/grid-defaults.ts
- src/attribute-editor/interfaces.ts
- src/attribute-editor/internal.tsx
- src/attribute-editor/row.tsx
- src/attribute-editor/styles.scss
- src/attribute-editor/utils.ts
- src/button-dropdown/__tests__/button-dropdown-item-click.test.tsx
- src/button-dropdown/__tests__/button-dropdown.test.tsx
- src/button-dropdown/interfaces.ts
- src/button-dropdown/internal.tsx
- src/button-dropdown/utils/use-button-dropdown.ts
- src/button-group/item-element.tsx
- src/form-field/interfaces.ts
- src/form-field/internal.tsx
- src/test-utils/dom/attribute-editor/index.ts
Allow flexibility of "column" width in attribute editor.
Related links, issue #, if available: CClEAoSKVzvJ
(NB this is a 'dummy' PR against a branch that has some other related PRs already in (#3114, #3118) so that it can be reviewed in isolation but without merge conflicts later)
New dev pages and unit tests
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CON …
> feat: Add flexible layout for attribute editor

- src/internal/components/dropdown/__tests__/dropdown-position.test.ts
- src/internal/components/dropdown/dropdown-fit-handler.ts
- src/internal/components/dropdown/dropdown-position.ts
- src/internal/components/dropdown/index.tsx
Issue: `AWSUI-59635`
- Manually, on real iOS device and with Chrome's mobile simulator
- Ran the changes on my pipeline
- Added unit tests
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/acces …
> fix: Prevent dropdown misplacement in iOS

- pages/multiselect/constants.ts
- pages/multiselect/multiselect.test.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/multiselect/__tests__/multiselect.test.tsx
- src/multiselect/interfaces.ts
- src/multiselect/internal.tsx
This moves inline tokens in multiselect out of beta and into a public feature.
<details>
- …
> feat: Inline multiselect tokens

- pages/popover/text-wrap.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/popover/interfaces.ts
- src/popover/internal.tsx
- src/popover/styles.scss
This reverts commit e1c488b01396999a4609573bece9dcf830311632.
<details>
- _If the code …
> revert: "chore: Underline styles for popover text trigger (#3060)"

- src/internal/components/tooltip/index.tsx
- src/popover/container.tsx
- src/select/__integ__/disabled-reason.test.ts
- src/select/__tests__/disabled.test.tsx
The tooltip test classes were attached to the div that contains a popover container. However, when the container becomes hidden due to scroll logic, the outer div stays and gives a false positive when checked with isDisplayed if using webdriverio v9. In the PR the classes are moved to the popover container so that the tests produce expected results.
See a failed dry-run: https://github.com/cloudscape-design/browser-test-tools/actions/runs/12945599198/job/36179765443?pr=109
The tests succeed with the fix applied: https://github.com/cloudscape-design/components/pull/3218 
<details> …
> chore: Attaches tooltip classes to popover container

- pages/popover/text-wrap.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/popover/interfaces.ts
- src/popover/internal.tsx
- src/popover/styles.scss
Dry-run: `7210316657`
<details> …
> feat: Popover text inline trigger

- src/app-layout/__integ__/app-layout-split-panel.test.ts
- src/app-layout/visual-refresh-toolbar/compute-layout.ts
- src/app-layout/visual-refresh-toolbar/index.tsx
Fixing a bug
Related links, issue #, if available: AWSUI-60293
1. Added a test
2. Will be also visible on screenshot tests, since they render the scrollbars now
<details> …
> fix: Incorporate split panel height when rendering stickyVerticalBottomOffset value

- .github/workflows/release.yml
Allows ability to trigger this workflow either through the UI or programmatically through the Octokit sdk. Additionally passes in some additional configuration to change the AWS role and the CodeBuild project used to perform the release.
Depends on: https://github.com/cloudscape-design/actions/pull/69
Tested in my personal fork: 
https://github.com/michaeldowseza/actions/blob/main/.github/workflows/release.yml
https://github.com/michaeldowseza/components/actions/runs/13006036611/job/36273066928 …
> chore: Add workflow dispatch to release workflow to allow e2e tests to trigger action

- src/app-layout/__integ__/app-layout-drawers.test.ts
- src/app-layout/__integ__/runtime-drawers.test.ts
- src/cards/__integ__/sticky-header.test.ts
- src/pie-chart/__integ__/pie-chart.test.ts
- src/select/__integ__/select.test.ts
Related links, issue #, if available: 
* AWSUI-59931
* https://github.com/cloudscape-design/browser-test-tools/pull/118
* used [browser-test-tools/scroll-validation](https://github.com/cloudscape-design/browser-test-tools/tree/scroll-validation) branch to run integration tests
<details> …
> chore: Fix elements scrolling with elementScrollTo in integration tests

- pages/table/sticky-columns.page.tsx
- pages/table/styles.scss
- src/table/header-cell/styles.scss
Spotted twice in Slack, looks like it was caused by #3198. The PR specifically skipped removing the background on the sticky header row, but missed the case of the sticky columns. I don't think there's any real fix besides restoring the background color to those sticky columns - and just not properly "supporting" sticky columns in transparent embedded tables.
Created a dev page addition for this.
<details>
- _Changes …
> fix: Correctly overlap sticky columns over static columns in borderless tables

- pages/table/editable.page.tsx
- src/table/__integ__/inline-editing.test.ts
- src/table/__tests__/body-cell.test.tsx
- src/table/__tests__/expandable-rows.test.tsx
- src/table/__tests__/table.test.tsx
- src/table/body-cell/disabled-inline-editor.tsx
- src/table/body-cell/index.tsx
- src/table/body-cell/styles.scss
- src/table/body-cell/td-element.tsx
- src/table/header-cell/index.tsx
The PR makes it possible to have cell editing in the first column of tables with expandable rows.
Rel: [tNAkA40KWyvj], AWSUI-43194.
* New unit and integration test
* Dry-run to live
<details> …
> fix: Allows table cells be expandable and editable at the same time

- src/progress-bar/__tests__/progress-bar.test.tsx
- src/progress-bar/index.tsx
- src/progress-bar/internal.tsx
Before this change, the `resultState` was not live-announced when displayed becaue the content of the `aria-live` container did not change.
With this change, the `InternalLiveRegion` componnt takes care about the live announcement, once the `resultState` is rendered.
Related links, issue #, if available: AWSUI-60207
- tested manually using Voice Over on Mac.
- How can reviewers test these changes efficiently?
- Open the `with-updates` demo page, enable VO and click the "Start" button. Live announcement is happening once the loading is done.
<details> …
> fix: Live announce resultState in ProgressBar

- src/date-range-picker/__tests__/date-range-picker.test.tsx
- src/date-range-picker/dropdown.tsx
When a user clicks on "Apply" in DateRangePicker, the error text should be reannounced 
Related links, issue #, if available: AWSUI-60295
with voice over on, following the recording in the ticket
<details> …
> fix: Reannounce validation error in date range picker on apply

- src/header/__tests__/internal.test.tsx
- src/header/internal.tsx
- src/wizard/wizard-form.tsx
Ensure focus moves to an element with an accessible role. One way to do this is to move focus to the `<h1 />` instead of a child `<span />`.
Before this change, screen reader users had difficulty determining the purpose and state of the `<span />`.
Related links, issue #, if available: AWSUI-60210
- added additional unit tests.
- verified manually by navigating through the wizard (simple) page via keyboard.
- I run it in my pipeline to check for visual/performance regressions (AwsUi-v3-jowejowe), all good.
<details> …
> fix: Focus element with accessible role when switching steps

- src/annotation-context/annotation/styles.scss
Extends the clickable area of the hotspot button to 24 pixels. This is to conform to WCAG 2.2 specs.
Related links, issue #, if available: AWSUI-60217
A more complicated solution with many more moving parts is also available in #3237. Feel free to compare the both solutions but we are leaning toward this solution which is simpler.
Dev pipeline screenshot tests
<details> …
> chore: Adds pseudo element around the annotation trigger

- src/annotation-context/annotation/styles.scss
Reverts cloudscape-design/components#3246
Seems that this is causing the hotspot to disappear in some circumstances in Firefox.
> revert: chore: Adds pseudo element around the annotation trigger

- .github/workflows/close-stale-issues.yml
After testing in https://github.com/cloudscape-design/demos/pull/184, apply the same workflow to the main repo (other repos with issues support will follow)
<details> …
> chore: add close-stale-issues workflow

- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/alert/__tests__/alert.test.tsx
- src/alert/internal.tsx
- src/button/internal.tsx
- src/flashbar/collapsible-flashbar.tsx
- src/flashbar/flash.tsx
- src/form-field/internal.tsx
- src/icon/__tests__/icon.test.tsx
- src/icon/interfaces.ts
- src/icon/internal.tsx
- src/table/__tests__/header-cell.test.tsx
- src/table/body-cell/index.tsx
- src/table/header-cell/index.tsx
```diff
+   /**
+    * Specifies alternate text for the icon. We recommend that you provide this for accessibility.
+    */
+   ariaLabel?: string;
/**
-    * Specifies alternate text for a custom icon (using the `url` attribute). We recommend that you provide this for accessibility.
+    * Specifies alternate text for a custom icon (using the `url` attribute).
* This property is ignored if you use a predefined icon or if you set your custom icon using the `svg` slot.
*
+    * @deprecated Use `ariaLabel` instead.
*/
alt?: string;
```
If you want to have an accessible label for your icon (assuming you don't have visible text next to it), you currently have to do this:
```tsx
<span role="img" aria-label="Success">
<Icon name="status-positive" />
</span>
```
Boo! Annoying! The current …
> feat: Add ariaLabel property to icon component

- package.json
- src/button/styles.scss
Created to "unblock" #3253. We're at the edge of a couple of the bundle size checks, and adding a new button variant pushed it over the edge. Taking a look at the CSS, I realized we were looping through and generating a chunk of CSS for each button variant, but a lot of it wasn't variant-dependent, so it didn't really belong in that for loop.
Just like that! A lot of pointless CSS removed (though with no particular user impact since I imagine it could easily be gzipped away)
```diff
lib/components/internal/plugins/index.js
Size limit: 14 kB
Size:       13.79 kB with all dependencies and minified
lib/components/internal/widget-exports.js
- Size limit: 800 kB
- Size:       796.35 kB with all dependencies and minified
+ Size limit: 750 kB
+ Size:       745 kB with all dependencies and …
```
> chore: Reduce duplicated styles on button component

- src/date-range-picker/__tests__/date-range-picker.test.tsx
- src/internal/components/button-trigger/index.tsx
- src/select/parts/trigger.tsx
`aria-expanded` is always false for the date range picker, because it opens a dialog. There's no open/close state to the trigger like there is for select or multiselect. So the attribute is incorrect and misleading here.
Related links, issue #, if available: AWSUI-60204
Added a unit test for the date range picker. The select already has one.
<details> …
> fix: Remove aria-expanded from date range picker trigger

- src/container/__tests__/sticky-header.test.tsx
- src/container/internal.tsx
- src/container/use-sticky-header.ts
The previous isStuck logic was causing some unintended visual issues. When the isStuck condition was falsey set to true, it was removing the border radius on an internal element. This caused that element to overlay on top of its parent container, hiding the curved borders on the corners. This problem became more noticeable when the screen was viewed at different zoom levels.
The isStuck was being falsely set to true because why the top pixel values from sequentially calling `.getBoundingClientRect()` on a parent and nested child element might not return the same values, even if they are in the same position. Here are some reasons as to why:
- Timing issues: The `.getBoundingClientRect()` method returns the size and position of the element relative to the viewport, and this can change …
> fix: Rigorizing the isStuck logic in container use-sticky-header

- src/tabs/__integ__/tabs.test.ts
- src/tabs/tab-header-bar.tsx
Ensure that tab focus is returned consistently to the active tab, whether or not tabs have actions.
Updated tests
<details> …
> fix: Ensure focus is returned to active tab

- src/code-editor/__tests__/code-editor.test.tsx
- src/code-editor/index.tsx
- src/i18n/messages-types.ts
- src/i18n/messages/all.ar.json
- src/i18n/messages/all.de.json
- src/i18n/messages/all.en-GB.json
- src/i18n/messages/all.en.json
- src/i18n/messages/all.es.json
- src/i18n/messages/all.fr.json
- src/i18n/messages/all.id.json
- src/i18n/messages/all.it.json
- src/i18n/messages/all.ja.json
- src/i18n/messages/all.ko.json
- src/i18n/messages/all.pt-BR.json
- src/i18n/messages/all.tr.json
- src/i18n/messages/all.zh-CN.json
- src/i18n/messages/all.zh-TW.json
What it says on the tin. We missed those strings earlier, adding support for them now.
Related links, issue #, if available: AWSUI-60202
Updated unit tests.
<details> …
> fix: Add I18nProvider support for code editor theme filtering input

- style-dictionary/visual-refresh/metadata.ts
Previously cjs would handle whether it was a folder of file. Now we expect a file there.
Also important to note that this theme isn't actually used anywhere in our build so there's no impact here.
Before the change I could not built visual refresh as the primary theme, now I can. …
> chore: Re-export metadata folder to work with updated style-dictionary ESM changes

- src/i18n/messages/all.en-GB.json
- src/i18n/messages/all.en.json
- src/i18n/messages/all.fr.json
- src/i18n/messages/all.ja.json
- src/i18n/messages/all.zh-TW.json
Fix a grammatical error in the text of the Collection preferences component under Column preferences.
Related links, issue #, if available: AWSUI-60354
- verified manually in dev pages
- 
<details> …
> chore: Sync i18n messages, apply grammar fix

- .eslintrc.js
- package-lock.json
- package.json
Self-explanatory: let's lint this rather than leaving it for humans to catch
<details>
- _If …
> chore: Add linter for no 'only' tests

- src/internal/components/option/__tests__/option.test.tsx
- src/internal/components/option/highlight-match.tsx
Reported by a user on Slack. This is just #1885 but the limit is set even lower. Based on empirical testing, the regex limit seems to be set at 32768 characters now.
We initially set it to 100,000 characters last time to avoid breaking any legitimate workflows and it worked in previous Chrome versions. But in retrospect, autosuggest matches with over 10,000 characters are probably well past most reasonable uses of the component anyway, so this should be fine.
Updated the tests.
<details> …
> fix: Prevent filtering highlighting from crashing when match is >10000 chars

- src/mixed-line-bar-chart/__tests__/test-chart-series-details.tsx
- src/tag-editor/__integ__/page/tag-editor-page.ts
- src/tag-editor/__tests__/tag-editor.test.tsx
- src/test-utils/dom/anchor-navigation/index.ts
- src/test-utils/dom/attribute-editor/index.ts
- src/test-utils/dom/date-range-picker/index.ts
- src/test-utils/dom/internal/abstract-switch.ts
- src/test-utils/dom/internal/chart-popover.ts
- src/test-utils/dom/radio-group/radio-button.ts
- src/test-utils/dom/side-navigation/index.ts
- src/test-utils/dom/tiles/tile.ts
Fix this use-case
```js
createWrapper()
.findAttributeEditor()
.findRow(1)
.findColumnLayout() // wrong - there is no column layout there, but types allow that
.toSelector()
```
Three cases will remain unfixed after this change
DropdownWrapper – there is too much code assuming it is an element wrapper, it requires a fix on its own
https://github.com/cloudscape-design/components/blob/9976a864d48e9b23bc4bc798bd0a5190fe480725/src/test-utils/dom/internal/dropdown.ts#L6
TooltipWrapper - this class is empty, unclear why it exists at all
https://github.com/cloudscape-design/components/blob/9976a864d48e9b23bc4bc798bd0a5190fe480725/src/test-utils/dom/internal/tooltip.ts#L7
OptionsList – same, also empty
https://github.com/cloudscape-design/components/blob/9976a864d48e9b23bc4bc798bd0a5190fe480725/sr …
> fix: Fix test-utils wrappers inheritance

- src/container/__tests__/sticky-header.test.tsx
- src/container/internal.tsx
- src/container/styles.scss
- src/container/use-sticky-header.ts
- src/header/__tests__/sticky-responsiveness.test.tsx
- src/table/sticky-header.tsx
The current implementation of the sticky header component can lead to a visual issue where the bottom corners of the sticky header jut out past the rounded borders of the table, causing a break in the visible border.
This pull request addresses this issue by making an enhancement to the useStickyHeader hook used by the Sticky Header and its parent component.
The key changes are:
Adding a new property called `isStuckAtBottom` to the object returned by the useStickyHeader hook. The isStuckAtBottom state is introduced to track whether the sticky header is aligned with the bottom edge of the table content. This is determined by comparing the bottom positions of the table container and the sticky header, and setting isStuckAtBottom accordingly. The internal table component then uses this state …
> fix: fixing broken corners of table with sticky header bottom when scrolled

- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/prompt-input/__tests__/prompt-input.test.tsx
- src/prompt-input/interfaces.ts
- src/prompt-input/internal.tsx
Add setSelectionRange to PromptInput
Related links, issue #, if available: AWSUI-60374
New unit test
<details> …
> feat: Add setSelectionRange to PromptInput

- pages/i18n/performance.page.tsx
- src/i18n/__tests__/i18n.test.tsx
- src/i18n/provider.tsx
After a bit of a deep dive, I can reduce the time taken by the format function by 10x (in my contrived dev page example).
Related links, issue #, if available: AWSUI-60323
Tested manually using the included dev page. Used a table rather than some other component because I wanted to reproduce their use-case closely rather than just rendering an i18n provider supported component over and over again. No automated tests, but we do have perf tests in the pipeline, so a regression here would presumably be visible there.
<details> …
> chore: Improve performance for repeated i18n format calls

- pages/select/select.test.page.tsx
- src/internal/components/dropdown/dropdown-fit-handler.ts
- src/select/__integ__/select.test.ts
- src/select/parts/plain-list.tsx
Fix issue AWSUI-60318
**Issue**: 
When Select locates top inside of a `overflow:hidden` container and at the bottom of the window, the select can not open upwards because `overflow:hidden` and has little space downwards to display the dropdown. When open the dropdown with a **selected option**, the page scrolls up. See screen recording in the ticket. 
**Cause**:
1. When dropdown has very small space to display, the height is calculated to a negative number (because 50 padding we usually have for the dropdown) https://github.com/cloudscape-design/components/blob/main/src/internal/components/dropdown/dropdown-fit-handler.ts#L294. Negative value does not limit the height, so the dropdown overflows out of the view port.
2. When an option is pre-selected, the option scrolls into view …
> fix: Parent container scrolls when select opens

- package-lock.json
- src/flashbar/__tests__/collapsible.test.tsx
- src/flashbar/flash.tsx
Adds proper role and label to the focus target in collapsed flashbar.
Related links, issue #, if available: AWSUI-60238
- Newly added unit test
- Manual check with voice over
<details> …
> chore: Adds group role and aria label to flash focus

- pages/tabs/permutations.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/__tests__/snapshot-tests/__snapshots__/test-utils-selectors.test.tsx.snap
- src/tabs/__tests__/tabs.test.tsx
- src/tabs/index.tsx
- src/tabs/interfaces.ts
- src/tabs/tab-header-bar.scss
- src/tabs/tab-header-bar.tsx
- src/test-utils/dom/tabs/index.ts
Add a slot for "actions", placed within the tabs header
Related links, issue #, if available: 4aAdA16jV0dV
New unit tests & permutations
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessi …
> feat: Add tab header "actions"

- package-lock.json
- package.json
Now that Safari 18 is out, we officially support only Safari 16+, but our current version of `caniuse` is still enforcing Safari 15 compatibility due to not being aware of Safari 18.
In particular, it is not allowing to use the `:has()` pseudo-selector which I need to use [here](https://github.com/cloudscape-design/components/pull/3303). (But updating the browsers list is good in itself anyway)
Upgraded `caniuse` by running `npx update-browserslist-db`.
Also had to upgrade `stylelint-no-unsupported-browser-features` due to [this issue](https://github.com/RJWadley/stylelint-no-unsupported-browser-features/issues/299).
Only after these changes I was able to commit https://github.com/cloudscape-design/components/pull/3303 without stylelint errors. …
> chore: Upgrade list of supported browsers

- src/icon/styles.scss
Noticed while working on drag and drop. The left icon is flipped automatically, but the right arrow isn't. Seems like an oversight, since the other right pointing icons were flipped.
Will be caught on RTL permutation tests.
<details>
- _Changes …
> chore: Flip arrow-right icon in RTL

- src/autosuggest/__tests__/autosuggest.test.tsx
- src/property-filter/__tests__/property-filter-extended-operators.test.tsx
- src/test-utils/dom/input/base-input.ts
- src/test-utils/dom/prompt-input/index.ts
- src/test-utils/dom/textarea/index.ts
The PR updates the uses of Simulate test-util from React with a custom event dispatcher.
Depends on: https://github.com/cloudscape-design/components/pull/3252
Rel: AWSUI-60345
* Existing unit tests pass with minor adjustments (calling change when the value remains the same now has no effect)
* Dry-run
<details> …
> chore: Removes dependencies on React <19 in test utils

- src/table/__tests__/analytics-events.test.tsx
- src/table/internal.tsx
When an `instanceIdentifier` is provided on a Table, it should be used as the reported funnel name (to match the behaviour of the various `funnel*` events).
Related links, issue #, if available: AWSUI-60419
<details> …
> fix: Table does not use instanceIdentifier for the reported task name in metrics

- src/autosuggest/__tests__/autosuggest.test.tsx
- src/internal/components/autosuggest-input/index.tsx
- src/internal/utils/dom.ts
This change caused a regression: AWSUI-60442
Reverts cloudscape-design/components#3176
> revert: Fixes unexpected autosuggest dropdown reopen when clicking outside browser window and back

- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/flashbar/__tests__/analytics-metadata.test.tsx
- src/flashbar/flash.tsx
- src/flashbar/interfaces.ts
- src/internal/base-component/index.ts
This PR adds a new field to the analytics metadata field of individual flash items. The `analyticsMetadata` field can currently already be used (see [code](https://github.com/cloudscape-design/components/blob/e30984564d0899802df1265b4831228d46cea7bc/src/flashbar/flash.tsx#L117)), but it is not documented, since it was only intended for internal testing. 
When the `suppressFlowMetricEvents` field is set, the flashbar will no longer be marked with analytics-related attributes, which will exclude it from generating flow metric events.
Related links, issue #, if available: Document `cVyaAI57bL8k`
Tested manually in the browser and added a unit test
<details> …
> feat: Add `suppressFlowMetricEvents` field to flashbars

- pages/autosuggest/simple.page.tsx
- src/autosuggest/options-list.tsx
- src/internal/components/option/option-announcer.ts
- src/select/__tests__/use-announcement.test.ts
- src/select/utils/use-announcement.ts
Adds option's `filteringText` to the announcement text. This follows the visual behavior and is added to the announcement text only when the text input matches the `filteringText`
Related links, issue #, if available: AWSUI-60198
<details> …
> chore: Adds missing filtering-tags to the announcer string

- pages/onboarding/i18n.ts
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/annotation-context/__tests__/annotation-context.test.tsx
- src/annotation-context/annotation/annotation-trigger.tsx
- src/annotation-context/interfaces.ts
The label should not consider the open/closed state anymore.
This is handled via the `aria-expanded` attribute on the button which informs screen reader users about it. 
Related links, issue #, if available: AWSUI-60206, CR-180686961
- verified manually on test pages.
- add additional unit test.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#br …
> chore: Add aria-expanded to Hotspot trigger buttons

- pages/app/components/theme-switcher.tsx
Removes this dropdown from the dev pages. It is not used anywhere.
Locally. Reviewer can see result in preview deployment
<details>
- …
> chore: Remove theme dropdown from dev pages

- src/flashbar/__tests__/analytics-metadata.test.tsx
- src/flashbar/flash.tsx
- src/internal/analytics/selectors.ts
- Adds back the `data-analytics-flashbar` attribute to Flashbar
- When suppressFlowMetricEvents is set, adds a `data-analytics-suppress-flow-events` attribute instead
- Updated existing unit test
<details> …
> chore: Add data attribute to flashbar to suppress metrics events

- pages/app-layout/with-sticky-notifications-and-header.page.tsx
- src/app-layout/__integ__/app-layout-sticky-elements.test.ts
- src/app-layout/visual-refresh-toolbar/notifications/index.tsx
Fixes the race condition in `ResizeObserver` listeners.
Related links, issue #, if available: AWSUI-60457
A few facts about the sticky headers:
1. We use `ResizeObserver` to recalculate `--awsui-sticky-vertical-top-offset` which determines the offset of the table's sticky header.
2. When there is a sticky notification in the page and it is dimissed, the recalculation takes place.
3. We rely on `ResizeObserver` to do the recalculation.
4. `ResizeObserver` listens to the `content-box` changes by default ([Ref](https://developer.mozilla.org/de/docs/Web/API/ResizeObserver/observe#options)). **Important!**
5. Sticky notification adds `8px` of padding when it has a content.
Now with the above points, this is what is happening when a sticky notification is dismissed:
1. `useContainerQuery` …
> chore: Merges the resize observers

- src/anchor-navigation/__tests__/anchor-navigation.test.tsx
- src/anchor-navigation/anchor-item/index.tsx
- src/anchor-navigation/internal.tsx
- src/anchor-navigation/utils.tsx
Nested lists are not marked up properly. Screen reader users may not be able to understand the hierarchy of these controls. With this change, they get marked up as expected.
Related links, issue #, if available: AWSUI-60224
- added additional unit test.
- tested manually on the simple test page in in the most recent browser versions (Chrome, FF, Safari, Edge).
- dry-run build to live: 7271978138
- green dry run including screenshot tests in my dev pipeline.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public …
> chore: Ensure AnchorNavigation lists are marked up properly

- src/wizard/styles.scss
The header background color in wizard is unnecessary, it had the same color with wizard bg so the color diff isn't visible unless the wizard background is themed.
<details> …
> fix: Remove unnecessary background color from wizard header

- src/button-dropdown/__tests__/button-dropdown-items.test.tsx
- src/button-dropdown/category-elements/category-element.tsx
Related a11y ticket: AWSUI-60215
A simple edit that makes disabled groups correctly have the `aria-disabled` over the `ul` instead of the `li` because it has a role of presentation. Screen readers may not announce this content as disabled.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support) …
> chore: Ensure aria-disabled is placed correctly in disabled groups

- pages/table/cell-permutations.page.tsx
- pages/table/permutations.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/table/__tests__/table-feature-metrics.test.tsx
- src/table/__tests__/table.test.tsx
- src/table/index.tsx
- src/table/interfaces.tsx
- src/table/internal.tsx
- src/table/selection/selection-cell.tsx
- src/table/selection/selection-control.tsx
- src/table/selection/styles.scss
This PR introduces a new API property for the table component, the: `cellVerticalAlign?: "middle" | "top"`. This property will complement the existing `columnDefinitions.verticalAlign?: "middle" | "top"` property, but is applicable for the entire table, including the selection column. When both properties are set, the `columnDefinitions.verticalAlign` takes precedence.
On the screenshot you can see how selection checkboxes are aligned to the cell's top when `cellVerticalAlign = "top"`. The last column alignment is overridden by setting the `columnDefinitions.verticalAlign = "middle"`.
Rel: AWSUI-59979
* Existing screenshot tests
<details> …
> feat: Table cell align for all cells

- src/__tests__/snapshot-tests/__snapshots__/test-utils-selectors.test.tsx.snap
- src/side-navigation/__tests__/side-navigation.test.tsx
- src/side-navigation/parts.tsx
- src/side-navigation/test-classes/styles.scss
- src/test-utils/dom/side-navigation/index.ts
Support this use-case
```js
<SideNavigation
items={[{ type: 'link', text: 'Something', info: 'find me' }]}
/>
```
```js
expect(createWrapper().findItemByIndex(1).findInfoSlot().getElement()).toHaveTextContent('find me');
```
Current utilities do not allow to specifically target only the info slot
Updated existing unit test to incorporate this use-case
<details> …
> feat: Add findInfo test-util to side navigation

- package.json
There are almost 300 linter errors in our codebase right now: https://github.com/cloudscape-design/components/actions/runs/13857497425/job/38777519759
Disabling this until the violations are fixed
PR build is green
<details> …
> chore: Temporarily disable eslint

- src/internal/analytics/__integ__/static-multi-page-create.test.ts
- src/internal/analytics/__integ__/static-single-page-flow.test.ts
- src/internal/analytics/__tests__/components/analytics-funnel.test.tsx
- src/internal/analytics/components/analytics-funnel.tsx
- src/internal/hooks/use-telemetry/index.ts
- src/internal/utils/__tests__/get-visual-theme.test.ts
- src/internal/utils/get-visual-theme.ts
- Pass the given environment theme down to the funnel metrics.
- Extract common visual theme code into helper function
- Updated unit test
- Internal pipeline testing …
> chore: Pass theme through to funnel metrics

- src/internal/hooks/use-portal-mode-classes/__tests__/use-portal-mode-classes.test.tsx
- src/internal/hooks/use-portal-mode-classes/index.ts
in VR only artifacts, we render this class in the DOM even if it is not needed for the implementation.
However this has an unwanted side effects as other code incorrectly assumes the current page is using dual classic/refresh artifacts
PR build passes, no regressions for the current code
<details> …
> fix: Remove awsui-visual-refresh class from portal propagation

- pages/bar-chart/horizontal-bars-permutations.page.tsx
- pages/bar-chart/horizontal-stacked-bars-permutations.page.tsx
- pages/bar-chart/other-permutations.page.tsx
- pages/bar-chart/threshold-permutations.page.tsx
- pages/bar-chart/vertical-bars-permutations.page.tsx
- pages/bar-chart/vertical-stacked-bars-permutations.page.tsx
Currently the dev page `bar-chart/permutations` takes around 11 seconds to load (LCP), and is too tall for permutation screenshots. Split it into smaller parts.
To do so without operational disruptions, let's follow these steps:
1. Create new pages from parts of the existing page (this PR)
2. Deploy
3. Create new tests for the new pages
5. Remove old permutations page and its tests
Related issue: `AWSUI-60431`
Compared load time on Chrome with performance dev tools. Each of the new pages takes between 0.33 and 0.78 seconds to load (LCP).
<details> …
> chore: Create smaller dev pages for Bar chart

- src/internal/components/option/utils/filter-options.ts
- src/internal/components/option/utils/flatten-options.ts
- src/multiselect/__tests__/multiselect.test.tsx
I came across this while writing a dev page where Multiselect options are handled via a `.map` call, [here](https://github.com/cloudscape-design/components/pull/3336/files#diff-e00abc4c2fe924a47acef423bc1d007b249f510859d0debce5b25d86a0af001fR60-R69).
There is no good reason why this should crash the component.
This fix is also part of #3336 but I am trying to separate things out. Also, better to have an explicit test for this.
Related: `AWSUI-59006`
- Added a unit test
- A dev page (and therefore also integration tests) in #3336 relies on this
<details> …
> fix: Tolerate multiselect options with child options explicitly set to undefined

- pages/table/editable.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/table/__integ__/inline-editing.test.ts
- src/table/__tests__/table-editable.test.tsx
- src/table/__tests__/table.test.tsx
- src/table/interfaces.tsx
- src/table/internal.tsx
- src/table/use-cell-editing.ts
Once a table cell is edited, the successful state it added to a cell by col- and row index. If column definitions change, it causes the focus to be lost and the successful state resets. However, if rows order change, e.g. because the new value is sorted differently, the successful state then stays attached to the wrong cell. The PR fixes that for tables with trackBy property used.
See before:
https://github.com/user-attachments/assets/cee720b3-62ad-45e4-8f59-0f96eb1d8041
See after:
https://github.com/user-attachments/assets/36630e92-2cdf-4f0e-bf9c-91e459306aee
Rel: AWSUI-60542
* Manual tests in the integ test page
<details> …
> fix: Fixes table editable success state placement when items order change

- pages/utils/screenshot-area.tsx
- src/__integ__/screenshot-area.test.ts
This removes console.error() recently introduced to screenshot area as it causes failures in screenshot tests that use narrow viewport sizes, which makes many pages to exceed the 16000px limit.
<details> …
> chore: Remove console error from screenshot-area

- src/app-layout/__tests__/desktop.test.tsx
- src/app-layout/drawer/index.tsx
- src/app-layout/mobile-toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/drawer-triggers.tsx
- src/app-layout/visual-refresh/drawers.tsx
The `role=toolbar` elements are unlabelled. It's fine to repeat the label of the `role=region` parents here, since the role itself is different even if the aria label is identical. Had to fiddle a couple of tests that were selecting by label, but hopefully the downstream user impact is minimal because it's still not the first element returned (which was the case with some a11y fixes earlier).
Related links, issue #, if available: AWSUI-60452
Unit tests, but I'm going to be a dry-run build to be double sure (see build 7294528292).
<details> …
> fix: Add aria-label to app layout toolbars

- src/select/parts/styles.scss
Fixing inline label visual issues in Safari or when theming is used to override border width from 2px to 1px.
Issue in Safari (at certain zoom levels)
Closes https://github.com/cloudscape-design/components/issues/3368
The feature was introduced here: https://github.com/cloudscape-design/components/pull/2355
* New permutations were added here: https://github.com/cloudscape-design/components/pull/3380
<details> …
> fix: Fixes select inline label style

- src/select/parts/styles.scss
- src/select/parts/trigger.tsx
This is a follow-up for https://github.com/cloudscape-design/components/pull/3372
The change makes styling of inline labels consistent between active and disabled states. Previously, the border radius was missing from the active state. The radius is visible when page's background is different from the label background.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob …
> chore: Apply consistent border rounding to inline label

- pages/select/select.test.page.tsx
- src/select/__integ__/select-native-search.test.ts
- src/select/internal.tsx
The native select search allows options selection by matching keyboard input - this has to be disabled when component is in read-only mode. We don't have to explicitly disable it for disabled mode because in that case the component is not focusable anyways.
Rel: AWSUI-60557
Closes https://github.com/cloudscape-design/components/issues/3384
* Added new integration test
<details> …
> fix: Disables select native search when read-only

- src/alert/actions-wrapper/index.tsx
Prevent the case where dynamically-injected runtime action causes actions slot to wrap without triggering the addition of the "wrapped" class.
Related links, issue #, if available: #3338
Tested locally
<details> …
> fix: Ensure runtime actions cause re-calculation of alert/flash wrapping

- src/popover/styles.scss
Applied default text styles to the popover trigger (`text-inline` type) to slightly increase the line height, based on a user request.
<details> …
> chore: Adjust popover trigger styles

- src/alert/styles.scss
- src/flashbar/styles.scss
Some consuming teams' builds failed with this syntax, rolling it back for now. It is anyway only supported by Chrome, so for now we just revert behavior in Chrome to what it is in other browsers.
<details> …
> fix: Remove CSS syntax unsupported by some versions of SASS

- package-lock.json
- pages/prompt-input/simple.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/prompt-input/__integ__/prompt-input.test.ts
- src/prompt-input/__tests__/prompt-input.test.tsx
- src/prompt-input/interfaces.ts
- src/prompt-input/internal.tsx
Add support for using `-1` in the `maxRows` prop to enable infinite expansion in the `PromptInput` component (i.e. no scrollbar and no height limit)
`AWSUI-60455`
https://github.com/cloudscape-design/components/issues/3283
Added an integration test to assert that the height is not limited by anything other than inputted text.
On simple demo page for this component there's a checkbox to enable infinite max rows, enabling it will allow you to manually test the change.
<details> …
> feat: Infinite maxRows for PromptInput using -1 value

- package.json
- src/app-layout/__tests__/drawers.test.tsx
- src/app-layout/__tests__/runtime-drawers.test.tsx
- src/app-layout/drawer/overflow-menu.tsx
All drawer's shown in the overflow menu items are currently implemented with `role="menuitemcheckbox"` roles, but not all have have a visual checked/unchecked semantics. 
With this change:
- regular drawers (provided via AppLayout's `drawers` property get `role="menuitem"` because only one of them is selectable.
- golbal drawers (added via runtime API) get `role="menuitemcheckbox"` because multiple of them are selectable
Related links, issue #, if available: AWSUI-60248
- verified manually in the browser in my local env
- build to live dry-run: 7312012546
- tested successfully in my dev pipeline
<details>
- _Changes are …
> chore: Change aria role in AppLayout drawer's overflow menu items to menuitem

- src/table/resizer/styles.scss
Easiest PR of all time - 2px more on each side and we hit 24px.
Related links, issue #, if available: AWSUI-60223
Relying on screenshot tests and unit tests - behavior and visuals should be unchanged.
<details> …
> fix: Increase width of table column resize control

- src/code-editor/resizable-box/__tests__/resizable-box.test.tsx
- src/code-editor/resizable-box/index.tsx
Noticed after the implementation shipped. Not a big deal, but still nice to fix.
Updated unit tests.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/a …
> fix: Prevent page scroll when resizing code editor with keyboard

- build-tools/tasks/docs.js
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/__tests__/snapshot-tests/documenter.test.ts
Re-enable snapshot tests after https://github.com/cloudscape-design/documenter/pull/58 is released
Build passes
<details> …
> chore: re-enable documenter snapshots

- src/autosuggest/__tests__/autosuggest-dropdown-states.test.tsx
- src/date-range-picker/__tests__/date-range-picker.test.tsx
- src/internal/components/autosuggest-input/index.tsx
- src/internal/components/dropdown-footer/__tests__/dropdown-footer.test.tsx
- src/internal/components/dropdown-footer/index.tsx
- src/multiselect/__tests__/multiselect.test.tsx
- src/select/__tests__/select-a11y.test.tsx
Before this change:
- The live announcement happened only on the initial dropdown open
- When re-opening the dropdown, no live announcement happened
With this change:
- The live announcement happens on every dropdown open
Related links, issue #, if available: AWSUI-60501
- added unit test to ensure the changes.
- manually tested in the following components in in error state by opening and re-opening:
- select
- expandToViewport set to `true` and `false`
- multislect
- expandToViewport set to `true` and `false`
- autosuggest
- expandToViewport set to `true` and `false`
- successful dry-run live build: 7313587195
- screenshot tests passed in my dev pipeline
<details>
- …
> fix: Re-announce dropdown footer message on dropdown toggle

- src/live-region/__integ__/live-region.test.ts
- src/live-region/__tests__/live-region.test.tsx
- src/live-region/internal.tsx
AWSUI-60601
Fixed text extraction logic in a way that does not concatenate words coming from dom nodes without spaces between them. 
Reproduction Steps:
Create a ⁠LiveRegion component.
Place two or more inline elements (e.g., ⁠<span>, ⁠<a>, ⁠<strong>) as direct children of the ⁠LiveRegion.
<LiveRegion>
<span>Documentation</span>
<span>Something</span>
</LiveRegion>
Ensure that the inline elements contain text content.
Use a screen reader to listen to the announcement of the ⁠LiveRegion's content.
Expected Behavior:
The screen reader should announce the text content of each inline element with a space separating them. For example, if the ⁠LiveRegion contains ⁠<span>Documentation</span><span>Something</span>, the screen reader should announce "Documentation Something".
Actual Behavior:
The …
> fix: LiveRegion text extraction

- src/app-layout/__tests__/mobile.test.tsx
- src/app-layout/visual-refresh/mobile-toolbar.tsx
The mobile navigation region has no accessible name. With this change, I'm adding the missing `aria-label` to the nav element to provide a short description of the navigation region's purpose.
Related links, issue #, if available: AWSUI-60249
- added unit tests to ensure the label is present across all `AppLayout` variants.
- verified manually in the browser.
<details> …
> fix: Add missing navigation aria-label to mobile nav

- build-tools/utils/pluralize.js
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/__tests__/snapshot-tests/__snapshots__/test-utils-selectors.test.tsx.snap
- src/__tests__/snapshot-tests/__snapshots__/test-utils-wrappers.test.tsx.snap
- src/test-utils/dom/tree-view/index.ts
- src/tree-view/__tests__/tree-view.test.tsx
- src/tree-view/index.tsx
- src/tree-view/interfaces.ts
- src/tree-view/test-classes/styles.scss
Added a dummy component to test `@awsuiSystem` declaration tag end-to-end
Build in my dev-pipeline: TBD
<details> …
> chore: Dummy tree view component

- pages/copy-to-clipboard/simple.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/__tests__/snapshot-tests/__snapshots__/test-utils-selectors.test.tsx.snap
- src/copy-to-clipboard/__tests__/copy-to-clipboard.test.tsx
- src/copy-to-clipboard/interfaces.ts
- src/copy-to-clipboard/internal.tsx
- src/copy-to-clipboard/test-classes/styles.scss
- src/test-utils/dom/copy-to-clipboard/index.ts
**Original customer ask:**
> As of now, when `CopyToClipboard` uses `inline` variant, it will ignore `copyButtonText` and use `textToCopy` for both display and copy value.
Make `inline` variant to have different `copyButtonText` and `textToCopy` values like `button` variant.
**Customer usecase:**
> When you want to display a date with `CopyToClipboard`, you may want to display the date in localized, readable format but allow copying in language agnostic, timezone agnostic way, for example, UTC format.
It's a problem because as shown in the screenshot, different variants have different icon color and hurts visual uniformity without good reasons.
**Main problem:**
With any custom implementation, i.e. combining `SpaceBetween` using the `variant="icon"` and a string, it will result in a grey …
> feat: CopyToClipboard - Allow separate content from text to copy for inline variant

- src/internal/components/drag-handle/__tests__/drag-handle-button.test.tsx
- src/internal/components/drag-handle/__tests__/drag-handle.test.tsx
- src/internal/components/drag-handle/button.tsx
- src/internal/components/drag-handle/index.tsx
- src/internal/components/drag-handle/interfaces.ts
This is needed for using the DragHandle component in the board components where we make use of ariaLabelledBy to reference multiple DragHandle's to one label.
Related links, issue #, if available: AWSUI-60240
- added additional unit tests
<details> …
> chore: Add ariaLabelledBy to InternalDragHandle component

- pages/key-value-pairs/permutations.page.tsx
- pages/key-value-pairs/simple.page.tsx
- src/key-value-pairs/__tests__/key-value-pairs.test.tsx
- src/key-value-pairs/interfaces.ts
- src/key-value-pairs/styles.scss
Update the `label` property to support `ReactNode` for custom components such as adding icons to the labels.
`AWSUI-55326`
`08LJAUcYhg64`
Manual, unit
<details> …
> feat: KeyValuePairs update pair label to ReactNode

- pages/app/app-context.tsx
- pages/table/performance-marks.page.tsx
- src/button-dropdown/__integ__/performance-marks.test.ts
- src/button/__integ__/performance-marks.test.ts
- src/internal/hooks/use-performance-marks/__tests__/is-in-viewport.test.tsx
- src/internal/hooks/use-performance-marks/index.ts
- src/internal/hooks/use-performance-marks/is-in-viewport.ts
- src/internal/utils/__tests__/mock-intersection-observer.test.ts
- src/internal/utils/__tests__/mock-intersection-observer.ts
- src/table/__integ__/performance-marks.test.ts
This PR updates our performance marks to include information about whether the component is inside the viewport or not.
Tested manually in the dev pages, added unit tests.
<details> …
> chore: Include viewport visibility in performance marks

- src/multiselect/__tests__/select-all.test.tsx
- src/multiselect/internal.tsx
Before: "Select all" appeared on empty virtualScroll multiselect causing a JS error.
After: "Select all" is not rendered when no options are available.
Fixes #3432
Related links, issue #, if available: `AWSUI-60656`
- verified manually be recreating the failing scenario and test the changes.
- updated existing unit test to test test in both `virtualScroll` modes.
<details> …
> fix: Do not render "select all" when there are no options to select

- src/key-value-pairs/styles.scss
After a previous PR that changed the `label` prop into a `ReactNode` the alignment of the info icon was changed.
This PR fixes that by moving the `display: inline-flex` style to the `key-label` instead of the whole label including the info link.
Before:
After:
Manual, error brought up via screenshot tests
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBU …
> fix: Fix info link alignment in KeyValuePairs

- src/flashbar/__tests__/analytics-metadata.test.tsx
- src/flashbar/analytics-metadata/interfaces.ts
- src/flashbar/collapsible-flashbar.tsx
Currently `expand` events are being post-processed by the analytics team to rename them to `collapse` if `expanded=false`. This saves storage for events database tables.
Changing this will align with the actual usage.
Updated unit tests, and added more
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._ Yes, the Analytics team logic already supports the new native format.
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/component …
> feat: Update analytics metadata expand event treatment for flashbar

- src/flashbar/styles.scss
This PR fixes a bug that's been introduced in [this change](https://github.com/cloudscape-design/components/pull/3439/files#diff-830d2afec0c4339df425e599c2a7294f079d8350460fd6426562f3106993526c) for VR improvements.
The expected block margin size is 1px for classic and 2px for VR.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/b …
> chore: Fix a space bug for VR improvements

- src/segmented-control/styles.scss
Before this change, the component was transparent, causing visual distractions when positioned over another element (e.g. over a border).
Updated the background after talking to @at-susie about. See `AWSUI-60657` for details.
Related links, issue #, if available: `AWSUI-60657`
- tested manually.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#br …
> chore: Add background color to SegmentedControl

- src/checkbox/__tests__/analytics-metadata.test.tsx
- src/checkbox/analytics-metadata/interfaces.ts
- src/checkbox/internal.tsx
- src/collection-preferences/__tests__/analytics-metadata.test.tsx
- src/table/__tests__/analytics-metadata.test.tsx
- src/table/analytics-metadata/interfaces.ts
- src/table/selection/selection-cell.tsx
- src/table/selection/selection-control.tsx
- src/table/thead.tsx
- src/toggle/__tests__/analytics-metadata.test.tsx
- src/toggle/analytics-metadata/interfaces.ts
- src/toggle/internal.tsx
Currently `select` (and similar) events are being post-processed by the analytics team to rename them to `deselect` if `selected=false`. This saves storage for events database tables.
Changing this will align with the actual usage.
Updated unit tests, and added more
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._ Yes, the Analytics team logic already supports the new native format. …
> chore: Update selection events analytics metadata

- build-tools/tasks/docs.js
- src/__tests__/utils.tsx
Support changes done in that PR: https://github.com/cloudscape-design/documenter/pull/67
* Inspected definitions directory locally, all files are expected
* Dry-run passes (eventually)
<details> …
> chore: Migrate to the new documenter API

- src/internal/base-component/__tests__/validate-props-production.test.ts
- src/internal/base-component/__tests__/validate-props.test.ts
- src/internal/base-component/index.ts
We have a new function to validate in runtime if there is a property from an unsupported system.
Two fixes in this PR
1. Do not throw in this use-case `<Button variant={undefined}>`
2. Add `isDevelopment` condition to remove this code from production builds
Updated unit test
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/ma …
> chore: Handle undefined values when validating props

- src/internal/components/drag-handle-wrapper/__tests__/portal-overlay.test.tsx
- src/internal/components/drag-handle-wrapper/index.tsx
- src/internal/components/drag-handle-wrapper/portal-overlay.tsx
Before this change, the update position effect has been run on every animation frame even though no position buttons have been shown.
With this change, the position calculation is only done when the position buttons are visible.
Related links, issue #, if available: AWSUI-60240
- manually tested in supported browsers
- added additonal unit tests
- screenshot tests in my pipeline run green
<details> …
> chore: Update PortalOverlay's position in DragHandleWrapper only when buttons are shown

- pages/drawer/permutations.page.tsx
- src/drawer/implementation.tsx
This PR addresses the issue with drawer paddings described here: https://github.com/cloudscape-design/components/issues/3466
<details> …
> fix: Drawer loading paddings

- pages/drawer/permutations.page.tsx
1. Remove duplicated combinations of loading state
2. Added random text to the empty `<Drawer />` case to make sure this permutation does not collapse to an empty div
Reviewed locally. Now this page is good for testing CR-194096177
<details>
- …
> chore: refactor drawer permutation page

- pages/date-range-picker/common.ts
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/date-range-picker/calendar/grids/index.tsx
- src/date-range-picker/calendar/grids/interfaces.ts
- src/date-range-picker/calendar/header/header-button.tsx
- src/date-range-picker/calendar/header/index.tsx
- src/date-range-picker/calendar/index.tsx
- src/date-range-picker/calendar/range-inputs.tsx
- src/date-range-picker/dropdown.tsx
- src/date-range-picker/interfaces.ts
- src/date-range-picker/relative-range/index.tsx
Currently the DatePicker imports its Granularity from CalendarProps, so this will ensure the types are the same between DatePicker and DateRangePacker and the one source of truth for the Granularity type lives in the CalendarProps
<details>
- …
> chore: Updating Granularity type to that of CalendarProps

- src/internal/components/drag-handle/__tests__/drag-handle.test.tsx
The property was introduced in #3431. Adding this test has been missed.
Related links, issue #, if available: `AWSUI-60240`
- updated existing unit test
<details> …
> chore: Add test for InternalDragHandle ariaDescribedby

- src/table/__tests__/inline-editor.test.tsx
- src/table/body-cell/inline-editor.tsx
A quick fix for an issue when you put an inline editing table inside an "outer form" (well, technically, you shouldn't nest forms, but, well...)
Related links, issue #, if available: AWSUI-60735
<details> …
> fix: Prevent forms wrapping inline editing table from submitting

- src/popover/container.tsx
When an Annotation Popover is open, and the user interacts with the page so that the layout changes (e.g. toggling the side navigation panel), the Popover needs to update its position. With the existing heuristic, the Popover recalculates whenever the user clicks on the page (or interacts with a button using the keyboard), but the current logic assumes that any layout update then happens in a single frame. In the case of the navigation panel opening, it slides in with an animation, so the Popover only adapts to the first frame.
With this change, the Popover continuously updates its position for one second after the user interacts with the page. This should give enough time for any layout-related animations to finish, and it smoothly updates the Popover's position while its trigger moves. …
> fix: Popover is positioned incorrectly when the layout changes

- src/link/styles.scss
Bold text in general should have the `font-smoothing` mixin applied. The "top-navigation" variant of the link component is niche enough that we missed it at some point. See the subtle boldness difference between "Link" and "Customer Name" [here](https://cloudscape.design/components/top-navigation/?tabId=playground).
Related links, issue #, if available: AWSUI-60745
Screenshot tests, though I'm curious if this is subtle enough to end up getting picked up.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-ap …
> fix: Fix font smoothing on top navigation link utilities

- package.json
- src/internal/components/drag-handle-wrapper/__tests__/drag-handle-wrapper.test.tsx
- src/internal/components/drag-handle-wrapper/index.tsx
- src/internal/components/drag-handle-wrapper/interfaces.ts
- src/internal/components/drag-handle/index.tsx
- src/internal/components/drag-handle/interfaces.ts
This mode allows the builder to decide when UAP action buttons are shown.
Use-case: On board items the UAP action buttons should be shown on key `Enter` press instead of `onFocus`. When using `onFocus` to show them, tabbing through a board with many board items gets visually noisy.
(This is a preparation for adding the InternalDragHandle to board-items)
Related links, issue #, if available: `AWSUI-60240`
- added additional unit tests for the new interaction mode
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#p …
> feat: Add uapTriggerMode property to InternalDragHandle component

- src/__tests__/snapshot-tests/__snapshots__/design-tokens.test.ts.snap
- style-dictionary/visual-refresh/metadata/colors.ts
The title explains it. We make the other button tokens themeable, no reason we can't allow customizing the link button variant.
Related links, issue #, if available: AWSUI-60747
Updated the snapshot tests.
<details> …
> chore: Make color-background-button-link-* tokens public and themeable

- build-tools/tasks/package-json.js
- pages/drag-handle/drag-handle-interaction-state-hook.page.tsx
- pages/drag-handle/styles.scss
- src/internal/components/drag-handle/hooks/__tests__/use-drag-handle-interaction-state.test.tsx
- src/internal/components/drag-handle/hooks/interfaces.ts
- src/internal/components/drag-handle/hooks/use-drag-handle-interaction-state.ts
- src/internal/do-not-use/drag-handle.ts
Add interaction state hook with DnD and keyboard support
Introduce useDragHandleInteractionState hook that implements a comprehensive state machine for drag handle components. The hook manages multiple interaction states:
- Pointer-based drag-and-drop (dnd-start, dnd-active, dnd-end)
- Keyboard-based universal access pattern (uap-action-start, uap-action-end)
The hook includes state transition logic, callback management, event handling, and metadata passing between states. 
Use-case: For complex drag/resize, the hook will trigger callbacks based on transition states. E.g. in the board components to put the board and board items into the different states based on the user interaction with the drag/resize handle.
Related links, issue #, if available: `AWSUI-60240`
- added new unit tests
- …
> feat: Add interaction state hook with DnD and keyboard support

- pages/funnel-analytics/table.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/table/__integ__/component-metrics.test.ts
- src/table/index.tsx
- src/table/interfaces.tsx
- src/table/internal.tsx
Exposes `resourceType` on the `analyticsMetadata` property for Table.
Updated integ test.
<details> …
> chore: Add resourceType to table

- src/table/__integ__/component-metrics.test.ts
- src/table/internal.tsx
- src/table/selection/use-selection.ts
Improve captured selection action type
For additional context you can look at this draft [PR](https://github.com/cloudscape-design/components/pull/3495) that includes all the relevant changes and shows the final state.
- Added new integ test
- _If the …
> chore: Improve Table task flow selection capture

- src/collection-preferences/index.tsx
- src/internal/analytics/interfaces.ts
- src/internal/context/__tests__/table-component-context.test.tsx
- src/internal/context/table-component-context.ts
- src/table/__integ__/component-metrics.test.ts
- src/table/__tests__/component-metrics.test.tsx
- src/table/internal.tsx
- Capture table preference changes in existing componentUpdated event
For additional context you can look at this draft [PR](https://github.com/cloudscape-design/components/pull/3495) that includes all the relevant changes and shows the final state.
- Added additional integ and unit test …
> chore: Improve Table task flow preferences capture

- pages/funnel-analytics/with-async-table.page.tsx
- src/table/__integ__/component-metrics.test.ts
- Add additional testing for async based tables
- Add an additional test for sorting
For additional context you can look at this draft [PR](https://github.com/cloudscape-design/components/pull/3495) that includes all the relevant changes and shows the final state.
- Tests pass …
> chore: Add additional testing for async table task flows

- pages/drag-handle/drag-handle-interaction-state-hook.page.tsx
- src/internal/components/drag-handle/hooks/__tests__/use-drag-handle-interaction-state.test.tsx
- src/internal/components/drag-handle/hooks/use-drag-handle-interaction-state.ts
Clicking a drag handle managed by `useInternalDragHandleInteractionState` could cause a an endless loop ("Maximum update depth exceeded"). It occurred because callbacks triggered by the hook would cause the consuming component to re-render. This re-render, in turn, re-triggered the hook's effect handler, which then re-processed the same (stale) callbacks because they weren't cleared from the hook's internal state, leading to an infinite loop.
This change adds the clear its internal `transitionCallbacks` immediately after they are processed. A new `CLEAR_CALLBACKS` action is dispatched within the `useCallbackHandler`'s effect post-execution, ensuring callbacks are only invoked once per state transition.
This fix eliminates the infinite loop, making drag handle interactions more stable and …
> chore: Prevent callback re-processing loop in useInternalDragHandleInteractionState

- src/internal/components/drag-handle-wrapper/__tests__/drag-handle-wrapper.test.tsx
- src/internal/components/drag-handle-wrapper/index.tsx
Before this change, in keyboard-activate mode:
- when focusing the drag handle and Tab away, it showed the buttons.
After this change, in keyboard-activate mode:
- when focusing the drag handle and Tab away, it won't show the buttons.
- add aditional unit test for this change.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/ …
> chore: Show buttons on any other key in DragHandle only in focus trigger mode

- build-tools/tasks/test-utils.js
Currently the tsbuildinfo file for test-utils is building to `/lib/components/test-utils/tsconfig.tsbuildinfo` which results in it being included in the published npm artifact. This change sets the output of this file to `/lib/{theme-name}-test-utils.tsbuildinfo` to maintain incremental typescript but remove it from the npm artifact.
Manually verified the file has moved and all checks still pass.
<details> …
> chore: Move tsbuildinfo from test-utils to lib

- .github/workflows/release.yml
This updates the release workflow to subsequently run the release workflows in downstream repositories (currently only chat-components configured for testing).
See also https://github.com/cloudscape-design/chat-components/pull/68 and https://github.com/cloudscape-design/actions/pull/76
Approach based on https://medium.com/hostspaceng/triggering-workflows-in-another-repository-with-github-actions-4f581f8e0ceb
Related links, issue #, if available: AWSUI-60697, ajEoAR4R2fG4#temp:C:eGb718a2a8234034c4eaab90ccdd
<details> …
> chore: Update release.yml to release downstream repositories

- src/app-layout/__tests__/app-layout-navigation.test.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
[This commit](https://github.com/cloudscape-design/components/commit/727c496d5df702d063f05f28aae92cc763d7c723) introduced a bug in the `AppLayout` component where the `onNavigationChange` callback is no longer triggered when the navigation panel is open.
Originally, this condition was added to prevent triggering the callback during the drawers’ expanded mode, in order to preserve the original state when exiting that mode. However, the issue is that the condition does not correctly check whether any drawer is currently in expanded state.
This PR fixes that logic and adds a corresponding test.
<details> …
> fix: OnNavigationChange callback

- src/internal/components/drag-handle-wrapper/motion.scss
This change addresses a UX issue where buttons briefly reappeared after their exit animation, causing an unwanted flicker effect (reported in https://github.com/cloudscape-design/board-components/pull/356#issuecomment-2913112051). By retaining the final keyframe state, we create a smoother transition without disrupting the intended hide behavior.
Before this change: When the exit animation completes, the element briefly reverts to its original state before being hidden. This happens because by default, CSS animations reset to their pre-animation state once completed ([see MDN docs for animation-fill-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode)). The specific animation sequence behavior before this change:
1. Initial state (buttons visible)
1. Exit animation …
> fix: Prevent drag handle arrow button flicker on exit animation

- src/internal/components/drag-handle-wrapper/__tests__/drag-handle-wrapper.test.tsx
- src/internal/components/drag-handle-wrapper/index.tsx
- src/internal/components/drag-handle-wrapper/interfaces.ts
- src/internal/components/drag-handle/index.tsx
- src/internal/components/drag-handle/interfaces.ts
Both options are used to allow more flexibility. Use cases:
- `hideButtonsOnDrag`: When using the UAP handles on board-items they're activated once clicked the handle. While dragging is active, the buttons, if visible, should be hidden. This helps to distinguish in between the pointer and step interaction modes.
- `clickDragThreshold`: A "click" happens when a "pointerdown" is followed by a "pointerup" with no "pointermove" between the two.
However, it would be a poor usability experience if a "click" isn't registered because, while pressing my mouse, I moved it by just one pixel, making it a "drag" instead. So we allow the pointer to move by `clickDragThreshold` to count as click instead of a move. …
> chore: Add hideButtonsOnDrag and clickDragThreshold property to InternalDragHandle

- package.json
- pages/funnel-analytics/with-table.page.tsx
- src/header/analytics/use-table-integration.ts
- src/header/internal.tsx
- src/internal/analytics/utils/__tests__/parse-count-text.test.ts
- src/internal/analytics/utils/parse-count-text.ts
- src/internal/context/__tests__/table-component-context.test.tsx
- src/internal/context/table-component-context.ts
- src/table/__integ__/component-metrics.test.ts
- src/table/internal.tsx
- src/text-filter/analytics/use-table-integration.ts
- src/text-filter/internal.tsx
Extracts count text from Table header as a fallback to the Filter count when a custom filter is used.
- Added integ tests for the Table integration
- Added unit tests for the added utility method that does the parsing …
> chore: Track table counter text from title as fallback

- src/button-dropdown/__tests__/analytics-metadata.test.tsx
- src/button-dropdown/interfaces.ts
- src/button-dropdown/internal.tsx
Needed to instrument button-group
<details> …
> feat: Accept position in internal ButtonDropdown for analytics purposes

- src/internal/components/drag-handle/__tests__/drag-handle-button.test.tsx
- src/internal/components/drag-handle/button.tsx
NVDA just skips past buttons if you use arrow keys on them while they're focused. Because pressing arrow keys on a button shouldn't do anything. The thing is, we don't have a role we could could for something like this, which means we fall back to our "I give up" ("application") role.
Related links, issue #, if available: AWSUI-60203
Modified a unit test.
<details> …
> fix: Use role="application" for two-dimensional drag handles

- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/table/__tests__/inline-editor.test.tsx
- src/table/body-cell/inline-editor.tsx
- src/table/interfaces.tsx
See 8vYGAsYRWx2h for API proposal.
Related links, issue #, if available: AWSUI-60735
Unit tests.
<details> …
> feat: Allow table inline editing to be rendered without a wrapping <form>

- src/internal/components/options-list/utils/use-highlight-option.ts
- src/multiselect/__tests__/multiselect-embedded.test.tsx
- src/multiselect/__tests__/multiselect.test.tsx
- src/multiselect/__tests__/select-all.test.tsx
- src/select/__integ__/page-objects/select-page.ts
- src/select/__integ__/select-native-search.test.ts
- src/select/__integ__/select.test.ts
- src/select/__tests__/disabled.test.tsx
- src/select/__tests__/use-select.test.ts
- src/select/utils/use-select.ts
NVDA borks if there's no aria-activedescendant on a focused listbox. So we select the first one by default.
Had to modify a bunch of tests because of the "screen reader text" internal implementation logic that leads to `.textContent` being duplicated. Thankfully `.toHaveTextContent()` seems to be immune to that, so I just switched to that instead.
Related links, issue #, if available: AWSUI-60825
Fought and defeated the unit tests.
Also dry-run build: 7415253429
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#p …
> fix: Highlight the first select option by default if none are selected

- src/app-layout/visual-refresh-toolbar/drawer/styles.scss
This reverts commit aed2aee5e25f35de6ef0f773b4cd3e52c9ddf5ed, #3534
The change was temporary, not needed anymore
<details> …
> revert: Global drawer for mobile view (#3534)

- pages/button/style-custom-types.page.tsx
This PR disables animations in the screenshot are for the Button custom types demo page.
> chore: Disabled animations in Button screenshot area

- pages/container/simple.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/container/index.tsx
- src/container/interfaces.ts
- src/container/internal.tsx
- src/table/internal.tsx
Expose disableFooterPaddings property on container (core only), for added consistency with other container slots.
<details> …
> feat: Expose disableFooterPaddings on container

- src/i18n/messages-types.ts
- src/i18n/messages/all.ar.json
- src/i18n/messages/all.de.json
- src/i18n/messages/all.en-GB.json
- src/i18n/messages/all.en.json
- src/i18n/messages/all.es.json
- src/i18n/messages/all.fr.json
- src/i18n/messages/all.id.json
- src/i18n/messages/all.it.json
- src/i18n/messages/all.ja.json
- src/i18n/messages/all.ko.json
- src/i18n/messages/all.pt-BR.json
- src/i18n/messages/all.tr.json
- src/i18n/messages/all.zh-CN.json
- src/i18n/messages/all.zh-TW.json
Added i18n translations
<details> …
> chore: Add i18n translations for tree view and date range picker

- src/alert/styles.scss
- src/anchor-navigation/styles.scss
- src/annotation-context/annotation/styles.scss
- src/breadcrumb-group/item/styles.scss
- src/breadcrumb-group/styles.scss
- src/button/styles.scss
- src/calendar/styles.scss
- src/checkbox/styles.scss
- src/code-editor/ace-editor.scss
- src/code-editor/pane.scss
- src/code-editor/resizable-box/styles.scss
- src/code-editor/styles.scss
- src/date-picker/styles.scss
- src/date-range-picker/calendar/grids/styles.scss
- src/date-range-picker/styles.scss
- src/expandable-section/styles.scss
- src/file-token-group/styles.scss
- src/flashbar/collapsible.scss
- src/flashbar/styles.scss
- src/form-field/styles.scss
Reverts cloudscape-design/components#3598. There's currently another part of the pipeline I'm blocking right now, and I'll wait to merge this one until everything else is green and 100% sure about Safari.
> revert: Revert "chore: Use CSS-native :focus-visible to track visible focus state (batch 1)"

- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
Following on this change https://github.com/cloudscape-design/documenter/pull/76
Dry-run
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility …
> chore: Update snapshot

- src/table/__tests__/inline-editor.test.tsx
Splitting #3624 into a PR someone else can approve/merge.
Fixing tests _is_ the PR. Maybe something broke during a version change, or maybe these tests didn't quite work as expected to begin with, but they're green again, and a little bit faster too.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browse …
> chore: Add missing await in inline editor tests

- pages/multiselect/select-all.page.tsx
- src/multiselect/__tests__/analytics-metadata.test.tsx
- src/multiselect/internal.tsx
- src/token-group/internal.tsx
Changes disabled multiselect items so that they get rendered as `readOnly` tokens for accessibility purposes.
Related links, issue #, if available: AWSUI-60953
New unit test
<details> …
> chore: Make disabled selected multiselect tokens readonly

- src/table/header-cell/index.tsx
- src/table/header-cell/styles.scss
- src/table/header-cell/th-element.tsx
- src/table/resizer/index.tsx
- src/table/resizer/styles.scss
We've received a report that hovering over last column's resizer causes layout shifts in Firefox & Safari.
While we could fix that, the question is: why do we have a non-visible interactive element in the first place? It's there, it receives focus and shows focus ring, but you need to know it exists to interact with it.
So, let's make it simple 
Related links, issue #, if available: AWSUI-60946
Before (with focus ring):
After:
- ✅ RUN through my dev pipeline to check screenshots 
- checked with visual design
<details> …
> feat: Show resizer for last table column

- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/app-layout/visual-refresh/mobile-toolbar.tsx
- src/app-layout/visual-refresh/trigger-button.tsx
- src/attribute-editor/internal.tsx
- src/button-dropdown/internal.tsx
- src/button/__tests__/button.test.tsx
- src/button/__tests__/internal.test.tsx
- src/button/__tests__/native-attributes.test.tsx
- src/button/index.tsx
- src/button/interfaces.ts
- src/button/internal.tsx
- src/code-editor/status-bar.tsx
- src/file-input/internal.tsx
- src/internal/utils/__tests__/with-native-attributes.test.tsx
- src/internal/utils/with-native-attributes.tsx
- src/tutorial-panel/components/tutorial-list/index.tsx
Allow button native attributes to be set.
Related links, issue #, if available: AWSUI-60858
New unit tests
<details>
- _If the code …
> feat: Allow button native element attributes to be set

- src/test-utils/dom/table/index.ts
in #3477 we moved styles file that was used in test utils, which led to regenerated hashes, which led to customers' integration test failing because of mismatched versions.
We discussed that using both old and new selector could be a solution if we absolutely have to change the selector.
Because there is no "old" selector anymore (we moved the file), I just copied the exact class name from the snapshot. Messy, but..
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public …
> fix: Add backward compatibility for expandable table test util

- pages/app-layout/runtime-drawers.page.tsx
- src/app-layout/__integ__/runtime-drawers.test.ts
- src/app-layout/__tests__/runtime-drawers.test.tsx
- src/app-layout/__tests__/utils.tsx
- src/app-layout/utils/use-drawers.ts
- src/internal/plugins/controllers/drawers.ts
This PR introduces a new method `resizeDrawer(drawerId: string, size: number)` for Cloudscape plugin api to programmatically resize drawers declared within `AppLayout` component.
**Usage example:**
```javascript
awsuiPlugins.appLayout.resizeDrawer('circle-global', 400)
```
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main …
> feat: resizeDrawer method for plugin api

- src/button/__tests__/button.test.tsx
- src/button/__tests__/internal.test.tsx
- src/button/internal.tsx
In case a button has an href, it is rendered as an anchor. When an anchor is disabled, it should not have both `aria-disabled` and `href`. We need to remove the `href` while adding a `role: "link"`.
Following this guideline: https://w3c.github.io/html-aria/?utm_source=chatgpt.com#:~:text=It%20is%20NOT%20RECOMMENDED%20to%20use%20aria%2Ddisabled%3D%22true%22%20on%20an%20a%20element%20with%20an%20href%20attribute.
Related links:
archives/C01BMLAMF1P/p1753117381571299
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md …
> chore: Provide correct role and href for disabled link buttons

- src/internal/styles/typography/mixins.scss
- src/top-navigation/styles.scss
The letter spacing of headers of drawers and split panels are not consistent with our header styles, since they are styled like an h3 header except for the letter spacing.
(And we also save a few pixels).
As an example, the screenshot below shows a split panel header with a Box with `variant="h3"` and `margin="n"` in the split panel content.
This change is confirmed with Visual Design.
Tested in my pipeline, visual diffs are as expected.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/ …
> fix: Harmonize drawer headers' letter spacing with other headers

- src/app-layout/__integ__/runtime-drawers.test.ts
Added `waitForAssertion` in a test for runtime drawers to make them more stable.
<details>
- …
> chore: Add waitForAssertion in runtime-drawers.test.ts

- pages/prompt-input/permutations.page.tsx
- pages/prompt-input/simple.page.tsx
- src/__tests__/snapshot-tests/__snapshots__/test-utils-selectors.test.tsx.snap
- src/prompt-input/__tests__/prompt-input.test.tsx
- src/prompt-input/interfaces.ts
- src/prompt-input/internal.tsx
- src/prompt-input/styles.scss
- src/prompt-input/test-classes/styles.scss
- src/test-utils/dom/prompt-input/index.ts
Allow custom primary actions. For example, to replace the default single action with multiple action buttons.
Related links, issue #, if available: AWSUI-60922
Updated unit tests and permutations
<details> …
> feat: Allow custom primary actions in prompt input

- src/popover/__tests__/popover.test.tsx
- src/popover/conditional-live-region.tsx
- src/popover/internal.tsx
Previously, `aria-live` and `aria-atomic` attributes on the popover content weren't effectively announcing content to screen readers.
Implements LiveRegion component to properly announce non-dismissible popover content to screen readers.
Note: This change only affects non-dismissible popovers since:
- Dismissible popovers receive focus and are naturally navigable by screen reader users
- Non-dismissible popovers lack focus management, requiring content to be announced via live regions
Related links, issue #, if available: `AWSUI-60746`
- update / add existing unit tests
- green dry run
How can reviewers test these changes efficiently?
- Open the popup examples with a screen reader turned on
- Navigate via keyboard to the popover trigger and press enter
- The popover content is live …
> fix: Add LiveRegion to non-dismissible Popover

- src/flashbar/__integ__/focus-interactions.test.ts
- src/flashbar/__integ__/pages/base.ts
- src/flashbar/__integ__/pages/interactive-page.ts
- src/flashbar/__tests__/common.test.tsx
- src/flashbar/__tests__/flash-utils.test.tsx
- src/flashbar/__tests__/flashbar.test.tsx
- src/flashbar/__tests__/focus-handling.test.tsx
- src/flashbar/collapsible-flashbar.tsx
- src/flashbar/common.tsx
- src/flashbar/flash.tsx
- src/flashbar/non-collapsible-flashbar.tsx
This introduces focus logic whenever a flash item gets dismissed, it works in both the collapsible and non-collapsible versions of the flashbar.
The idea works as the following:
- for each flash item we attach a ref
- when a flash item gets dismissed, we call a onDissmied callback that figures out the next flash item to focus and focues it
- if no flash items are remianing, we focus the main element (or an element with role="main")
- we prioritise focusing the dismiss button in case a flash is dismissed, otherwise we focus the focus invisible container of the flash item
AWSUI-60902
Added integration tests to it
Tested it locally as well in the flashbar interactive page
<details> …
> chore: Introduce focus behavior when flash items gets dismissed

- pages/prompt-input/permutations.page.tsx
- src/prompt-input/internal.tsx
- src/prompt-input/styles.scss
> fix: Restore reponsiveness inside prompt input secondary actions

- src/table/body-cell/styles.scss
The inset property over the hovered inline editing table cells causes a hover flicker issue when there are table editing cells under each other, why? because the inset inline gives a negative -1px for the horizontal edges postion, so when you hover 1px away (when zooming for example) you might actually be hovering the table editing cell, and then it unhovers cause of that 1px difference.
A video attached here to show a reproducible video in the demos 
https://github.com/user-attachments/assets/16dd3610-094d-449e-960f-a7893f89233f
AWSUI-61035
<details>
_The following items are to be evaluate
d by the author(s) and the reviewer(s)._ …
> chore: Remove inset inline property in inline-editing cells

- pages/app-layout/global-breadcrumbs.page.tsx
- src/app-layout/__tests__/global-breadcrumbs.test.tsx
- src/app-layout/visual-refresh-toolbar/skeleton/breadcrumbs/index.tsx
- src/app-layout/visual-refresh-toolbar/skeleton/breadcrumbs/styles.scss
- src/internal/plugins/helpers/use-global-breadcrumbs.ts
Revert this PR: https://github.com/cloudscape-design/components/pull/3704, and also add some extra fixes and tests
Apparently these styles served extra purpose, not only backward compatibility
Related links, issue #, if available: V1881484904
Added a regression test
<details>
- _Changes …
> fix: prevent double discovered breadcrumbs

- src/app-layout/__tests__/state.test.tsx
- src/app-layout/__tests__/utils.tsx
Make sure we do not unmount main node when app layout state changes
<details>
- _If the code …
> chore: Add more tests on app layout state management

- src/app-layout/visual-refresh-toolbar/multi-layout.ts
- src/internal/plugins/controllers/app-layout-widget.ts
When app layout is suspended (e.g. intersection observer reported it is not intersecting), the inner app layout state still shows it is in "secondary" mode, which might be unexpected
n/a, I did not find any real manifestations of this bug
<details> …
> fix: Properly handle app layout suspended state

- pages/badge/style-custom-types.page.tsx
Text colors were initially set to default palette values (neutral10 and neutral100) and were changed to explicit 'white' and 'black' values to better identify potential styling errors.
<details> …
> chore: Changed colors for the style-custom-types page

- src/flashbar/interfaces.ts
The `onDismiss` was not documented  in the `FlashbarProps` interface. Now it is.
Related links, issue #, if available: `AWSUI-61104`
- updated snapshot
- green review checks
<details> …
> chore: Add API docs for `onDismiss` in Flashbar component

- src/app-layout/__integ__/global-breadcrumbs.test.ts
- src/app-layout/__integ__/utils.ts
- src/app-layout/__tests__/trigger-button.test.tsx
- src/app-layout/__tests__/utils.tsx
Make sure we use `appLayoutToolbar` feature flag is used in all places as expected.
The `appLayoutWidget` flag logic is still tested in dedicated tests: https://github.com/cloudscape-design/components/blob/main/src/internal/widgets/__tests__/widgets.test.tsx
Test-only change
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/ma …
> chore: reorganize app layout feature flags

- src/internal/hooks/use-intersection-observer/__tests__/use-intersection-observer.test.tsx
- src/internal/hooks/use-intersection-observer/index.ts
Fixing a bug where `useIntersectionObserver` only checks the first change entry instead of the latest.
Check the docs: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
> The list of entries received by the callback includes one [IntersectionObserverEntry](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry) object for each threshold-crossing event — multiple entries can be received at a time, either from multiple targets or from a single target crossing multiple thresholds in a short amount of time. The entries are dispatched using a queue, so they should be ordered by the time they were generated, but you should preferably use [IntersectionObserverEntry.time](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry/time) …
> fix: Handle multiple intersection changes in a single callback

- pages/list/sortable-permutations.page.tsx
- src/collection-preferences/content-display/__integ__/content-reordering.test.ts
- src/collection-preferences/content-display/__integ__/pages/content-display-page.ts
- src/collection-preferences/content-display/__integ__/pages/dnd-page-object.ts
- src/internal/components/drag-handle-wrapper/__tests__/drag-handle-wrapper.test.tsx
- src/internal/components/drag-handle-wrapper/index.tsx
- src/internal/components/drag-handle-wrapper/interfaces.ts
- src/internal/components/drag-handle/button.tsx
- src/internal/components/drag-handle/index.tsx
- src/internal/components/drag-handle/interfaces.ts
- src/internal/components/drag-handle/styles.scss
- src/internal/components/sortable-area/__tests__/sortable-area.test.tsx
- src/internal/components/sortable-area/index.tsx
- src/internal/components/sortable-area/keyboard-sensor/index.ts
- src/internal/components/sortable-area/keyboard-sensor/utilities/__tests__/scroll.test.ts
- src/internal/components/sortable-area/keyboard-sensor/utilities/events.ts
- src/internal/components/sortable-area/keyboard-sensor/utilities/scroll.ts
- src/internal/components/sortable-area/styles.scss
- src/internal/components/sortable-area/use-drag-and-drop-reorder.ts
- src/list/__tests__/list-sortable.test.tsx
Add pointer-only/"UAP" buttons to sortable list
Related links, issue #, if available: AWSUI-61051
New unit and integ tests
<details>
- …
> chore: Add dnd drag buttons to list

- pages/tabs/with-iframe.page.tsx
- src/tabs/__integ__/with-iframe.test.ts
- src/tabs/tab-header-bar.tsx
Without this fix, pressing Tab when the focus is on the active tab header does not move focus to the content. The keyboard navigation with left/right arrow keys does not work either.
Rel: AWSUI-61144
* New integration tests
<details> …
> fix: Fixes tabs focus and navigation when rendered inside iframe

- src/flashbar/__integ__/collapsible.test.ts
- src/flashbar/__integ__/focus-interactions.test.ts
- src/flashbar/__integ__/pages/base.ts
- src/flashbar/__integ__/pages/interactive-page.ts
- src/flashbar/__tests__/focus-handling.test.tsx
- src/flashbar/collapsible-flashbar.tsx
- src/flashbar/common.tsx
- src/flashbar/flash.tsx
- src/flashbar/utils.ts
I'll be honest here, I didn't feel like diving into the weird transition/animation logic going on with the flashbar components. So I just changed the throttle logic to do a debounce instead (so it always waits for the animation to complete while still preventing repeated flashbar insertions from annoying users). Sue me.
Actually, if new flash items go from bottom to top now (as they do with collapsible flashbars), debounce is actually better. So yay me, actually!
Related links, issue #, if available: AWSUI-61128
Added unit tests. But also tested locally in a dev page. Try it out yourself — go to the `flashbar/interactive` page, enable stack items, and add an error flash. The focus move to the newly added flash message should work (it didn't before).
<details> …
> fix: Fix focus management for flashbar when motion is enabled

- src/date-range-picker/__integ__/date-range-picker.test.ts
- src/date-range-picker/__tests__/time-offset.test.ts
- src/date-range-picker/__tests__/utils.test.ts
- src/date-range-picker/time-offset.ts
- src/internal/utils/date-time/__tests__/format-date-iso.test.ts
- src/internal/utils/date-time/__tests__/format-date-localized.test.ts
- src/internal/utils/date-time/__tests__/format-date-time-with-offset.test.ts
- src/internal/utils/date-time/__tests__/format-time-offset.test.ts
- src/internal/utils/date-time/format-time-offset.ts
- src/internal/utils/date-time/index.ts
This is a second attempt at #3763.
This pull request changes how UTC dates are formatted to use the `Z`
suffix instead of `+00:00`. This should make UTC dates more succinct and
readable. cc @jperals
```
2018-01-16T00:00:00+00:00
```
```
2018-01-16T00:00:00Z
```
The key difference between this and #3763 is that it makes a distinction
between formatting ISO timestamps for internal use vs. formatting them
for display. Internal ISO timestamps are used in (for example) the
`onChange` event in `DateRangePicker`. Those internal ISO timestamps
retain the `+00:00` suffix to ensure backward compatibility with
customers' parsing logic.
✅ I've updated all existing unit tests.
I wasn't able to get the integration tests to run on my machine. Those may need additional changes.
<details> …
> feat: Use succinct UTC time zone offset: "+00:00" -> "Z" (take 2)

- src/internal/hooks/use-virtual/index.ts
In the PR we update the bail-out counter in the use-virtual to match React's one for "Maximum update depth exceeded". Over time, the React counter changed from 50 to 100 and then back to 50. We use 49 just for extra safety. A lower counter means that there is a chance the virtual frame does not have enough opportunity to settle down, which increases a risk of virtual frame computation errors (some items can appear smaller or larger than they should).
Rel: AWSUI-61148
* We don't have a reliable test for this one, but we got reports logging the "Maximum update depth exceeded". We will monitor if the PR will help getting rid of those.
Update: there is a way to test this, although the exact correlation between our counter and the React one is not quite clear. We can consistently reproduce the …
> fix: Adjusts use-virtual safety counter to prevent max update depth crashes

- pages/table-fragments/grid-navigation-custom.page.tsx
- src/internal/context/__tests__/single-tab-stop-navigation-context.test.tsx
- src/internal/context/__tests__/utils.tsx
- src/internal/context/single-tab-stop-navigation-context.tsx
The PR makes it possible to nest STSN providers. The use cases that we have are:
1. Rendering a button group inside table cells;
2. Rendering a button group inside tree view items (we are adding keyboard nave in there, too).
The idea of the change is rather simple: at any given point in time only one provider can be active. The active provider is the outer-most provider with navigationActive=true. If the outer provider changes state from true to false - the nested provider becomes active instead. This allows a dynamic switch of navigation contexts (e.g. when a tree toggle is focused - the tree navigation is engaged; when the focus is inside a tree item - the button group which can be rendered inside receives control). In some cases, it is not even necessary to do the switching. Thus, the …
> chore: Nested STSN providers support

- eslint.config.mjs
- src/app-layout/visual-refresh-toolbar/state/props-merger.ts
- src/copy-to-clipboard/__tests__/copy-to-clipboard.test.tsx
This commit enables the `prefer-object-spread` rule to automatically transform `Object.assign` calls that are equivalent to spreads, and fixes one violation of the rule.
<details> …
> chore: Add prefer-object-spread rule to ESLint config

- pages/table-fragments/grid-navigation-custom.page.tsx
- src/internal/context/__tests__/single-tab-stop-navigation-context.test.tsx
- src/internal/context/__tests__/utils.tsx
- src/internal/context/single-tab-stop-navigation-context.tsx
This reverts commit 42a9704842f2854c7fe3cbe1a31b6f08f9fa21ed.
Reverting because of observed exception in the table component.
<details> …
> revert: Nested STSN providers support (#3781)

- build-tools/utils/custom-css-properties.js
- pages/app-layout/styles.scss
- pages/app-layout/utils/external-global-left-panel-widget.tsx
- pages/app-layout/utils/external-sidecar-widget-demo.tsx
- src/app-layout/visual-refresh-toolbar/drawer/global-ai-drawer.tsx
- src/app-layout/visual-refresh-toolbar/drawer/styles.scss
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/styles.scss
This PR includes visual updates for the left global panel in accordance with the design bug bash (q`MzUMAouvFuAa`)
<details> …
> chore: Left drawer visual updates

- src/__tests__/snapshot-tests/__snapshots__/test-utils-selectors.test.tsx.snap
- src/button/icon-helper.tsx
- src/button/internal.tsx
- src/button/styles.scss
- src/test-utils/dom/button/index.ts
- src/test-utils/dom/toggle-button/index.ts
- src/toggle-button/internal.tsx
- src/toggle-button/test-classes/styles.scss
Previously, `findToggleButton` would also find button instances. This fixes that. (And vice-versa: `findButton` now finds no toggle buttons).
<details> …
> fix: Ensure toggle button test utils only find toggle buttons

- src/i18n/messages/all.ar.json
- src/i18n/messages/all.de.json
- src/i18n/messages/all.en-GB.json
- src/i18n/messages/all.en.json
- src/i18n/messages/all.es.json
- src/i18n/messages/all.fr.json
- src/i18n/messages/all.id.json
- src/i18n/messages/all.it.json
- src/i18n/messages/all.ja.json
- src/i18n/messages/all.ko.json
- src/i18n/messages/all.pt-BR.json
- src/i18n/messages/all.tr.json
- src/i18n/messages/all.zh-CN.json
- src/i18n/messages/all.zh-TW.json
Sync i18n messages, rename S3 Resource selectors labelBreadcrumbs property.
Related links, issue #, if available: `AWSUI-61048`
- reviewed EN and DE diff manually.
<details> …
> chore: Sync i18n messages, rename S3 Resource selectors labelBreadcrumbs property

- pages/app-layout/styles.scss
Removed a custom color from the `pages` to make it meet color contrast
<details>
- _If the …
> fix: AI panel title color

- src/internal/components/selectable-item/styles.scss
- src/select/parts/styles.scss
Some of the last few pixel changes I made got missed in my dev pipeline because they were getting compared with the larger select icon changes. Mostly me undoing whatever CSS I added/removed because I thought it wasn't important.
<details>
- …
> chore: Fix visual diffs caused by #3833

- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
Updated snapshots for this change: https://github.com/cloudscape-design/documenter/pull/90
PR build is expected to fail because the original PR is not released yet. 
I will restart the build when it is ready. But an early review and approval will save time
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md# …
> chore: Update documenter snapshots

- src/key-value-pairs/internal.tsx
Putting a popover inside a key meant that the dismiss button was nested inside the `<label>` of the key, and clicking on that counted as clicking on the button and the popover would just reopen. I don't think we need the label here; the `<dt>`/`<dd>` already creates a relationship between the key and the value, more isn't needed here.
Related links, issue #, if available: AWSUI-61213
Just a simple element change, relying on existing tests to not fail.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis) …
> fix: Allow interactive elements to be placed inside key of a key-value pair

- src/mixed-line-bar-chart/__tests__/mixed-chart.test.tsx
- src/mixed-line-bar-chart/hooks/use-popover.ts
The charts popover should not reopen immediately after it was unpinned and dismissed. The prev implementation did not checked for popover's prev state, which means that any call to dismissPopover() would result in the timeout reset. That affected our tests where we issue the Escape command and then navigate the popover immediately after.
* New unit test for Escape listener that secures regression
<details> …
> fix: Fixes mixed chart popover reopen in tests

- src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
- src/link/__tests__/index.test.tsx
- src/link/interfaces.ts
- src/link/internal.tsx
- src/toggle-button/__tests__/toggle-button.test.tsx
- src/toggle-button/index.tsx
- src/toggle-button/interfaces.ts
- src/toggle-button/internal.tsx
- src/toggle/__tests__/toggle.test.tsx
- src/toggle/interfaces.ts
- src/toggle/internal.tsx
Add native attributes support for link, toggle, toggle button
<details>
- _If the code …
> feat: Add native attributes support for link, toggle, toggle button

- src/table/internal.tsx
Fixing a regression after resize observer switch: https://github.com/cloudscape-design/component-toolkit/pull/154
* Locally
* Because the regression was only in Firefox, not testable in the integration tests. Screenshot tests capture it (that's how the issue was detected)
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/ …
> fix: Table scrollable detection

- pages/app-layout/runtime-drawers.page.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/styles.scss
This PR addresses a recent regression causes a new left drawer's trigger to reduce right triggers' container size. This PR sets the size of the container explicitly.
Ran screenshot tests in my dev pipeline - no diff.
<details> …
> fix: Drawers triggers size

- src/mixed-line-bar-chart/bar-groups.tsx
The PR fixes an issue reproducible in the latest Firefox version. The browser ignores SVG elements placement if the element has no color.
Before:
https://github.com/user-attachments/assets/1dedc4f9-d493-470e-b305-0e9286ba3b35
After:
https://github.com/user-attachments/assets/a298d72f-c04c-498b-9475-f65584bc8917
* This will be captured by existing screenshot tests
<details> …
> fix: Fixes bar chart popover placement in Firefox

- src/app-layout/__tests__/widget-old-mocks.ts
- src/app-layout/visual-refresh-toolbar/drawer/global-drawers.tsx
- src/app-layout/visual-refresh-toolbar/drawer/index.ts
- src/app-layout/visual-refresh-toolbar/drawer/local-drawer.tsx
- src/app-layout/visual-refresh-toolbar/internal.tsx
- src/app-layout/visual-refresh-toolbar/navigation/index.tsx
- src/app-layout/visual-refresh-toolbar/notifications/index.tsx
- src/app-layout/visual-refresh-toolbar/split-panel/index.tsx
- src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
Follow up for https://github.com/cloudscape-design/components/pull/3721
This code is not used anymore
PR build
<details> …
> chore: Remove unused app layout widget code

- pages/container-queries.page.tsx
- src/mixed-line-bar-chart/__tests__/mixed-chart.test.tsx
This is necessary for https://github.com/cloudscape-design/component-toolkit/pull/165.
JSDOM does not have access to actual element dimensions and returns 0 for everything. For this reason  in the mixed chart tests we are mocking  `window.getComputedStyle` to return 2px for border width among other things. But we are not mocking `HTMLElement.prototype.getBoundingClientRect`, so these tests still assume that all values are 0 for the values that this function returns. Then the changes in https://github.com/cloudscape-design/component-toolkit/pull/165 causes the calculated dimensions of the chart to be negative, because a non-zero border coming from `window.getComputedStyle` is subtracted from the zero width of the chart coming from `getBoundingClientRect` …
> chore: Mock getBoundingClientRect in mixed chart tests

- src/multiselect/__integ__/multiselect.test.ts
- src/select/utils/use-select.ts
Ensure that items aren't selected when typing a space after having hovered an item with the mouse
Related links, issue #, if available: AWSUI-61276
New integ tests
<details> …
> fix: Ensure hovered (multi)select items aren't selected when typing space

- pages/area-chart/partial.page.tsx
- pages/area-chart/series.ts
In area chart we support partial data, but for that the points must be explicitly provided with y=0. The new test page demonstrates that.
Rel: AWSUI-61312
<details> …
> chore: Additional test page for area chart

- pages/app-layout/utils/external-global-left-panel-widget.tsx
- src/app-layout/__tests__/runtime-drawers-widgetized.test.tsx
- src/app-layout/utils/use-ai-drawer.ts
- src/internal/plugins/widget/interfaces.ts
Added a methods to programmatically expand and collapse the AI panel 
```javascript
updateDrawer({ type: 'expandDrawer', payload: { id: 'drawer-id' } });
updateDrawer({ type: 'exitExpandedMode' });
```
<details> …
> feat: Add enter and exit focus mode methods to the plugin API

- src/app-layout/visual-refresh-toolbar/compute-layout.ts
Fixing a bug where ai drawer is stuck in max width before it is expected by design. 
It should resize all way up to 360px width remaining for the main content
Manually
<details> …
> fix: Allow ai drawer to have bigger max width

- src/app-layout/visual-refresh-toolbar/compute-layout.ts
This reverts commit 87a2493c28e2868de677c38d2a85e16bf6aa662e.
<details>
- _If the code …
> revert: Allow ai drawer to have bigger max width
