.github/ISSUE_TEMPLATE/1_bug_report.yaml
.github/ISSUE_TEMPLATE/2_feature_request.yaml
.github/ISSUE_TEMPLATE/3_documentation.yaml
.github/ISSUE_TEMPLATE/4_figma_bug_report.yaml
.github/ISSUE_TEMPLATE/5_figma_feature_request.yaml

fix: Fix issue templates format

---

.github/ISSUE_TEMPLATE/3_documentation.yaml
.github/ISSUE_TEMPLATE/4_figma_bug_report.yaml
.github/ISSUE_TEMPLATE/5_figma_feature_request.yaml

fix: Fix issue templates format for figma

---

.github/ISSUE_TEMPLATE/1_bug_report.yaml
.github/ISSUE_TEMPLATE/2_feature_request.yaml
.github/ISSUE_TEMPLATE/3_documentation.yaml
.github/ISSUE_TEMPLATE/4_figma_bug_report.yaml
.github/ISSUE_TEMPLATE/5_figma_feature_request.yaml
.github/ISSUE_TEMPLATE/config.yml

chore: Update links in issues templates

---

.github/workflows/build-lint-test.yml

The new CodeQL job in the build workflow (see https://github.com/cloudscape-design/.github/pull/5) needs additional permissions.
Tested with the documenter package first, see https://github.com/cloudscape-design/documenter/pull/11.
https://github.com/cloudscape-design/documenter/pull/11
<details>
</details>

chore: Update workflow permissions for codeql

---

README.md

*Issue #, if available:*
Fixes #81 
*Description of changes:*
Added a hyperlink to AWS in README.md

Added hyperlink to AWS in README.md

---

src/code-editor/__integ__/code-editor.test.ts

Accessing `.ace_content` only gives the content currently in view. The `textarea` does not contain full content either. Both solutions also rely on internals. Thereby, we use the official `getValue()` API
Existing test suites
<details>
</details>

test: Use ace API to access content

---

src/test-utils/dom/attribute-editor/index.ts

Change import in `<AttributeEditor />` to import individual wrapper instead of root path. Thereby, break circular dependency between root and individual components import. 
Not needed.
<details>
</details>

fix(test-utils): Import from component path

---

.github/PULL_REQUEST_TEMPLATE.md

The closing underscores for two of the review checklist has been missing. The affected list items are now italic as expected.
- Manually tested the changes.
N/A
<details>
</details>

docs(pr-template): Syntax fixes in PR template

---

pages/calendar/simple.page.tsx
src/date-picker/__integ__/date-picker.test.ts
src/date-picker/calendar/header/button/index.tsx
src/date-picker/calendar/header/index.tsx
src/date-picker/calendar/index.tsx
src/date-picker/index.tsx

Refactor date picker calendar by removing unneeded variable.
Existing tests -- no behaviour changes expected. Added an integration test to cover date selection.
<details>
</details>

Remove date-picker/calendar calendarHasFocus as unneeded

---

CONTRIBUTING.md

Adds missing links in the CONTRIBUTING.md file.
Rendered markdown at https://github.com/cloudscape-design/components/blob/e3df6324c8a1d382648cc2cb11170532659f479f/CONTRIBUTING.md
n/a
n/a
<details>
</details>

fix: Add links to website in CONTRIBUTING.md

---

src/date-range-picker/dropdown.tsx

Replaces use of tab trap component with a simpler Focus lock implementation
Existing tests
<details>
</details>

Use FocusLock instead of tab trap in date range picker

---

src/tabs/tab-header-bar.tsx

AWSUI-18908: parent element of ul in tablist changed to div from span

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/mixed-line-bar-chart/interfaces.ts

Add previously missing documentation about defining threshold series.
<details>
</details>

docs: Add details for threshold series type

---

pages/date-range-picker/calendar-permutations.page.tsx

Fix date-range-picker permutations for screenshots.
Original commit: https://github.com/cloudscape-design/components/pull/31/commits/37ccf1fbba7b194ec3ee5a914bbd02747aba2f90
<details>
</details>

Fix drp permutations for screenshots

---

src/breadcrumb-group/__tests__/breadcrumb-group.test.tsx
src/breadcrumb-group/internal.tsx
src/button-dropdown/interfaces.ts
src/button-dropdown/internal.tsx

dropdown button has aria-label

---

src/split-panel/index.tsx

split-panel toggle has aria-expanded

---

src/internal/styles/utils/theming.scss

This import is unused
PR build
Removing this opens a bigger opportunity of removing some code in the theming package: https://github.com/cloudscape-design/theming-core/pull/20
<details>
</details>

remove unused export

---

pages/button-dropdown/simple.page.tsx

Add padding to screenshot area

---

src/property-filter/token-editor.tsx

Refactored property filter token editor:
* Split EditorFields component into PropertyInput, OperatorInput and ValueInput
* Split temporaryToken/setTemporaryToken into propertyKey, operator and value
The refactoring was done in anticipation of custom properties, see: https://github.com/cloudscape-design/components/pull/166
Existing tests
<details>
</details>

Refactor property filter token editor

---

CONTRIBUTING.md

Self-explanatory. You need a `run` for tasks other than `start` or `test`.
It's a markdown change.
- I guess? It's a very tiny markdown change.
<details>
</details>

chore: Fix incorrect npm commands in CONTRIBUTING.md

---

package-lock.json
package.json

Removes unused package from dev dependencies. 
<details>
</details>

chore: Removed unused dependency

---

pages/property-filter/token-editor.page.tsx
src/select/parts/item.tsx
src/select/parts/styles.scss

Add screenshot test CR-75277877
- AWSUI-19165
<details>
</details>

Fix wrapped operation value in property filter

---

.github/workflows/release.yml

Follow up for this change: https://github.com/cloudscape-design/.github/pull/7
Add explicit configuration for subfolders to publish
Release job in my feature branch: https://github.com/cloudscape-design/components/runs/8155108876?check_suite_focus=true
<details>
</details>

update publish workflow

---

package.json

Our build could be 3.5 min faster if we remove this step. We already have `npm run build` step in all workflows:
* **build-lint-test** https://github.com/cloudscape-design/.github/blob/09b6dc80c5dbe6486149226da6bf6922c7ef3a13/.github/workflows/build-lint-test.yml#L28
* **dry-run** https://github.com/cloudscape-design/.github/blob/09b6dc80c5dbe6486149226da6bf6922c7ef3a13/.github/actions/build-package/action.yml#L56
* **release** https://github.com/cloudscape-design/.github/blob/09b6dc80c5dbe6486149226da6bf6922c7ef3a13/.github/workflows/release.yml#L50
<details>
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

remove double build run

---

src/property-filter/__tests__/controller.test.ts
src/property-filter/controller.ts
src/property-filter/interfaces.ts
src/property-filter/token-editor.tsx

Integrate with extended operator (see [commit](https://github.com/cloudscape-design/collection-hooks/commit/5726a4df8384d78bd77ef6c7fa036d8c439c744c#diff-2ee8da4ec0f3c043c7e097851af07383ae3ce13022973c8727312e06bf2b89b3R114)) and restructure token editor in preparation for custom forms (see https://github.com/cloudscape-design/components/pull/166).
Updated unit test to cover extended operator notation.
<details>
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

Update property filter types and token editor to prepare for custom forms

---

pages/property-filter/token-editor.page.tsx

Update property filter token editor test page to simplify integration with screenshot tests.
Screenshot tests
<details>
</details>

Update property filter token editor test page

---

src/input/internal.tsx

Reverts cloudscape-design/components#269

Revert "fix: Make spellCheck to false in input"

---

pages/property-filter/common-props.ts
pages/property-filter/table.data.ts
src/date-input/internal.tsx
src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/interfaces.ts
src/property-filter/styles.scss
src/property-filter/token.tsx

A set of small improvements for property-filter.
Screenshot tests for property filter token editor style change.
<details>
</details>

Minor improvements for property filter

---

src/date-range-picker/calendar/index.tsx
src/date-range-picker/styles.scss

Small styles refactoring for date range picker.
Screenshot tests
<details>
</details>

Use simpler grid layout for drp date-time wrapper

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/tag-editor/interfaces.tsx

Fix new prop added in a recent pr https://github.com/cloudscape-design/components/pull/202
<details>
</details>

Make errorIconAriaLabel optional

---

src/annotation-context/annotation/annotation-popover.tsx

The popover refactor messed up the background
Locally, plus screenshot tests.
<details>
</details>

fix(annotation-context): Fix incorrect background for popover

---

src/calendar/grid/day/index.tsx
src/calendar/internal.tsx
src/calendar/styles.scss
src/date-picker/__tests__/date-picker-calendar.test.tsx
src/date-range-picker/__integ__/page-objects/date-range-picker-page.ts
src/date-range-picker/styles.scss

A set of small code improvements noticed when working on https://github.com/cloudscape-design/components/pull/331.
No tests needed.
<details>
</details>

Minor refactoring for calendar styles

---

pages/header/permutations.page.tsx

Add permutations page in preparation for refactoring and new functionality.
<details>
</details>

test: Add Header permutations page

---

pages/date-range-picker/simple.page.tsx
src/date-range-picker/calendar/__tests__/calendar.test.tsx
src/date-range-picker/calendar/grids/grid.tsx
src/date-range-picker/calendar/index.tsx

AWSUI-19213
Removing role "none" and "button" from the table.
<details>
</details>

Drp calendar table markup

---

src/date-range-picker/calendar/index.tsx
src/date-range-picker/styles.scss

- Use form field internally to show constraint text.
- Simplify layout by removing unnecessary elements are removing dependency on date-only class.
Visual regression tests and screenshot tests.
<details>
</details>

Refactor date range picker layout

---

src/popover/internal.tsx
src/popover/styles.scss

Fixing a regression introduced here: https://github.com/cloudscape-design/components/pull/373/files?w=1#r997176846
Manual check.
<details>
</details>

Fix popover display styles

---

src/internal/utils/browser-scrollbar-size.ts

This was useful when we used `removeComments` config in typescript, but we do not do this anymore
Local build, checked that the important comment is preserved
<details>
</details>

remove workaround comment

---

pages/multiselect/screenshot.page.tsx
pages/select/screenshot.page.tsx

For CR-78454541
<details>
</details>

Add test id for select and multiselect

---

pages/app-layout/with-absolute-components.page.tsx

Follow up for this PR: https://github.com/cloudscape-design/components/pull/415
one more page got missing
Dry-run
<details>
</details>

add testid for select component

---

style-dictionary/visual-refresh/metadata/color-charts.ts

Expose new tokens on user request: AWSUI-19539
Build passes 
<details>
</details>

expose chart color tokens

---

.github/workflows/lint-pr.yml

Validate PR title in this repository by using [lint-pr](https://github.com/cloudscape-design/.github/blob/main/.github/workflows/lint-pr.yml) workflow  
In my forked repo
<details>
</details>

chore: use lint pr title workflow

---

src/flashbar/index.tsx

For some very technical reasons we cannot use "Cloudscape" in comments
Dry-run
<details>
</details>

chore: Fix documentation comment

---

src/tag-editor/internal.tsx

So, here's what's happening. React 18 has a [new strict mode](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state). Essentially, the big change is that when new components are added, they're (1) rendered, (2) destroyed, and (3) recreated, and only then are they added to the DOM. As with other strict mode quirks, this is to ensure components are more resilient against future changes. You can read more about their reasoning in the article.
But importantly, refs aren't recreated when the component is recreated, because refs are outside React's state by definition. This means that when the component is first destroyed (2), our cleanup effect runs, which cancels the fetcher and doesn't let another one start.
But do we need to clean up the in-progress fetch function at all? We …

fix: Fix tag editor key suggestions getting stuck in React 18's strict mode

---

src/internal/components/dropdown-status/index.tsx
src/select/utils/use-select.ts
src/tag-editor/__tests__/tag-editor-a11y.test.tsx

Remove unused code
Left over since https://github.com/cloudscape-design/components/pull/445
* Locally
* PR build
<details> …

chore: Remove unused code

---

pages/progress-bar/with-updates.page.tsx

Use cross platform typing: https://stackoverflow.com/questions/45802988/typescript-use-correct-version-of-settimeout-node-vs-window
PR build
<details> …

chore: Fix timeout type definitions

---

src/table/internal.tsx

Fix visual regression introduced in #522 
Locally …

fix: Fix border of last table cells when table has a footer

---

scripts/prepare-package-lock.js

chore: Fix check order of codeartifact in package-lock

---

src/internal/metrics.ts
src/internal/utils/__tests__/metrics.test.ts
src/wizard/internal/analytics.tsx

chore: Use correct custom event handler for metrics

---

src/internal/context/app-layout-context.ts

We do not mutate this object ever, so no point in creating a copy
PR build
<details>
- _If …

chore: remove unncessary spread

---

pages/top-navigation/utilities.page.tsx
src/button-dropdown/internal.tsx

Correct heading level provided for the menu dropdown in TopNavigation
Follow-up for [#539](https://github.com/cloudscape-design/components/pull/539)
Related links, issue #, if available:AWSUI-19250
Manually
<details> …

chore: Use correct heading tag in Top navigation menu dropdown

---

themes/icons/delete-marker.svg

Update of the delete marker icon
Locally …

chore: Update delete-marker icon

---

src/container/index.tsx
src/container/internal.tsx

Follow up fix of https://github.com/cloudscape-design/components/pull/663 to apply fix for internal & external use cases. 
<details> …

fix: Intenral container without content has incorrect border radius

---

src/flashbar/collapsible.scss

Before:
After:
- Manually tested (see screenshots)
- Visual regression tests are in place
<details> …

fix: Improve responsiveness of Flashbar notification bar

---

.github/workflows/build-lint-test.yml
.github/workflows/dry-run.yml

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
Well... let's merge it and see. Can't try merge queues in personal repos.
<details> …

chore: Run required workflows when a PR is added to the merge queue

---

.github/workflows/lint-pr.yml

See #739. It turns out Lint PR title was a required workflow as well, and I missed it.
<details> …

chore: Also run title lint check when PR is added to the merge queue

---

src/table/styles.scss

This is a follow-up to [this Pull Request](https://github.com/cloudscape-design/components/pull/710).
Safari doesn't fully support `fit-content`, so the Property Filter update was breaking it.
This PR adds a fall back to any browser that doesn't support `fit-content`, to use `auto` instead.
It also adds back the small amount of right margin, so that pagination and the search box don't touch when they run out of space.
Ran it through my pipeline and verified the changes fix the issues.
<details> …

fix: Fixes Property Filter wrapping on Safari

---

pages/wizard/navigation.page.tsx
src/wizard/__tests__/wizard.test.tsx
src/wizard/index.tsx
src/wizard/internal/analytics.tsx

chore: Emit metric when wizard is unmounted

---

pages/content-layout/with-header-toggles.page.tsx

Newly added integration test page (ref: CR-85603254) was missing screenshot area element.
<details> …

chore: Add Screenshot Area element to new content layout permutation page

---

src/internal/components/option/highlight-match.tsx
src/select/parts/item.tsx

revert: Un-revert "fix: Prevent filtering highlight from crashing with Google Translate"

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/date-input/interfaces.ts

Clarify the `value` format. Copied description from `DatePicker`.
Related links, issue #, if available: AWSUI-20523
N/A
<details>
- _If …

chore: Clarify date input value API description

---

src/internal/events/index.ts
src/tabs/__tests__/tabs.test.tsx
src/tabs/tab-header-bar.tsx

Self explanatory
Related links, issue #, if available: AWSUI-20587
Added an extra test
<details> …

fix: Do not switch tabs when modifier key is used

---

pages/file-upload/form-field-permutations.page.tsx
pages/file-upload/permutations.page.tsx
pages/file-upload/shared.tsx
pages/file-upload/simple.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/__tests__/form-field-controls-integration.test.tsx
src/__tests__/required-props-for-components.ts
src/file-upload/__tests__/file-upload-rendering.test.tsx
src/file-upload/file-option.tsx
src/file-upload/index.tsx
src/file-upload/interfaces.ts
src/file-upload/internal.tsx
src/file-upload/styles.scss
src/test-utils/dom/file-upload/index.ts
src/token-group/abstract-token-group.tsx

POC: File upload with editable names

---

pages/space-between/permutations.page.tsx
src/area-chart/internal.tsx
src/mixed-line-bar-chart/__tests__/mixed-chart.test.tsx
src/mixed-line-bar-chart/internal.tsx
src/pie-chart/__tests__/pie-chart.test.tsx
src/pie-chart/index.tsx
src/space-between/__tests__/space-between.test.tsx
src/space-between/internal.tsx
src/space-between/styles.scss
src/token-group/internal.tsx

This reverts commit d3bc9d025534c756f535ed7b2d8c6a552ec33dbe.
<details>
- _If the code …

revert: "fix: Remove spacing around null SpaceBetween children (#832)"

---

src/token-group/styles.scss

fix: Token group tokens height

---

src/tutorial-panel/__tests__/tutorial-panel.test.tsx
src/tutorial-panel/components/tutorial-detail-view/congratulation-screen.tsx
src/tutorial-panel/components/tutorial-detail-view/index.tsx
src/tutorial-panel/interfaces.ts

Closes https://github.com/cloudscape-design/components/issues/885
New unit test added.
<details> …

feat: Tutorial panel feedback can be optional

---

src/table/__integ__/table.test.ts
src/table/header-cell/styles.scss
src/table/resizer/styles.scss

This change updates the appearance of table column headers.
- Sorting icon is now vertically centered
- The vertical gap between lines is reduced by choosing a lower line-height. The overall layout is preserved by adding some padding
- Column separators now match the height of the text, instead of only filling the middle 50% of the row
Manual local testing
<details> …

chore: Update table column header appearance

---

pages/file-upload/permutations.page.tsx

Format date in file-upload permutations for consistency. 
<details> …

fix: Make file upload permutations stable

---

src/autosuggest/__tests__/virtual-scroll.test.tsx
src/select/__tests__/virtual-scroll.test.tsx

Improve test coverage for this feature
Related links, issue #, if available: originally added as a part of #969, but since the change was cancelled, extracted unit tests separately
This PR only adds tests
<details> …

chore: Add test coverage for virtual scroll mode

---

package.json

This should allow us to access more GitHub metrics, e.g. https://github.com/cloudscape-design/components/network/dependents
N/A
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/). …

chore: Align package.json name with our primary NPM package

---

package-lock.json

Follow-up from #1029 
N/A
<details> …

chore: Also update package name in package-lock

---

backstop.config.js

I had 5 consecutive green test runs with this change.
<details> …

chore: Add backstop delay to reduce VR tests flakiness

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/top-navigation/interfaces.ts

chore: Update logo prop docs in TopNavigation

---

style-dictionary/visual-refresh/metadata/colors.ts

This PR adds several new tokens to the public theme API in order to adjust the presentation of the `AppLayout`, `ContentLayout`, and `TopNavigation` components.
<details> …

feat: Addition of new public theme tokens.

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/top-navigation/interfaces.ts

This PR adds documentation for the properties that were added in https://github.com/cloudscape-design/components/pull/1042 . The description for these properties is aligned with the `onFollow` and `onItemFollow` properties in the Link component and the ButtonDropdown component.
n/a
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/ …

chore: Add missing documentation for `onFollow` and `onItemFollow`

---

src/app-layout/__tests__/context.test.tsx

Additional test, no specific reason
<details> …

chore: Add applayout contexts test

---

src/app-layout/__tests__/context.test.tsx
src/app-layout/index.tsx
src/app-layout/visual-refresh/context.tsx
src/container/__tests__/sticky-header.test.tsx
src/internal/context/app-layout-context.ts
src/split-panel/index.tsx

Removal of unused property
<details> …

chore: Remove unnecessary property from AppLayout context

---

pages/app-layout/with-wizard-and-table.page.tsx
pages/content-layout/with-absolute-components.page.tsx

Update for screenshot tests
<details> …

chore: Update dev pages for screenshot tests

---

style-dictionary/visual-refresh/metadata/colors.ts

#1146, #803 
<details>
- _Changes include appropriate documentation updates._ Yes
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._ Confirmed
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._ Confirmed …

feat: Make design tokens for normal buttons background public and themeable

---

src/alert/__tests__/alert.test.tsx
src/alert/internal.tsx
src/breadcrumb-group/__tests__/breadcrumb-item.test.tsx
src/breadcrumb-group/item/item.tsx
src/container/__tests__/analytics.test.tsx
src/flashbar/__tests__/flashbar.test.tsx
src/flashbar/flash.tsx
src/form-field/__tests__/form-field-analytics.test.tsx
src/form-field/internal.tsx
src/form/__tests__/analytics.test.tsx
src/header/__tests__/header.test.tsx
src/header/internal.tsx
src/internal/analytics/__tests__/components/analytics-funnel.test.tsx
src/internal/analytics/__tests__/hooks/use-funnel-sub-step.test.tsx
src/internal/analytics/__tests__/hooks/use-funnel.test.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/hooks/use-funnel.ts
src/internal/analytics/interfaces.ts
src/internal/analytics/selectors.ts
src/link/internal.tsx
src/wizard/__tests__/analytics.test.tsx

- Move all data attributes to constants to be better reused
- Fixed funnelSuccessful being called at incorrect time
- Realign componentTheme property to theme
- Updated relevant unit tests
<details> …

chore: Analytics fixes

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/column-layout/interfaces.ts

Simplified the description of the `columns` property in Column layout. Follow-up from https://github.com/cloudscape-design/components/pull/1123#discussion_r1219353227
<details> …

chore: Update documentation for `columns` in Column Layout

---

pages/onboarding/with-app-layout.page.tsx

App layout takes the full screen width, so for realistic screenshot tests we should not render the gutter
Locally, looks good after the change
<details> …

chore: remove unwanted gutters on onboarding dev page

---

pages/container/media.page.tsx

Adjust screenshot area to not include settings in the media page.
<details> …

chore: Fix ScreenshotArea in media page

---

build-tools/tasks/styles.js
src/__tests__/__snapshots__/design-tokens.test.ts.snap
src/__tests__/design-tokens.test.ts
src/__tests__/utils.tsx

- Provides descriptions for design tokens by using the new API introduced in https://github.com/cloudscape-design/theming-core/commit/3e97baae2321c4fa699bb1f4fdee0cebdbdcc664
- Add unit tests to ensure that this artifacts exist and have the right file name.
Local build
The dry-run should be enough due to added tests
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components …

feat: Add descriptions and tests for design tokens in JSON format

---

src/__tests__/__snapshots__/design-tokens.test.ts.snap
style-dictionary/visual-refresh/metadata/colors.ts

Align descriptions copy to other color tokens.
<details>
- _Changes include appropriate documentation updates._ Yes …

fix: Design tokens descriptions discrepancies

---

src/__tests__/__snapshots__/design-tokens.test.ts.snap
style-dictionary/visual-refresh/metadata/spacing.ts

Update design token descriptions to better reflect the changes made in #1318, so they display accurately on the [website](https://cloudscape.design/foundation/visual-foundation/design-tokens/#tokens).
Ran tests locally
<details> …

chore: Update VR spacing design token descriptions

---

.github/workflows/bundle-size.yml

chore: Fix for a bug in the bundle size workflow

---

package-lock.json

Updating package.lock to fix the dry-run here: https://github.com/cloudscape-design/components/pull/1348
<details>
- _If the code …

chore: Update package.lock

---

build-tools/tasks/generate-environment.js

We modify this file when applying themes. With JSON version of this, it would be easier propagate unchanged values to the modified file
Locally. The file is there and looks good
<details> …

chore: Generate JSON version of the environment file

---

src/app-layout/drawer/__tests__/drawers-helpers.test.ts
src/app-layout/drawer/drawers-helpers.ts
src/app-layout/drawer/index.tsx
src/app-layout/drawer/interfaces.ts
src/app-layout/drawer/overflow-menu.tsx
src/app-layout/drawer/styles.scss
src/app-layout/index.tsx
src/app-layout/mobile-toolbar/index.tsx
src/app-layout/visual-refresh/context.tsx
src/app-layout/visual-refresh/drawers.tsx

fix: Refactor drawers overflow

---

src/area-chart/model/use-chart-model.ts
src/internal/components/chart-popover/index.tsx
src/internal/utils/__tests__/dom.test.ts
src/internal/utils/dom.ts
src/mixed-line-bar-chart/hooks/use-mouse-hover.ts
src/pie-chart/pie-chart.tsx
src/popover/container.tsx

Remove the copy of the util which is already available inside the toolkit package
PR build. 
There should not be any behavior differences because the code is the same in both
<details> …

refactor: Use nodeContains from the shared package

---

src/mixed-line-bar-chart/bar-series.tsx

A follow-up fix for https://github.com/cloudscape-design/components/pull/1458. The bars are made slightly narrower (by 1 px). To compensate for the reduced width/height the bars need to be moved by 1 / 2 px, not 1 px. Also updated offsets to avoid half-pixels.
Before:
After:
<details>
- …

fix: Bar chart bars alignment

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/icon/interfaces.ts
themes/icons/anchor-link.svg

Expose an icon for linking to a specific content element on a page
Related links, issue #, if available: -
-
<details>
- _If the code …

feat: Add anchor link icon

---

src/internal/analytics/__tests__/components/analytics-funnel.test.tsx
src/internal/analytics/components/analytics-funnel.tsx

chore: Rename creation edit flow event name

---

src/app-layout/drawer/__tests__/drawers-helpers.test.ts
src/app-layout/drawer/drawers-helpers.ts
src/app-layout/mobile-toolbar/index.tsx
src/app-layout/visual-refresh/drawers.tsx

This code is unused and can be removed
<details> …

refactor: Remove unused code from splitItems utility

---

src/app-layout/__integ__/app-layout-drawers.test.ts
src/app-layout/__tests__/desktop.test.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/__tests__/utils.tsx

Improve test coverage
This is test only PR
<details> …

chore: Add more tests on drawers

---

src/i18n/messages-types.ts
src/i18n/messages/all.de.json
src/i18n/messages/all.en-GB.json
src/i18n/messages/all.en.json
src/i18n/messages/all.es.json
src/i18n/messages/all.fr.json
src/i18n/messages/all.id.json
src/i18n/messages/all.it.json
src/i18n/messages/all.ja.json
src/i18n/messages/all.ko.json
src/i18n/messages/all.pt-BR.json
src/i18n/messages/all.tr.json
src/i18n/messages/all.zh-CN.json
src/i18n/messages/all.zh-TW.json

Updated i18n messages to support the upcoming changes.
<details> …

chore: Update i18n messages

---

pages/table-fragments/grid-navigation-performance.page.tsx
pages/table-fragments/styles.scss
src/table/table-role/__tests__/use-grid-navigation.test.tsx
src/table/table-role/use-grid-navigation.ts
src/table/table-role/utils.ts

Added test page to assert tree navigation performance. Removed the unnecessary computations.
<details> …

refactor: Tree grid performance

---

src/app-layout/__tests__/desktop.test.tsx
src/app-layout/__tests__/main.test.tsx
src/app-layout/__tests__/utils.tsx
src/app-layout/index.tsx
src/app-layout/styles.scss

Simplify our markup a bit
* PR build
<details> …

refactor: Remove unnecessary wrapper in app layout

---

src/i18n/messages-types.ts
src/i18n/messages/all.de.json
src/i18n/messages/all.en-GB.json
src/i18n/messages/all.en.json
src/i18n/messages/all.es.json
src/i18n/messages/all.fr.json
src/i18n/messages/all.id.json
src/i18n/messages/all.it.json
src/i18n/messages/all.ja.json
src/i18n/messages/all.ko.json
src/i18n/messages/all.pt-BR.json
src/i18n/messages/all.tr.json
src/i18n/messages/all.zh-CN.json
src/i18n/messages/all.zh-TW.json

Updates the latest messages from the `AWS-UI-Components-I18n ` package. Followed the instructions and ran `npm run build` in that package and copied over the outputs to here.
<details> …

chore: Updates latest i18n messages

---

.github/workflows/bundle-size.yml

Upgrade `actions/github-script` now that it's been released with NodeJS 20 support: https://github.com/actions/github-script/issues/421.
<details> …

chore: Upgrade actions/github-script to v7

---

src/button/__integ__/performance-marks.test.ts
src/internal/hooks/use-performance-marks.ts
src/table/__integ__/performance-marks.test.ts

chore: Replace 'cloudscape' string with 'awsui'

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/mixed-line-bar-chart/interfaces.ts

Small follow-up with minor changes after more feedback and discussion with content design.
<details> …

chore: Fine tune API doc description for `detailPopoverSeriesContent`

---

src/internal/analytics/__tests__/hooks/use-funnel-step.test.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/context/analytics-context.ts
src/internal/analytics/hooks/use-funnel.ts

The refactoring is made to prevent issues similar to one occurred recently in table resizable columns: https://github.com/cloudscape-design/components/pull/1745#discussion_r1398860225
The PR covers part of the codebase, related PRs: https://github.com/cloudscape-design/components/pull/1801, https://github.com/cloudscape-design/components/pull/1806, https://github.com/cloudscape-design/components/pull/1807.
<details> …

refactor: Replace records having numeric keys with maps, part 4

---

src/select/__integ__/async-select.test.ts

test: Async select tests in VR and Classic

---

src/table/table-role/__tests__/grid-navigation.test.tsx
src/table/table-role/__tests__/stubs.tsx

Refactored grid navigation unit test to remove dependency on implementation detail and support https://github.com/cloudscape-design/components/pull/1856
<details> …

refactor: Improve grid nav unit tests

---

pages/onboarding/tutorials.tsx

Restore steps removed in https://github.com/cloudscape-design/components/pull/1850
They are actually in use in the page onboarding/with-app-layout
<details> …

chore: Restore removed steps

---

src/column-layout/grid-column-layout.tsx
src/flashbar/collapsible-flashbar.tsx
src/internal/animate.ts
src/mixed-line-bar-chart/__tests__/utils.test.ts
src/mixed-line-bar-chart/bar-series.tsx
src/mixed-line-bar-chart/utils.ts
src/table/sticky-columns/__tests__/use-sticky-columns.test.tsx
src/table/sticky-columns/interfaces.ts
src/table/sticky-columns/use-sticky-columns.ts
src/table/sticky-columns/utils.ts

Reintroduce https://github.com/cloudscape-design/components/pull/1801 after revert (https://github.com/cloudscape-design/components/pull/1826).
Screenshot tests.
<details> …

refactor: Replace records having numeric keys with maps, part 1 (#2)

---

.github/workflows/visuals.yml

Fix incorrect report link from #1868
The link works now: TODO
<details>
- _If the code …

chore: Fix visual regression tests report link

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/app-layout/interfaces.ts

fix: Fix a typo in app layout api documentation

---

src/internal/analytics/__integ__/static-single-page-flow.test.ts

Without await, this assertion does not work
PR build 
<details> …

chore: Add missing await in a test

---

src/calendar/__tests__/calendar.test.tsx

Addressing a gap in calendar tests: the date states (current, selected, disabled) were not tested.
<details> …

test: Add unit tests for calendar date states

---

backstop.config.js

Skipping this, because they are flaky
<details> …

chore: Skip pie-chart permutation screenshots

---

pages/app-layout/with-cards.page.tsx
src/app-layout/visual-refresh/mobile-toolbar.scss
src/app-layout/visual-refresh/mobile-toolbar.tsx
src/app-layout/visual-refresh/trigger-button.scss
src/app-layout/visual-refresh/trigger-button.tsx
src/cards/index.tsx
src/cards/styles.scss
src/container/internal.tsx
src/container/styles.scss
src/internal/utils/content-header-utils.ts
src/wizard/internal.tsx
src/wizard/styles.scss
src/wizard/wizard-form-header.tsx
src/wizard/wizard-navigation.tsx

Implement design optimizations for high contrast header removal from VR.
<details>
- _If the …

chore: optimization high contrast header removal

---

src/cards/index.tsx
src/cards/styles.scss

fix: update style condition to make the style adjustment happen only for full-page card

---

.stylelintrc
src/pagination/styles.scss
src/pie-chart/styles.scss
src/popover/arrow.scss
src/popover/body.scss
src/popover/container.scss
src/popover/styles.scss
src/progress-bar/styles.scss
src/property-filter/styles.scss
src/radio-group/styles.scss
src/s3-resource-selector/s3-in-context/styles.scss
src/segmented-control/segment.scss
src/select/parts/styles.scss
src/side-navigation/styles.scss
src/spinner/mixins.scss
src/spinner/styles.scss
src/split-panel/styles.scss
src/status-indicator/styles.scss

This PR is a subset of the changes drafted in https://github.com/cloudscape-design/components/pull/1713 that affect only the subset of components that being with the letters "N/O/P/Q/R/S".

chore: Migrate "N/O/P/Q/R/S" components to logical properties

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/expandable-section/interfaces.ts
src/header/interfaces.ts

Addressing frequent confusion from our consumers
Doc changes only
<details>
- _If the code …

chore: Update documentation for headingTagOverride props

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/app-layout/index.tsx
src/container/index.tsx
src/flashbar/common.tsx
src/internal/hooks/use-base-component/__tests__/use-base-component.test.tsx
src/internal/hooks/use-base-component/index.ts
src/internal/hooks/use-telemetry/index.ts
src/table/index.tsx

Report usage metrics for props: Vg2OAA5ArJn8
Updated related unit tests
<details>
- _If the …

chore: Introduce props reporting in telemetry

---

src/table/__tests__/resizable-columns.test.tsx

Replace internal path with its public equivalent.
PR build 
<details> …

chore: Fix import path

---

src/table/index.tsx

Added table's `enableKeyboardNavigation` prop to metrics.
<details> …

chore: Add keyboard navigation to table metrics

---

package.json

Unit tests expect the machine running them to be in UTC, with some tests generating `new Date()` and asserting on it. Jest doesn't have an easy config for this, so the two options are:
1. Set the time zone for Node at the script level.
2. Update every test using dates to rely on [Jest's timer mocks](https://jestjs.io/docs/timer-mocks), specifically `jest.setSystemTime()`.
Option 1 can be an easy temporary solution as it's just a couple lines, but long term I think option 2 is better practice.
Note that this is also a quick PR to test my permissions for the automated verification on the repo, as suggested by @timogasda.
Ran `npm run test:unit` before the change on a non-UTC machine, and confirmed 6 date-related tests were failing:
<details> …

chore: run unit tests in UTC

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/app-layout/interfaces.ts

Calling out an important corner-case
n/a, doc only change
<details> …

chore: Update drawers API description

---

build-tools/tasks/styles.js

Cleaning up our public API
PR build
<details> …

chore: Use internal import for internal theming build

---

src/anchor-navigation/internal.tsx
src/box/layout.scss
src/box/spacing.scss
src/column-layout/styles.scss
src/expandable-section/styles.scss
src/link/styles.scss
src/select/parts/styles.scss
src/toggle/styles.scss

This PR adds RTL support for a list of components categorized as having a small implementation effort.

chore: Add RTL support for small components

---

.github/workflows/build-lint-test.yml

chore: Run git-secrets in GitHub Actions

---

.github/workflows/release.yml

After this https://github.com/cloudscape-design/actions/pull/30 we can switch over to using the new release flow as we no longer need to worry about publishing individual packages.
Tested in my dev branch: https://github.com/cloudscape-design/components/actions/runs/8404439160
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/ …

chore: Use new release flow

---

src/table/index.tsx

A follow-up to https://github.com/cloudscape-design/components/pull/2000
<details>
- _If the …

chore: Add table expandable rows to metrics

---

src/table/body-cell/styles.scss
src/table/expandable-rows/styles.scss
src/table/header-cell/styles.scss

The refactoring is a prerequisite for https://github.com/cloudscape-design/components/pull/2070
Rel: AWSUI-36760
Screenshot tests, manual tests
<details> …

refactor: Refactor table cell focus outline styles

---

pages/table/inline-actions.page.tsx
src/button-dropdown/internal.tsx
src/table/__integ__/inline-actions.test.ts
src/table/table-role/grid-navigation.tsx
src/table/table-role/utils.ts

There is an issue reproducible in Chrome for table sticky columns: when an interactive element inside a sticky column receives focus the table container scrolls so that the column becomes in view as no longer sticky.
Scenarios:
* A button inside a sticky column is clicked - no issue here;
- no Fix needed.
* Any focusable element inside a sticky column is navigated to with Tab / Shift + Tab - the scroll issue happens;
- Not fixed. The keyboard focus is taken care of by the browser so no easy way to fix and no strong justification either.
* A button dropdown option is selected - the scroll issue happens;
- Fixed by preventing scroll when moving focus back to the button dropdown trigger.
* In table with keyboard navigation a cell inside a sticky column is clicked - the scroll issue happens; …

fix: Table inline actions in sticky column to cause no horizontal scroll

---

pages/date-picker/positioning.page.tsx
pages/top-navigation/logos/long-logo.svg
pages/top-navigation/logos/narrow-logo.svg
src/calendar/grid/index.tsx
src/calendar/grid/use-calendar-grid-keyboard-navigation.ts
src/date-range-picker/__tests__/date-range-picker-absolute.test.tsx
src/date-range-picker/calendar/grids/grid.tsx
src/date-range-picker/calendar/grids/index.tsx
src/date-range-picker/calendar/grids/styles.scss
src/internal/direction.ts
src/internal/utils/handle-key-down.ts
src/internal/utils/handle-key.ts
src/segmented-control/__tests__/desktop.test.tsx
src/segmented-control/internal-segmented-control.tsx
src/tabs/__tests__/scroll-utils.test.tsx
src/tabs/__tests__/tabs.test.tsx
src/tabs/scroll-utils.ts
src/tabs/tab-header-bar.tsx

This PR adds RTL support for a list of components categorized as having a medium implementation effort.

chore: Add RTL support for medium components.

---

src/table/body-cell/index.tsx
src/table/body-cell/td-element.tsx
src/table/expandable-rows/expand-toggle-button.tsx
src/table/expandable-rows/expandable-rows-utils.ts
src/table/internal.tsx
src/table/table-role/__tests__/table-role-helper.test.ts
src/table/table-role/table-role-helper.ts

Updated internal table APIs to support upcoming change https://github.com/cloudscape-design/components/pull/2108.
<details>
- _If the …

refactor: Table expandable item props internal api rework

---

src/internal/utils/handle-key.ts

Allow this util to accept both native `KeyboardEvent` and `React.KeyboardEvent` leveraging structural typing
PR build 
<details> …

refactor: Relax handleKey argument types

---

src/app-layout/index.tsx

Add additional data to telemetry to better understand our use-cases
PR build
<details>
- _If …

chore: Add extra metadata to app layout props reporting

---

src/internal/components/dropdown/index.tsx
src/internal/components/dropdown/styles.scss

Current treatment of borders, introduced in [refactoring](https://github.com/cloudscape-design/components/pull/1961), removes all block borders for the dropdown _content wrappers_. Instead we have shadows (existed before) and special borders in VR. 
It didn't cause any issues for most of the components. However, in _classic_ components with selectable lists now rely on list items' borders to have both block borders.
This change unifies treatment of borders for selectable list items.
Related links, issue #, if available: AWSUI-36083
Before:
After:
- Checked in dev pipeline
- verified with designer
- new screenshots tests will be added
- can check in a dev page: https://d21d5uik3ws71m.cloudfront.net/components/a92e043490b1b66593dd5447f71370f454e38df3/dev-pages/index.html#/light/dropdown/expa …

fix: Show select dropdown border with expandToViewport

---

src/table/internal.tsx

Remove direct DOM manipulations
PR build + locally
<details> …

chore: Use container query for table header

---

src/internal/__tests__/animate.test.ts

Add extra tests to make linter upgrade PR #2200 pass the coverage bar
PR build
<details>
- …

chore: Add missing coverage

---

src/app-layout/visual-refresh/header.tsx
src/app-layout/visual-refresh/universal-toolbar.scss
src/app-layout/visual-refresh/universal-toolbar.tsx

fix: toolbar overflow

---

src/modal/body-scroll.ts

Add a comment to internal modal utils to highlight AWSUI-41915.
<details> …

chore: Add comment to modal body scrolling

---

src/area-chart/__tests__/area-chart-model-utils.test.ts
src/area-chart/model/compute-chart-props.ts
src/mixed-line-bar-chart/__tests__/use-navigation.test.tsx
src/mixed-line-bar-chart/chart-container.tsx
src/mixed-line-bar-chart/hooks/use-navigation.ts

This PR adds RTL support for the `Mixed Line and bar chart` component.

chore: Add RTL support for the Mixed Line and bar chart component.

---

src/icon/styles.scss

This PR adds the resize area icon to the list that needs to be inverted in RTL.

chore: Invert resize area Icon in RTL.

---

src/flashbar/__tests__/dismiss.test.tsx

Add Flashbar unit test requiring disableMotion.
Rel: AWSUI-42546
<details> …

chore: Add new unit test to Flashbar highlighting need to disable motion 

---

src/header/styles.scss

This PR removes an unnecessary conditional change to the header display property.

chore: Remove header conditional display property in rtl.

---

src/form-field/styles.scss
src/link/styles.scss

This PR removes an unnecessary conditional change to the link display property.

chore: Remove link conditional display property in rtl.

---

pages/app-layout/with-full-page-table-and-split-panel.page.tsx
src/app-layout/__integ__/app-layout-sticky-elements.test.ts
src/app-layout/constants.scss
src/app-layout/drawer/styles.scss
src/app-layout/split-panel/styles.scss

Fix AWSUI-43021
* Added extra tests
<details> …

fix: Unify z-index for tools and split panels in app layout

---

pages/button/performance-marks-in-modal.page.tsx

This PR adds a missing property in a dev page. The property is required to pass the a11y tests.
<details> …

chore: Add missing property in dev page

---

src/wizard/internal.tsx
src/wizard/styles.scss
src/wizard/wizard-form-header.tsx
src/wizard/wizard-navigation.tsx

Part of high-contrast header removal
Locally
<details> …

feat: Remove high-contrast header in wizard

---

src/app-layout/skeleton/index.tsx
src/app-layout/skeleton/layout.tsx
src/app-layout/skeleton/styles.scss

Follow up for https://github.com/cloudscape-design/components/pull/2276, adding mobile view support
Locally using existing dev page
<details> …

chore: Mobile view support for skeleton app layout

---

src/app-layout/skeleton/styles.scss

Fixing feature parity between app layout and its skeleton sub-part
Locally. Not visible on screenshot tests yet, because [my skeleton dev page](https://github.com/cloudscape-design/components/blob/main/pages/app-layout/skeleton.page.tsx) is still work in progress. 
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIB …

chore: Fix transparent background color for app layout skeleton

---

src/app-layout/__tests__/widgetized-layout.test.tsx
src/app-layout/internal.tsx
src/app-layout/widget.tsx
src/split-panel/__tests__/widgetized-panel.test.tsx
src/split-panel/internal.tsx
src/split-panel/widget.tsx

Address previous PR comment: https://github.com/cloudscape-design/components/pull/2277#discussion_r1610459082
Remove unused files, make code navigation simpler. 
PR build passes, which ensures we do not depend on this import anywhere
<details>
- …

chore: Remove unused files

---

pages/app/app-context.tsx
pages/app/index.tsx
src/internal/utils/content-header-utils.ts
src/internal/utils/global-flags.ts

chore: Remove removeHighContrastHeader global flag

---

src/table/table-role/utils.ts

Remove mention of cloudscape due to internal checks.
<details> …

chore: Remove reference to cloudscape in code

---

src/wizard/wizard-form-header.tsx

No longer needed after the removal of high-contrast header
<details> …

chore: Remove dynamic overlap hook from wizard

---

src/wizard/internal.tsx
src/wizard/styles.scss

chore: Remove unnecessary styles in wizard

---

pages/app/index.tsx
pages/container/sticky-permutations.page.tsx

feat: Add new dev page for future screenshot tests

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/internal/base-component/index.ts

Addressing frequent confusion about this property. We deprecated it in general, not only for styling
PR build
<details> …

chore: Update id prop documentation text

---

src/app-layout/drawer/index.tsx
src/app-layout/mobile-toolbar/index.tsx
src/app-layout/visual-refresh/drawers.tsx
src/app-layout/visual-refresh/navigation.tsx
src/app-layout/visual-refresh/tools.tsx
src/app-layout/visual-refresh/trigger-button.tsx
src/button-dropdown/category-elements/category-element.tsx
src/button-dropdown/category-elements/mobile-expandable-category-element.tsx
src/button-dropdown/mobile-expandable-group/mobile-expandable-group.tsx
src/content-layout/internal.tsx
src/drawer/implementation.tsx
src/help-panel/implementation.tsx
src/internal/components/cartesian-chart/inline-start-labels.tsx
src/internal/components/option/highlight-match.tsx
src/internal/components/option/index.tsx
src/slider/__tests__/slider.test.tsx
src/slider/internal.tsx
src/slider/slider-labels.tsx
src/slider/tick-marks.tsx
src/split-panel/side.tsx
src/table/internal.tsx
src/table/selection/selection-control.tsx
src/token-group/dismiss-button.tsx
src/wizard/wizard-form-header.tsx
src/wizard/wizard-form.tsx
src/wizard/wizard-navigation.tsx

Why not
dev pipeline
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._N/A …

chore: Remove unnecessary usage of clsx utility for classNames

---

src/app-layout/visual-refresh/background.scss
src/app-layout/visual-refresh/drawers.scss
src/app-layout/visual-refresh/layout.scss
src/app-layout/visual-refresh/navigation.scss
src/app-layout/visual-refresh/split-panel.scss
src/app-layout/visual-refresh/tools.scss
src/internal/generated/custom-css-properties/list.js

No longer needed after https://github.com/cloudscape-design/components/commit/2c26d4dcde4b0e4bd6a03d5c289c4daa8fa9c3b8
dev pipeline
<details> …

chore: Remove notificationsGap from app layout grid

---

src/date-range-picker/index.tsx

This change adds the date range picker's `hideTimeOffset` property to the component metrics.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibi …

chore: Add property metrics for data range picker's `hideTimeOffset`

---

src/button-group/icon-button-item.tsx
src/button-group/internal.tsx
src/button-group/menu-dropdown-item.tsx
src/button-group/styles.scss

* Improved spacing between items and size and color of the divider
* Made tooltips also show on focus
Rel: mQ5BAuVbAg6J
<details>
- _If …

chore: Button group styling

---

src/annotation-context/__tests__/annotation-context.test.tsx
src/app-layout/__tests__/common.test.tsx
src/app-layout/__tests__/desktop.test.tsx
src/app-layout/__tests__/mobile.test.tsx
src/area-chart/__tests__/area-chart-use-chart-model.test.tsx

Remove not needed code
<details> …

chore: remove redundant act from unit tests in a* components

---

pages/button-group/permutations.page.tsx
pages/button-group/test.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/area-chart/__tests__/area-chart-model-utils.test.ts
src/area-chart/model/use-chart-model.ts
src/area-chart/model/utils.ts
src/button-group/interfaces.ts
src/button-group/internal.tsx
src/internal/utils/__tests__/circle-index.test.ts
src/internal/utils/circle-index.ts
src/tabs/tab-header-bar.tsx

chore: Button group employs toolbar role and uses keyboard navigation

---

.github/workflows/release.yml

A single `*` character does not allow slashes in the match. To match a branch name containing slashes we should use `**`
Related docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
This setup will allow to have better organized branches, such as `dev-v3-my-name/feature-name`
* See this PR – release works
* See another PR https://github.com/cloudscape-design/components/pull/2419 – no release there
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#p …

chore: Allow release workflow for dev branch with slashes

---

pages/table/expandable-rows-performance.page.tsx

A new test page to ensure the expandable rows feature when enabled does not impact table's performance.
<details>
- _If the code …

chore: Table with expandable rows performance page

---

src/table/index.tsx

chore: Metrics for table progressive loading

---

src/i18n/messages-types.ts
src/i18n/messages/all.ar.json
src/i18n/messages/all.de.json
src/i18n/messages/all.en-GB.json
src/i18n/messages/all.en.json
src/i18n/messages/all.es.json
src/i18n/messages/all.fr.json
src/i18n/messages/all.id.json
src/i18n/messages/all.it.json
src/i18n/messages/all.ja.json
src/i18n/messages/all.ko.json
src/i18n/messages/all.pt-BR.json
src/i18n/messages/all.tr.json
src/i18n/messages/all.zh-CN.json
src/i18n/messages/all.zh-TW.json

This PR adds Arabic translations to the i18n directory as well other build output.

chore: Add build output from components i18n repo

---

pages/app/index.tsx
pages/copy-to-clipboard/scenario-split-panel.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/copy-to-clipboard/__tests__/copy-to-clipboard.test.tsx
src/copy-to-clipboard/index.tsx
src/copy-to-clipboard/interfaces.ts
src/copy-to-clipboard/internal.tsx
src/test-utils/dom/copy-to-clipboard/index.ts

The`CopyToClipboard` component utilizes the `Popover` component's `renderWithPortal` API ([link to API docs](https://cloudscape.design/components/popover/?tabId=api)), rendering the popover in the root stacking context using a Portal.
Before this change, `CopyToClipboard` forced this behavior ([link to source](https://github.com/cloudscape-design/components/blob/1dcf65791464d1c3ed0e0058de49c0f5953e7f23/src/copy-to-clipboard/internal.tsx#L67C1-L68C1)), causing issues like incorrect popover placement within split panels with scrollable content. See screen recording:
https://github.com/cloudscape-design/components/assets/569011/e90b46b0-12a6-4807-8505-9cf2f2743961
A new `popoverRenderWithPortal` property, mirroring Popover's `renderWithPortal`, lets developers control stacking context …

chore: Add popoverRenderWithPortal API to CopyToClipboard component

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/key-value-pairs/__tests__/key-value-pairs.test.tsx
src/key-value-pairs/index.tsx
src/key-value-pairs/interfaces.ts
src/key-value-pairs/internal.tsx

chore: Add ariaLabel and ariaLabelledby props to KVP component

---

src/button-group/__integ__/button-group.test.ts
src/button-group/icon-button-item.tsx
src/button-group/internal.tsx
src/button-group/item-element.tsx

fix: Fix issues and make tests green

---

pages/app-layout/multi-layout-iframe.page.tsx
pages/app-layout/multi-layout-simple.page.tsx
pages/app-layout/utils/iframe-wrapper.scss
pages/app-layout/utils/iframe-wrapper.tsx
src/__a11y__/a11y-page-object.ts
src/app-layout/__integ__/multi-app-layout.test.ts
src/app-layout/utils/use-app-layout-placement.ts
src/app-layout/utils/use-observed-element.ts

Add demo pages and tests for multi app layout use-case
<details> …

chore: Add iframe dev pages

---

src/__a11y__/a11y-page-object.ts

Noticed recently that this file has a bunch of old things that aren't needed anymore.
The tests are more sensitive. If there are no false positives, we're good.
<details> …

chore: Remove unnecessary exceptions in a11y testing suite

---

pages/app-layout/utils/iframe-wrapper.tsx
src/__a11y__/a11y-page-object.ts

Fix iframe demo page, currently it does not render correctly in Firefox, because of this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=543435
Manually
<details> …

chore: Fix iframe demo page

---

src/container/__tests__/analytics-metadata.test.tsx
src/container/analytics-metadata/interfaces.ts
src/container/analytics-metadata/styles.scss
src/container/index.tsx
src/container/internal.tsx
src/form/__tests__/analytics-metadata.test.tsx
src/form/analytics-metadata/interfaces.ts
src/form/analytics-metadata/styles.scss
src/form/index.tsx
src/form/internal.tsx
src/header/analytics-metadata/styles.scss
src/header/internal.tsx
src/internal/__tests__/analytics-metadata-test-utils.ts

feat: Add analytics metadata to Container and Form

---

src/i18n/messages-types.ts
src/i18n/messages/all.ar.json
src/i18n/messages/all.de.json
src/i18n/messages/all.en-GB.json
src/i18n/messages/all.en.json
src/i18n/messages/all.es.json
src/i18n/messages/all.fr.json
src/i18n/messages/all.id.json
src/i18n/messages/all.it.json
src/i18n/messages/all.ja.json
src/i18n/messages/all.ko.json
src/i18n/messages/all.pt-BR.json
src/i18n/messages/all.tr.json
src/i18n/messages/all.zh-CN.json
src/i18n/messages/all.zh-TW.json

Syncs the translation resources.
<details> …

chore: Syncs translations

---

src/link/__tests__/analytics-metadata.test.tsx
src/link/analytics-metadata/interfaces.ts
src/link/index.tsx

feat: Add analytics metadata to Link

---

src/checkbox/__tests__/analytics-metadata.test.tsx
src/checkbox/analytics-metadata/interfaces.ts
src/checkbox/index.tsx
src/checkbox/internal.tsx
src/internal/components/abstract-switch/analytics-metadata/styles.scss
src/internal/components/abstract-switch/index.tsx
src/radio-group/__tests__/analytics-metadata.test.tsx
src/radio-group/analytics-metadata/interfaces.ts
src/radio-group/index.tsx
src/radio-group/internal.tsx
src/radio-group/radio-button.tsx

feat: Add analytics metadata to Checkbox and Radio Group

---

src/app-layout/__tests__/app-layout.ssr.test.tsx
src/app-layout/__tests__/utils.tsx

1. Add an test for that change  https://github.com/cloudscape-design/component-toolkit/pull/79, but using real app layout component
2. Add more assertions for the toolbar mode
Test-only addition
<details> …

chore: App layout testing improvements

---

src/pagination/__tests__/analytics-metadata.test.tsx
src/pagination/analytics-metadata/interfaces.ts
src/pagination/index.tsx
src/pagination/internal.tsx

feat: Add analytics metadata to Pagination

---

src/form-field/__tests__/analytics-metadata.test.tsx
src/form-field/analytics-metadata/interfaces.ts
src/form-field/analytics-metadata/styles.scss
src/form-field/index.tsx
src/form-field/internal.tsx
src/radio-group/__tests__/analytics-metadata.test.tsx

feat: Add analytics metadata to Form Field

---

src/table/__tests__/analytics-metadata.test.tsx
src/table/analytics-metadata/interfaces.ts
src/table/analytics-metadata/styles.scss
src/table/body-cell/td-element.tsx
src/table/header-cell/index.tsx
src/table/header-cell/th-element.tsx
src/table/header-cell/utils.ts
src/table/index.tsx
src/table/internal.tsx
src/table/selection/selection-control.tsx
src/table/thead.tsx

feat: Add analytics metadata to Table

---

src/form-field/__tests__/analytics-metadata.test.tsx
src/radio-group/__tests__/analytics-metadata.test.tsx

See comments in https://github.com/cloudscape-design/components/pull/2515
<details> …

chore: Fix analytics metadata typos in tests

---

src/button-dropdown/analytics-metadata/interfaces.ts
src/button-dropdown/category-elements/expandable-category-element.tsx
src/button-dropdown/category-elements/mobile-expandable-category-element.tsx
src/button/analytics-metadata/interfaces.ts
src/button/internal.tsx
src/checkbox/analytics-metadata/interfaces.ts
src/checkbox/internal.tsx
src/container/analytics-metadata/interfaces.ts
src/container/index.tsx
src/form/analytics-metadata/interfaces.ts
src/link/analytics-metadata/interfaces.ts
src/link/index.tsx
src/pagination/analytics-metadata/interfaces.ts
src/pagination/index.tsx
src/pagination/internal.tsx
src/radio-group/analytics-metadata/interfaces.ts
src/radio-group/index.tsx
src/table/analytics-metadata/interfaces.ts
src/table/index.tsx

See https://github.com/cloudscape-design/components/pull/2502#discussion_r1689172124
<details> …

chore: Update label syntax for analytics metadata

---

src/test-utils/dom/autosuggest/index.ts
src/test-utils/dom/button-dropdown/index.ts
src/test-utils/dom/code-editor/index.ts
src/test-utils/dom/date-range-picker/index.ts
src/test-utils/dom/input/base-input.ts
src/test-utils/dom/internal/dropdown-host.ts
src/test-utils/dom/prompt-input/index.ts
src/test-utils/dom/textarea/index.ts

chore: Replace act import in test utils

---

src/property-filter/__tests__/property-filter-token-list.test.tsx
src/property-filter/token.tsx

A follow-up for https://github.com/cloudscape-design/components/pull/2547
<details>
- _If the …

fix: Hide operator for all properties contain case

---

src/help-panel/implementation.tsx

Support our dual-named feature flag added in this PR: https://github.com/cloudscape-design/components/pull/2522
Locally
<details> …

fix: Fix app layout feature flag application for help panel

---

pages/table/resizable-columns.page.tsx

chore: Store columns to url

---

pages/button-group/test.page.tsx

chore: Add screenshot area to button group test page

---

src/wizard/internal.tsx
src/wizard/wizard-form-header.tsx
src/wizard/wizard-form.tsx
src/wizard/wizard-navigation.tsx

Avoid passing down unnecesary properties
PR build
<details> …

refactor: Simplify props drilling in wizard

---

src/toggle/__tests__/analytics-metadata.test.tsx
src/toggle/analytics-metadata/interfaces.ts
src/toggle/index.tsx
src/toggle/internal.tsx

Similar to https://github.com/cloudscape-design/components/commit/8cd280c02db40a03666c2cc1e1d802a2566aca28
<details>
- _If the code …

feat: Add analytics metadata to Toggle

---

src/radio-group/radio-button.tsx
src/tiles/__tests__/analytics-metadata.test.tsx
src/tiles/analytics-metadata/interfaces.ts
src/tiles/analytics-metadata/styles.scss
src/tiles/index.tsx
src/tiles/internal.tsx
src/tiles/tile.tsx

Similar to Similar to https://github.com/cloudscape-design/components/commit/8cd280c02db40a03666c2cc1e1d802a2566aca28
<details>
- _If …

feat: Add analytics metadata to Tiles

---

src/table/__tests__/analytics-metadata.test.tsx
src/tiles/index.tsx

- Use standard label structure for tiles
- Strengthen tests for table to include cases with counter and info link
<details>
- _If the …

chore: Update labels and tests for analytics metadata

---

pages/property-filter/common-props.tsx
pages/property-filter/custom-forms.scss
pages/property-filter/custom-forms.tsx
pages/property-filter/token-editor.page.tsx

Updated custom forms to match new guidelines: when rendered in token editor the form should use denser elements.
Rel: [Qeb3AbRK3bNw]
* Manual testing on test pages
* Screenshot tests on token editor test page
<details> …

chore: Updated property filter custom forms in test pages

---

build-tools/tasks/styles.js

See the inline comment: https://github.com/cloudscape-design/components/pull/2598#discussion_r1724874588
PR build
<details> …

chore: Remove unused code in styles build task

---

src/modal/__tests__/analytics-metadata.test.tsx
src/modal/analytics-metadata/interfaces.ts
src/modal/analytics-metadata/styles.scss
src/modal/index.tsx
src/modal/internal.tsx

Similar to https://github.com/cloudscape-design/components/pull/2580
<details> …

feat: Add analytics metadata to Modal

---

src/tabs/__tests__/analytics-metadata.test.tsx
src/tabs/analytics-metadata/interfaces.ts
src/tabs/analytics-metadata/styles.scss
src/tabs/index.tsx
src/tabs/tab-header-bar.tsx

Similar to https://github.com/cloudscape-design/components/pull/2580
<details> …

feat: Add analytics metadata to Tabs

---

src/expandable-section/__tests__/analytics-metadata.test.tsx
src/expandable-section/analytics-metadata/interfaces.ts
src/expandable-section/analytics-metadata/styles.scss
src/expandable-section/expandable-section-container.tsx
src/expandable-section/expandable-section-header.tsx
src/expandable-section/index.tsx
src/expandable-section/internal.tsx

Similar to https://github.com/cloudscape-design/components/pull/2580.
Depends on https://github.com/cloudscape-design/component-toolkit/pull/91.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles …

feat: Add analytics metadata to Expandable section

---

.github/workflows/release.yml

This reverts commit af065e345bb5b0aacffb0161f32ca024a2248910.
<details>
- _If the code …

revert: Disable release checks (#2630)

---

pages/app-layout/default.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/app-layout/index.tsx
src/app-layout/interfaces.ts
src/form/index.tsx
src/form/interfaces.ts
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/interfaces.ts
src/wizard/index.tsx
src/wizard/interfaces.ts

Adds additional metadata property for additional flows
<details> …

chore: Extend analytics metadata for experimental edit and dashboard

---

src/internal/components/token-list/analytics-metadata/interfaces.ts
src/internal/components/token-list/token-limit-toggle.tsx
src/token-group/__tests__/analytics-metadata.test.tsx
src/token-group/analytics-metadata/interfaces.ts
src/token-group/dismiss-button.tsx
src/token-group/index.tsx
src/token-group/internal.tsx

Similar to https://github.com/cloudscape-design/components/commit/24407b38efa400fc5114b1b6db8867c93c9b66a0
- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/ma …

feat: Add analytics metadata to Token Group

---

src/app-layout/__integ__/app-layout-split-panel.test.ts

Related to https://github.com/cloudscape-design/browser-test-tools/pull/105 (see dry-run test failures).
Switching to Chromium --headless=new causes failures to our tests that depend on screen size. The refactoring fixes the issue for some of the app layout tests to either remove the dependency completely or make assertions depend on the measured viewport height.
Next PR: https://github.com/cloudscape-design/components/pull/2660
* Verified the tests work with old and new headless mode
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob …

refactor: Update integration tests to resolve chromium upgrade 1

---

pages/breadcrumb-group/responsive.page.tsx
pages/breadcrumb-group/scenarios.page.tsx

To prepare for the release of responsive breadcrumbs
<details> …

chore: Prepare for new tests in breadcrumb group

---

src/property-filter/interfaces.ts

Depends on this one to be released: https://github.com/cloudscape-design/collection-hooks/pull/79
<details> …

fix: Fixes import from collection-hooks

---

src/internal/components/button-trigger/analytics-metadata/interfaces.ts
src/internal/components/button-trigger/analytics-metadata/styles.scss
src/internal/components/button-trigger/index.tsx
src/select/__tests__/analytics-metadata.test.tsx
src/select/analytics-metadata/interfaces.ts
src/select/index.tsx

Similar to https://github.com/cloudscape-design/components/commit/dde24620bceb97c2fd3e59aa45b0e95af8402313
- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/ma …

feat: Add analytics metadata to Select component

---

src/multiselect/__tests__/analytics-metadata.test.tsx
src/multiselect/analytics-metadata/interfaces.ts
src/multiselect/index.tsx

Similar to https://github.com/cloudscape-design/components/commit/dde24620bceb97c2fd3e59aa45b0e95af8402313
Depends on https://github.com/cloudscape-design/components/pull/2668
<details> …

feat: Add analytics metadata to Multiselect

---

src/popover/body.tsx
src/popover/internal.tsx
src/property-filter/__tests__/analytics-metadata.test.tsx
src/property-filter/__tests__/common.tsx
src/property-filter/analytics-metadata/interfaces.ts
src/property-filter/analytics-metadata/styles.scss
src/property-filter/filtering-token/index.tsx
src/property-filter/index.tsx
src/property-filter/internal.tsx
src/property-filter/token-editor.tsx
src/property-filter/token.tsx

Similar to https://github.com/cloudscape-design/components/pull/2669
Depends on https://github.com/cloudscape-design/components/pull/2667, https://github.com/cloudscape-design/components/pull/2668, https://github.com/cloudscape-design/components/pull/2669
<details> …

feat: Add analytics metadata to Property filter

---

src/flashbar/__tests__/flashbar.test.tsx

Remove complete duplicate of tests.
Verified with my editor feature, these line ranges are completely identical
PR build
<details> …

chore: Remove duplicated tests

---

src/tabs/index.tsx

Add metrics metadata to track the usage of the "tabs with actions" feature.
<details>
- _If …

chore: Add missing metrics for tabs features such as actions, fitHeight, and disabledReason

---

src/app-layout/__integ__/app-layout-refresh-content-width.test.ts
src/app-layout/__integ__/app-layout-refresh-edge-controls.test.ts
src/app-layout/__integ__/app-layout-refresh-notifications.test.ts
src/app-layout/__integ__/app-layout-sticky-elements.test.ts
src/app-layout/__integ__/awsui-applayout-sticky.test.ts
src/app-layout/__integ__/awsui-applayout.test.ts
src/app-layout/__integ__/multi-app-layout.test.ts
src/app-layout/__integ__/utils.ts

Enable toolbar test in files that don't require major implementation changes.
Some tests have been skipped for now, those will be addressed in a later commit.
<details> …

test: Enable toolbar integration tests

---

src/side-navigation/__tests__/analytics-metadata.test.tsx
src/side-navigation/__tests__/side-navigation.test.tsx
src/side-navigation/analytics-metadata/interfaces.ts
src/side-navigation/analytics-metadata/styles.scss
src/side-navigation/index.tsx
src/side-navigation/parts.tsx

Similar to https://github.com/cloudscape-design/components/commit/2e32ba37c3fb6c6e8735dfe88d713735c7d61cb9
<details>
- _If the code …

feat: Add analytics metadata to Side navigation

---

src/internal/components/button-trigger/index.tsx

fix: Fixes visual regression in disabled property filter token

---

src/app-layout/__tests__/mobile.test.tsx
src/app-layout/visual-refresh-toolbar/index.tsx
src/app-layout/visual-refresh-toolbar/skeleton/index.tsx
src/app-layout/visual-refresh-toolbar/toolbar/index.tsx

- Focus management when navigation opens
- force closure of the navigation in mobile
- activation of additional mobile tests
<details> …

fix: controlled behavior of navigation in toolbar

---

src/app-layout/__tests__/mobile.test.tsx
src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
src/app-layout/visual-refresh-toolbar/toolbar/styles.scss

fix: Disable body scroll in mobile toolbar when a panel is open

---

src/app-layout/__tests__/main.test.tsx
src/app-layout/classic.tsx
src/app-layout/visual-refresh-toolbar/skeleton/index.tsx
src/app-layout/visual-refresh-toolbar/toolbar/index.tsx

- Activate more tests for toolbar
- Fix one a11y violation: aside cannot be inside a span
<details> …

chore: Enable additional tests for toolbar

---

src/breadcrumb-group/__integ__/breadcrumb-group.test.ts
src/breadcrumb-group/implementation.tsx
src/breadcrumb-group/styles.scss

Related links, issue #, if available: AWSUI-59666
<details> …

fix: avoid test utils selector to return ghost items

---

src/app-layout/__tests__/desktop.test.tsx

These tests can now be activated
<details> …

chore: Activate desktop test for toolbar

---

src/app-layout/__integ__/runtime-drawers-with-updates.test.ts
src/app-layout/__integ__/utils.ts

Enable integration tests in `runtime-drawers-with-updates` for toolbar
<details>
- _If the …

test: Enable more integration tests for toolbar

---

src/text-filter/__tests__/analytics-metadata.test.tsx
src/text-filter/analytics-metadata/interfaces.ts
src/text-filter/index.tsx

Similar to https://github.com/cloudscape-design/components/commit/88059b64348e385e4f25dadc9784936ad186d236
<details>
- _If the code …

feat: Add analytics metadata to Text filter

---

src/collection-preferences/__tests__/analytics-metadata.test.tsx
src/collection-preferences/analytics-metadata/interfaces.ts
src/collection-preferences/analytics-metadata/styles.scss
src/collection-preferences/analytics-metadata/utils.ts
src/collection-preferences/content-display/index.tsx
src/collection-preferences/index.tsx
src/collection-preferences/utils.tsx
src/collection-preferences/visible-content.tsx
src/modal/internal.tsx

Similar to https://github.com/cloudscape-design/components/commit/2e32ba37c3fb6c6e8735dfe88d713735c7d61cb9
<details>
- _If the code …

feat: Add analytics metadata to Collection preferences

---

pages/prompt-input/permutations.page.tsx
pages/prompt-input/simple.page.tsx
pages/utils/permutations-view.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/__tests__/__snapshots__/test-utils-selectors.test.tsx.snap
src/internal/styles/forms/mixins.scss
src/prompt-input/__integ__/prompt-input.test.ts
src/prompt-input/__tests__/prompt-input.test.tsx
src/prompt-input/interfaces.ts
src/prompt-input/internal.tsx
src/prompt-input/styles.scss
src/prompt-input/test-classes/styles.scss
src/test-utils/dom/prompt-input/index.ts

Reverts cloudscape-design/components#2790

feat: Prompt input secondary actions and content slots

---

pages/steps/permutations.page.tsx

Disabling animation for screenshot tests
<details> …

fix: Disable animation for steps permutations

---

src/app-layout/__integ__/awsui-applayout-sticky.test.ts
src/app-layout/__integ__/mobile.test.ts
src/app-layout/__tests__/mobile.test.tsx
src/app-layout/visual-refresh-toolbar/compute-layout.ts
src/app-layout/visual-refresh-toolbar/drawer/global-drawer.tsx
src/app-layout/visual-refresh-toolbar/drawer/local-drawer.tsx
src/app-layout/visual-refresh-toolbar/index.tsx
src/app-layout/visual-refresh-toolbar/navigation/index.tsx
src/app-layout/visual-refresh-toolbar/skeleton/styles.scss

Fix several bugs for mobile view on the toolbar
<details> …

fix: Fix mobile view issues on app layout toolbar

---

src/app-layout/visual-refresh-toolbar/skeleton/styles.scss

https://github.com/user-attachments/assets/f104e4be-3fc5-42c0-85b3-a7884d07d5b7
<details>
- …

fix: Horizontal overflow on mobile view on table demo

---

pages/common/options-loader.ts
pages/multiselect/multiselect.async.example.page.tsx
src/internal/components/options-list/index.tsx
src/internal/components/options-list/styles.scss
src/internal/components/options-list/utils/use-open-state.ts
src/multiselect/__integ__/multiselect-embedded.test.ts
src/multiselect/__tests__/multiselect-embedded.test.tsx
src/multiselect/embedded.tsx
src/multiselect/internal.tsx
src/multiselect/styles.scss
src/multiselect/use-multiselect.tsx
src/select/utils/use-select.ts

Introduces an internal embeddable multiselect list component that does not have a dropdown. The component to be used in the property filter for multi-choice forms.
<details> …

chore: Embedded multiselect list component

---

src/app-layout/visual-refresh-toolbar/notifications/styles.scss

https://github.com/user-attachments/assets/6a91f416-b2e0-45f4-a69c-d1ab1e574f7a
<details>
- …

fix: Unexpected gap between content and sticky notifications

---

src/app-layout/__tests__/main.test.tsx

chore: Enable controlled tools test in toolbar

---

pages/app-layout/utils/content-blocks.tsx
pages/app-layout/with-split-panel.page.tsx
src/app-layout/__integ__/app-layout-drawers.test.ts
src/app-layout/__integ__/app-layout-split-panel.test.ts
src/app-layout/classic.tsx
src/app-layout/split-panel/constants.ts
src/app-layout/split-panel/split-panel-utils.ts
src/app-layout/visual-refresh-toolbar/compute-layout.ts
src/app-layout/visual-refresh/context.tsx

Rel: AWSUI-54993
The issue:
https://github.com/user-attachments/assets/7c0dbd99-382d-49a2-acd8-91d71b42d048
* New integration test
* Manual testing with Classic, VR, Toolbar
<details> …

fix: Fixes split panel bouncing on the edge between side/bottom when scrollbar appears

---

pages/app-layout/landing-page.page.tsx
pages/app-layout/landing-page.scss
src/app-layout/__tests__/header-variant.test.tsx
src/app-layout/visual-refresh-toolbar/index.tsx
src/app-layout/visual-refresh-toolbar/notifications/index.tsx
src/app-layout/visual-refresh-toolbar/notifications/styles.scss
src/app-layout/visual-refresh-toolbar/skeleton/index.tsx
src/app-layout/visual-refresh-toolbar/skeleton/styles.scss
src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
src/app-layout/visual-refresh-toolbar/toolbar/trigger-button/index.tsx

The support does not include `contentHeader` and embedding `ContentLayout`. We will add it at a later stage if needed
<details>
- _If …

feat: Add support for headerVariant in toolbar

---

src/app-layout/__integ__/app-layout-drawers.test.ts

This increases the context of the drawers integ tests for app layout component
Increases tests for drawers and resize events
<details> …

chore: making more assertions for integ tests for AppLayout drawers

---

src/app-layout/__tests__/main.test.tsx
src/app-layout/__tests__/tools.test.tsx
src/app-layout/utils/use-drawers.ts
src/app-layout/visual-refresh-toolbar/index.tsx
src/app-layout/visual-refresh-toolbar/interfaces.ts
src/app-layout/visual-refresh-toolbar/toolbar/drawer-triggers.tsx
src/app-layout/visual-refresh-toolbar/toolbar/index.tsx

This reverts commit 227dd63ea3e3706353ff3e00de4e03c254ca47b4.
<details>
- _If the code …

fix: Revert "fix: Partially controllable tools (#2793)"

---

src/app-layout/visual-refresh-toolbar/drawer/local-drawer.tsx

Avoid revert https://github.com/cloudscape-design/components/pull/2826
<details> …

fix: hide inactive local drawer

---

src/app-layout/__integ__/app-layout-focus-delegation.test.ts

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._
- _Changes are covered with new/existing unit tests?_
- …

chore: Activate one more toolbar test

---

src/app-layout/__tests__/common.test.tsx
src/app-layout/__tests__/multi-layout.test.tsx
src/app-layout/visual-refresh-toolbar/drawer/local-drawer.tsx
src/app-layout/visual-refresh-toolbar/index.tsx

chore: Activate common test for toolbar

---

src/app-layout/__integ__/awsui-applayout.test.ts

instead of skipping the tests for refresh and refresh-toolbar where resizeObserver errors were found, we just ignore the check for them so tests still can be done
This also does not test for the preservation of breadcrumbs in refresh toolbar as it is not needed
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTIN …

chore: app layout toolbar test enabling

---

pages/app/components/page-view.scss
pages/app/components/page-view.tsx

Re-opening #2655.
Related links, issue #, if available: 
- This PR reverted in #2693 because it was causing `<Flashbar />` shadow to disappear.
- The fix to the `<Flashbar />` shadow already merged: #2767
<details> …

chore: Re-opens: Adds background color to page and permutation containers (#2655)

---

src/app-layout/__tests__/header-variant.test.tsx
src/app-layout/visual-refresh-toolbar/toolbar/index.tsx

chore: Remove high-contrast treatment from toolbar

---

.github/workflows/release.yml
build-tools/tasks/integ.js

Introducing shards for integ test same as it is done for a11y tests
<details> …

chore: Sharded integ tests support

---

src/expandable-section/index.tsx
src/select/index.tsx

This change adds metrics for the new `inlineLabelText` property in select, and the `headerActions` property for expandable section.
<details> …

chore: Add metrics for recently added features in select and expandable section

---

src/table/__integ__/resizable-columns.test.ts

Increasing delays to make sure resize events fire
* Validated by running the test over 100 times in GitHub actions
<details>
- _If the …

chore: Fixes flakiness in resizable columns integ test

---

src/app-layout/__tests__/multi-layout.test.tsx

Add more tests for some recently found use-cases 
These are tests
<details>
- _If the code …

chore: Add more app layout deduplication tests

---

package-lock.json
package.json
src/__a11y__/axe.ts
src/button-dropdown/__tests__/button-dropdown-accessibility.test.tsx

Upgrading axe-core to improve performance in unit tests.
However, one test and one new rule were ignored as now reporting new violations that require a validation. This is to be addressed as a follow-up.
Rel: AWSUI-59822
<details> …

chore: Upgrade axe-core

---

pages/app-layout/disable-paddings-with-split-panel.page.tsx

chore: Adds missing screenshot area to app layout test page

---

.github/workflows/release.yml

Skipping all tests for release job as unnecessary: for main branch the tests are already run as part of the PR actions and for dev branches that technically allows a change with failing tests propagate to the dev. environment which is ok.
<details> …

chore: Removes test runs from release workflows

---

src/property-filter/__tests__/property-filter.test.tsx

Increasing test coverage for property filter async loading
<details> …

test: More property filter async loading tests

---

pages/app-layout/runtime-drawers.page.tsx
pages/app-layout/styles.scss
pages/app-layout/utils/content-blocks.tsx
pages/app-layout/utils/external-widget.tsx
src/app-layout/__integ__/runtime-drawers.test.ts
src/app-layout/drawer/index.tsx
src/app-layout/resize/styles.scss
src/app-layout/visual-refresh-toolbar/compute-layout.ts
src/app-layout/visual-refresh-toolbar/drawer/global-drawer.tsx
src/app-layout/visual-refresh-toolbar/drawer/local-drawer.tsx
src/app-layout/visual-refresh-toolbar/navigation/index.tsx
src/app-layout/visual-refresh-toolbar/split-panel/index.tsx
src/app-layout/visual-refresh/drawers.scss
src/internal/plugins/helpers/runtime-content-wrapper.tsx
src/internal/plugins/helpers/styles.scss

Reverts cloudscape-design/components#2924 because there is a visual regression for side nav without header

revert: Extra scrollbars in drawers

---

src/internal/hooks/use-table-interaction-metrics/__tests__/use-table-interaction-metrics.test.tsx
src/internal/hooks/use-table-interaction-metrics/index.ts

Current table metrics are being reported while in forms or wizards while we are more interested when Table is on its own. This changes these metrics to only be emitted when the table it outside of a Funnel.
<details>
- _Changes …

chore: Do no emit table interaction metrics while in funnel

---

pages/app/index.tsx
pages/funnel-analytics/static-multi-page-flow.page.tsx
pages/funnel-analytics/static-single-page-flow.page.tsx
src/internal/analytics/__integ__/static-multi-page-create.test.ts
src/internal/analytics/__integ__/static-single-page-flow.test.ts

- Modify testing pages to use app layout
- Modify Funnel integ tests to test using applayout with and without the toolbar
- Modified existing tests
<details> …

chore: Add test for funnels with toolbar

---

pages/table/expandable-rows-performance.page.tsx
pages/table/expandable-rows-test.page.tsx
pages/table/expandable-rows/expandable-rows-configs.tsx
pages/table/inline-editor.permutations.page.tsx
src/table/body-cell/disabled-inline-editor.tsx
src/table/body-cell/index.tsx
src/table/body-cell/styles.scss

The PR removes unused table body cell styles for inline editing.
* Manual testing, screenshot tests
<details> …

refactor: Refactors table body cell styles

---

package-lock.json

chore: Upgrade package dependencies

---

src/app-layout/__tests__/runtime-drawers.test.tsx

Follow-up to meet codecov bar for [the PR](https://github.com/cloudscape-design/components/commit/0c31f9fb7f4b35eafb1043915901ba559c9a6630)
<details> …

chore: Test for overflown drawer trigger

---

src/table/sticky-scrollbar/sticky-scrollbar.tsx
src/table/sticky-scrollbar/styles.scss

When a table has a horizontal scrollbar, this scrollbar is placed at the bottom of the table's container. There, it overlaps with the rounded corners and overflows them, hiding the border. After this change, the scrollbar adopts the same rounding as the container, so that it does not hide the border anymore.
The rounding is achieved with the `clip-path` property. It limits the rendering area of the element, but does not affect any content of the table (like `overflow` potentially would), since it can be applied directly on the element that needs to be clipped.
Related links, issue #, if available: AWSUI-43012
<details>
- …

fix: Table scrollbar overflows container

---

pages/table/cell-permutations.page.tsx

Adding more cell content variations to support this refactoring: https://github.com/cloudscape-design/components/pull/3061
<details>
- …

chore: Updates table cell permutations page

---

src/internal/components/options-list/utils/use-highlight-option.ts

Optimize rendering performance. Before this fix, the whole PropertyFilter (or Autosuggest, or Select) re-renders on every mouse move
https://github.com/user-attachments/assets/51816638-bd75-4438-afa6-3a2959f9662d
Profiler view before the fix (I set 6x slowdown to make it more aparent)
Profiler view after the fix
<details> …

fix: Optimize dropdown items rendering on mouse hover

---

src/mixed-line-bar-chart/__integ__/mixed-line-bar-chart.test.ts

When migrating Webdriver to v9 (see https://github.com/cloudscape-design/browser-test-tools/pull/109) a test is failing for unknown reason, also reproducible locally.
This PR suppresses the test and a follow-up ticket will be open to re-introduce it once the migration is done.
<details> …

chore: Suppress test failing with WebdriverIO v9

---

src/calendar/__tests__/calendar.test.tsx
src/calendar/internal.tsx

Ensure that calendar handles invalid `value` input without crashing.
Related links, issue #, if available: AWSUI-60142
Unit tests
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/ …

fix: Handle invalid input to calendar component

---

src/collection-preferences/index.tsx

A small addition for collection preferences metrics.
<details> …

chore: Enhances collection preferences feature metrics

---

package.json
src/alert/__tests__/runtime-content.test.tsx
src/flashbar/__tests__/runtime-content.test.tsx
src/flashbar/internal/analytics.ts
src/internal/metrics.ts
src/internal/plugins/__tests__/api.test.ts
src/internal/plugins/api.ts
src/internal/plugins/controllers/__tests__/drawers.test.ts
src/internal/plugins/controllers/alert-flash-content.ts
src/internal/plugins/controllers/drawers.ts
src/internal/plugins/helpers/metrics.ts
src/internal/plugins/helpers/use-discovered-content.tsx

Report all unexpected situations with our metrics
Updated all existing warning tests to assert metric emitted
<details> …

chore: Add metrics reporting to runtime API code

---

package-lock.json
package.json

chore: Update @types/node to v20

---

src/top-navigation/styles.scss

This reverts commit 13ff9d4597e62ebf8c95d8391f6370a0bea12c01.
<details>
- _If the code …

revert: Revert "feat: Add bottom border to top navigation (#3192)"

---

src/alert/__tests__/runtime-content.test.tsx
src/flashbar/__tests__/runtime-content.test.tsx
src/internal/plugins/__tests__/api.test.ts
src/internal/plugins/controllers/__tests__/drawers.test.ts
src/internal/plugins/helpers/metrics.ts

Another fix to unblock: https://github.com/cloudscape-design/component-toolkit/pull/117
Built with the new version of the toolkit, it compiles now
<details> …

chore: Update metrics reporting

---

src/multiselect/index.tsx

We recently released inline tokens in multiselect as an official feature. We should also be tracking the usage of this property using our metrics tracking tooling.
<details> …

chore: Adds inline tokens to metrics tracking

---

pages/funnel-analytics/static-single-page-flow.page.tsx
src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
src/form-field/interfaces.ts
src/internal/analytics/__integ__/static-single-page-flow.test.ts

Seems this field was missed.
Added to the integ test
<details> …

chore: Make FormField analyticsMetadata public

---

src/table/body-cell/styles.scss
src/table/body-cell/td-element.tsx
src/table/styles.scss

Updated table cell alignment to fix an issue in Firefox where the top alignment was not working.
* New screenshot tests
* Manual tests
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibi …

fix: Fixes table cell vertical align in Firefox

---

src/modal/index.tsx
src/table/index.tsx

Include the flowType in the component metrics emitted by modal and table
<details> …

chore: Add flowType to component metrics for modal and table

---

pages/table/cell-permutations.page.tsx

chore: Disables animations in cell permutations test page

---

src/app-layout/__tests__/utils.tsx

The linked PR https://github.com/cloudscape-design/component-toolkit/pull/118 is released now, the tests pass without the workaround
test-only change
<details> …

chore: remove temporary workaround in tests

---

package-lock.json
src/flashbar/__tests__/collapsible.test.tsx
src/flashbar/flash.tsx

This reverts commit c6ed14c6fac1fec7af85a31ab0af73169246590f.
<details>
- _If the code …

revert: Adds group role and aria label to flash focus (#3263)

---

package-lock.json
src/flashbar/__tests__/collapsible.test.tsx
src/flashbar/flash.tsx

Re-opens the https://github.com/cloudscape-design/components/pull/3302. (original change: https://github.com/cloudscape-design/components/commit/c6ed14c6fac1fec7af85a31ab0af73169246590f)
After going through the issue causing a revert, we discovered that the build to live issue is not on our side. We can release this as is.
Related links, issue #, if available: AWSUI-60251
Dev pipeline
<details> …

revert: revert Adds group role and aria label to flash focus

---

package-lock.json
src/flashbar/__tests__/collapsible.test.tsx
src/flashbar/flash.tsx

Reverting to cloudscape-design/components#3315 to open up the deployment.
Will re-open once the blockers are removed.

revert: Adds group role and aria label to flash focus

---

src/i18n/messages/all.ar.json
src/i18n/messages/all.de.json
src/i18n/messages/all.en-GB.json
src/i18n/messages/all.en.json
src/i18n/messages/all.es.json
src/i18n/messages/all.fr.json
src/i18n/messages/all.id.json
src/i18n/messages/all.it.json
src/i18n/messages/all.ja.json
src/i18n/messages/all.ko.json
src/i18n/messages/all.pt-BR.json
src/i18n/messages/all.tr.json
src/i18n/messages/all.zh-CN.json
src/i18n/messages/all.zh-TW.json

Sync i18n messages, apply labelHotspot updates
Related links, issue #, if available: AWSUI-60206, https://github.com/cloudscape-design/components/pull/3321
- verified manually
<details> …

chore: Sync i18n messages, apply labelHotspot updates

---

package-lock.json
package.json

Upgrade something insignificant to test our PR build
PR build
<details>
- _If the code …

chore: Upgrade wait-on

---

src/date-range-picker/calendar/__tests__/intl.test.ts

Remove unnecessary tests due to dependency on external environment.
<details> …

chore: Remove arabic tests for data range picker

---

src/i18n/messages-types.ts
src/i18n/messages/all.ar.json
src/i18n/messages/all.de.json
src/i18n/messages/all.en-GB.json
src/i18n/messages/all.en.json
src/i18n/messages/all.es.json
src/i18n/messages/all.fr.json
src/i18n/messages/all.id.json
src/i18n/messages/all.it.json
src/i18n/messages/all.ja.json
src/i18n/messages/all.ko.json
src/i18n/messages/all.pt-BR.json
src/i18n/messages/all.tr.json
src/i18n/messages/all.zh-CN.json
src/i18n/messages/all.zh-TW.json

This provides new strings necessary for #3336.
<details> …

chore: Update i18n strings

---

pages/select/trigger.permutations.page.tsx

Adds missing permutations to support https://github.com/cloudscape-design/components/pull/3372
<details> …

chore: Adds missing inline label permutations

---

src/table/__integ__/table-sticky-columns.test.ts
src/table/__tests__/use-prevent-sticky-click-scroll.test.tsx
src/table/body-cell/styles.scss
src/table/internal.tsx
src/table/use-prevent-sticky-click-scroll.ts

Rel: AWSUI-60466
Before:
https://github.com/user-attachments/assets/4ec25600-9815-4e09-8365-c7dd59bf74ea
Now:
https://github.com/user-attachments/assets/c0641138-7cfb-45ae-a77d-a50069465c1d
<details> …

fix: Fixes table sticky cells clicks

---

package.json

Now that there's some assurance that it's safe on React 19, I guess it's time.
Related links, issue #, if available: AWSUI-60489
Tested with internal demos, and with upgrading the package itself and manually verifying that all the failures are due to "local" usage only.
<details>
- …

feat: Extend support to React 19

---

build-tools/tasks/docs.js
src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap

Apply changes from these PRs
https://github.com/cloudscape-design/documenter/pull/61
https://github.com/cloudscape-design/documenter/pull/63
Build passes 
<details> …

chore: Fix snapshot tests

---

package.json
src/button-dropdown/category-elements/expandable-category-element.tsx
src/button-dropdown/category-elements/styles.scss
src/button-dropdown/item-element/index.tsx
src/button-dropdown/item-element/styles.scss
src/flashbar/styles.scss
src/internal/components/button-trigger/styles.scss
src/internal/components/selectable-item/index.tsx
src/internal/components/selectable-item/styles.scss
src/internal/styles/forms/mixins.scss
src/prompt-input/__integ__/prompt-input.test.ts
src/prompt-input/internal.tsx
src/segmented-control/styles.scss
src/tiles/styles.scss

This PR fixes bugs identified in screenshot tests for VR improvements ([Original PR](https://github.com/cloudscape-design/components/pull/3374)), including:
- The disabled and selected state of Tiles
- The height of Segmented control in classic, etc.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browse …

chore: Fix bugs VR improvements

---

src/multiselect/index.tsx

Add metrics tracking for the prop added in #3336.
<details> …

chore: Add enableSelectAll prop to Multiselect metrics

---

src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
src/attribute-editor/index.tsx
src/attribute-editor/internal.tsx
src/tag-editor/index.tsx

Add some metrics for various attribute editor properties
<details> …

chore: Add metrics for attribute editor properties

---

src/internal/base-component/__tests__/validate-props.test.ts
src/internal/base-component/index.ts

Not used in the code directly, but it will be needed for code generation changes I will add later
Added some unit tests
<details> …

chore: Add property validation function

---

build-tools/tasks/package-json.js

To be used in charts test utils
<details> …

chore: Exposes internal chart filter test utils

---

src/date-input/__tests__/utils.test.ts
src/date-input/internal.tsx
src/date-input/utils.ts

This PR extracts the mask generation logic from the DateInput component into a dedicated utility function. The changes include:
- Created a new utils.ts file with the generateMaskArgs function that handles mask configuration
- Added support for ISO date format through an optional isIso parameter (that will be utilized in later PRs within the Custom Date Formats project)
- Moved related utility functions and constants from internal.tsx to utils.ts
- Added comprehensive unit tests for the utility function
- Modified the function to accept undefined parameters for better flexibility
Benefits
- Improves code organization by separating concerns
- Makes the mask generation logic reusable across components
- Adds support for ISO date format
- Increases test coverage with dedicated unit tests
- …

chore: enhancing and moving Date Input masking to a separate & tested file

---

package.json
src/app-layout-toolbar/__tests__/analytics-metadata.test.tsx
src/app-layout-toolbar/analytics-metadata/interfaces.ts
src/app-layout-toolbar/index.tsx
src/app-layout/visual-refresh-toolbar/drawer/global-drawer.tsx
src/app-layout/visual-refresh-toolbar/drawer/local-drawer.tsx
src/app-layout/visual-refresh-toolbar/navigation/index.tsx
src/app-layout/visual-refresh-toolbar/toolbar/trigger-button/index.tsx

Similar to https://github.com/cloudscape-design/components/pull/2764
<details> …

feat: Add analytics metadata to AppLayoutToolbar

---

src/drawer/styles.scss

fix: Flex styles causing a build failure

---

src/app-layout/visual-refresh-toolbar/drawer/styles.scss

Fixed styles causing build errors `7376262968`
<details> …

fix: Unsupported flex styles

---

src/app-layout/visual-refresh-toolbar/drawer/styles.scss

fix: Global drawer for mobile view

---

.github/workflows/release.yml

This reverts commit 250c45e855e19c9c6c10c7dbd9e0a8bb9168bdf3.
See also https://github.com/cloudscape-design/actions/pull/80
<details> …

revert: "chore: Update release.yml to release downstream repositories (#3484)"

---

src/__tests__/snapshot-tests/__snapshots__/test-utils-selectors.test.tsx.snap
src/autosuggest/__tests__/autosuggest.test.tsx
src/select/__tests__/i18n.test.tsx
src/select/__tests__/select-a11y.test.tsx
src/test-utils/dom/autosuggest/index.ts
src/test-utils/dom/internal/dropdown-host.ts

Ticket: `AWSUI-60828`
<details> …

fix: Fix findHighlightedAriaLiveRegion not retrieving the expected element

---

src/button-group/__tests__/analytics-metadata.test.tsx
src/button-group/analytics-metadata/interfaces.ts
src/button-group/index.tsx
src/button-group/internal.tsx
src/button-group/item-element.tsx
src/button-group/menu-dropdown-item.tsx

feat: Add analytics metadata to ButtonGroup component

---

src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
src/flashbar/interfaces.ts

One type was missing: adding it here.
N/A
<details> …

chore: Update flashbar API docs

---

src/internal/hooks/use-intersection-observer/index.ts

We have a situation in Firefox with nested app layouts that aren't firing intersection changes when they show/hide. This is happening because the iframes are hidden by setting `display: none` on the parent element of the iframe, and IntersectionObserver instances inside an iframe can't detect changes caused by changes above the iframe on Firefox.
Minimal reproduction: https://codesandbox.io/p/sandbox/rzwsfc
Also validated the issue on the relevant broken pages by patching this script into the page head:
```
const mu = new MutationObserver(() => {
document.querySelectorAll("iframe").forEach((iframe) => {
try {
iframe.contentWindow.addEventListener("DOMContentLoaded", () => {
iframe.contentWindow.IntersectionObserver = window.top.IntersectionObserver;
console.log("Patched!");
})
} catch {} …
```

fix: Fix useIntersectionObserver not firing when running inside iframe on Firefox

---

src/internal/components/options-list/utils/use-highlight-option.ts
src/multiselect/__tests__/multiselect-embedded.test.tsx
src/multiselect/__tests__/multiselect.test.tsx
src/multiselect/__tests__/select-all.test.tsx
src/select/__integ__/page-objects/select-page.ts
src/select/__integ__/select-native-search.test.ts
src/select/__integ__/select.test.ts
src/select/__tests__/disabled.test.tsx
src/select/__tests__/use-select.test.ts
src/select/utils/use-select.ts

Reverts cloudscape-design/components#3546 😭

revert: Revert "fix: Highlight the first select option by default if none are selected"

---

src/internal/components/options-list/utils/use-highlight-option.ts
src/multiselect/__tests__/multiselect-embedded.test.tsx
src/multiselect/__tests__/multiselect.test.tsx
src/multiselect/__tests__/select-all.test.tsx
src/select/__integ__/page-objects/select-page.ts
src/select/__integ__/select-native-search.test.ts
src/select/__integ__/select.test.ts
src/select/__tests__/disabled.test.tsx
src/select/__tests__/use-select.test.ts
src/select/utils/use-select.ts

See cloudscape-design/components#3546. Opened pull requests against packages that blocked the release of this commit.

fix: Highlight the first select option by default if none are selected

---

src/__tests__/snapshot-tests/__snapshots__/documenter.test.ts.snap
src/button/interfaces.ts
src/toggle-button/interfaces.ts

This PR removes the Style API from the Toggle Button interface.

fix: Remove Style API from Toggle Button

---

pages/funnel-analytics/static-single-page-flow.page.tsx
src/alert/__tests__/alert-analytics.test.tsx
src/internal/analytics/__integ__/static-single-page-flow.test.ts
src/internal/analytics/interfaces.ts

To support this change: CR-207227974
Dryrun: 7441706497
<details> …

chore: Update errorCategory API to align with AWS standard error names

---

src/__a11y__/to-validate-a11y.ts
src/__tests__/functional-tests/test-a11y-validator.test.tsx
src/app-layout/__tests__/main.test.tsx
src/app-layout/visual-refresh-toolbar/toolbar/index.tsx
src/app-layout/visual-refresh-toolbar/toolbar/styles.scss

Code cleanup
* manually tested locally
* PR build
<details> …

chore: Resolve todo items

---

src/internal/utils/__tests__/with-native-attributes.test.tsx
src/internal/utils/with-native-attributes.tsx

chore: Fix wording to meet guidelines

---

src/checkbox/__tests__/analytics-metadata.test.tsx
src/checkbox/analytics-metadata/interfaces.ts
src/checkbox/internal.tsx
src/toggle/__tests__/analytics-metadata.test.tsx
src/toggle/analytics-metadata/interfaces.ts
src/toggle/internal.tsx

Needed for page scanner
<details> …

chore: Add value in Checkbox and Toggle analytics metadata

---

src/input/__tests__/analytics-metadata.test.tsx
src/input/analytics-metadata/interfaces.ts
src/input/index.tsx
src/input/internal.tsx
src/textarea/__tests__/analytics-metadata.test.tsx
src/textarea/analytics-metadata/interfaces.ts
src/textarea/index.tsx

Similar to many other components.
<details> …

feat: Add analytics metadata to input and textarea components

---

src/multiselect/__tests__/analytics-metadata.test.tsx
src/multiselect/analytics-metadata/interfaces.ts
src/multiselect/index.tsx

Needed for page scanner
<details> …

chore: Add selected options values in multiselect analytics metadata

---

src/button-dropdown/__tests__/button-dropdown.test.tsx
src/button-dropdown/index.tsx
src/button-dropdown/interfaces.ts
src/button-dropdown/internal.tsx

Title says it all :)
<details> …

feat: Add native attributes for button dropdown

---

package.json
pages/container/style-custom.page.tsx
src/container/__tests__/container.test.tsx
src/container/interfaces.ts
src/container/internal.tsx
src/container/style.tsx

This PR adds Style API support for the `Container` component. A screenshot of the demo page is included below.

feat: Implementation of the Container component Style API 

---

pages/app-layout/dashboard-content-type.page.tsx
src/app-layout/__integ__/app-layout-split-panel.test.ts

Mirror this use-case from the demos package: 
* Code: https://github.com/cloudscape-design/demos/blob/a2708c23608a399864451acc027a5510ac4eee27/src/pages/form/app.tsx#L41-L46
* Test: https://github.com/cloudscape-design/demos/blob/a2708c23608a399864451acc027a5510ac4eee27/test/e2e/form.test.ts#L89-L95
I made a regression for that use-case, but none of the integration tests failed until demos package. 
This is not expected, we should have a test here
Test-only addition
<details> …

chore: Add a test on split panel programmatic focus

---

pages/checkbox/style-custom.page.tsx
pages/radio-group/style-custom.page.tsx
pages/toggle/style-custom.page.tsx
src/checkbox/__integ__/checkbox.test.ts
src/checkbox/__tests__/checkbox.test.tsx
src/checkbox/interfaces.ts
src/checkbox/internal.tsx
src/checkbox/style.tsx
src/checkbox/styles.scss
src/internal/components/abstract-switch/index.tsx
src/internal/components/abstract-switch/styles.scss
src/internal/components/checkbox-icon/index.tsx
src/internal/utils/__tests__/style.test.ts
src/internal/utils/style.ts
src/radio-group/__integ__/radio-group.test.ts
src/radio-group/__tests__/radio-group.test.tsx
src/radio-group/interfaces.ts
src/radio-group/internal.tsx
src/radio-group/radio-button.tsx
src/radio-group/style.tsx
src/radio-group/styles.scss
src/toggle/__integ__/toggle.test.ts
src/toggle/__tests__/toggle.test.tsx
src/toggle/interfaces.ts
src/toggle/internal.tsx
src/toggle/style.tsx
src/toggle/styles.scss

This PR adds Style API support for Abstract Switch components including Toggle, Radio, and Checkbox.

feat: Implementation of the Style API for Abstract Switch components

---

src/multiselect/index.tsx

Add missing metadata for the new feature.
<details> …

chore: Add metadata for `inlineLabelText` in multiselect

---

src/app-layout/__tests__/multi-layout.test.tsx
src/app-layout/visual-refresh-toolbar/skeleton/multi-layout.ts

chore: Add metrics on multi-app-layout-usage

---

.npmrc
package-lock.json
package.json

Upgrades "eslint-plugin-unicorn" to latest version.
`npm audit` lists 4 vulnerabilites. 3 of those are from the documentation repository.
```
@eslint/plugin-kit  <0.3.4
@eslint/plugin-kit is vulnerable to Regular Expression Denial of Service attacks through ConfigCommentParser - https://github.com/advisories/GHSA-xffm-g5w8-qvg7
fix available via `npm audit fix --force`
Will install eslint-plugin-unicorn@60.0.0, which is a breaking change
node_modules/@eslint/plugin-kit
node_modules/eslint-plugin-unicorn/node_modules/@eslint/plugin-kit
eslint-plugin-unicorn  58.0.0 - 59.0.1
Depends on vulnerable versions of @eslint/plugin-kit
node_modules/eslint-plugin-unicorn
```
The braking change in `eslint-plugin-unicorn@60.0.0` is that the plugin now requires Node v20.10, which is the current LTS …

chore: upgrade eslint-plugin-unicorn

---

src/flashbar/__integ__/collapsible.test.ts
src/flashbar/__integ__/focus-interactions.test.ts
src/flashbar/__integ__/pages/interactive-page.ts
src/flashbar/__tests__/focus-handling.test.tsx
src/flashbar/collapsible-flashbar.tsx
src/flashbar/common.tsx
src/flashbar/flash.tsx
src/flashbar/utils.ts

Reverts cloudscape-design/components#3782.

fix: Fix focus management for flashbar when motion is enabled

---

src/__tests__/snapshot-tests/__snapshots__/test-utils-selectors.test.tsx.snap
src/button/icon-helper.tsx
src/button/internal.tsx
src/button/styles.scss
src/button/test-classes/styles.scss
src/test-utils/dom/button/index.ts
src/test-utils/dom/toggle-button/index.ts
src/toggle-button/internal.tsx
src/toggle-button/test-classes/styles.scss

Reverts cloudscape-design/components#3816
Let's see if this works

revert: Ensure toggle button test utils only find toggle buttons

---

src/__tests__/snapshot-tests/__snapshots__/test-utils-wrappers.test.tsx.snap

Update snapshot after this change https://github.com/cloudscape-design/test-utils/pull/100
<details> …

chore: Update test utils wrappers snapshot

---

.github/workflows/build-lint-test.yml

Applied small fixes as a follow-up for: https://github.com/cloudscape-design/components/pull/3829.
<details> …

chore: Experiment

---

src/anchor-navigation/__integ__/anchor-navigation.test.ts
src/app-layout/__integ__/app-layout-focus-delegation.test.ts
src/app-layout/classic.tsx
src/app-layout/utils/use-focus-control.ts
src/app-layout/visual-refresh-toolbar/state/use-app-layout.tsx
src/app-layout/visual-refresh/context.tsx
src/property-filter/__integ__/async-loading.test.ts

A follow-up for: https://github.com/cloudscape-design/components/pull/3888
<details> …

chore: Fixes some integ tests for React 18

---

src/__tests__/snapshot-tests/__snapshots__/design-tokens.test.ts.snap
style-dictionary/visual-refresh/colors.ts
style-dictionary/visual-refresh/metadata/colors.ts

This PR allows teams to theme the border color for components that use dropdown and popover components.

feat: Add new public themable tokens for dropdown and popover containers.

---

src/app-layout/visual-refresh-toolbar/compute-layout.ts

Re-apply #3917 in its original form after additional discussion. This is the behavior we want now
Same as before
<details> …

fix: Allow ai drawer to have bigger max width
