.github/workflows/visuals.yml

This reverts commit b5fc5b2c5e9a26851cbe64119c5c54ee5e488771 and enables visual regression tests again. They were originally disabled because they cannot easily run without the dependencies being published to npm.
We have used this in the past, so it should work.
~~This initial run will fail, though, because there will be no reference images. It will work as normal with the PR after this one.~~ Because we kept the original testing files and just disabled the workflow, this should just work immediately after merging.
<details>
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and …

Enable Visual Regression Tests again

---

pages/app-layout/legacy-table-sticky-notifications.page.tsx
src/app-layout/index.tsx
src/app-layout/test-classes/styles.scss
src/app-layout/visual-refresh/layout.tsx
src/container/__integ__/awsui-legacy-applayout-sticky.test.ts
src/container/use-sticky-header.ts
src/table/__tests__/empty-state.test.tsx

Fixed multiple issues:
- In a classic app layout with `contentType="table"` and `disableBodyScroll={true}`, don't include the header height in provided top offset (see `src/app-layout/index.tsx`)
- In classic and visual refresh, `disableBodyScroll={true}` caused sticky scroll in headers to ignore the top offset because they incorrectly considered the app layout to be an invalidating scrolling container. Changed the logic to stop searching when it hits the app layout scrolling root (see `src/container/use-sticky-header.ts`)
The rest are test classes, dev pages, and integration tests.
Added an integration test for sticky positioning inside `disableBodyScroll`.
AWSUI-18582
It's much more robust to test this in …

fix(container): Fix sticky offset calculation under disableBodyScroll

---

src/alert/interfaces.ts
src/tutorial-panel/components/tutorial-list/index.tsx

Mark `visible` property as deprecated. It should not be used in new code, `{condition && <Alert />}` does the same thing
Only JSDOC change
<details>
</details>

Mark visible property on alert as deprecated

---

pages/tag-editor/shared.ts
src/__tests__/__snapshots__/documenter.test.ts.snap
src/tag-editor/__tests__/tag-editor.test.tsx
src/tag-editor/index.tsx
src/tag-editor/interfaces.tsx

There's some info text below the add button in the tag editor specifying the number of tags that can be added. Text like "You can add up to N _more_ tags" doesn't read well in the empty state, where there aren't any tags to begin with. This PR allows devs to write an empty state only message in a cleaner way:
```javascript
tagLimit: (availableTags, tagLimit) =>
availableTags === tagLimit
? `You can up to ${tagLimit} tags.`
: availableTags === 1
? 'You can add up to 1 more tag.'
: `You can add up to ${availableTags} more tags.`,
```
Thankfully, function arity isn't checked by TypeScript, so this is a backward compatible change.
Visual tests, basically. The dev pages build fine and this change should be reflected as internal screenshot changes.
[*Do the changes include any API documentation …

feat(tag-editor): Provide tag limit to the additional info i18n callback

---

src/select/__tests__/use-select.test.ts
src/select/utils/use-select.ts

Add aria-controls to combobox
Manually test and unit test.
AWSUI-18450
<details>
</details>

fix: Add ariacontrols to combobox

---

src/app-layout/__integ__/app-layout-split-panel.test.ts
src/app-layout/index.tsx
src/app-layout/visual-refresh/context.tsx
src/app-layout/visual-refresh/layout.tsx
src/app-layout/visual-refresh/split-panel.tsx
src/split-panel/utils/size-utils.ts

Fixing the poor experience when the page is zoomed to 200%. The split panel is too small at that zoom level, and we don't allow resizing because it hits all the minimum/maximum thresholds for the split panel at that size.
Had a chat with a bunch of folks in the team about the "right" way to do this and I think this is the best middle ground of complexity. Adding all the complexity to measure the mobile app bar is way too unnecessary, but doing % or static difference of clientHeight didn't work great in local testing because a single line additional line of header text or the addition of a footer could end up changing the available height by 10-20%, so it could be anything from 60-85%.
So, I just lift the height calculation into the context level (don't see anything "wrong" with that), and …

fix(app-layout): Allow split panel to extend to full height on height-constrained viewports

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/flashbar/interfaces.ts

`@visualrefresh` has to be below the general list, otherwise it will be cut in two
Locally launched our doc website, it renders correctly now
Affected docs page: https://cloudscape.design/components/flashbar/?tabId=api
<details>
</details>

fix markdown issues in flashbar documentation

---

src/icon/__tests__/icon-ssr.test.tsx
src/icon/__tests__/icon.test.tsx
src/icon/internal.tsx

Icons don't have a contextual height when used with `size="inherit"` until TTI.
Only locally. Do it yourself:
```
<div dangerouslySetInnerHTML={{
__html: ReactDOMServer.renderToString(<Icon name="external" size="inherit" />)
}} />
```
AWSUI-18521
<details>
Only manual testing for now, we probably need to do SSR stuff in a more comprehensive way.
</details>

fix(icon): Improve default size when server rendering

---

src/app-layout/visual-refresh/hooks/__tests__/use-dynamic-overlap.test.tsx
src/app-layout/visual-refresh/hooks/use-dynamic-overlap.ts
src/container/internal.tsx
src/internal/components/content-layout/index.tsx
src/wizard/wizard-form-header.tsx

Introduces new `useDynamicOverlap` hook, which centralizes the needed code into a common utility hook. Further, it also fixes issues, where the dynamic overlap will not be reset. 
closes #83 
Unit tests
<details>
</details>

refactor: Add useDynamicOverlap hook

---

pages/calendar/simple.page.tsx
src/date-picker/calendar/index.tsx
src/date-picker/index.tsx

Move focusedDate state inside date picker calendar to separate the concerns better.
Existing tests
<details>
</details>

Move focusedDate state inside date picker calendar

---

src/app-layout/visual-refresh/hooks/use-dynamic-overlap.ts

In this n-to-1 mapping between context and utility hook, `disabled` means **no effect at all**. Otherwise, the last call takes precedence leading to unexpected behavior. 
Screenshot testing.
<details>
</details>

fix(dynamic-overlap) No set on disabled

---

src/date-picker/calendar/index.tsx
src/date-picker/index.tsx
src/internal/components/focus-lock/index.tsx
src/internal/components/focus-lock/utils.ts

The date picker calendar has a tricky focusing logic as it requires to focus on the date buttons every time when a keyboard selection is made. Also, the calendar is automatically focused when rendered. That is not suitable if the calendar needs to be rendered as standalone.
<details>
</details>

Refactor focus handling in the date-picker calendar

---

src/link/internal.tsx

This moves the `onFollow` event of (the button variant of) the Link to be fired when the key is pressed down instead of when the key is released.
This aligns it with the behaviour of the native HTML button and the Cloudscape button.
It also prevents an issue that occurs when the Link is used to open a Model: when closing the Modal by pressing and releasing the Enter key, the Link used to fire an `onFollow` event (because it caught the releasing of the key) where it shouldn't.
_How did you test to verify your changes?_  
Manual testing in the dev pages
_How can reviewers test these changes efficiently?_  
Modify `pages/modal/simple.page.tsx` to use a Link (without href) instead of a button, and open and close the Modal using the Enter key.
[_Check for unexpected visual regressions, see …

fix(link): Fire event on keyDown instead of keyUp

---

package.json

Removes IE11 from browserslist config. 
https://aws.amazon.com/blogs/aws/heads-up-aws-support-for-internet-explorer-11-is-ending/
Not
<details>
</details>

chore: Removal IE11 from browserslist config

---

src/date-range-picker/calendar/header/button/index.tsx
src/date-range-picker/calendar/header/index.tsx
src/date-range-picker/calendar/index.tsx

Refactor date picker calendar by removing unneeded variable.
Existing tests -- no behaviour changes expected
<details>
</details>

Remove calendarHasFocus from date-range-picker/calendar as unneeded

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/property-filter/interfaces.ts

Improving some of the documentation of [Property filter](https://cloudscape.design/components/property-filter/). When the default Equals operator ("=") is excluded from the list of `operators`, customers need to also specify a new `defaultOperator`. The motivation with this change is to make that dependency more clear.
Before (see https://cloudscape.design/components/property-filter/?tabId=api):
> * operators [Array]: A list of all operators supported by this property. **Equals operator should always be supported, even if you omit it in the list.**
> * defaultOperator [ComparisonOperator]: Optional parameter that changes the default operator used with this filtering property. Use it only if your API does not support "equals" filtering terms with this property.
After:
> * operators …

docs(property-filter): Improve documentation of `defaultOperator`

---

src/property-filter/__tests__/utils.test.ts
src/property-filter/controller.ts
src/property-filter/utils.ts

Parse property filter operators in about the same way as property names to support wider range of operators anticipating new non-symbolic operators.
Existing unit- and integration tests, manual testing.
New unit tests were added to cover the new utils.
<details>
</details>

Refactor property-filter operator parsing to support wider range of operators

---

src/date-range-picker/calendar/index.tsx
src/date-range-picker/dropdown.tsx
src/date-range-picker/index.tsx

This change moves the start of week normalization from the date range picker level to the calendar level (as was done with date picker calendar)
Existing tests
<details>
</details>

Move startOfWeek normalization to the date range picker calendar

---

pages/dropdown/focus-trap.page.tsx
src/autosuggest/internal.tsx
src/internal/components/dropdown/__integ__/dropdown-focus-trap.test.ts
src/internal/components/dropdown/index.tsx
src/internal/components/dropdown/interfaces.ts

Add dropdown focus trap as a generalised solution over recovery focus trap in autosuggest.
The change is needed to decouple autosuggest trigger and footer.
Added new integration tests.
<details>
</details>

Add dropdown focus trap

---

src/date-picker/calendar/index.tsx
src/date-picker/calendar/utils/locales.ts
src/date-range-picker/calendar/index.tsx

We were previously duplicating this normalizeStartOfWeek functionality across both date picker and date range picker. This PR creates a shared function to be used by both
Existing tests
<details>
</details>

Make startOfWeek normalization a shared function for date (range) picker

---

src/progress-bar/internal.tsx

Removes redundant `aria-valuemax` in favor of using just the `max` attribute
Built locally and reviewed rendered HTML to confirm that` aria-valuemax `has been removed 
- [ X] _No._
See AWSUI-18906﻿
<details>
- [x ] _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](CONTRIBUTING.md#public-apis)._
- [x ] _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](CONTRIBUTING.md#browsers-support)._
- [x ] _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._
</details>
By submitting …

remove aria-valuemax from progress bar

---

src/internal/components/option/index.tsx
src/internal/components/option/option-parts.tsx

Converts divs that are parts of an option item into spans because they are sometimes the child of a button tag and buttons cannot have div children
* Visual Diff
* Inspected rendered DOM
* Validated with W3C Nu Validator
AWSUI-18930
<details>
</details>

convert select option item divs into spans to preserve HTML validity

---

src/split-panel/__tests__/split-panel.test.tsx
src/test-utils/dom/split-panel/index.ts

Added a test-utility to asset split panel header content
Updated existing unit test to cover this feature
<details>
</details>

feat: Add test-util for split panel header

---

src/annotation-context/annotation/annotation-popover.tsx

Removed unnecessary `preventDefault` wrapper, which was preventing annotation-popover links to be opened.
Locally and with existing tests.
<details>
- [] _Changes are covered with new/existing integration tests?_
</details>

chore: Remove preventDefault from annotation-popover to allow links to work

---

src/app-layout/__integ__/app-layout-split-panel.test.ts
src/app-layout/index.tsx

Fix bug (AWSUI-19070) where AppLayout content would be hidden by split panel when it's repositioned
Tested locally & new integ test
<details>
</details>

fix: Ensure split panel resizes content area correctly when repositioned

---

src/date-range-picker/index.tsx
src/date-range-picker/styles.scss

Format date-range-picker absolute range as string which allows to decouple the formatter from styling.
Existing tests. Manually checked responsiveness.
<details>
</details>

Format date-range-picker absolute range as string

---

src/table/__tests__/selection.test.tsx
src/table/use-selection.ts

This solves an issue when the user has a pagination with checkboxes in the table and tries to select an item and then go the next page, in this case the checkbox in the table's header will not be selected and this is not desired.
To test the problem you can go to `light/table/sticky-header-scrollable-container` page and try with/without this change.
<details>
_The following items are to be evaluated by the author(s) …

fix: Set indeterminate property to true if there are selected items

---

pages/date-input/permutations.page.tsx
src/date-picker/index.tsx
src/date-range-picker/calendar/index.tsx
src/internal/components/date-input/__tests__/date-input.test.tsx
src/internal/components/date-input/index.tsx

Use iso dates in date input to avoid conversion on the consumer side. Necessary to make different date components compatible, (see [example](https://github.com/cloudscape-design/components/pull/166/files#diff-4d9ae9648adfb58e4bcf4f9f26729adc8aef14f7491b76f79981f43f56ef8e7aR1106)).
Updated existing unit tests
<details>
</details>

Use iso dates in date input

---

pages/mixed-line-bar-chart/thresholds.page.tsx

Add charts thresholds examples for time scale. The time scale is different as the dates are compared by reference.
Manual tests.
<details>
</details>

Add charts thresholds examples for time scale

---

pages/popover/scenarios.page.tsx
src/popover/__integ__/popover-placement.test.ts
src/popover/body.scss

Changed the `max-width` of the `large` Popover in smaller viewports.
Locally, existing tests and new test for the smaller viewport.
Use the `Popover` component with `size="large"` and set your viewport width to 400px.
AWSUI-19009
<details>
- [] _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …

chore: Adjust large popover max-width on smaller viewports

---

src/internal/utils/date-time/__tests__/shift-timezone-offset.test.ts
src/internal/utils/date-time/shift-timezone-offset.ts

Shift timezone offset correctly when UTC timezone indicator is used.
When found an UTC timezone indicator it must be excluded when shifting the offset. The regression was introduced here: https://github.com/cloudscape-design/components/commit/5fb56014a78127fe345c95c8c45d19d03eaf1a2b. See [original implementation](https://github.com/cloudscape-design/components/commit/5fb56014a78127fe345c95c8c45d19d03eaf1a2b#diff-1784082b42c1ceb0d2b5e4faab3708be97eee646281975067cf907c5d662d1b0L132).
Added additional unit test to cover the condition.
<details>
</details>
By …

Shift timezone offset correctly when UTC timezone indicator is used

---

pages/button-dropdown/item-element.permutations.page.tsx
src/button-dropdown/__tests__/button-dropdown-navigation.test.tsx
src/button-dropdown/__tests__/use-highlighted-menu.test.ts
src/button-dropdown/category-elements/category-element.tsx
src/button-dropdown/category-elements/expandable-category-element.tsx
src/button-dropdown/category-elements/mobile-expandable-category-element.tsx
src/button-dropdown/category-elements/styles.scss
src/button-dropdown/interfaces.ts
src/button-dropdown/internal.tsx
src/button-dropdown/item-element/index.tsx
src/button-dropdown/item-element/styles.scss
src/button-dropdown/items-list.tsx
src/button-dropdown/utils/use-button-dropdown.ts
src/button-dropdown/utils/use-highlighted-menu.ts

Split https://github.com/cloudscape-design/components/pull/56 into buttondropdown and select/multiselect/autosuggest. This is buttondropdown part.
Changes:
1. change to blue border on focused items
2. add more content for screenshot test
3. add unit test 
Why:
to meet a11y color contrast criteria
consistent with other focus indicator in the system
indicate hover focus and select state with more noticeable different style
AWSUI-15375
<details> …

Improve focus indicator on buttondropdown

---

pages/app-layout/with-breadcrumbs.page.tsx
src/app-layout/visual-refresh/app-bar.scss

AWSUI-19088
Ensure that breadcrumb behavior in VR matches classic - truncated with ellipsis rather than overflowing container.
Tested in dev pipeline, inc. visual refression
AWSUI-19088
<details>
</details>

fix: Ensure that breadcrumb behavior in VR matches classic

---

pages/property-filter/property-filter-autosuggest.page.tsx
src/autosuggest/internal.tsx
src/property-filter/__tests__/controller.test.ts
src/property-filter/__tests__/property-filter-autosuggest.test.tsx
src/property-filter/controller.ts
src/property-filter/index.tsx
src/property-filter/property-filter-autosuggest.tsx

Property filter uses autosuggest internally but requires more features that the public autosuggest API has to offer. The coming changes to the property filter (see https://github.com/cloudscape-design/components/pull/166) would only worsen this problem.
In this PR a new internal property-filter-autosuggest component is introduced that is similar to autosuggest but includes the property filter-related changes. Those extra properties are removed from the internal autosuggest as no longer required.
<details>
</details>
By submitting this pull …

Introduce property-filter-autosuggest derived from internal autosuggest

---

pages/tabs/responsive-integ.page.tsx
src/tabs/__integ__/tabs.test.ts
src/tabs/tab-header-bar.tsx

The default behavior of the buttons is a formAction of submit. This changes it to none so that it if used in a form it will not submit the form when scrolling left and right.
We currently have a [test for outer from submissions](https://github.com/cloudscape-design/components/blob/main/src/__tests__/outer-form-submit.test.tsx), however these buttons are not visible in wider view ports and we cannot set a viewport for this test as it's executed in jsdom.
Updated integ test page and added an integ test and validate that no form submission occurs. In this integ test a form submission would trigger a navigation, so we test that no …

chore(tabs): Change overflow button navigation formAction to none

---

src/breadcrumb-group/__tests__/breadcrumb-group.test.tsx
src/breadcrumb-group/__tests__/breadcrumb-item.test.tsx
src/breadcrumb-group/item/item.tsx

Removed href on last breadcrump in a group so that we can use aria-disabled on it while retaining validity of the HTML. 
* Ran axe-core against build
* Validated rendered HTML in W3C Nu Validator
* Inspected rendered DOM
AWSUI-18939
<details>
</details>

Ensure last breadcrumb doesn't have an href so that it can have aria-disabled="true"

---

src/property-filter/controller.ts
src/property-filter/interfaces.ts

To support new extended operators in collection-hooks the filtering property type has to be generic. Also, the new operator type can be an object. See https://github.com/cloudscape-design/collection-hooks/pull/21, https://github.com/cloudscape-design/collection-hooks/pull/22.
Manual testing
<details>
</details>

Update property filter types to prepare for collection hooks changes

---

src/checkbox/internal.tsx
src/checkbox/styles.scss
src/internal/components/abstract-switch/__tests__/abstract-switch.test.tsx
src/internal/components/abstract-switch/index.tsx
src/internal/components/abstract-switch/styles.scss
src/radio-group/radio-button.tsx
src/radio-group/styles.scss
src/toggle/internal.tsx
src/toggle/styles.scss

Refactored abstract-switch to make outline style definition better encapsulated so that consumer components do not rely on the abstract-switch structure.
<details>
</details>

Make abstract-switch outline definition better encapsulated

---

pages/link/icon-overflow-permutations.page.tsx
pages/link/permutations.page.tsx

The link permutation page is getting worryingly long, and the new permutations aren't helping.
They'll be visually tested.
<details>
</details>

chore(link): Move icon overflow permutations to a new page

---

pages/select/item.permutations.page.tsx
pages/selectable-item/permutations.page.tsx
src/autosuggest/__tests__/controller.test.ts
src/autosuggest/autosuggest-option.tsx
src/autosuggest/controller.ts
src/autosuggest/internal.tsx
src/autosuggest/options-controller.ts
src/autosuggest/options-list.tsx
src/autosuggest/plain-list.tsx
src/autosuggest/virtual-list.tsx
src/internal/components/options-list/__tests__/use-highlight-option.test.ts
src/internal/components/options-list/__tests__/use-keyboard.test.ts
src/internal/components/options-list/utils/use-highlight-option.ts
src/internal/components/options-list/utils/use-keyboard.ts
src/internal/components/selectable-item/index.tsx
src/multiselect/internal.tsx
src/property-filter/property-filter-autosuggest.tsx
src/select/__tests__/use-select.test.ts
src/select/internal.tsx
src/select/parts/item.tsx
src/select/parts/multiselect-item.tsx
src/select/parts/plain-list.tsx
src/select/parts/virtual-list.tsx
src/select/utils/render-options.tsx
src/select/utils/use-native-search.ts
src/select/utils/use-select.ts

The isKeyboard ref was used to alter the following change of highlight based on the type of interaction. Instead, the highlight type now depends on the callback method being used. The `setHighlightedIndex` is used for mouse highlight and all other - for keyboard highlight.
Updated existing tests
<details>
</details>

Remove unnecessary isKeyboard ref from use-highlighted-option

---

src/__a11y__/to-validate-a11y.ts
src/__tests__/test-a11y-validator.test.tsx

Enable html validator element-permitted-content rule
Should have no violation once we merge https://github.com/cloudscape-design/components/pull/109
<details>
</details>

Enable html validator element-permitted-content rule

---

src/autosuggest/__tests__/controller.test.ts
src/autosuggest/controller.ts
src/autosuggest/dropdown-controller.ts
src/autosuggest/internal.tsx
src/autosuggest/options-controller.ts
src/property-filter/property-filter-autosuggest.tsx

This refactoring is a step towards creating an abstract autosuggest to be shared between public autosuggest component and property-filter. The autosuggest items and dropdown logic was decoupled as the abstract variant can have any content, not only an options list.
Updated unit tests to cover the changed hooks structure.
<details>
</details>

Decouple autosuggest items and dropdown controllers

---

src/app-layout/__integ__/app-layout-split-panel.test.ts
src/split-panel/__tests__/split-panel.test.tsx
src/split-panel/index.tsx

Reverts cloudscape-design/components#215
This change introduced a visual regression on the split panel inside the app-layout/with-split-panel example page.

Revert "AWSUI-18910 : Splitpanel slider made keybaord accessible when position is on side"

---

src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/dropdown-controller.ts

Align autosuggest focus behaviour with select. When browser tab is left - the dropdown stays open.
Select uses the same mechanism, see:
* https://github.com/cloudscape-design/components/blob/main/src/select/utils/use-select.ts#L184
* https://github.com/cloudscape-design/components/blob/main/src/input/internal.tsx#L136
* Ticket AWSUI-19147
<details>
</details>

Align autosuggest focus behaviour with select

---

src/date-picker/calendar/__tests__/calendar.test.tsx
src/date-picker/calendar/index.tsx
src/date-picker/calendar/utils/move-focus-handler.ts

This change fixes two issues:
1) Scenario value set to a day in March, all dates <= April are disabled:
When opening the date picker, April was shown as month because and not march as the value stated.
With this change, March is now shown instead of April to reflect the current input value.
2) When attempting to use isDateEnabled given a set of available dates, there was an issue when the list of available dates was not continuous by month. E.g. if the following dates `['2022-04-14', '2022-03-14', '2022-01-14']` are enabled, the component was not allowing to go back to previous months: navigating from March 2022 into the past was not possible (making 2022-01-14 inaccessible).
- tested manually.
- add additional unit tests to cover the fix.
[*Do the changes include any API documentation …

fix(date-picker): Fix baseDate handling when navigating through the calendar

---

src/app-layout/navigation-panel.tsx
src/app-layout/styles.scss

For some text-heavy scenarios, the user may find that the scroll position gets lost as they resize the window.
If you think about it programmatically, it makes sense. The page is scrolled by a fixed `N` pixels, and when you shrink the content, the previous paragraphs reflow and take up more height, so the paragraph you were reading may move down your screen (or vice versa).
Thankfully, browsers have a solution to this, called [scroll anchoring](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor/Guide_to_scroll_anchoring). In short, the browser picks an element to keep fixed in a position relative to the viewport. So if you're reading an article and a huge ad pops up higher in the page, it won't mess with you. Unfortunately, in our case, the browser is picking the left …

fix(app-layout): Fix scroll anchoring breaking on desktop classic app layout

---

src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/autosuggest-option.tsx
src/internal/components/selectable-item/index.tsx
src/multiselect/__tests__/multiselect.test.tsx
src/select/__tests__/select-a11y.test.tsx
src/select/parts/item.tsx
src/select/parts/multiselect-item.tsx

Currently aria-selected is set only when the value is true. However it should be set to true/false when select is possible. Aria-checked needs be set when it is multi-selection.  Aria-selected and aria-checked should not be set at the same time. 
AWSUI-18451
<details>
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …

fix: Option should have aira-selected or aria-checked

---

src/header/interfaces.ts

closes #241 
`HeaderProps` namespace wasn't exported so consumers of the library couldn't import it's properties like`Varinat` and `HeadingTag`
manually by importing `HeaderProps.Variant` in one of the pages files
https://github.com/cloudscape-design/components/issues/241
<details>
</details>

fix(header): Export HeaderProps namespace

---

src/date-range-picker/index.tsx
src/internal/utils/date-time/__tests__/format-date-range.test.ts
src/internal/utils/date-time/format-date-range.ts
src/internal/utils/date-time/index.ts

Extract formatDateRange util from date range picker and add tests for it.
New unit test.
<details>
</details>

Move format date range util from DRP to internal date-time utils

---

src/code-editor/ace-editor.scss
src/code-editor/index.tsx
src/code-editor/styles.scss

Allows to set a custom value for code editor border radius. The fix is needed before making the border radius themeable (https://github.com/cloudscape-design/components/pull/221)
[_How did you test to verify your changes?_] Locally
https://github.com/cloudscape-design/components/pull/221
- [N/A] _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._
- [N/A] _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` …

fix(code-editor): Allow for correct border radius theming

---

src/autosuggest/internal.tsx
src/autosuggest/styles.scss
src/internal/components/autosuggest-input/__tests__/autosuggest-input.test.tsx
src/internal/components/autosuggest-input/index.tsx
src/internal/components/autosuggest-input/styles.scss
src/property-filter/controller.ts
src/property-filter/index.tsx
src/property-filter/property-filter-autosuggest.tsx
src/test-utils/dom/internal/autosuggest-input.ts

Move autosuggest input to internal components and add corresponding internal test util.
A follow up from https://github.com/cloudscape-design/components/pull/240.
Existing unit tests.
<details>
</details>

Move autosuggest input to internal components

---

src/container/styles.scss

Allows to set a custom value for the container border radius without impacting the bottom left/right radius of container header. Needed to make container border radius themeable (https://github.com/cloudscape-design/components/pull/221).
[_How did you test to verify your changes?_] Locally
https://github.com/cloudscape-design/components/pull/221
- [N/A] _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._
- [N/A] _If the code …

fix(container): Allow for correct border radius theming

---

style-dictionary/visual-refresh/metadata/borders.ts

Make border radius design tokens public and themeable

feat: Make border-radius design tokens public and themeable

---

src/date-picker/styles.scss
src/date-range-picker/styles.scss
src/internal/styles/forms/mixins.scss

This change updates the radius of the focus outline for the dropdown part of the Date Picker and the Date Range Picker. While the dropdown acts as a container, it has a different `border-radius` than the Container component. The radius for the focus outline did not match this different border-radius.
_How did you test to verify your changes?_  
Manual testing in the browser
_How can reviewers test these changes efficiently?_  
- Open http://localhost:8080/#/light/date-picker/simple
- Focus the input field
- Press <kbd>Tab</kbd> to move the focus to the button, and <kbd>Enter</kbd> to open the dropdown
- Observe the focus radius around the dropdown
*Do the changes …

fix(date-picker,date-range-picker): Focus outline radius

---

src/container/internal.tsx
src/container/styles.scss
src/expandable-section/expandable-section-container.tsx

https://github.com/cloudscape-design/components/pull/243 introduced a regression in bottom border radius of expandable section with `variant=container`. This change addressed the regression.
[_How did you test to verify your changes?_] Locally
https://github.com/cloudscape-design/components/pull/243
- [N/A] _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._
- [N/A] _If the code …

fix: Rounded corners in container variant of expandable section

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/icon/interfaces.ts

Update API description of alt to specify url instead of "custom icon", because alt only applies when url is set (see [code](https://github.com/cloudscape-design/components/blob/main/src/icon/internal.tsx#L99)), also being more consistent with [guideline writing](https://polaris.a2z.com/components/icon/?tabId=usage&props=N4IgdghgtgpiBcIDOMAuqCWYDmSQBpkMAvORMAewCcoIAbAkANwiowjFQXGtocICuVBohABfIA#:~:text=For%20custom%20icons%20(using%20the%20url%20attribute)%2C%20use%20the%20alt%20attribute%3A)
**AWSUI-18904** …

Update icon alt description

---

src/code-editor/ace-editor.scss
src/code-editor/index.tsx
src/code-editor/styles.scss
style-dictionary/visual-refresh/metadata/borders.ts

- Reverting a CSS change that caused build issue
- Making `borderRadiusCodeEditor`token private, as its themeability depends on that CSS change.
Locally
- [N/A] _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._
- [N/A] _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/interna …

Fix code editor build

---

pages/autosuggest/autosuggest-input.page.tsx
src/autosuggest/internal.tsx
src/internal/components/autosuggest-input/__integ__/autosuggest-input.test.ts
src/internal/components/autosuggest-input/__tests__/autosuggest-input.test.tsx
src/internal/components/autosuggest-input/index.tsx
src/internal/components/dropdown/index.tsx
src/internal/components/dropdown/interfaces.ts
src/property-filter/controller.ts
src/property-filter/index.tsx
src/property-filter/property-filter-autosuggest.tsx

The autosuggest input was extracted out from autosuggest (see https://github.com/cloudscape-design/components/pull/240, https://github.com/cloudscape-design/components/pull/246).
It works well when having a list of options as its content, but requires changes to support different content which might not require click to be muted and can have different size.
This is done in preparation for custom content in property filter (see https://github.com/cloudscape-design/components/pull/166).
Added new unit and integ tests.
<details>
</details>
By submitting this pull …

Make autosuggest input support custom content

---

src/table/__tests__/table.test.tsx
src/table/header-cell/index.tsx

This PR adds the `scope` attribute to column headers in the Table component.
Motivation:
Most a11y guidelines recommend adding `scope='col'` to `th` elements. Example [[ref]](https://www.a11yproject.com/posts/accessible-data-tables/#row-and-column-headings:~:text=Column%20headers%20should,should%20be%20unique.)
I've added a unit test to confirm that the attribute is rendered.
Run the unit test, and check in browser.
No visual regressions
<details> …

fix(table): add scope attribute on column headers

---

src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/index.tsx
src/property-filter/property-filter-autosuggest.tsx

Property filter autosuggest component requires both autosuggest.root and property-filter.input classes.
Added new unit tests.
<details>
</details>

Fix property filter input classes assignment

---

src/property-filter/styles.scss
src/property-filter/token-editor.tsx

Add separator to the property filter token editor between editor form and actions, same as in the date range picker.
Manual testing, screenshot testing.
<details>
</details>

Add property filter token editor actions separator

---

src/property-filter/__integ__/async-loading.test.ts
src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/styles.scss
src/property-filter/token-editor.tsx

Use grid layout for property filter token editor to prepare for non-select (custom) fields that can be wider than 200px.
Reference: https://github.com/cloudscape-design/components/pull/166
Screenshot tests.
<details>
</details>

Use grid layout for property filter token editor

---

pages/property-filter/common-props.ts
pages/property-filter/table.data.ts
pages/property-filter/token-editor.page.tsx

Extended property filter token editor test page with datetime and boolean props. The new test scenario is to be covered with screenshot tests to expectedly fail when the custom properties support is added (ref: https://github.com/cloudscape-design/components/pull/166).
Screenshot tests.
* CR-75879700
<details>
</details>

Add custom props test pages for property filter

---

style-dictionary/utils/contexts.ts

Add empty flashbar context for CR-75880450
To prepare for pr https://github.com/cloudscape-design/components/pull/194
In order to change focus indicator border color in flashbar context 
<details>
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

Add empty flashbar context

---

src/input/internal.tsx

Disabling the `spellCheck` from `Input` component, this will be followed up with another PR adding a new API to allow the customer to control the `spellCheck` in our component.

fix: Make spellCheck to false in input

---

src/property-filter/styles.scss
src/property-filter/token-editor.tsx

The use of our form field simplifies the existing code and makes adding custom forms easier.
Approved by the design.
Screenshot tests.
<details>
</details>

Use form field internally in property filter token editor

---

pages/flashbar/permutations.page.tsx

Replace custom label definitions with a generic function
A11y tests in the PR build
<details>
</details>

auto-fill flashbar labels on permutation page

---

src/input/internal.tsx
src/textarea/__tests__/textarea.test.tsx
src/textarea/index.tsx

This change disables spellchecking in the Input component and the Textarea component.
Tested locally in dev pages.
n/a
<details>
</details>

Disable spellchecking in Input and Textarea

---

src/date-range-picker/styles.scss

Remove unnecessary grid for date-only drp input layout.
Manual tests.
<details>
</details>

Simpler css for drp date-only input layout

---

pages/flashbar/dismissal.page.tsx
style-dictionary/classic/contexts/flashbar.ts
style-dictionary/classic/index.ts
style-dictionary/visual-refresh/index.ts

AWSUI-18907
Blue focus indicator in flashbar (info error) in classic has a contrast ratio of less than 3:1 
Change the focus indicator color to grey-100 as VR
Added screenshot test  CR-75687450
<details>
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

Change color of focus indicator of actionable elements in flashbar

---

src/autosuggest/__tests__/autosuggest.test.tsx
src/internal/components/autosuggest-input/index.tsx
src/internal/components/dropdown/index.tsx
src/internal/components/dropdown/interfaces.ts
src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/property-filter-autosuggest.tsx

When no options found but the empty state or "use" option is present - show the dropdown but set the aria-expanded as "false". In property filter when disableFreeTextFiltering=true it is possible for the dropdown to be hidden completely.
Manual tests.
<details>
</details>

Fix autosuggest and property filter dropdown expanded state

---

src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/styles.scss
src/property-filter/token-editor.tsx

When property key changes the old value is likely to no longer be meaningful. Clear it.
That is even more important for the custom props, see https://github.com/cloudscape-design/components/pull/166. 
Updated existing unit test.
<details>
</details>

In token editor clear value when property key changes

---

pages/annotation-context/with-hotspot-inside-switch.page.tsx
pages/tiles/permutations.page.tsx
src/annotation-context/annotation/annotation-popover.tsx
src/annotation-context/annotation/annotation-trigger.tsx
src/app-layout/__integ__/app-layout-split-panel.test.ts
src/button/__tests__/button.test.tsx
src/checkbox/__tests__/checkbox.test.tsx
src/checkbox/__tests__/common-tests.tsx
src/checkbox/internal.tsx
src/internal/components/abstract-switch/__tests__/abstract-switch.test.tsx
src/internal/components/abstract-switch/index.tsx
src/radio-group/__integ__/label-styling.test.ts
src/radio-group/__tests__/radio-group.test.tsx
src/radio-group/radio-button.tsx
src/table/__integ__/resizable-columns.test.ts
src/table/selection-control/index.tsx
src/tiles/__tests__/tiles.test.tsx
src/tiles/internal.tsx
src/toggle/__tests__/toggle.test.tsx
src/toggle/internal.tsx

when a Hotspot is placed inside a checkbox label (or the label of a Toggle, Radio Button or Tile) and the user clicks on an element inside the Hotspot's Annotation popover, this click event also bubbles up to the checkbox's `<label>` element. This then triggers a duplicated/redirected event on the native `<input>` element.
While the bubbling of the first click event can be prevented with `e.stopPropagation`, this does not prevent the dispatching of the second event. According to [this StackOverflow answer](https://stackoverflow.com/a/67613046), this is known _"legacy-pre-activation behavior"_ and cannot be prevented since it is part of the WHATWG specification - the label->input event duplication/redirection happens before the actual event dispatching.
This change deactivates the legacy …

fix: Hotspot events inside a checkbox label unexpectedly toggle the checkbox

---

build-tools/utils/files.js
pages/popover/container-test.page.tsx
pages/popover/scrollable.page.tsx
pages/popover/text-wrap.page.tsx
src/annotation-context/annotation/annotation-popover.tsx
src/area-chart/__tests__/area-chart-initial-state.test.tsx
src/button-dropdown/tooltip.tsx
src/internal/components/chart-popover/index.tsx
src/popover/__tests__/positions.test.ts
src/popover/body.scss
src/popover/body.tsx
src/popover/container.scss
src/popover/container.tsx
src/popover/internal.tsx
src/popover/utils/positions.ts

When popover content is tall sometimes it can be cut by the viewport. The fix allows the content to become scrollable when necessary.
* Manual tests for overflow using new test page;
* Screenshot tests;
* Existing placement integration tests;
* New unit tests for updated positioning logic.
<details>
</details>

Make popover body scrollable when needed

---

src/form-field/internal.tsx
src/test-utils/dom/form-field/index.ts

#202 changed the test util to contain both the error icon and the error message, where it previously contained just the error message text. Unfortunately, this is a breaking change, so it's best to revert for now.
No visual changes, just a "revert". This mostly only affects tests that check DOM structure instead of text, so our own tests don't fail. And I'm not inclined to write a test to assert a DOM structure.
<details>
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

fix(form-field): Restore findError() selector to keep backwards compatibility

---

pages/checkbox/styles.scss
pages/radio-group/styles.scss
pages/toggle/styles.scss
src/internal/components/abstract-switch/index.tsx

This updates the selector in the custom styles used in our screenshot test. The test checks that the clickable area does not change.
Manual testing in dev pages (e.g. http://localhost:8080/#/light/checkbox/labels-highlight )
<details>
</details>

fix: Label highlight in screenshot tests

---

pages/calendar/integ.page.tsx
pages/calendar/simple.page.tsx
pages/date-picker/permutations.page.tsx
pages/date-picker/positioning.page.tsx
pages/date-picker/simple.page.tsx
pages/date-picker/with-default-date.page.tsx
pages/date-picker/with-event-handlers.page.tsx
pages/date-range-picker/embedded.page.tsx
pages/date-range-picker/simple.page.tsx
pages/date-range-picker/small-viewport.page.tsx
src/calendar/__tests__/calendar.test.tsx
src/calendar/internal.tsx

Use normalised locale for start of week calculation in calendar.
Manual check with dev-tool sensors and unit tests.
<details>
</details>

Use correct locale for start of week in calendar

---

build-tools/utils/files.js
src/__tests__/__snapshots__/documenter.test.ts.snap
src/__tests__/form-field-controls-integration.test.tsx
src/__tests__/utils.ts
src/autosuggest/interfaces.ts
src/calendar/__integ__/calendar.test.ts
src/calendar/__tests__/calendar.test.tsx
src/calendar/interfaces.ts
src/calendar/internal.tsx
src/date-input/__integ__/date-input.test.ts
src/date-input/__tests__/date-input.test.tsx
src/date-input/index.tsx
src/date-input/internal.tsx
src/input/interfaces.ts
src/input/internal.tsx
src/internal/components/autosuggest-input/index.tsx
src/textarea/interfaces.ts
src/time-input/interfaces.ts

Release date input and calendar.
Manual check of the build outputs, documenter test.
The API docs were reviewed separately in the website integration.
<details>
</details>

Make date-input and calendar public

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/radio-group/interfaces.ts

ControlId of RadioGroup has no effect. There is ControlId of individual RadioButton in RadioGroup (items), which is in use and attach to each RadioButton input. No group form element to attach to the ControlId of RadioGroup.
Decision discussed and made in doc _Checkbox-Toggle-and-Formfield-controlId-association_
<details>
</details>
By …

deprecate controlid of radiogroup

---

src/cards/__tests__/cards.test.tsx
src/cards/index.tsx
src/container/internal.tsx

This PR adds aria label relation between cards header and cards. It also adds the `role` attribute on cards list.
Related Ticket: **AWSUI-19077**
I've added some unit tests.
<details>
- [] _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._ …

fix(card): add aria label support and role for cards

---

src/input/__tests__/input.test.tsx
src/input/internal.tsx

Comment in the code explains it all.
// Chrome and Safari have a weird built-in behavior of letting focused
// number inputs be controlled by scrolling on them. However, they don't
// lock the browser's scroll, so it's very easy to accidentally increment
// the input while scrolling down the page.
Limiting the scope of this to number inputs because Firefox also fires wheel events as the mouse goes past the input, and not just starting a scroll on it like it does with Safari and Chrome. So if this starts happening everywhere, it would get annoying.
Couldn't really figure my way around emulating "real" scroll with webdriverio, so I just went with the unit test route.
AWSUI-19371
<details>
_The …

fix(input): Prevent scrolling from changing value of number inputs

---

src/split-panel/__tests__/split-panel.test.tsx
src/split-panel/index.tsx
src/split-panel/styles.scss
src/split-panel/utils/use-pointer-events.ts

https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events
Basically, renamed all "mouse event" stuff to be "pointer event" stuff.
Locally, with unit tests preserved. I would encourage playing around with this on your phones too, but keep in mind you'll have to pull out your phone for this because desktop browsers don't fire touch events.
<details>
- https://caniuse.com/pointer
</details>

fix(split-panel): Support touch events for slider

---

pages/container/simple.page.tsx
src/container/styles.scss

Prior, a fixed height container (for example placed in a 1x1 Grid) would place the footer at the end of the content area and consuming additional vertical space in the footer. This change ensure that the footer sticks to the bottom and gives additional vertical space to the content slot.
Screenshot test
<details>
</details>

feat: Grow content area if additional vertical space is available

---

pages/s3-resource-selector/data/i18n-strings.ts
src/__tests__/__snapshots__/documenter.test.ts.snap
src/s3-resource-selector/__tests__/fixtures.ts
src/s3-resource-selector/__tests__/s3-in-context.test.tsx
src/s3-resource-selector/interfaces.ts
src/s3-resource-selector/s3-in-context/index.tsx

Adds a new key `inContextViewButtonAriaLabel` to the `i18nStrings` of S3 Resource Selector to assign an `aria-label` to the View button.
Tested manually. Adjusted unit tests.
AWSUI-19209
<details>
</details>

feat: Add ability to add aria-label to View button in S3 Resource Selector

---

src/date-picker/__tests__/date-picker.test.tsx
src/date-picker/index.tsx

- Proper role for calendar-picker dialog
- aria-label for calendar-picker
<details>
</details>

AWSUI-19186: proper role for calender dialog and aria-label

---

src/calendar/calendar.scss
src/calendar/styles.scss
src/date-range-picker/calendar/grids/day/styles.scss

A step towards reusing calendar and date-range picker calendar styles.
Manual tests, visual checks.
<details>
</details>

Reuse calendar sass variables

---

src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/index.tsx

When operator is automatically inserted the load details need to be adjusted accordingly.
New unit tests added.
* Ticket: AWSUI-19150
<details>
</details>

Fix property filter on-load-items arguments when operator is inserted

---

src/split-panel/index.tsx
src/split-panel/interfaces.ts
src/split-panel/utils/use-pointer-events.ts

This change updates the calculation of the size of the split panel so that the resize handle is always centered on the cursor while dragging.
_Before: the resize handle is slightly lower than the cursor_
_After: the resize handle is centered on the cursor_
Manual testing in dev pages (http://localhost:8080/#/light/app-layout/with-split-panel), in both bottom and side position.
<details>
</details>
By submitting this pull request, I …

fix(split-panel): Align resize handle with cursor

---

pages/expandable-section/permutations.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/expandable-section/__tests__/expandable-section.test.tsx
src/expandable-section/expandable-section-header.tsx
src/expandable-section/interfaces.ts
src/expandable-section/internal.tsx

Adds a new `headerAriaLabel` property to Expandable Section that adds an explicit `aria-label` to the header button.
This is useful if you have multiple expandable sections with the same title on one page.
Tested manually. Added unit tests.
<details>
</details>

feat: Add `headerAriaLabel` property to Expandable Section

---

pages/modal/focus-restoration.page.tsx
src/modal/__integ__/modal.test.ts
src/modal/__tests__/modal.test.tsx
src/modal/internal.tsx

Make modal focus lock only use auto-focus when the modal is opened but not when the focused element inside the modal gets removed to avoid the unexpected focusing to the close button that may cause scroll.
Manual testing + new integration test.
* Ticket WSUI-19440
<details>
</details>

Fix modal focus lock auto-focus behaviour

---

pages/table/tall-rows.page.tsx
src/table/__integ__/tall-rows.test.ts
src/table/internal.tsx
src/table/use-mouse-down-target.ts

When the table row receives focus it scrolls to its top. However, that is not expected when the element inside table's row is clicked as the scroll action prevents element from receiving the click.
Added new integration tests.
* Ticket: AWSUI-19438
<details>
</details>

Fix table row scroll

---

src/__integ__/__snapshots__/themes.test.ts.snap
style-dictionary/classic/colors.ts

The existing color in dark mode looks like it was correct. The original definition was `colorTextIconCaret`, which is defined as `{ light: '{colorGrey500}', dark: '{colorGrey450}' }`.
For the original PR, I tested the colors I got from Chrome devtools, which doesn't always resolve CSS custom properties correctly, so that's on me 🤦 
Reverted to existing known state. Any visual changes in light more are intentional.
<details>
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

fix(table): Fix incorrect dark mode change in b97589

---

src/breadcrumb-group/item/styles.scss

Make the current page bold in the breadcrumbs. This ensures there is a non-color differentiation between current and parent breadcrumb items.
Tested locally. 
AWSUI-19124
<details>
</details>

fix: Make current breadcrumb item bold

---

src/tabs/tab-header-bar.scss

Firefox, Tabs header starts to scrollable when zoom 133%.
AWSUI-19384
<details>
</details>

Prevent vertical scroll on tabs header

---

src/calendar/__tests__/calendar.test.tsx
src/calendar/grid/index.tsx
src/calendar/internal.tsx
src/calendar/styles.scss
src/date-picker/__tests__/date-picker-calendar.test.tsx

Although the table layout is used the actual behaviour for screen-readers remains unchanged so far due to table's role set to "none" and cell's role set to "button". The next step would be to change the behaviour accordingly.
Visual regression tests, screenshot tests
* AWSUI-19185
<details>
</details>

Use table layout for calendar

---

src/date-range-picker/index.tsx
src/date-range-picker/styles.scss

Before this change, the word beak worked differently on Chrome,
FF and Safari on narrow screens (Safari and FF did not break the
label into two rows at all, Chrome did).
This change adds a work break right after the start or before the end time range throughout all browsers:
- I'm adopting existing screenshot tests to cover the narrow case.
- Checkout this PR, open the `/#/light/date-range-picker/with-default-date` example in Chrome, FF and Safari
- When doing so, set the viewport width to 450px to test the narrow case.
- AWSUI-19387
<details>
</details>
By submitting this pull request, I confirm that you can use, …

fix(date-range-picker): Get consistent label word breaks on narrow screens

---

src/date-range-picker/calendar/grids/day/index.tsx
src/date-range-picker/calendar/grids/grid.tsx

Removed React.memo and React.ref wrappers from date range picker calendar day.
The memo was irrelevant because the onSelectDay handlers created in the calendar wasn't memoized anyway causing all days to re-render whenever selection changes. The memoization can be added back if needed with a more elegant solution e.g. the date objects can be memoized in the parent:
```
const cache = {}
function memoizeDate(date) {
// ...
}
// function Grid
return <GridDay date={memoizeDate(date)} baseDate={memoizeDate(baseDate)} ... />
function GridDay() {...}
export default memo(GridDay) // no need to provide a comparator function
```
No additional tests needed.
<details> …

Refactor date range picker calendar grid

---

src/date-range-picker/calendar/__tests__/calendar.test.tsx
src/date-range-picker/calendar/grids/grid.tsx
src/date-range-picker/calendar/grids/index.tsx
src/date-range-picker/calendar/grids/styles.scss
src/date-range-picker/styles.scss
src/test-utils/dom/date-range-picker/index.ts

Update drp calendar layout to use table but set role to "none" to temporarily keep the old behaviour.
Similar request for calendar component: https://github.com/cloudscape-design/components/pull/343
Visual regression tests and screenshot tests.
* AWSUI-19213
<details>
</details>

Use table layout for drp calendar

---

pages/alert/permutations.page.tsx
pages/alert/simple.page.tsx
pages/app-layout/dark-header-main.page.tsx
pages/content-layout/dark-header-main.page.tsx
pages/content-layout/standalone.page.tsx
pages/content-layout/with-header-toggle.page.tsx
pages/date-range-picker/common.ts
pages/form/permutations.page.tsx
pages/form/simple.page.tsx
pages/s3-resource-selector/permutations.page.tsx
pages/s3-resource-selector/with-alert.page.tsx
pages/wizard/common.ts
src/__tests__/__snapshots__/documenter.test.ts.snap
src/alert/__tests__/alert.test.tsx
src/alert/interfaces.ts
src/alert/internal.tsx
src/date-range-picker/dropdown.tsx
src/date-range-picker/interfaces.ts
src/form/interfaces.ts
src/form/internal.tsx
src/tutorial-panel/interfaces.ts
src/wizard/interfaces.ts
src/wizard/wizard-form.tsx

Add new properties to allow annotate status icon in alert and derived components
Dry-run
<details>
</details>

add statusIconAriaLabel to alert and propagate to other components

---

src/date-picker/index.tsx
src/date-picker/styles.scss
src/internal/components/screenreader-only/index.tsx
src/internal/components/screenreader-only/styles.scss

A follow-up for https://github.com/cloudscape-design/components/pull/351.
Manual testing.
<details>
</details>

Introduce screenreader-only internal component

---

src/date-range-picker/calendar/__tests__/calendar.test.tsx
src/date-range-picker/calendar/header/index.tsx

When DRP calendar header live region is polite the NVDA does not really announce it or announce partially. Making it assertive fixes the problem. The VO behaviour does not change.
Manual testing with Safari/Chrome+VO and Firefox/Chrome+NVDA
* Ticket: AWSUI-19507
<details>
</details>

Fix drp calendar header nvda announcement

---

src/form/__tests__/form.test.tsx
src/form/internal.tsx

Replace aria-live with live-region component in form.
Added new unit test, manual testing with VO and NVDA.
<details>
</details>

Use live region in form component

---

package-lock.json
package.json

Revert "chore(deps): bump d3-color and d3-scale" because it blocks multiple consumers. There's a need to review those, and agree on the next steps.
- existing unit and integ tests run green after the revert.
- N/A
<details>
</details>

Revert "chore(deps): bump d3-color and d3-scale"

---

src/__a11y__/to-validate-a11y.ts
src/__tests__/__snapshots__/documenter.test.ts.snap
src/__tests__/test-a11y-validator.test.tsx
src/attribute-editor/__tests__/attribute-editor.test.tsx
src/attribute-editor/interfaces.ts
src/attribute-editor/internal.tsx
src/attribute-editor/row.tsx
src/tag-editor/__tests__/tag-editor-a11y.test.tsx
src/tag-editor/index.tsx

Added new property to attribute editor component
```ts
/**
* An object containing all the necessary localized strings required by the component.
*/
i18nStrings?: AttributeEditorProps.I18nStrings;
```
```ts
interface I18nStrings {
errorIconAriaLabel?: string;
}
```
Added extra a11y tests, checked that they fail when the labels are missing
<details>
</details>

expose error icon label on attribute editor

---

src/__integ__/page-objects/button-dropdown-page.ts
src/button-dropdown/__integ__/button-dropdown-disabled-reason.test.ts
src/button-dropdown/__integ__/button-dropdown-items.test.ts
src/button-dropdown/internal.tsx

Focus on first menu item of dropdown list when button dropdown is opened so it will be announced in the screen reader
- Added a unit test
- Tested manually, first menu item is announced by screen reader when the dropdown is opened
AWSUI-18913
<details>
</details>

fix(button-dropdown): Focus on first item of dropdown list when it's opened

---

src/date-picker/index.tsx
src/date-range-picker/calendar/index.tsx
src/internal/components/live-region/index.tsx
src/internal/components/live-region/styles.scss
src/internal/components/screenreader-only/index.tsx

Use screenreadaer-only by live-region and live-region by date-picker.
Manual check.
<details>
</details>

Make live-region use screenreader-only

---

src/__integ__/page-objects/button-dropdown-page.ts
src/button-dropdown/__integ__/button-dropdown-disabled-reason.test.ts
src/button-dropdown/__integ__/button-dropdown-nested-click.test.ts
src/button-dropdown/internal.tsx

This reverts commit fb2eeac09572b49f4a54cc8b20d3286acee91c79.
that commit introduced flakiness in button dropdown mobile integ tests
<details>
</details>

Revert "fix: Focus on first item of dropdown list when it's opened

---

src/__a11y__/to-validate-a11y.ts
src/alert/__tests__/alert.test.tsx
src/app-layout/__tests__/main.test.tsx
src/app-layout/__tests__/slots.test.tsx
src/app-layout/__tests__/utils.tsx
src/app-layout/notifications/index.tsx
src/app-layout/visual-refresh/notifications.tsx
src/area-chart/__tests__/area-chart-initial-state.test.tsx
src/date-range-picker/__tests__/date-range-picker-absolute.test.tsx
src/date-range-picker/__tests__/date-range-picker-relative.test.tsx
src/date-range-picker/index.tsx
src/internal/components/chart-popover/index.tsx
src/internal/components/dropdown/index.tsx
src/popover/internal.tsx

Increase a11y coverage in unit tests and fix axe/html-validate reported issues.
New tests
<details>
</details>

Increase a11y test coverage

---

src/date-range-picker/calendar/grids/grid.tsx
src/date-range-picker/calendar/grids/index.tsx
src/date-range-picker/calendar/header/index.tsx
src/date-range-picker/calendar/index.tsx
src/date-range-picker/styles.scss

This change wraps the month names of the absolute range selector in a `heading` role, to improve the announcement in screen readers.
Tested manually with VoiceOver in Chrome & Safari
- AWSUI-19214
<details>
</details>

fix(date-range-picker): Use heading role for month names

---

src/button-dropdown/__integ__/button-dropdown-items.test.ts
src/button-dropdown/internal.tsx
src/button-dropdown/utils/use-button-dropdown.ts

When dropdown is closed the focus returns back to the trigger but only when an item was activated or Escape was pressed. When closing with a TAB or a mouse click the focus should transition to another element instead.
Added new integration test.
A pre-requisite for: https://github.com/cloudscape-design/components/pull/378
<details>
</details>

Fix focus return logic when dropdown is closed

---

pages/date-range-picker/simple.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/date-range-picker/__tests__/date-range-picker-absolute.test.tsx
src/date-range-picker/__tests__/time-offset.test.ts
src/date-range-picker/embedded.tsx
src/date-range-picker/index.tsx
src/date-range-picker/interfaces.ts
src/date-range-picker/time-offset.ts
src/date-range-picker/use-date-range-picker.tsx
src/internal/utils/date-time/__tests__/format-date-range.test.ts
src/internal/utils/date-time/format-date-range.ts

The new getTimeOffset API allowing time offsets to be provided per date to account for daylight savings if different between start and end dates of the selected range.
Usage examples:
```
// Same as default
<DateRangePicker ... getTimeOffset={date => -1 * new Date(date).getTimezoneOffset()} />
// Parse in a custom timezone
import moment from 'moment-timezone'
<DateRangePicker ... getTimeOffset={date => -1 * moment.tz(date, 'America/Toronto')} />
```
* Ticket AWSUI-19513
<details>
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

Introduce getTimeOffset API to date-range picker

---

pages/calendar/simple.page.tsx
pages/date-picker/simple.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/calendar/__tests__/calendar.test.tsx
src/calendar/interfaces.ts
src/calendar/internal.tsx
src/date-picker/__integ__/blur-event.test.ts
src/date-picker/__integ__/page-objects/date-picker-page.ts
src/date-picker/__tests__/date-picker.test.tsx
src/date-picker/index.tsx
src/test-utils/dom/date-picker/index.ts

This PR adds support for announcing a useful name for the Date Picker's dialog and the Calendar component.
<details>
</details>

feat(calendar, date-picker): Improve ARIA labels and description

---

src/input/__tests__/internal.test.tsx
src/input/index.tsx
src/input/internal.tsx

This reverts commit a42106952cf883d5c44529476316a2205959f1f4.
The fix that is being reverted did bring aria-labelledby and aria-describedby to the internal input which made it available for the select and multiselect search input. However, the search input need to be labelled separately instead.
No tests required for revert.
* Ticket: AWSUI-19125
<details>
</details>

Revert "Move formFieldContext to internal Input component (#396)"

---

src/date-range-picker/__tests__/date-range-picker-relative.test.tsx
src/date-range-picker/relative-range/index.tsx
src/input/__tests__/internal.test.tsx
src/input/index.tsx
src/input/internal.tsx

A second attempt for: https://github.com/cloudscape-design/components/pull/396
The new internal input behaviour is now under flag to not cause regression in select/multiselect.
Added new tests.
* Ticket: AWSUI-19215
<details>
</details>

Allow internal input to inherit form-field props

---

src/property-filter/property-filter-autosuggest.tsx
src/property-filter/styles.scss

The dropdown content requires an overflow. In property filter editor the top-level DIV element was created to assign a ref. Setting its display to `contents` fixes the problem.
Before:
Now:
Manual check
AWSUI-19364
<details>
</details>

Fix overflow for property filter editor dropdown

---

src/__tests__/form-field-controls-integration.test.tsx
src/internal/components/screenreader-only/index.tsx
src/select/__tests__/trigger.test.tsx
src/select/parts/trigger.tsx

AWSUI-18917
Fix: aira-label has no influence on select with selected option because of aria-labelledby is set too.
[_How did you test to verify your changes?_] 
<details>
</details>

Fix aria label overriden by selected option arialabelledby

---

src/annotation-context/annotation/annotation-popover.tsx
src/annotation-context/annotation/styles.scss
src/popover/__tests__/popover-body.test.tsx
src/popover/__tests__/popover-container.test.tsx
src/popover/body.tsx
src/popover/container.scss
src/popover/container.tsx

Break tight coupling between popover and annotation context:
* Move annotation-context popover-specific classes to annotation-context;
* Remove "annotation" variant of the popover;
Added more unit tests to popover elements.
<details>
</details>

Decouple popover and annotation context

---

src/date-picker/index.tsx
src/date-picker/styles.scss
src/date-range-picker/dropdown.tsx
src/date-range-picker/styles.scss
src/internal/components/focus-lock/index.tsx

This seemed to have been broken during some refactor along the way. 
Visually. Reduce the screen height and you should see a scrollbar on the dropdown. If there's no height constraint, there should be no scrollbar.
There is a dev page for this but it's not being screenshot tested. I'll add that test separately.
AWSUI-19364
<details>
</details>

fix(date-picker,date-range-picker): Fix scrolling on dropdown content

---

src/header/styles.scss

`awsui-h1-sticky` renders a `h1` element with `h2` styles, which means if there is any global styling for h1 it will override the line height of headers using `awsui-h1-sticky`. these global styles could come from previous versions of the system. 
tested locally, no visual difference
- [x ] _No._
<details>
</details>

fix(header): Reset h2 line-height

---

src/calendar/grid/index.tsx
src/calendar/header/index.tsx
src/calendar/internal.tsx
src/calendar/styles.scss

AWSUI-19188
Use `h2` for calendar header, and label the table with the header. 
<details>
</details>

Use h2 for calendar header

---

pages/code-editor/base-props.ts
pages/code-editor/controllable-height.page.tsx
pages/code-editor/error.page.tsx
pages/code-editor/loading.page.tsx
pages/code-editor/simple.page.tsx
pages/code-editor/vertical-scroll.page.tsx
pages/code-editor/with-errors-no-warnings.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/code-editor/__tests__/preferences-modal.test.tsx
src/code-editor/index.tsx
src/code-editor/interfaces.ts
src/code-editor/preferences-modal.tsx

Allow to limit what syntax themes are available for selection
```js
import 'ace-builds/css/theme/dawn.css';
import 'ace-builds/css/theme/tomorrow_night_bright.css';
// the list should match imported files
<CodeEditor themes={{light: ['dawn'], dark: ['tomorrow_night_bright']}} />
```
Added a unit test
<details>
</details>

code-editor: support listing only supported themes

---

pages/date-range-picker/calendar-permutations.page.tsx
pages/date-range-picker/range-calendar.page.tsx
src/date-range-picker/calendar/grids/grid.tsx
src/date-range-picker/calendar/grids/index.tsx
src/date-range-picker/calendar/index.tsx
src/date-range-picker/dropdown.tsx
src/date-range-picker/styles.scss

Similar to Calendar, we want DRP calendar (Range calendar) to become a standalone component. It requires adjustments to the component's API for it to receive similar properties to DRP.
Existing tests including screenshots, manual tests with new page.
<details>
</details>

Make DRP calendar better decoupled from DRP

---

pages/date-range-picker/calendar-permutations.page.tsx
pages/date-range-picker/range-calendar.page.tsx
src/date-range-picker/calendar/grids/grid.tsx
src/date-range-picker/calendar/grids/index.tsx
src/date-range-picker/calendar/index.tsx
src/date-range-picker/calendar/range-inputs.tsx
src/date-range-picker/index.tsx
src/date-range-picker/interfaces.ts

Updated date range picker calendar API to match closely DRP API. Extended calendar's date/time inputs to a separate component. The next step is to extract the range calendar component (w/o date/time inputs).
Existing unit/integ tests, manual tests.
* Previous step: https://github.com/cloudscape-design/components/pull/411
<details>
</details>

Range calendar API

---

src/internal/components/option/option-announcer.ts
src/select/utils/use-announcement.ts

The property filter uses label prefixes in the operator and value selection. But these labels don't get announced. Going back through commit/version history, it looks like it's something we accidentally missed.
Manually on VoiceOver/NVDA.
<details>
- We've noticed that people test things by their "accessible names", so this might break tests. But I don't think this should count.
</details>

fix(property-filter): Include option prefix in the aria announcement

---

pages/pie-chart/permutations.page.tsx
src/internal/components/chart-legend/__tests__/chart-legend.test.tsx
src/internal/components/chart-legend/index.tsx
src/internal/components/chart-legend/styles.scss

Change the role of the legend from a mysterious "application" to a more standard "toolbar". The interactions are actually mostly preserved here, with arrow keys for navigation. The focus is now on individual toolbar buttons, but the hover behavior is unchanged.
Though one choice I made was to detach the hover interactions and the focus interactions. It felt like a bad idea to throw the focus around without any explicit keyboard action from the user or with only a casual hover.
The unit tests have been adapted to match the new behavior, but you're also welcome (and recommended!) to try with a screen reader. It should announce the individual toolbar buttons as you move around. On NVDA, it works with both browse and focus modes (though with browse mode, it only works on activation rather …

fix(charts): Make legend behave like an ARIA toolbar

---

.gitignore
build-tools/tasks/bundle-vendor-files.js
gulpfile.js
src/internal/vendor/__tests__/d3-scale-third-party-licences.test.ts
vendor/README.md
vendor/rollup.config.mjs

Make vendor files bundling scoped to build for it to not affect quick-build.
Moved vendor deps setup to the root for better visibility.
Tested quick-build and build
<details>
</details>

Make vendor files bundling scoped to build

---

pages/dropdown/focus-trap.page.tsx
pages/multiselect/multiselect.test.page.tsx
pages/select/select.test.async.page.tsx
src/autosuggest/__integ__/async-autosuggest.test.ts
src/autosuggest/internal.tsx
src/internal/components/autosuggest-input/__tests__/autosuggest-input.test.tsx
src/internal/components/autosuggest-input/index.tsx
src/internal/components/dropdown-status/index.tsx
src/internal/components/dropdown/index.tsx
src/internal/components/dropdown/interfaces.ts
src/multiselect/__integ__/multiselect.test.ts
src/multiselect/internal.tsx
src/select/__integ__/async-select.test.ts
src/select/__integ__/events-select.test.ts
src/select/__tests__/use-select.test.ts
src/select/internal.tsx
src/select/utils/use-select.ts

Hey, look at me. Take a deep breath. We're going to get through this. I'll be overexplaining this but it's not a particularly complicated PR.
So, what's the problem? Basically, when you have `expandToViewport` set to `true`, the dropdown is positioned at the end of the DOM. With select and multiselect, the focus gets moved into the options list inside the dropdown. Then, you hit `Tab`, and you're sent off the page instead of to the element after the select trigger. Not good UX.
```
<select>
<trigger /> [1. start here]
<dropdown>
<options-list /> [2. focus automatically moved here]
<dropdown />
</select>
<some-input /> [3. hitting tab gets you here]
```
```
<select>
<trigger /> [1. start here]
</select>
<some-input /> [you skipped me :(]
<portal>
<dropdown>
<options-list /> [2. focus …
```

feat: Improve tabbing behavior for select, multiselect, and autosuggest with expandToViewport enabled

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/pagination/__tests__/pagination.test.tsx
src/pagination/interfaces.ts
src/pagination/internal.tsx

New area-label property for Pagination component.
Allows users to distinguish context in cases of multiple pagination components in a page.
Manually tested using VoiceOver and NVDA.
Unit test updated.
<details>
</details>

feat: Add aria label for pagination group

---

src/app-layout/visual-refresh/app-bar.scss
src/app-layout/visual-refresh/app-bar.tsx
src/app-layout/visual-refresh/background.scss
src/app-layout/visual-refresh/background.tsx
src/app-layout/visual-refresh/context.tsx
src/container/internal.tsx

Currently the `AppLayout` component is using the `contentType` property to determine whether or not a child component is implementing `stickyHeader` behavior. The assumption was that the `cards` and `table` content types would always be accompanied by the use of a sticky header. This was not the case in classic thus creating a feature dependency in visual refresh that is considered a regression.
This PR adds a new property to the visual refresh `AppLayout` component called `hasStickyBackground`. A child component will communicate up via the `AppLayout` context to determine whether or not a sticky header is implemented independent of the `contentType` property.

Remove the AppLayout contentType dependency for stickyHeader behavior.

---

pages/app-layout/with-cards.page.tsx
src/cards/index.tsx
src/container/internal.tsx
src/container/styles.scss
src/split-panel/icons/bottom-icon-refresh.tsx
src/split-panel/icons/icons-styles.scss
src/split-panel/icons/side-position-refresh.tsx
src/table/__integ__/table.test.ts
src/table/header-cell/index.tsx
src/table/header-cell/styles.scss
src/table/internal.tsx
src/table/sticky-header.tsx
src/table/styles.scss
src/table/thead.tsx

This change updates the column headers of the full-page variant of the Table component. They are now using the same colour scheme as the body of the table, instead of being part of the dark page header.
Local testing in the dev pages
- AWSUI-19627
<details>
</details>

feat(table): New header visuals for full-page table columns

---

pages/app-layout/disable-paddings-edge-controls.page.tsx
src/app-layout/__integ__/app-layout-refresh-edge-controls.test.ts
src/app-layout/visual-refresh/navigation.scss
src/app-layout/visual-refresh/split-panel.scss
src/app-layout/visual-refresh/tools.scss
src/app-layout/visual-refresh/trigger-button.scss

<details>
<summary><strong>Demo recording</strong></summary>
https://user-images.githubusercontent.com/983897/200972832-efdfda31-85bf-4ea0-8972-24828b83e48b.mov
</details>
The refresh app layout has scaffolding that blocks mouse clicks from passing through it to the content below. Normally, that wouldn't be a problem, because the only thing under that area are content paddings. But... if you disable content paddings and want to have interactive controls from edge to edge, then you're going have issues.
To resolve those without tweaking around the app layout structure and breaking a million other things, I just set `pointer-events: none` on the wrapper elements, and reactivate pointer events on the child elements (i.e. the panels and toggle buttons).
Check out that dev page! Check out …

fix: Prevent app layout from obscuring clicks when disableContentPaddings=true

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/internal/hooks/forward-focus/radio-group.ts
src/radio-group/__tests__/radio-group.test.tsx
src/radio-group/index.tsx
src/radio-group/interfaces.ts
src/radio-group/internal.tsx
src/tiles/__tests__/tiles.test.tsx
src/tiles/index.tsx
src/tiles/interfaces.ts
src/tiles/internal.tsx
src/tiles/tile.tsx

Added a shared hook for picking the right radio button in a radio group and moving focus to it.
- Added docs for ref. Stole the exact string from other components. 
AWSUI-19658
<details>
</details>

feat: Add .focus() ref method to tiles and radio group

---

src/autosuggest/__tests__/autosuggest.test.tsx
src/internal/components/autosuggest-input/index.tsx

When the suggestions are collapsed, the aria-owns/aria-controls attributes on the field refers to a non-existent ID. so 
removing aria-owns/aria-controls when the dropdown is closed and only show it on open
<details>
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

fix: Remove aria-controls and aria-owns when autosuggest dropdown is closed

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/index.tsx
src/autosuggest/interfaces.ts
src/autosuggest/internal.tsx
src/internal/components/autosuggest-input/index.tsx

AWSUI-19732
show focus() and select() functions in api
add tests for focus() and select()
<details>
</details>

feat: Add autosuggest ref functions in api

---

.github/workflows/release-gh-notes.yml

Add a workflow to release github notes to this repository, this workflow calls the main [workflow](https://github.com/cloudscape-design/.github/blob/main/.github/workflows/release-gh-notes.yml)
in my forked repo https://github.com/abdhalees/components/releases
<details>
</details>

chore: Add release gh notes workflow

---

package-lock.json
package.json

Fixing dependabot warning. 
Since webpack 5, this feature is now built-in and this loader is not used anywhere
* PR build
* Built this feature branch into my dev pipeline
<details>
</details>

chore: Remove file loader dependency

---

.github/workflows/release-gh-notes.yml

Add content write permissions to release notes workflow, the current repository settings needs explicit permissions for github actions to create release notes in the repository 
in my forked repo I've replicated this repo's settings and tested the change
<details>
</details>

chore: Add content write permissions to release notes workflow

---

src/app-layout/__integ__/app-layout-split-panel.test.ts
src/app-layout/index.tsx

This fixes the height calculations of the split panel when the screen is manually resized and the split panel preferences is set to `position: 'side'` 
This problem applies only in classic, to reproduce open the classic split panel demo -> make split panel preferences apply to the side -> resize the screen to mobile viewport -> observe the scroll, you will not be able to scroll to the content's end.
Added an integration test for that
<details>
_The following items are to …

fix: Fix split panel height calculations when screen viewport is resized

---

src/cards/index.tsx
src/code-editor/index.tsx
src/help-panel/index.tsx
src/internal/components/live-region/index.tsx
src/s3-resource-selector/s3-in-context/index.tsx
src/table/internal.tsx
src/tag-editor/index.tsx
src/tutorial-panel/components/tutorial-list/index.tsx

Wrapping something in a live-region makes it invisible. Fixing that for those items that are expected to be displayed.
<details>
</details>

fix: Make loading states displayed again

---

src/tiles/styles.scss

Unlike other form elements, the Tiles component currently does not have a background color set (unless the tile is selected or disabled). Example: https://codesandbox.io/s/vigilant-ritchie-tgtb0h.
This change makes sure that the Tiles always have a solid background color set.
Tested locally.
https://codesandbox.io/s/vigilant-ritchie-tgtb0h
<details>
</details>

fix: Make sure Tiles always have a solid background color

---

pages/app-layout/with-wizard-and-table.page.tsx
src/wizard/styles.scss

A customer issue was received that used a large `Table` component in the `content` slot of one of the `Wizard` component `steps`. This caused a grid blowout that pushed the content beyond the containing grid definition in the `Wizard` component. The resolution was to wrap the second column definition in a `minmax()` function.
**Before:**
**After:**
The fix was manually tested in all major browsers. In addition, a new test page was added to the `AppLayout` category called `with-wizard-and-table`.
*Do the changes include any API documentation changes?*
<details>
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

fix: Prevent grid blowouts in the Wizard component

---

src/attribute-editor/__tests__/attribute-editor.test.tsx
src/attribute-editor/row.tsx

1. Add role="group" to visually grouped controls in attribute editor.
2. Using first control label and value as the accessible name of the grouped control. 
Related links, issue **AWSUI-19064**
Added unit test, manually test on NVDA+chrome/ff, VO+safari.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/acces …

fix: Attribute editor form controls need to be programmatically grouped

---

src/app-layout/__integ__/app-layout-focus-delegation.test.ts
src/app-layout/__integ__/app-layout-split-panel.test.ts
src/app-layout/__tests__/split-panel.test.tsx
src/split-panel/index.tsx

When the split panel is opened, we previously moved focus to the close button. But this isn't great because it's the third (and often last) item in the tab order, after the resizer and the preferences button. While it would be nice to keep this, making the close button the first thing in the tab order (without changing the visuals) is unintuitive, especially because it's the right-most item in the header area. So we just move focus to the resize handler, which seems like the most sensible thing for the time being. And we're probably going to revisit focus moves at some point.
Related links, issue #, if available: AWSUI-19409
~~Too lazy to run all the tests. If a test yells at me, I'll update it. Or else, I'll write a test.~~ Updated unit and integration tests.
<details> …

fix: Focus resize handler when split panel is opened

---

src/tabs/tab-header-bar.scss

When there is a tab with `disabled: true` and `href: '<some-link>` properties the mouse click on the tab routes to that link even when it is disabled.
reference to the issue: https://github.com/cloudscape-design/components/issues/478
Added an integration test for it
Open the tabs page `pages/tabs/responsive-integ.page.tsx` and add a `href: '/'` to one of the disabled tabs, click on it using mouse and observe. You can verify my fix by pulling this branch -> open the same page and click on the disabled tab and verify nothing happens.
- [-] _No._
[*Attach any …

fix: Fix prevent anchor navigation in disabled tabs with `href`

---

pages/app-layout/with-sticky-table-and-split-panel.page.tsx
src/app-layout/visual-refresh/main.scss
src/app-layout/visual-refresh/main.tsx
src/app-layout/visual-refresh/split-panel.scss
src/internal/generated/custom-css-properties/list.js

This PR fixes the unexpected table header overscroll when the table has few items and split panel gets opened at bottom position.
Steps to reproduce this issue:
1. Open https://cloudscape.design/examples/react/split-panel-multiple.html
2. Set filter to XLOWCQQFJJHM80
3. Open split-panel
4. Scroll down
- tested manually on all supported browsers.
- additional screenshot tests will be added.
- AWSUI-19765
<details>
</details>

fix: Table header stays sticky with few itmes and open split panel

---

pages/onboarding/i18n.ts
src/__tests__/__snapshots__/documenter.test.ts.snap
src/annotation-context/__tests__/annotation-context.test.tsx
src/annotation-context/__tests__/data.tsx
src/annotation-context/annotation/annotation-trigger.tsx
src/annotation-context/annotation/closed-annotation.tsx
src/annotation-context/annotation/open-annotation.tsx
src/annotation-context/index.tsx
src/annotation-context/interfaces.ts

Current aria-label on annotation trigger has only _open/close_ state, the aria-labels are "open/close annotation". However, one page can have multiple annotations with same accessible name, screenreader users cant distinguish them. The PR is to add steps information to the aria-label, being for example "open annotation Step 3/6".
Related links, issue #AWSUI-19245
Added unit test. 
<details>
- _Changes …

feat: Add steps information to annotation trigger aria label

---

pages/app-layout/with-sticky-table-and-split-panel.page.tsx
src/container/internal.tsx

Before this change, the sticky background got reset when mounting and unmounting another component which uses the `InternalContainer`. This resulted in a header background which did not had the full width after unmounting. See #505 for details.
Related links, issue #, if available: AWSUI-19824, CR-80122674
- manually tested in all browsers we currently support.
- added additional screenshot tests for verification.
<details> …

fix: Prevent resetting StickyBackground from elements using InternalContainer

---

pages/breadcrumb-group/scenarios.page.tsx
src/breadcrumb-group/interfaces.ts
src/breadcrumb-group/internal.tsx
src/breadcrumb-group/item/item.tsx
src/breadcrumb-group/item/styles.scss

revert #492  
This reverts commit 916caba64c9bbe6a94e0d52c8dcfd843396398a5.
Because of performance regression. 
<details> …

revert: Show popover for truncated Breadcrumb text on hover or focus (#492)

---

src/tutorial-panel/__tests__/tutorial-panel.test.tsx
src/tutorial-panel/components/tutorial-detail-view/task.tsx

Tutorial panel steps titles content is not descriptive and can be the same on one page, like multiple "Total steps: 2". Add more descriptive label by joining the task title with steps title.
Related links, issue **AWSUI-19244**
<details>
- _If the …

feat: Add descriptive aria-label to tutorial pabel task list steps title

---

pages/app-layout/with-sticky-table-and-split-panel.page.tsx

Screenshot tests failed because of non-deterministic
table items. When toggling in between the item count
the items did not stay the same. This commit fixed that
behaviour and the related failing screenshot tests.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/acce …

fix: Use deterministic table items for AppLayout page

---

pages/app/components/error-boundary.tsx

Print not only the error message, but also a stacktrace
Pr build
<details> …

chore: Print stack trace in error message

---

src/tutorial-panel/__tests__/tutorial-panel.test.tsx
src/tutorial-panel/components/tutorial-detail-view/index.tsx

When tutorial is completed, the completion message should be announced.
Related links, issue #AWSUI-19249
Added unit test.
<details> …

feat: Screen reader should announce tutorial completion message

---

src/date-range-picker/__tests__/date-range-picker-absolute.test.tsx
src/date-range-picker/calendar/__tests__/calendar.test.tsx
src/date-range-picker/calendar/index.tsx

Split calculations and side effects into separate places. First, we figure which changes we need to make, then make these changes. Basically, this
```js
// before
if(condition) {
rangeStart.setDate(foo)
} else {
rangeStart.setDate(bar)
}
// after
let newValue
if(condition) {
newValue = foo
} else {
newValue = bar
}
// all side-effects are below
if(newValue) {
rangeStart.setDate(newValue)
}
```
In the next PR I am going to change `rangeStart.setDate` signature, so it would be very nice to change 1 line and not 4
PR build + locally
<details>
- _Changes are backward-compatible if …

refactor: Join all state changes in a single place

---

jest.unit.config.js

Disable code coverage when running locally. Can be overridden, via command line: `npx jest -c jest.unit.config.js --collectCoverage`
* Locally – no coverage by default, faster tests, cleaner console
* CI - See the CodeCov comment below
<details> …

chore: Disable code coverage when running locally

---

pages/app/index.html
pages/wizard/analytics.page.tsx
src/internal/hooks/use-analytics/__tests__/use-analytics.test.tsx
src/internal/hooks/use-analytics/index.ts
src/wizard/index.tsx
src/wizard/wizard-form.tsx

Adds an internal hook that will check for the presence of a beta data attribute to enable auto tagging of the Wizard component for better analytics integration.
- Added a simple unit test for the hook
- Manual validation of added tags
<details> …

chore: Add analytics beta hook

---

src/area-chart/__integ__/area-chart.test.ts
src/area-chart/internal.tsx
src/area-chart/model/index.ts
src/area-chart/model/use-chart-model.ts
src/mixed-line-bar-chart/__integ__/mixed-line-bar-chart.test.ts
src/mixed-line-bar-chart/chart-container.tsx
src/pie-chart/__integ__/pie-chart.test.ts
src/pie-chart/pie-chart.tsx

The accessibility issue in question is that the details popovers appear on hover or during keyboard navigation, but they obscure content when they appear. Assistive technology users need a way to be able to dismiss these popovers without needing to drag the cursor all the way out of the chart.
Related links, issue #, if available: AWSUI-19204, AWSUI-19231, AWSUI-19238, AWSUI-19254, four issues baby wooo let's goooo
Integration tests, but feel free to test it yourself manually too!
<details>
- _Changes do not …

fix: Allow popovers in charts to be dismissed by pressing Esc

---

src/annotation-context/__tests__/annotation-context.test.tsx
src/annotation-context/annotation/annotation-popover.tsx
src/popover/body.tsx

**Current problem**: when clicking the "next" button, the focus does not move to the "x" button, but stays on the "next" button. It only happens when two steps pointing to the same the trigger/hotspot. In this case, the popover only updates, not recreate. It works as expected when trigger/hotspot changes. 
**Solution:** Giving popover body a key, to always create new dialog instead of updating the current one, when step changes. Because screen reader has native behavior to announce dialog content when it shows and with focus on the start of the dialog, for example, NVDA announces content inside one by one, VO announces e.g "with 7 items" in the dialog. Always creating new dialog no matter hotspot changes, keeps consistent expected behavior from screenreader.
**Another update in this PR**: …

fix: Annotation focus on the start of the popover on clicking next

---

src/table/styles.scss

Table rounded corner causes gap between header. The fix is to remove the border-radius when header exists.  
Related links, issue AWSUI-19854
<details> …

fix: Remove table round corner under header

---

pages/date-range-picker/calendar-permutations.page.tsx
pages/date-range-picker/custom-control.page.tsx
pages/date-range-picker/range-calendar.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/date-range-picker/__tests__/date-range-picker-absolute.test.tsx
src/date-range-picker/calendar/index.tsx
src/date-range-picker/calendar/utils.ts
src/date-range-picker/dropdown.tsx
src/date-range-picker/index.tsx
src/date-range-picker/interfaces.ts
src/date-range-picker/styles.scss
src/date-range-picker/utils.tsx

Allow to render a custom control in absolute selection mode. Check the new `custom-control.page.tsx` demo for usage example.
Locally, build in my dev-pipeline (link in DM)
<details> …

feat: Add slot for custom controls in absolute range date picker

---

src/internal/components/option/index.tsx

When the label of a suggested value in the property filter is empty, it uses the value instead. However, the value contains the property name, so the property name is duplicated. With this change, an empty value of an option is correctly displayed as empty.
Related links, issue #, if available: AWSUI-19878
Manual testing in a dev page
<details> …

fix: Property filter duplicates property name in suggestion when the label is empty

---

pages/onboarding/i18n.ts
src/__tests__/__snapshots__/documenter.test.ts.snap
src/tutorial-panel/__tests__/data.tsx
src/tutorial-panel/__tests__/tutorial-panel.test.tsx
src/tutorial-panel/components/tutorial-list/index.tsx
src/tutorial-panel/interfaces.ts

Add `labelTutorialListDownloadLink` and `labelLearnMoreLink` props, to allow aria-label on download link and learn more link.
Related links, issue AWSUI-19243
<details> …

feat: Add arialabels for download and read more link in tutorial panel

---

src/internal/components/dropdown/__tests__/dropdown.test.tsx
src/internal/components/dropdown/index.tsx

If an element inside dropdown dismisses itself after click, the click away listener detects it as a click outside. To prevent this from happening, moved the listener to capture phase. `setTimeout` are also not needed anymore, because it was only to work around bubbling issues, which are not happening when using capture
Found when integrating feature https://github.com/cloudscape-design/components/pull/531 in the real use case
Added an extra unit test
<details> …

fix: Prevent dropdowns from closing when elements inside self-dismiss

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/code-editor/__tests__/code-editor.test.tsx
src/code-editor/index.tsx
src/code-editor/interfaces.ts
src/code-editor/util.ts

Currently, we support languages from a predefined list of languages. Users can add custom languages globally to the ace library (syntax highlighting, syntax validation, other goodies) before initializing the component, but our component has a fixed list of "display names" for languages that needs to be manually kept up to date. A much more scalable solution is to allow users to define the language being passed into the ace library, and also provide a custom label for unknown languages.
This is mostly not my work - **huge thanks to @andre-araujo** for contributing this internally a while ago. Unfortunately, it ended up getting lost in the backlog pile until we received a similar feature request recently.
The API docs have already been approved. …

feat: Allow custom languages for code editor

---

src/pie-chart/__integ__/pie-chart.test.ts
src/pie-chart/index.tsx

In the pie chart if a user clicks on a segment so it become pinned and tries to click on another segment, the highlight will remain on the first pinned segment, check the video: 
https://user-images.githubusercontent.com/99883674/203754470-43216d09-c9aa-4e65-9988-ff65cd1ff84b.mov
Added an integration test for it
<details> …

fix: Change the highlighted pinned segment on mouse down in Pie Chart

---

.github/PULL_REQUEST_TEMPLATE.md

When viewing a PR, relative URLs in the description will be prepended `https://github.com/cloudscape-design/components/pull` by the browser and lead to a 404. You can see that happening by hovering over the links to `CONTRIBUTING.md` under the "Review checklist" section further down.
Using absolute URLs as for the `safeUrl` link in the Security section further down seems a reasonable fix.
No related tickets.
- Navigated to the two changed URLs by Cmd+clicking on my IDE, verified that the browser loaded the intended pages and sections.
- Verified that the link to `checkSafeUrl` works correctly on PR pages
<details>
- …

chore: Fix links in PR template

---

src/table/use-sticky-header.ts

- Add missing dependancies to `useLayoutEffect`
- Remove code that was specific for angular
Related links, issue #, if available: AWSUI-19844
Reproduced the bug manually and tested locally after the fix. to reproduce the bug: 
1. Go to table demo (classic theme)
2. Ensure that no horizontal scrollbar is present on the table (determined at page load time)
3. Use the text filter to reach the empty state
4. Resize the browser window vertically to a smaller size until the table starts to jump
5. make sure you have scrollbars are always enabled in mac settings 
<details>
- _Changes are backward-compatible if not indicated, …

fix: Prevent empty table from flickering

---

src/app-layout/index.tsx
src/app-layout/visual-refresh/split-panel.tsx
src/internal/context/split-panel-context.ts
src/split-panel/__tests__/split-panel.test.tsx
src/split-panel/bottom.tsx
src/split-panel/index.tsx
src/split-panel/interfaces.ts
src/split-panel/side.tsx

There already were  separate `TransitionContentBottom` and `TransitionContentSide` components, but cramped into a single file for some reason. Let's finish the refactoring and move them into separate files
* PR build
* Locally
<details>
- …

chore: Move split panel side and bottom positions into separate files

---

src/wizard/styles.scss

Does what it says on the tin. When the refresh wizard collapses to a 1-column view in responsive situations, everything gets shifted to the first column. This changes the column widths so that the the contents are always rendered in a `minmax(0, 1fr)`.
Related links, issue #, if available: AWSUI-19794
Visual tests, and manual checks on all browsers. We have screenshots for this but it looks like this issue was missed.
<details> …

fix: Prevent grid blowout on Firefox with table in wizard

---

src/table/use-sticky-header.ts

This reverts commit 3349cc853c9d9a01d85a2ad341b56c7b54f64975.
caused some regressions in table column widths
<details> …

revert: fix: Prevent empty table from flickering (#542)

---

src/internal/hooks/use-visual-mode/__tests__/use-visual-mode.test.tsx
src/internal/hooks/use-visual-mode/__tests__/use-visual-refresh-static.test.tsx
src/internal/hooks/use-visual-mode/index.ts

1. Add a development mode warning when visual refresh class was detected too late
2. Removed CSS-vars checks, because we do not support any browsers without CSS-vars
3. Optimize `ALWAYS_VISUAL_REFRESH` constant handling, help minifiers to detect and remove unused code
Added extra unit tests
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browser …

feat: Optimize visual refresh detection and add development warning

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/autosuggest/interfaces.ts
src/select/interfaces.ts

Reflect the option fields where the default filtering applies in the API docs.
Code reference to
- autosuggest component's searchable fields: https://github.com/cloudscape-design/components/blob/main/src/autosuggest/utils/utils.ts#L34
- select component's searchable fields: https://github.com/cloudscape-design/components/blob/main/src/internal/components/option/utils/filter-options.ts#L8
- manually verified the changes.
- update documenter snapshots to reflect the changes.
<details> …

chore: Update autosuggest and select API docs

---

src/form-field/__tests__/form-field-context.test.tsx
src/form-field/__tests__/form-field-control-id.test.tsx
src/form-field/internal.tsx
src/test-utils/dom/form-field/index.ts

- include the icon in error id
- change `findError` selector to not break the test util for customers
- update our tests to use a custom selector as the `id` is not on the wrapper div
updated tests
<details> …

fix: Change the error message ID to include the error icon

---

src/property-filter/__tests__/utils.test.ts
src/property-filter/utils.ts

Ensure that property filter prefers an exact case-sensitive match of property key
over a non-exact match.
AWSUI-19954
New unit test
<details> …

fix: Ensure property filter prefers case-sensitive match

---

src/property-filter/__tests__/utils.test.ts
src/property-filter/utils.ts

Follow-up for #575 - fix a case in which that wasn't properly selecting the appropriate property.
Tested locally, updated unit test.
<details> …

fix: Fix property filter case sensitivity

---

src/area-chart/__integ__/area-chart.test.ts
src/area-chart/__tests__/area-chart-use-chart-model.test.tsx
src/area-chart/elements/chart-popover.tsx
src/area-chart/internal.tsx
src/area-chart/model/index.ts
src/area-chart/model/use-chart-model.ts
src/internal/components/chart-popover/index.tsx
src/internal/components/chart-popover/styles.scss
src/mixed-line-bar-chart/__integ__/mixed-line-bar-chart.test.ts
src/mixed-line-bar-chart/__tests__/use-mouse-hover.test.ts
src/mixed-line-bar-chart/chart-container.tsx
src/mixed-line-bar-chart/chart-popover.tsx
src/mixed-line-bar-chart/hooks/use-mouse-hover.ts
src/pie-chart/__integ__/pie-chart.test.ts
src/pie-chart/__tests__/pie-chart.test.tsx
src/pie-chart/pie-chart.tsx
src/pie-chart/segments.tsx

The issue in question is that for screen magnification users, hovering over a point (or a vertical line) presents a popover, but when they move the mouse to read the popover, it goes away (because it's tracking only the point being hovered on). The solution for this is to have an area around the popover that disables the hover logic when the pointer is on top of it.
Related links, issue #, if available: AWSUI-19236, AWSUI-19205
Added integ/unit tests and changed the behaviour for existing tests
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/compo …

feat: Allow mouse to enter popover in charts

---

jest.unit.config.js

The current pattern specified (`internal/vendor$`) excludes all paths ending in `internal/vendor`, this does not work to ignore the bundled d3-scale from coverage. This PR updates that path to match all files under `internal/vendor`.
Verified by comparing coverage output from `jest` before and after change
<details> …

fix: change unit test ignorePaths to exclude bundled vendor deps

---

src/app-layout/index.tsx
src/app-layout/utils/use-observed-element.ts
src/app-layout/visual-refresh/context.tsx
src/app-layout/visual-refresh/layout.tsx
src/app-layout/visual-refresh/split-panel.tsx
src/internal/context/split-panel-context.ts
src/split-panel/__tests__/split-panel.test.tsx
src/split-panel/bottom.tsx
src/split-panel/index.tsx

Move resize observers down from app layout to split panel code
Locally, PR build, dev pipeline
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessi …

refactor: Move size observers into split panel code

---

pages/table/permutations.page.tsx

Adding a striped table to the permutations page for a visual screenshot test.
See the CR link with id CR-81552994 for more context.
<details> …

feat: Adds striped row for screenshot test

---

pages/container/fit-height.page.tsx
pages/container/fit-height.scss
pages/container/simple.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/container/interfaces.ts
src/container/internal.tsx
src/container/styles.scss

Added new property to align multiple containers rendered on a single row
Added a new page for screenshot testing
<details> …

feat: Add fitHeight property to container

---

src/area-chart/model/use-chart-model.ts
src/mixed-line-bar-chart/__integ__/mixed-line-bar-chart.test.ts
src/mixed-line-bar-chart/__tests__/mixed-chart.test.tsx
src/mixed-line-bar-chart/chart-container.tsx
src/pie-chart/__integ__/pie-chart.test.ts
src/pie-chart/__tests__/pie-chart.test.tsx
src/pie-chart/pie-chart.tsx

Ensure that after clicking outside of a chart component, highlighted segment will be cleared.
Additionally fixes discrepancy between space and enter keys behaviour for Pie chart.
It will work similarly to other charts.
Area chart behaviour will be adjusted separately. 
Related links, issue #, if available: AWSUI-19991
New integration tests.
<details> …

fix: Click outside of chart removes section selection

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/internal/components/button-trigger/index.tsx
src/multiselect/__tests__/multiselect.test.tsx
src/multiselect/interfaces.ts
src/multiselect/internal.tsx
src/select/__tests__/select.test.tsx
src/select/__tests__/trigger.test.tsx
src/select/__tests__/use-select.test.ts
src/select/interfaces.ts
src/select/internal.tsx
src/select/utils/use-select.ts

Give select and multiselect a feature that other components already have
PR build
<details>
- …

feat: Add autofocus property on select and multiselect component

---

pages/cards/tall-cards.page.tsx
src/cards/__integ__/tall-cards.test.ts
src/cards/index.tsx
src/internal/hooks/use-mouse-down-target.ts
src/table/internal.tsx

Fixed a bug when the first click inside a card would cause a scroll.
Same issue has been solved for tables already: https://github.com/cloudscape-design/components/pull/335
Added new integ test.
<details> …

fix: Fixed cards scroll on click issue

---

src/internal/components/chart-legend/__tests__/chart-legend.test.tsx
src/internal/components/chart-legend/index.tsx

When button is focused and series is highlighted, the selected state should be announced by screenreader. 
Related links, issue #AWSUI-19996
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/acc …

feat: Announce selected state of chart legend button  by screen reader

---

pages/container/fit-height.page.tsx
src/container/styles.scss

The https://github.com/cloudscape-design/components/pull/589 broke container styles when used in a specific way because certain styles have been unconditionally removed.
Before fix:
After fix:
SIM: AWSUI-20048
Manual tests so far. Can add a screenshot test for fitHeight=false after merged.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers …

fix: Container flex styles

---

src/__tests__/required-props-for-components.ts
src/__tests__/utils.tsx
src/app-layout/index.tsx
src/app-layout/visual-refresh/main.tsx
src/app-layout/visual-refresh/split-panel.tsx
src/app-layout/visual-refresh/tools.tsx
src/internal/context/split-panel-context.ts
src/split-panel/__tests__/helpers.ts
src/split-panel/__tests__/split-panel.test.tsx

Add explicit assertion about split panel used inside app layout.
Using it outside app layout is not supported, so it is better to fail fast than dealing with unclear bug reports.
* Locally, added an extra unit test
* Deployed this branch to my dev pipeline
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md# …

chore: Add context assertion to split panel component

---

src/internal/components/dropdown-status/index.tsx
src/multiselect/internal.tsx
src/select/internal.tsx

Dropdown footer is rendered with select and wrapped by aria-live https://github.com/cloudscape-design/components/blob/40a405bd591436179a2e1e9a4287664bc7f6582c/src/internal/components/dropdown-footer/index.tsx#L17. In order to announce the content when opening the dropdown, the content should be updated dynamically when the dropdown opens. 
Related links, issue AWSUI-19995
<details> …

fix: Select options state be announced by screen reader

---

src/app-layout/interfaces.ts

This property was originally added to support legacy behaviours. Thankfully, they are gone by 2023, so we can also declare it deprecated on our end, to prevent new code with this property to be created
n/a
<details> …

chore: mark disableBodyScroll property as deprecated

---

pages/app/app-context.tsx
pages/app/components/theme-switcher.tsx
pages/app/index.tsx
src/internal/hooks/use-telemetry/index.ts
src/internal/metrics.ts
src/internal/utils/__tests__/init-metrics.test.ts
src/internal/utils/__tests__/metrics.test.ts

We want to identify the "runtime" Visual Refresh theme in the metrics, which is currently taken from the `THEME` environment variable and ignores the VR context. This change re-introduces the forgotten `initMetrics` function that overrides the metrics theme for VR.
Related links, issue #, if available: AWSUI-20010
I have tested this locally.
<details> …

chore: Support Visual Refresh theme in metrics

---

build-tools/tasks/package-json.js

Remove the package-lock file from the template of themeable-components.
AWSUI-19722
<details> …

chore: Remove package-lock from themeable source template

---

pages/table/editable-with-app-layout.page.tsx
pages/table/tall-rows.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/table/__tests__/body-cell.test.tsx
src/table/__tests__/inline-editing-test-utils.test.tsx
src/table/body-cell/index.tsx
src/table/body-cell/inline-editor.tsx
src/table/header-cell/index.tsx
src/table/interfaces.tsx
src/table/internal.tsx

This PR changes some the types used by Inline Editing to be weaker. The stronger types seem to break some consuming packages. 
Includes changes proposed by @just-boris in #595 
Dry run build 6282595099 and 6284939920
<details> …

chore: use weaker types for inline editing

---

package-lock.json
package.json
src/code-editor/__integ__/code-editor.test.ts
src/code-editor/__tests__/code-editor.test.tsx
src/code-editor/index.tsx
src/code-editor/pane.tsx
src/code-editor/resizable-box/__tests__/resizable-box.test.tsx
src/code-editor/resizable-box/index.tsx
src/code-editor/resizable-box/styles.scss
src/code-editor/resize-handler.tsx
src/code-editor/styles.scss

This library is unmaintained and not compatible with React 18
* Locally, compared behaviors against stable release
* Added tests for most important behaviors
<details> …

chore: Remove react-resizable dependency

---

src/code-editor/index.tsx
src/code-editor/styles.scss

Fix visual regression introduced in #616
Note: the PR title does not say `fix:` because the original change was not released, so there is nothing to announce as "fixed"
Locally
<details> …

chore: Fix visual regression in code editor

---

src/attribute-editor/__tests__/attribute-editor.test.tsx
src/attribute-editor/additional-info.tsx
src/attribute-editor/internal.tsx
src/internal/components/live-region/__tests__/live-region.test.tsx
src/internal/components/live-region/index.tsx
src/tag-editor/index.tsx

This change makes two improvements to the additional information text in attribute editor (and tag editor) for assistive technology:
1. Connect the text to the Add button using `aria-describedby`
2. Put the additional content in an ARIA live region
Related links, issue #, if available: AWSUI-20074
Tested manually with VoiceOver.
<details> …

feat: Announce additional information in Attribute editor to assistive technology

---

src/app-layout/index.tsx
src/app-layout/visual-refresh/app-bar.tsx
src/app-layout/visual-refresh/background.tsx
src/app-layout/visual-refresh/context.tsx
src/app-layout/visual-refresh/header.tsx
src/app-layout/visual-refresh/index.tsx
src/app-layout/visual-refresh/layout.tsx
src/app-layout/visual-refresh/main.tsx
src/app-layout/visual-refresh/navigation.tsx
src/app-layout/visual-refresh/notifications.tsx
src/app-layout/visual-refresh/split-panel.tsx
src/app-layout/visual-refresh/tools.tsx
src/container/__tests__/sticky-header.test.tsx
src/container/internal.tsx
src/content-layout/index.tsx
src/internal/context/app-layout-context.ts
src/internal/hooks/use-dynamic-overlap/__tests__/use-dynamic-overlap.test.tsx
src/internal/hooks/use-dynamic-overlap/index.ts
src/split-panel/index.tsx
src/table/internal.tsx
src/table/sticky-scrollbar.tsx
src/wizard/wizard-form-header.tsx

There are two app layout contexts. One for use inside other components to calculate offsets (mostly for sticky elements). Second is intended to be used only inside app layout sub-components and only in visual refresh. Let's make it more strict
* PR build
* Dev pipeline build
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/ma …

refactor: Use app layout internals only inside app layout

---

pages/container/fit-height.page.tsx
src/container/styles.scss

Reverts cloudscape-design/components#603
The change was applied to let some teams update their code and stop relying on container styles. The issue is resolved now, so we can release it again

revert: Container flex styles

---

src/wizard/__tests__/wizard.test.tsx
src/wizard/index.tsx
src/wizard/internal/analytics.tsx

Removed `trackStartStep` as a dependency of the effect hook. As the functions inside the `useWizardAnalytics` hook are recreated on render it causes this hook to trigger multiple times. The intention of the effect is to send an event only when the step index changes.
A quick test in the dev page while logging the events while triggering a re-render in the parent component. As seen in the before multiple events are fire but in the after only a single event is fired.
Before:
After:
<details> …

chore: Fix wizard rerendering causing multiple start step events

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/table/interfaces.tsx

The API Doc for this field seems to have gone missing between the first release and re-release somehow. This PR restores this doc.
Content reviewed by @fralongo on 22.12.2022
<details> …

fix: Add missing API doc for table cell render function

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/autosuggest/__tests__/autosuggest.test.tsx
src/internal/components/dropdown-status/__tests__/dropdown-status.test.tsx
src/internal/components/dropdown-status/index.tsx
src/internal/components/dropdown-status/interfaces.ts
src/multiselect/__tests__/multiselect.test.tsx
src/multiselect/internal.tsx
src/select/__tests__/select.test.tsx
src/select/internal.tsx

This PR adds the `errorIconAriaLabel` prop to Select, Multiselect, Autosuggest.
Related links, issue #, if available: 
AWSUI-20070
Added unit tests for all affected components.
<details> …

feat: Add errorIconAriaLabel prop in Select, Multiselect, and Autosuggest

---

pages/table/editable-with-app-layout.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/table/__tests__/body-cell.test.tsx
src/table/__tests__/inline-editing-test-utils.test.tsx
src/table/__tests__/inline-editor.test.tsx
src/table/__tests__/table.test.tsx
src/table/__tests__/use-focus-navigation.test.tsx
src/table/body-cell/index.tsx
src/table/body-cell/inline-editor.tsx
src/table/interfaces.tsx

This PR refactors the API for Inline Editing in Table to remove edit mode out of `columnDefinition.cell` function.
Initial release of the feature included this update to the API for `columnDefinition`
```diff
-     cell(item: ItemType): React.ReactNode;
+     cell(item: ItemType, cellContext: CellContext<any>): React.ReactNode;
```
Multiple consoles appear to be using this function for their own testing; this API change then causes the build failures due to mismatching call signature (TypeScript type mismatch).
We decided to rollback this API change and adopt this API where edit mode rendering is done through `columnDefinition.editConfig`
```diff
export interface EditConfig<T, V = any> {
ariaLabel?: string;
errorIconAriaLabel?: string;
editIconAriaLabel?: string;
constraintText?: string; …
```

refactor: Move edit mode cell render to its own function

---

src/button-dropdown/__tests__/button-dropdown.test.tsx
src/date-picker/index.tsx
src/internal/components/dropdown/index.tsx

Cause: 
when clicking on the trigger in Buttondropdown, it firstly calls onDropdownClose() which closes the dropdown https://github.com/cloudscape-design/components/blob/40a405bd591436179a2e1e9a4287664bc7f6582c/src/internal/components/dropdown/index.tsx#L271-L283
Then it calls toggleDropdown(), it reopens the dropdown https://github.com/cloudscape-design/components/blob/11b4eacd8433b467c2ef7f3e7b7f695e53cfa104/src/button-dropdown/internal.tsx#L81-L84
Calling onDropdownClose when the clicking target is the trigger is also not ideal for other components using Dropdown and onDropdownClose, which are DateRangePicker and DatePicker. For example, when clicking the trigger of DRP, the dropdown gets closed and opened again. 
The fix is to treat trigger as dropdown content, not call …

fix: Buttondropdown trigger should toggle dropdown

---

src/internal/components/dropdown-footer/__tests__/dropdown-footer.test.tsx
src/internal/components/dropdown-footer/index.tsx

It is a follow up fix of https://github.com/cloudscape-design/components/pull/608. 
When using `expandToViewport` the dropdown status rendered when dropdown opens. The aria-live div and its content comes in the same time, so no real content change to get announced. The delay in LiveRegion helps the content in aria-live does get changed and announced. 
Related links, issue AWSUI-19995
<details> …

fix: Dropdown status not announced by screenreader using expandToViewport

---

src/app-layout/__tests__/common.test.tsx
src/app-layout/mobile-toolbar/index.tsx

The mobile toolbar buttons are structured as a clickable button wrapped by a clickable wrapper element. If you clicked on the inner button, event bubbling meant that the outer wrapper would also call the click handler, and this would lead to the function being called twice.
```
<wrapper onClick={onClick}> // <- bubbles up here
<button onClick={onClick}></button> // <- source
</wrapper>
```
This is a bit of an edge-case and isn't a big deal in _most_ React apps, but it's still incorrect. I went with a simple fix without touching the event bubbling logic itself.
Related links, issue #, if available: AWSUI-20134
Made changes to unit tests.
<details> …

fix: Call onNavigationChange and onToolsChange only once per change

---

src/app-layout/__integ__/app-layout-split-panel.test.ts
src/app-layout/index.tsx
src/app-layout/visual-refresh/split-panel.tsx
src/internal/context/split-panel-context.ts
src/split-panel/__tests__/helpers.ts
src/split-panel/bottom.tsx
src/split-panel/styles.scss

Reverts cloudscape-design/components#635 because it caused a visual regression

revert: Make split panel header scrollable when page height is small"

---

src/input/internal.tsx

This PR changes the outer element of the Internal Input to a span, rather than a div to ensure that when nested in a span (as in the Text Filter Component) that the HTML remains valid.
Note: the element already had display:flex applied so no changes needed to preserve box layout
Addresses AWSUI-20178
Tested manually with local build, visual regression
<details>
- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._
- _Changes are covered with new/existing unit tests?_
- _Changes are covered …

fix: Improve HTML validity of Internal Inputs in TextFilter

---

src/text-filter/__tests__/text-filter.test.tsx
src/text-filter/internal.tsx

<TextFilter> component has div as child element of span. 
Related links, issue AWSUI-20167
<details> …

fix: Invalid html markup div as child element span

---

src/internal/components/dropdown/index.tsx
src/internal/components/focus-lock/__tests__/focus-lock.test.tsx
src/internal/components/focus-lock/index.tsx
src/internal/components/tab-trap/index.tsx
src/internal/hooks/use-merge-refs/index.tsx
src/modal/internal.tsx

Switch from "react-focus-lock" to a much more basic homegrown implementation that is mostly just a pair of wrapping focus guards. In the process, added a "restoreFocus" prop to the internal focus lock to handle returning focus automatically.
Also, minor things: ~~(1) slightly renamed things in tab-trap.tsx, (2) moved around imports in modal so they're a little less chaotic~~ *undone to hit code coverage*, and (3) added nicer typings to useMergeRefs. Basically just touched up everything I ended up encountering.
Related links, issue #, if available: AWSUI-20140
Existing tests in modal should continue to not fail. ~~Writing unit tests for this, I felt like I was just reimplementing modal, so I let modal test this logic for me.~~ Fine, Codecov, I wrote unit tests.
<details> …

fix: Make focus locking for modals less aggressive

---

pages/container/simple.page.tsx
src/container/index.tsx

When container has no content and disableContentPaddings, the bottom border radius are overlapped by header. The change adds border radius when no content in the container, as we did for collapsed ExpandableSection. 
For test, add one more instance in simple.page, it will show in the screenshot tests. 
Related links, issue AWSUI-20171
<details> …

fix: Container with empty content has incorrect header border radius

---

src/input/internal.tsx

Reverts cloudscape-design/components#658
The same issue was fixed by another PR https://github.com/cloudscape-design/components/pull/653. The #653 approach is preferred because it is more precisely scoped to the component which required a fix

revert: Improve HTML validity of Internal Inputs in TextFilter

---

src/side-navigation/__tests__/side-navigation.test.tsx
src/side-navigation/internal.tsx
src/side-navigation/styles.scss

We hadn't done this in the past because having an `<h2>` persistently before the `<h1>` in the DOM order would lead to a confusing page hierarchy. But all signals now point to DOM order not being as important as the meaningful hierarchy of the title itself, so... let's do it
Related links, issue #, if available: AWSUI-19376
Only a small change in the HTML tag used; can't think of a test case that wouldn't be a brittle one. Also, there should be no visual changes caused by this change either.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/componen …

fix: Use semantic heading for side navigation header

---

pages/autosuggest/permutations.page.tsx
pages/input/permutations.page.tsx
pages/text-filter/permutations.page.tsx

To mitigate some permutation matching issues for components as a temporary solution.
Permutations should be identical, if not a little bit cleaner
<details> …

chore: Remove clear labels from the permutation objects

---

src/link/styles.scss

The link component resets font smoothing at the component boundary, which makes sense for most cases except `secondary` links, which inherit font weight.
It's a `chore:` cause it's a bugfix for a change that hasn't gone out yet.
Only locally, but this should be screenshot testing visible.
<details> …

chore: Inherit font smoothing for secondary links

---

pages/radio-group/progressive-disclosure.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/radio-group/__tests__/radio-group.test.tsx
src/radio-group/interfaces.ts
src/radio-group/internal.tsx

This PR adds the `ariaControls` prop to RadioGroup component.
This should allow users to implement a progressive disclosure pattern AND make it accessible.
~~NOTE: The API documentation needs to reviewed and potentially changed; hold off on merging just yet.~~ _approved_
* Updated existing Unit Tests
* Created a dev page that uses the prop to implement this pattern.
<details> …

feat: Add ariaControls prop to RadioGroup

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/flashbar/interfaces.ts

Removed wrong `@deprecated` tag from the `items` property in the `Flashbar` component interfaces.
Without this fix, it would generate wrong documentation.
<details> …

fix: Remove wrong deprecated tag on flashbar interfaces

---

src/checkbox/styles.scss
src/internal/components/abstract-switch/__tests__/abstract-switch.test.tsx
src/internal/components/abstract-switch/index.tsx

You can't put `<div>`s inside `<label>`s, so using divs for the abstract switch disqualifies it from a bunch of pretty common situations.
Both divs are flexboxes, so nothing should change.
<details> …

fix: Allow checkboxes and toggles to be nested inside label elements

---

src/top-navigation/internal.tsx

It looks like the `.inputs` div occupies space even if there's no content to show because of uncollapsable paddings. So the solution is to remove it from the DOM completely so that the expectations match up with reality.
Alternatively, I could have updated the calculations in use-top-navigation, but it's better to have less wasted space :)
Local screenshot checks. Compare the "top-navigation/screenshot" page and you'll find that only the final text-only identity should truncate.
<details> …

fix: Prevent top navigation identity title from truncating too early

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/flashbar/interfaces.ts

Whoopsie. Just noticed "ariaRole" is described as a boolean. Also removed "id" from being visual refresh exclusive, because we do use it for checking equality between renders for ariaRole (just like key, so I didn't feel the need to elaborate further in the property docs either)
It's a docs change.
<details> …

chore: Fix flashbar items property docs

---

src/collection-preferences/__tests__/visible-content.test.tsx
src/collection-preferences/visible-content.scss
src/collection-preferences/visible-content.tsx

Given the visual and positional context of the Visible content title, it is perceived as a heading.
We are making this text and explicit heading (h3) to make reflect the semantics in code.
Related links, issue #, if available: AWSUI-20177
Tested locally using VoiceOver.
<details>
- …

chore: Turn visible content title into an H3

---

pages/flashbar/collapsible.permutations.page.tsx
pages/flashbar/interactive.page.tsx
src/flashbar/__tests__/collapsible.test.tsx
src/flashbar/collapsible-flashbar.tsx
src/flashbar/interfaces.ts
src/flashbar/utils.ts

Adopt naming conventions from latest API review of the Stacked notifications feature before making it public.
- Manually tested to make sure animations continue to work
- No changes in automated tests
<details> …

chore: Update Stacked Flashbar API

---

pages/flashbar/interactive.page.tsx
src/flashbar/__tests__/collapsible.test.tsx
src/flashbar/__tests__/common.ts
src/flashbar/__tests__/flashbar.test.tsx
src/flashbar/collapsible-flashbar.tsx
src/flashbar/common.tsx
src/flashbar/interfaces.ts
src/flashbar/non-collapsible-flashbar.tsx

A requirement for an ARIA label was defined while developing the Stacked notifications feature. For that reason the ARIA label was added to the "collapsible" version of the Flashbar only, but in reality it should always be there, also when not using the new feature.
This change backports the ARIA label to the "regular Flashbar, making sure that once the stacking feature is released, the new `i18nStrings.ariaLabel` prop has the desired effect regardless of the stacking feature being used (i.e, `stackItems` set to `true`) or not.
(The prop itself will become public once the stacking feature is public)
- Added 2 unit tests, which are run twice each (with and without animations)
- Manually tested by inspecting the list element with browser tools …

fix: Add ARIA label to Flashbar

---

src/wizard/__tests__/wizard.test.tsx
src/wizard/index.tsx
src/wizard/internal/analytics.tsx

This reverts commit f15cf9a715a17b502f19c5a023d2ee56ff1692b8. (Accidentally pushed to main 🤷🏻‍♂️)
Fixes a bug that didn't track the full start to end duration of the wizard .
<details> …

chore: Fix wizard analytics for total time spent

---

src/property-filter/index.tsx

Add missing clearAriaLabel for PropertyFilter
Related links, issue AWSUI-20272
<details> …

fix: Add missing clearAriaLabel for PropertyFilter

---

pages/flashbar/collapsible.permutations.page.tsx
pages/flashbar/interactive.page.tsx
src/flashbar/__integ__/collapsible.test.ts
src/flashbar/__integ__/focus-interactions.test.ts
src/flashbar/__integ__/pages/interactive-page.ts
src/flashbar/__tests__/collapsible.test.tsx
src/flashbar/collapsible-flashbar.tsx

After this change, the behavior of the Flashbar when using the Stacking feature matches the current behavior when it comes to item order: the first item in the `items` array is displayed visually at the top of the stack and the last one of the array is displayed at the bottom.
- Covered by existing unit tests and integration tests
- Added one integration test
- Manually tested
<details> …

chore: Let Flashbar render the items in the same order as in the array, also when using the Stacked notifications feature

---

pages/app-layout/notifications-refresh.page.tsx
src/app-layout/__tests__/mobile.test.tsx
src/app-layout/visual-refresh/header.tsx
src/app-layout/visual-refresh/main.scss
src/app-layout/visual-refresh/notifications.tsx

When the AppLayout is used in mobile view and the navigation panel is opened, it covers the whole page. Before this PR, the contents of the `notifications` and `contentHeader` slots were still accessible through tabbing and through screenreaders. This PR makes the covered areas inaccessible while the side panels are open.
- AWSUI-20253
Manual testing in the dev page at http://localhost:8080/#/light/app-layout/notifications-refresh
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTIN …

fix: AppLayout announces hidden slots in mobile view

---

src/breadcrumb-group/__tests__/breadcrumb-group.test.tsx
src/breadcrumb-group/__tests__/breadcrumb-item.test.tsx
src/breadcrumb-group/item/item.tsx
src/test-utils/dom/breadcrumb-group/index.ts

Previously the current page item was kinda a link and kinda not, which was causing some accessibility issues. After internal discussion and reviewing reference implementations, the best approach is to make it just text.
Related links, issue #, if available: AWSUI-20172
Updated unit tests, deployed locally & tested with VO & Chrome. See internal ticket for more details.
<details> …

fix: Make current page breadcrumb item not a link

---

pages/attribute-editor/simple.page.tsx
pages/tag-editor/shared.ts
src/__tests__/__snapshots__/documenter.test.ts.snap
src/attribute-editor/__tests__/attribute-editor.test.tsx
src/attribute-editor/interfaces.ts
src/attribute-editor/internal.tsx
src/tag-editor/__tests__/tag-editor.test.tsx
src/tag-editor/interfaces.tsx

This PR introduces two new props in AttributeEditor & TagEditor, these props allow you to announce removal of an item to screenreader users.
Resolves a11y bug reported in AWSUI-20076
Unit tests & manual testing with VoiceOver
<details>
- _Changes …

feat: Announce removal of items from AttributeEditor & TagEditor

---

pages/flashbar/common.ts
pages/flashbar/interactive.page.tsx
pages/flashbar/sticky-app-layout.page.tsx
pages/flashbar/sticky.page.tsx
src/app-layout/notifications/styles.scss
src/app-layout/visual-refresh/notifications.scss
src/flashbar/__integ__/collapsible.test.ts
src/flashbar/__integ__/pages/base.ts
src/flashbar/__integ__/pages/interactive-page.ts
src/flashbar/__integ__/pages/sticky-page.ts
src/flashbar/collapsible-flashbar.tsx
src/flashbar/collapsible.scss
src/internal/generated/custom-css-properties/list.js

The Stacked notifications feature adds an element called "notifications bar" to the Flashbar, which partially overlaps the Flashbar and partially overlaps the content below. We don't want it to create extra space with the content below (e.g, sticky table headers should still collapse without any space between the flashbar and the table), but at the same time, there should be some space with the window bottom in order to prevent the notifications bar from getting cropped (there is a function for that called `updateBottomSpacing`).
Right:
Wrong:
This change fixes a few issues that were making this behavior not totally reliable:
- Account for extra margin of the parent notifications region when using App Layout with Visual Refresh
- The extra padding was being applied to non-sticky Flashbar, …

fix: Flashbar bottom spacing management logic

---

pages/flashbar/common.ts

Small follow-up from #715 (see [comment](https://github.com/cloudscape-design/components/pull/715#discussion_r1099963151)): reuse existing `generateUniqueId` logic instead of creating a new one.
<details> …

chore: reuse unique ID function to de-duplicate logic

---

.github/workflows/build-lint-test.yml

Add GitHub deployment job that will deploy all dev page assets for the head commit  change of a pull request.
Depends on this change in the base workflows
https://github.com/cloudscape-design/.github/pull/35
Tested in a forked branch: https://github.com/michaeldowseza/components/pull/4
<details> …

chore: Add branch deployment to build workflow on pull-request

---

src/flashbar/collapsible.motion.scss

In the [previous PR](https://github.com/cloudscape-design/components/pull/715) the class name of the Flashbar notification bar had been renamed from the old `toggle` to the new `notification-bar`, both in the component as well as in the `collapsible.scss` file —but not in `collapsible.motion.scss`. This led to the notification bar not animating anymore when collapsing and expanding.
This PR fixes this by applying that missing renaming.
Tested manually only. We don't have a proper way to test animations programmatically AFAIK.
<details> …

fix: Stacked Flashbar notification bar animation

---

src/flashbar/collapsible.scss

The recent shadow updates in #702, unified how we apply shadows in many components, including simplifying the shadow approach in Flashbars. Previously, Flashbars applied shadows on different elements depending on the theme (pseudo element in refresh, directly on the Flash item in classic). However the latest update simplified both themes to use a single approach (pseudo element) ([see code diff](https://github.com/cloudscape-design/components/commit/222b99ff1eab212a62dcf7a5154055623e6d38da#diff-830d2afec0c4339df425e599c2a7294f079d8350460fd6426562f3106993526cL28-L49)).
This unintentionally brought a tiny existing bug to light in the unreleased stacked Flashbar feature. More specifically, stacked Flashbars should have a [different shadow](https://github.com/cloudscape-design/components/blob/ …

fix: Apply stacked flashbar feature shadows to correct element

---

src/wizard/__tests__/wizard.test.tsx
src/wizard/index.tsx
src/wizard/internal/analytics.tsx

Pass the wizard id, that is optional and deprecated, to the custom metric event as the funnel id. This is a best effort attempt for grouping metrics by an id as there is currently no other identifier available. 
Added a base unit test.
<details> …

chore: Use wizard id for funnel id in metrics

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/flashbar/__tests__/collapsible.test.tsx
src/flashbar/collapsible-flashbar.tsx
src/flashbar/common.tsx
src/flashbar/index.tsx
src/flashbar/interfaces.ts
src/flashbar/non-collapsible-flashbar.tsx
src/test-utils/dom/flashbar/index.ts

This change does the following:
- Merge the private API props for the Stacked notifications feature with the public Flashbar API
- Make changes to the new API prop docs according to content review
- Make changes to test utils docs, also content reviewed
Documenter output was fed into a website build, albeit in a semi-manual process.
<details> …

feat: Make Stacked notifications feature public

---

src/flashbar/__tests__/collapsible.test.tsx
src/flashbar/__tests__/utils.test.ts
src/flashbar/collapsible-flashbar.tsx
src/flashbar/utils.ts

See https://github.com/cloudscape-design/components/pull/719#discussion_r1100554050 for more context.
Our `scrollElementIntoView` helper calls the native `scrollIntoView` with the `block' option set to 'nearest', which will not scroll if the element is already in the viewport. Therefore it's not necessary to call to check beforehand if that is the case.
- Adapted unit test accordingly
- Manually tested that the view does not scroll if the button is already in the viewport, with Chrome and Firefox
<details> …

chore: Avoid unnecessary use of getBoundingClientRect in Flashbar

---

pages/table/permutations.page.tsx
pages/table/shared-configs.tsx
pages/table/simple-permutations.page.tsx

Split the `SIMPLE_COLUMNS` permutations for the table, to decrease page length in our screenshot tests.
<details>
- _If the code …

chore: Split simple columns permutations for the Table

---

src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/autosuggest-option.tsx

The `enteredTextLabel` (e.g. "Use ...") item previously got a screenreader override that didn't contain the appropriate message. This fixes that.
Related links, issue #, if available: AWSUI-20334
Tested DOM output, and checked for expected announcements in VO & Chrome.
<details>
- …

fix: Ensure autosuggest `enteredTextLabel` is accessible

---

src/flashbar/collapsible.scss

For a container width below ~400px, the text in the header was unintentionally breaking in Firefox.
Before:
After:
Manually tested on Chrome, Firefox and Safari.
Currently visual regression testing does not cover responsiveness. That can come after #729 is merged.
<details>
- _Changes …

fix: Notification bar responsiveness in Firefox

---

package-lock.json
package.json
src/__tests__/use-base-component.test.tsx
src/__tests__/use-telemetry-usage.test.tsx
src/flashbar/internal/analytics.ts
src/internal/base-component/index.ts
src/internal/base-component/init-awsui-versions.ts
src/internal/hooks/use-base-component/__tests__/use-base-component.test.tsx
src/internal/hooks/use-base-component/component-metadata.ts
src/internal/hooks/use-base-component/index.ts
src/internal/hooks/use-telemetry/index.ts
src/internal/hooks/use-telemetry/telemetry.ts
src/internal/metrics/index.ts
src/internal/metrics/log-clients.ts
src/internal/metrics/metrics-formatters.ts
src/internal/metrics/metrics.ts
src/internal/utils/__tests__/init-metrics.test.ts
src/internal/utils/__tests__/metrics.test.ts
src/wizard/internal/analytics.tsx
tsconfig.json
tsconfig.unit.json

This reverts commit 78f5b59d86946d8af20b948b1cf5828a2ce308d1.
Reason: downstream build failures.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/acces …

chore: Revert use base-component utils from the toolkit (#714)

---

style-dictionary/visual-refresh/metadata/colors.ts

`grey-125` is a new color we added to the system to support Striped Rows in Visual Refresh. Because it wasn't used in any public-facing design tokens, it wasn't showing up on our website in the [list of colors](https://cloudscape.design/foundation/visual-foundation/colors/#system-color-palette) on the foundation page. `grey-125` is used in the token `colorBackgroundCellShaded`.
That pulls from this metadata page, so adding it here will add it to that page.
<details> …

fix: Adds colorBackgroundCellShaded to metadata

---

package-lock.json

This change appears locally when I run `npm install` and does not go away after running `scripts/unlock-package-lock.js` 
I guess, it means that the change belongs to version control now
n/a
<details> …

chore: Fix package lock

---

pages/autosuggest/async.page.tsx
pages/autosuggest/events.page.tsx
pages/autosuggest/simple.page.tsx
pages/autosuggest/virtual-resize.page.tsx
src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/autosuggest-option.tsx
src/autosuggest/options-list.tsx
src/autosuggest/plain-list.tsx
src/autosuggest/virtual-list.tsx

After some testing and internal discussion, it's more appropriate to have only the currently-selected item marked as `aria-selected="true"` in autosuggest (previously it was used to indicate the currently focused/highlighted item). This also aligns the behavior with Select and Multiselect.
Related links, issue #, if available: AWSUI-20335
Tested in VO + Chrome/Safari
<details> …

fix: Ensure only current autosuggest item is marked as aria-selected

---

src/internal/motion.ts

`window.matchMedia` isn't defined in JSDOM. We do have a check for this in TypeScript, but the way we constructed that check means that the function could return undefined. And setState doesn't "dedupe" `undefined` and `false`, so MutationObserver ends up updating the state after the React render.
This feels like debugging incorrect type issues in JavaScript again, but JSDOM quirks are hopefully few and far between...
Related links, issue #, if available: AWSUI-20146 (partial fix)
Manually, in a demo app. But the semantics shouldn't have changed :)
<details> …

fix: Remove update outside of act() for components using useReducedMotion in JSDOM

---

src/flashbar/collapsible.scss

The visual implementation of the Notifications bar is based on the button's implementation, and it is supposed to have the same height as well (22px, excluding padding and border). However, there is a `button` element inside the Notifications bar without a padding defined, which gets the browser default of 1px of vertical padding, making the Notifications bar 2px taller than it should be. This also caused the text to not be fully vertically centered.
This fixes it by explicitly setting this internal button's vertical padding to 0.
Before:
After:
- Manually tested, in Classic as well as Visual Refresh
- Visual regression tests will catch the differences and will have to be reviewed and manually approved
<details> …

fix: Notifications bar height

---

pages/container/fit-height.page.tsx
src/container/internal.tsx
src/container/styles.scss

If container has no footer, ensure it still has some spacing outside the scroll fold
1. Visit [container/fit-height](https://d21d5uik3ws71m.cloudfront.net/components/c86eeea228e412b01ce7ae0e95bad699206e22e5/index.html#/light/container/fit-height) demo page to try new behaviors
2. I also deployed it for screenshot tests in my dev-pipeline
<details> …

fix: Changed container bottom spacing for fit height mode

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/button/__tests__/button.test.tsx
src/button/index.tsx
src/button/interfaces.ts
src/button/internal.tsx

Added a `rel` attribute to the `Button` component. 
Without this change, when we add an `href` to the `Button` component with a `target="_blank"`, the `Button` component automatically adds the `rel` value of `"noreferrer noopener"`, and doesn't offer the option of overwriting this value. Some customers need to alter this default behaviour, hence this change.
Our `Link` component already has a way to override the `rel` attribute but the `Button` does not have this prop, so this change will also play into consistency across our components.
Related issue: AWSUI-20328
<details> …

feat: Add 'rel' attribute to Button

---

src/flashbar/styles.scss

Avoid Flashbar list gets additional padding.
Related links, issue #AWSUI-20382
<details> …

fix: Avoid flashbar list gets additional padding

---

src/internal/components/visual-context/index.tsx

With React 18, `useMutationObserver` seems to be firing its callback _after_ the rendering is complete, which causes it to throw "an update was not wrapped in act(...)" errors in the top navigation component, since it renders a dropdown inside a custom visual context. So the visual context is initially `""`, but is updated after render to be `"top-navigation"`.
Unlike other "settings" (mode, motion, and density), visual contexts are used internally within the components in pretty close proximity to the children and aren't really updated outside of the React loop, so we could just get away with a simple `useLayoutEffect` instead of a mutation observer.
Related links, issue #, if available: AWSUI-20146 (partial fix)
Existing tests should cover this. Also tested this in a demo application, …

fix: Remove mutation observer from useVisualContext

---

src/app-layout/notifications/styles.scss
src/app-layout/styles.scss
src/app-layout/visual-refresh/navigation.scss
src/app-layout/visual-refresh/notifications.scss
src/app-layout/visual-refresh/split-panel.scss
src/app-layout/visual-refresh/tools.scss
src/split-panel/styles.scss

In the App layout, currently the Split panel has a higher z-index (851) than the Flashbar (825). This causes usability issues when a certain number of notifications are displayed, since they are partly covered by the Split panel. If using the Stacked notifications feature, this can also lead to the Notifications bar falling out of reach.
This change fixes this by reordering the following z-indices:
- Side navigation and Tools drawer: from 850 down to 830
- Split panel: from 851 down to 840
- Notifications: from 825 up to 850
This leaves all of them within the range of 800-850 as stated by our [documentation](https://cloudscape.design/get-started/dev-guides/z-index). This is still a safe distance to the next higher z-index elements such as Mobile toolbar, Popover and Top navigation drawer, …

fix: Display notifications on top of split panel

---

pages/utils/screenshot-area.tsx

The current max page size for the screenshots is out of date (reduced from 20000 to 16000). This PR updates it.
There is also a corresponding [PR](https://github.com/cloudscape-design/browser-test-tools/pull/37) for browser-test-tools, as these values should be kept in sync.
My dev pipeline (v3-rucarva)
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTI …

chore: Update screenshot max page height

---

src/button-dropdown/__tests__/button-dropdown.test.tsx
src/internal/components/dropdown/index.tsx

Use [composedPath](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath) to support click events originating from a shadow DOM
Our application is a micro-frontend that is rendered inside a Shadow DOM. We have been using this UI library for about a year now.
However, this [commit](https://github.com/cloudscape-design/components/commit/5fced58558b90769fc22a58c4657fdb8ff2bac58) seems to have broken our `ButtonDropdown`. 
When a user picks an option, the menu dropdown closes but the `onItemClick` does **not get triggered** anymore.
See: [How event retargeting and how event propagation works inside Shadow DOM
](https://pm.dartus.fr/blog/a-complete-guide-on-shadow-dom-and-event-propagation/#event.prototype.target-and-event-retargeting) …

fix: Use composedPath to support click events originating from a shadow DOM

---

src/flashbar/collapsible.scss

The following was happening to the notification bar on viewports below ~410px width:
- It would occupy the whole container width, covering the stacked notifications and therefore removing the visual cues about multiple notifications being present:
- It would not allow to shrink below ~250px, and it would start to occupy space to the right for narrower viewports:
This change introduces the following improvements:
- A margin to the sides is reserved, so that the bottom items in the stack is always visible:
- Horizontal margin was removed from the item counter block, so that the component can shrink somewhat further before continuing to wrap:
- When shrinking even further, the item counters can also wrap. All items are kept centered:
- Manually tested on Chrome, Firefox and Safari
- Visual …

fix: Responsiveness of Flashbar notification bar

---

src/flashbar/collapsible.scss

On refactoring, the border width of the notification bar in Visual Refresh was accidentally changed from 2px to 3px in #775. This made the notification bar 2px taller than expected in Visual Refresh. This PR reverts that unintended change.
This was caught by visual regression tests.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-suppor …

fix: notification bar border width in Visual Refresh

---

src/property-filter/__tests__/utils.test.ts
src/property-filter/utils.ts

We can't control casing of property values, so want to ensure that case-sensitive
matching is preferred over looser case-insensitive.
Related links, issue #, if available: AWSUI-20452
New unit tests
<details> …

fix: Prefer case-sensitive match for property filter value matching

---

src/s3-resource-selector/s3-modal/__tests__/buckets-table.test.tsx
src/text-filter/__tests__/text-filter.test.tsx
src/text-filter/internal.tsx

1. Debounce countText using `LiveRegion` instead of using aria-live directly, so that announcements wait for a little bit after text input is done being announced. Went for 2 seconds after manual testing, but there's no rule here.
2. Attach countText to the input using `aria-describedby` as a "fallback", so it's always announced at the end when the user focuses into the text field.
Related links, issue #, if available: AWSUI-20166
Unit tests
<details>
- …

fix: Debounce countText announcement and link it to text filter input

---

src/internal/components/option/highlight-match.tsx
src/select/parts/item.tsx

Bit of a quick fix for https://github.com/facebook/react/issues/11538, specifically in the case of filtering highlight styles (the blue text that highlights the part of the selection that's matched).
Related links, issue #, if available: AWSUI-20453
Soo... you'll have to manually test this.
1. Download Google Translate from the Chrome Web Store.
2. Set your primary language in the extension to something other than English.
3. Pick a page with the property filter, select with filtering, or multiselect with filtering and translate the page.
4. Try filtering the results - the app shouldn't crash.
Maybe, in the long term, we could somehow assert that the DOM never has text nodes with siblings, maybe with a MutationObserver or something, but that's just a idea floating in my head.
<details> …

fix: Prevent filtering highlight from crashing with Google Translate

---

pages/collection-preferences/simple.page.tsx
src/collection-preferences/__integ__/collection-preferences.test.ts
src/collection-preferences/index.tsx
src/collection-preferences/interfaces.ts
src/collection-preferences/utils.tsx

This change makes sure that the collection preferences modal switches to a one-column layout (instead of two columns) whenever possible. For example, when there is only content for the left-hand side (page sizes, custom preferences, ...), or when there's only content for the right-hand side (visible column preferences).
Additionally, the size of the modal is reduces from "large" to "medium" if only one column is rendered.
These changes removes some unused space and makes sure that we use the space more efficiently.
Related links, issue #, if available: AWSDesignSystem-369
Internal document: mp8XA9mFCRQI
<details>
- …

feat: Improve collection preferences modal responsiveness when only using some features

---

src/collection-preferences/__tests__/collection-preferences.test.tsx
src/collection-preferences/index.tsx

This PR fixes a small typo in a warning message.
There is a unit test that covers this message, which was affected by the same typo and it was fixed as well.
<details> …

fix: Typo in Collection preferences warning

---

src/table/__tests__/a11y.test.tsx
src/table/internal.tsx

Previous calculation was incorrect: announced e.g. "Items 1 to 21" when 20 items are displayed per page.
Unit test update
<details> …

fix: Calculate `lastIndex` of table renderAriaLive correctly

---

src/internal/components/option/highlight-match.tsx
src/select/parts/item.tsx

Reverting this temporarily to unblock later changes while we sort out issues with downstream consumers.

revert: Revert "fix: Prevent filtering highlight from crashing with Google Translate"

---

pages/popover/header-variant.page.tsx
src/popover/body.scss

When using a popover without a title, fixed width and a long content string, the closing icon was displaced outside the popover.
Defining the min-width for the content fixed this behavior and place the closing icon inside the popover.
See this before/after image:
Related links, issue #, if available: AWSUI-20388
- verified manually on in our supported browsers.
- added additional screenshot test covering the new example page.
<details>
- _Changes do not …

fix: Popover dismiss button and content displaced

---

src/internal/components/options-list/utils/use-keyboard.ts
src/select/__tests__/select.test.tsx

It's a button, and buttons activate with Enter. This isn't what the native `<select>` does, but accessibility software announces the listbox trigger as a button, so keyboard users expect button controls.
<details>
- _Changes …

fix: Allow select/multiselect buttons to be activated with Enter

---

src/button-dropdown/__tests__/button-dropdown.test.tsx
src/internal/components/dropdown/index.tsx

This reverts commit bf4538668390b58a0d7687bc0245f015edd1df76.
this broke unit tests for some users
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/acc …

revert: "fix: Use composedPath to support click events originating from a shadow DOM (#781)"

---

src/popover/__tests__/popover.test.tsx
src/popover/body.tsx
src/popover/index.tsx

The current state is: if a popover has no header, it's not marked as a dialog, even if it traps focus. Not great.
This was originally changed to ensure popover dialogs always have valid titles, but an unlabeled dialog is better (well, less terrible) than a non-dialog focus trap. We may need to allow users to provide assistive tech only aria-labels for dialog headings in the future, but I'll wait for customer data before I do that; an explicit heading still provides an equal experience for everyone, and screen readers still read out unlabeled dialog contents.
So we have popovers acting as:
- Announcements: (e.g. "Text copied", no dismiss button, just aria-live)
- Modal dialogs: (i.e. has a dismiss button, should have a header)
- Non-modal dialogs: (i.e. annotation popovers, you can tab …

fix: Always set role="dialog" on popover with dismiss button

---

themes/icons/edit.svg

This change replaces the existing "Edit" icon with a new icon. This is intended to reduce confusion caused by the similar appearance of the "External" icon and the "Edit" icon.
Note that GitHub's commit diff renders the icons incorrectly, because it does not contain our logic for setting the appropriate stroke width per icon size. You can see a screenshot of the new icon in each size here:
Tested manually in the dev pages.
Check out this PR locally, run the package and visit
-  http://localhost:8080/#/light/icon/variant-normal and
-  http://localhost:8080/#/light/table/editable-with-app-layout/
<details> …

feat: Update "Edit" icon

---

.eslintrc
pages/tsconfig.json
tsconfig.json

Well, this is embarrassing. Turns out my PR to target ES2015 didn't actually target ES2015. Let's fix that :)
I discovered my mistake while looking at the generated assets, and I can confirm it works by doing just that again.
Check my internal pipeline; no non-flaky failures. An internal dry-run also succeeded, Slack me for the build link :)
<details> …

chore: Compile to ES2015 (following up from #794)

---

pages/app-layout/with-table.page.tsx
pages/table/sticky-header-focusable-elements.page.tsx
src/checkbox/internal.tsx
src/internal/components/abstract-switch/index.tsx
src/internal/components/abstract-switch/styles.scss
src/table/__integ__/sticky-header.test.ts
src/table/__tests__/header-cell.test.tsx
src/table/__tests__/sorting.test.tsx
src/table/header-cell/index.tsx
src/table/internal.tsx
src/table/resizer/index.tsx
src/table/selection-control/index.tsx
src/table/sticky-header.tsx
src/table/thead.tsx

Basically, this implementation manually tracks the three kinds of focusable elements in the header: selection checkbox, sort button, resize control — and passes it to the sticky header, which draws fake focus rings around them. This means keyboard users always interact with the "real" controls, but the focus visuals are always visible. Mouse interaction still means that focus is placed inside an aria-hidden region, but... baby steps. This is the clearest approach for now, since we're sorta stuck with using the fake floating header (can't use `position: sticky` because of an inner scroll container).
After shipping the immediate fix, it might be nice to pass the focus to the "real" control on click so that you can switch between keyboard/mouse, but that might introduce weird unintended …

fix: Ensure correct selection and resize controls are focused when sticky header is enabled

---

pages/app/styles.scss
src/app-layout/styles.scss
src/app-layout/visual-refresh/background.scss
src/app-layout/visual-refresh/layout.scss
src/app-layout/visual-refresh/notifications.scss
src/container/styles.scss
src/content-layout/styles.scss
src/internal/components/dark-ribbon/styles.scss
src/table/styles.scss
src/wizard/styles.scss

Spinner with `normal` variant picks up the current color of its context. If there is no color defined in parent elements it is using the default black color. Adding `$color-text-body-default` color to Applayout, to make sure the currentColor is the default text color.
For dark headers in `awsui-context-content-header` context, need to define `$color-text-body-default` to correct children `currentColor` in this context(dark mode color). Otherwise it still uses the light mode color. 
Related links, issue #AWSUI-20480
<details> …

fix: Add default text color to applayout

---

src/side-navigation/__tests__/side-navigation.test.tsx
src/side-navigation/internal.tsx

This reverts commit [9359ffd](https://github.com/cloudscape-design/components/commit/9359ffd24cc5d9b5041f007510d1e36af8b9d6c8)
While the change was approved by AWS A11y team, a11y test tools like Continuum and Axe are strict on this markup.
Assuming that customers may also have automated a11y tests, it's better to revert this change and reconsider the approach. 
<details> …

revert: "fix: Add role 'presentaion' to SideNavigation divider (#800)"

---

src/app-layout/constants.scss
src/app-layout/content-wrapper/index.tsx
src/app-layout/content-wrapper/styles.scss
src/app-layout/index.tsx
src/app-layout/visual-refresh/layout.scss

Change content width for `contentType="dashboard"`, according to design feedback
* Can be seen on [this page](https://d21d5uik3ws71m.cloudfront.net/components/49cc0fa40ff3006d6857e53c219b3bfddd7d835b/index.html#/light/app-layout/dashboard-content-type)
* Also see the CR-85870916 for relevant screenshot test changes
<details> …

feat: Custom content widths for dashboard content type

---

src/code-editor/__tests__/code-editor.test.tsx
src/code-editor/tab-button.tsx

Title says it all :)
Related links, issue #, if available: AWSUI-20526
New unit test
<details> …

fix: Ensure CodeEditor buttons don't submit parent forms

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/code-editor/__tests__/code-editor.test.tsx
src/code-editor/__tests__/util.tsx
src/code-editor/index.tsx
src/code-editor/interfaces.ts

Adding a `ref` to the code editor with `focus` function to allow customers to have the ability to focus on the code editor component when needed.
AWSUI-20473
<details> …

feat: Add ref with focus to code editor

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/alert/interfaces.ts
src/code-editor/interfaces.ts

Remove deprecatedTag in event api to unblock fix https://github.com/cloudscape-design/documenter/pull/18.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-princip …

chore: Remove deprecatedTag in event api 

---

src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/index.tsx

Property Filter has div as child element of span.
AWSUI-20592
Added a11y test.
<details> …

fix: Invalid html markup in property filter

---

pages/space-between/permutations.page.tsx
src/area-chart/internal.tsx
src/mixed-line-bar-chart/__tests__/mixed-chart.test.tsx
src/mixed-line-bar-chart/internal.tsx
src/pie-chart/__tests__/pie-chart.test.tsx
src/pie-chart/index.tsx
src/space-between/__tests__/space-between.test.tsx
src/space-between/internal.tsx
src/space-between/styles.scss
src/token-group/internal.tsx

Ensure that conditionally-rendered (and therefore potentially null/empty) children are handled by SpaceBetween. Also take the opportunity to modernize the approach (as we no longer need to support IE11).
Related links, issue #, if available: AWSUI-20570
Screenshot tests run in dev pipeline
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers …

fix: Remove spacing around null SpaceBetween children

---

src/side-navigation/__tests__/complex-side-navigation.test.tsx
src/side-navigation/index.tsx
src/side-navigation/internal.tsx
src/side-navigation/styles.scss
src/test-utils/dom/side-navigation/index.ts

Follow-up for https://github.com/cloudscape-design/components/pull/613, https://github.com/cloudscape-design/components/pull/800
Dividers are used to split the list of items in side navigation into different `<ul>`. This will improve the perception of the side navigation for screenreader users.
Related links, issue #, if available: AWSUI-20463, AWSUI-20493
New unit test added to cover more complex structure of the side nav
<details> …

feat: Split Side navigation by dividers into separate lists

---

src/app-layout/__tests__/split-panel.test.tsx
src/app-layout/visual-refresh/tools.scss
src/app-layout/visual-refresh/tools.tsx
src/test-utils/dom/split-panel/index.ts

findSplitPanel() always return true in VR because `splitPanelStyles.root` is available in `aside` for tool and splitpanel toggle button. 
The fix is to remove this class from `aside`.
Also to change findOpenButton() not rely on SplitPanelWrapper because it is not always inside a split panel. 
Related links, issue #AWSUI-20594
Add unit test. Build succeed 6382342675
<details> …

fix: FindSplitPanel selector returns true without splitpanel

---

src/autosuggest/__integ__/events-autosuggest.test.ts
src/autosuggest/__integ__/page-objects/events-autosuggest-page.ts
src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/internal.tsx

This option actually does nothing, because the value is already there. It basically operates like a "close dropdown" button
Related links, issue #, if available: AWSUI-20591
* Updated related test
* Running compatibility tests in my dev pipeline
<details> …

fix: Do not emit change events when use-entered option is selected

---

.eslintrc
src/annotation-context/index.tsx
src/annotation-context/utils.ts
src/date-range-picker/dropdown.tsx
src/multiselect/internal.tsx
src/tutorial-panel/components/tutorial-detail-view/task-list.tsx

Components can use other components internally but importing from `index.tsx` is disallowed.
However, there were three imports that violate the rule because of having `/index.js` path which was probably auto-inserted by the IDE.
Runner `npm run lint` with updated rule configuration.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-suppor …

fix: Internal component imports

---

src/code-editor/preferences-modal.tsx
src/modal/internal.tsx
src/popover/internal.tsx

Previously, inputs within a Modal were getting auto-labelled/described by a parent FormField of the Modal component. This prevents that from happening.
Related links, issue #, if available: AWSUI-20621
Tested locally
<details> …

fix: Ensure FormFieldContext doesn't leak into modal-style components

---

src/autosuggest/__integ__/events-autosuggest.test.ts
src/autosuggest/__integ__/page-objects/events-autosuggest-page.ts
src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/internal.tsx

This broke valid use-cases, so we need to revisit this approach
Reverts cloudscape-design/components#834

revert: Do not emit change events when use-entered option is selected

---

.github/workflows/visuals.yml

The `visuals` workflow (for Visual regression testing) is still using `actions/download-artifact` v2 and `actions/upload-artifact` v2. Upgrading these to v3 ensures that we're using at least NodeJS 16.
No expected breaking changes apart from the Node/npm upgrade, see https://github.com/actions/upload-artifact/releases/tag/v3.0.0.
<details> …

chore: Upgrade NodeJS for visuals workflow

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/autosuggest/__integ__/events-autosuggest.test.ts
src/autosuggest/__integ__/page-objects/events-autosuggest-page.ts
src/autosuggest/__tests__/autosuggest-and-token-group.test.tsx
src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/interfaces.ts
src/autosuggest/internal.tsx

Follow up for https://github.com/cloudscape-design/components/pull/834. Another attempt to resolve AWSUI-20591, but this time in a backward compatible way
Related links, issue #, if available: AWSUI-20591
Added extra tests 
<details> …

feat: Add extra detail to autosuggest onSelect handler

---

pages/token-group/generic.page.tsx
pages/token-group/styles.scss
src/token-group/generic-token-group.tsx
src/token-group/internal.tsx

The generic token group is an internal component to reuse token group for arbitrary content. It is needed to support the addition of file upload component, see https://github.com/cloudscape-design/components/pull/829.
Relying on the existing tests because the new component is an excerpt from the internal token group.
Added new test page to be used as dev. reference/playground.
<details> …

feat: Internal generic token group component

---

src/internal/i18n/context.ts

Let's say, hypothetically, some consumers also mock out useCallback. It's also unnecessary now, since the function it relies on isn't stable anymore.
I can send you the failed build to validate.
<details> …

fix: Remove uses of useCallback from internal i18n hook

---

src/pagination/internal.tsx

Previous identifier was incorrect, this should allow the correct strings to be picked up.
https://github.com/cloudscape-design/components/blob/main/src/internal/i18n/messages/all.en.json#L40-L42
<details> …

fix: Use correct message pack path for pagination labels

---

src/table/__tests__/inline-editor.test.tsx
src/table/body-cell/inline-editor.tsx

The `editConfig.constraintText` API for table inline editing was not implemented.
Tested this manually and added a unit test. Visually this will also be covered by the new permutations in https://github.com/cloudscape-design/components/pull/857.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-su …

fix: Fix constraint text for table inline editing

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/link/interfaces.ts

This change slightly rephrases the documentation text of Link's `onFollow` event. We received feedback that this is a little unclear for button-variant links.
<details> …

chore: Update documentation of Link's `onFollow` event to be more clear

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/interfaces.ts
src/button-dropdown/__tests__/button-dropdown-items.test.tsx
src/button-dropdown/interfaces.ts
src/button-dropdown/item-element/index.tsx
src/internal/components/option/index.tsx
src/internal/components/option/interfaces.ts
src/multiselect/__tests__/multiselect.test.tsx
src/select/__tests__/select.test.tsx
src/select/interfaces.ts

We signed this off a while ago - just got confirmation on some accessibility-related things today, got the descriptions approved, and we're good to ship.
Related links, issue #, if available: AWSUI-19568 and AWSUI-20461
Added unit tests for all affected components.
<details>
- _Changes …

feat: Add lang property to option types

---

pages/table/inline-editor.permutations.page.tsx

Adds a permutation page that displays the table inline editor component in various states. Used for visual regression testing.
<details> …

chore: Add permutations for table inline editor

---

pages/table/editable-with-app-layout.page.tsx

Add ScreenshotArea to inline editing page for visual regression testing.
<details>
- _If the …

chore: Add ScreenshotArea to inline editing page

---

src/internal/i18n/__tests__/i18n.test.tsx
src/internal/i18n/__tests__/ssr.test.ts
src/internal/i18n/__tests__/test-component.tsx
src/internal/i18n/provider.tsx

Whoops. This one's on me. Thought optional chaining on `document` would save me here, but I would still need to explicitly check that the variable is even defined in SSR. 
Wrote an SSR test to make sure this doesn't break.
<details>
- _Changes …

fix: Fix SSR support in I18nProvider

---

src/internal/i18n/context.ts

refactor: Remove useContext hack from i18n context

---

src/app-layout/__integ__/awsui-applayout.test.ts

Since refresh and classic are separate implementations it would be great to run the same test on both versions to ensure their compatibility
Related links, issue #, if available: The tests failed before https://github.com/cloudscape-design/components/pull/839 and pass now
This is testing changes
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#br …

chore: Run more app layout tests for visual refresh

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/autosuggest/internal.tsx
src/calendar/grid/index.tsx
src/calendar/header/header-button.tsx
src/calendar/header/index.tsx
src/calendar/interfaces.ts
src/calendar/internal.tsx
src/date-picker/index.tsx
src/internal/i18n/context.ts
src/internal/i18n/messages/all.de.json
src/internal/i18n/messages/all.en-GB.json
src/internal/i18n/messages/all.en.json
src/internal/i18n/messages/all.es.json
src/internal/i18n/messages/all.fr.json
src/internal/i18n/messages/all.id.json
src/internal/i18n/messages/all.it.json
src/internal/i18n/messages/all.ja.json
src/internal/i18n/messages/all.ko.json
src/internal/i18n/messages/all.pt-BR.json
src/internal/i18n/messages/all.zh-CN.json
src/internal/i18n/messages/all.zh-TW.json
src/internal/i18n/provider.tsx
src/property-filter/index.tsx
src/wizard/__tests__/wizard.test.tsx
src/wizard/index.tsx
src/wizard/interfaces.ts
src/wizard/wizard-actions.tsx
src/wizard/wizard-form.tsx

Because the messages came back after the implementation, I missed a few components that should've been included in the latest batch of translation strings.
The translation files were also wrong because they swapped wizard and autosuggest. So I switched them out, sorted them alphabetically, and spaced them out so they looked nice and maintainable.
Existing unit tests.
<details> …

chore: Add i18n to autosuggest, date picker, and wizard

---

src/table/header-cell/index.tsx

This attribute is only valid on certain roles (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled#associated_roles) so it's incorrect to use it here on a plain `div`.
<details> …

fix: Remove `aria-disabled` from non-sortable columns

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/tutorial-panel/__tests__/tutorial-panel.test.tsx
src/tutorial-panel/components/tutorial-list/index.tsx
src/tutorial-panel/interfaces.ts

Make download link in tutorial panel optional by not rendering the link when `downloadUrl` is not passed
Related links, issue #872 
added a unit test
<details> …

fix: Make tutorial panel downloadUrl optional

---

src/breadcrumb-group/__tests__/breadcrumb-group.test.tsx
src/breadcrumb-group/internal.tsx
src/breadcrumb-group/styles.scss

Ensure breadcrumb group test utils work for short lists
Related links, issue #, if available: AWSUI-20701
Updated unit tests
<details> …

fix: Ensure breadcrumb group test utils work for short lists

---

src/container/internal.tsx
src/container/styles.scss

This partially reverts commit e66b674ba1e2c6c5629d0ff1e9abb004ce77ccaf.
The dev pages changes stay, the source code changes revert
Reverting the change because it caused issues for static dashboard demo https://cloudscape.design/examples/react/dashboard.html
This vertical scrollbar is a bug
This behavior is not reproducible on demo pages (needs negative margins to show up). Will be tested later in the pipeline with the demo pages build
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CO …

revert: Changed container bottom spacing for fit height mode (#766)

---

src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/index.tsx
src/property-filter/property-filter-autosuggest.tsx
src/property-filter/styles.scss
src/s3-resource-selector/s3-modal/__tests__/buckets-table.test.tsx
src/test-utils/dom/property-filter/index.ts
src/text-filter/__tests__/text-filter.test.tsx
src/text-filter/internal.tsx
src/text-filter/search-results.tsx
src/text-filter/styles.scss

Fixed an issue (AWSUI-20714) with property-filter countText resulting in an extra padding when undefined. Additionally, aligned search results handling between property-filter and text-filter based on the recent change to the latter: https://github.com/cloudscape-design/components/pull/782.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browser …

fix: Empty search results result in extra padding

---

themes/icons/drag-indicator.svg
themes/icons/resize-area.svg

fix: Size of new drag-indicator and resize-area icons

---

src/table/body-cell/styles.scss

Editable table cells can be focused with a keyboard, and they have a special visual state when hovering over them with your mouse. This change fixes a problem where the keyboard focus outline on a cell would become invisible when the user also hovers over the cell.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIB …

chore: Make sure focus outline in table editing is not hidden by mouse hover

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/attribute-editor/__tests__/attribute-editor.test.tsx
src/attribute-editor/interfaces.ts
src/attribute-editor/internal.tsx
src/tag-editor/__integ__/tag-editor.test.ts
src/tag-editor/__tests__/tag-editor.test.tsx
src/tag-editor/index.tsx

Standardize focus handling when removing tags in TagEditor: focus another tag when possible, otherwise the 'Add tag' button.
Related links, issue #, if available: AWSUI-20696
New unit tests
<details> …

fix: Standardize focus behavior when removing tags

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/autosuggest/interfaces.ts
src/input/interfaces.ts
src/internal/components/autosuggest-input/index.tsx

This was accidentally added to the BaseInputProps interface, hopefully no-one has started using it yet...
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-princip …

fix: Remove unwanted `clearInputLabel` from input elements that do not support it

---

build-tools/tasks/typescript.js

Before this change, the sources pointed to the relative path outside of the code package. This is fine during development but points to a wrong path when consuming the built artifacts. See screenshot which illustrates the wrong mapping:
Setting the `sourceRoot` fixes that and points to the correct location in dev mode and when consuming the
artifacts.
AWSUI-20467
Verified in a vite and webpack project. Also in components local dev env.
You can test the changes when checking out this PR and browse through the devtools sources tree.
<details> …

chore: Update set source map's sourceRoot path

---

pages/focus-lock.page.tsx
pages/table/editable.page.tsx
src/internal/components/focus-lock/__integ__/focus-lock.test.ts
src/internal/components/focus-lock/index.tsx
src/table/__integ__/inline-editing.test.ts
src/table/__integ__/table.test.ts
src/table/__tests__/inline-editor.test.tsx
src/table/body-cell/inline-editor.tsx
src/table/header-cell/styles.scss
src/table/resizer/styles.scss

This reverts commit 1c3d3084e5a3256671ff7c9a26d777d4e89cafd7.
<details>
- _If the code …

chore: Revert update table column header appearance

---

pages/expandable-section/permutations.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/expandable-section/__tests__/expandable-section.test.tsx
src/expandable-section/expandable-section-header.tsx
src/expandable-section/interfaces.ts
src/expandable-section/styles.scss
src/tutorial-panel/__tests__/tutorial-panel.test.tsx

Allow standard expandable sections to have a heading tag (rather than plain div) for accessibility/semantic purposes.
<details> …

feat: Allow headings in expandable-section

---

pages/button/tab-navigation.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/button/__integ__/button.test.ts
src/button/__tests__/button.test.tsx
src/button/interfaces.ts
src/button/internal.tsx
src/wizard/__tests__/wizard.test.tsx
src/wizard/wizard-actions.tsx

This change makes buttons with `loading={true}` focusable by only setting the `aria-disabled` attribute but not `disabled`.
Buttons are usually not in a loading state from the beginning. Users activate a button, which starts some kind of background process and turns on the loading state to visually indicate this. However, a `<button>` element with the attribute `disabled` cannot be focused. So if a keyboard user activates a button which then turns into a loading state, the keyboard focus is lost and goes to the document body.
This can be a frustrating experience for pattern like Wizard flows where the next step is loaded asynchronously, or during table inline editing.
Tested manually with keyboard and VoiceOver. Also did a successful dry-run. …

feat: Buttons in loading state can now be focused for better screen reader experience

---

src/tutorial-panel/__tests__/tutorial-panel.test.tsx
src/tutorial-panel/components/tutorial-detail-view/task.tsx

The `headerText` slot is designed only for plain text, so applying styling within it causes unexpected side-effects, but that styling is necessary for 
Tested locally, will follow-up with improved screenshot test coverage
<details>
- _Changes …

fix: Use `header` slot of ExpandableSection for tutorial steps

---

src/app-layout/__tests__/common.test.tsx
src/app-layout/drawer/index.tsx

It turns out I did fix this issue earlier, but it was only raised for mobile toggles. I don't _love_ this fix (or the original code), but I guess it was what we had to do when we put clickable elements inside clickable elements.
Related links, issue #, if available: AWSUI-20745
Added a new unit test for this case.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main …

fix: Fix classic app layout calling onNavigationToggle and onToolsToggle twice on desktop

---

src/attribute-editor/row.tsx
src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/internal.tsx
src/expandable-section/expandable-section-header.tsx
src/internal/hooks/use-unique-id/index.ts
src/property-filter/property-filter-autosuggest.tsx
src/select/parts/trigger.tsx

Revived version of #233
Native hook produces deterministic ids in server-side rendering, which is useful feature and not possible to adopt without changes in our components
* Our demos package uses React 18, so it will cover that condition
* Also deployed to my dev pipeline to have a closer look at all demos
<details> …

feat: Use native useId hook if available

---

pages/onboarding/with-app-layout.page.tsx

Allow onboarding page to be used in screenshots, to catch possible regressions sooner in our pipeline.
Will add integration tests once merged.
<details> …

chore: Allow onboarding page to be used in screenshot tests

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/__tests__/target-rel-test-helper.ts
src/button/__tests__/button.test.tsx
src/link/__tests__/index.test.tsx
src/top-navigation/__tests__/top-navigation-overflow-menu.test.tsx
src/top-navigation/__tests__/top-navigation-utility.test.tsx
src/top-navigation/interfaces.ts
src/top-navigation/parts/overflow-menu/menu-item.tsx
src/top-navigation/parts/utility.tsx

Added "target" and "rel" attributes for top-nav link utilities. We support these attributes for buttons and links.
Ticket: 20785
New unit tests
<details> …

feat: Add target and rel attributes to top-nav utilities

---

src/top-navigation/__tests__/top-navigation-overflow-menu.test.tsx
src/top-navigation/__tests__/top-navigation-utility.test.tsx
src/top-navigation/parts/utility.tsx

The events fired when the utility button is clicked from the header and from the overflow menu must be the same. The utilities of type="button" are not expected to have any attributes in the detail object.
Closes https://github.com/cloudscape-design/components/issues/915
<details> …

fix: Top navigation utility clicks event details misalignment

---

src/expandable-section/__tests__/expandable-section.test.tsx
src/expandable-section/expandable-section-header.tsx

A previous change introduced the ability to have different semantic headings for Expandable Sections that don't use the `container` variant (https://github.com/cloudscape-design/components/pull/919). However, this also added additional code for ARIA that is not needed for default variants, because these variants don't use `headerDescription` or `headerCounter`.
This PR removes the unnecessary code for these variants.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#publi …

chore: Remove unnecessary ARIA code for default expandable section

---

pages/token-group/custom.page.tsx
src/internal/components/filtering-token/index.tsx
src/internal/components/token-list/index.tsx
src/internal/components/token-list/interfaces.ts
src/internal/components/token-list/token-focus-controller.tsx
src/property-filter/index.tsx
src/property-filter/token.tsx
src/token-group/__tests__/token-group.test.tsx
src/token-group/internal.tsx
src/token-group/token.tsx

Although technically it works, having aria-label, aria-description or aria-disabled on li elements is not recommended and has been reported by html-validator. Instead it is possible to use role=group for the tokens that are directly nested under li  elements.
Tested manually with VO and NVDA.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#brows …

fix: Add role=group to token-group and property-filter tokens

---

src/flashbar/__tests__/collapsible.test.tsx
src/test-utils/dom/flashbar/index.ts

This adds a new test util to Flashbar which lets teams target the toggle button for stacked notifications. This enables them to expand stacked notifications.
Related links, issue #, if available: AWSUI-20428, AWSUI-20787
<details> …

feat: Add `findToggleButton` test utility to Flashbar

---

src/app-layout/visual-refresh/app-bar.tsx

This is a follow up to #925 that resolves a minor error in the component logic. The application toolbar should not be suppressed if the drawers API is present. Currently it only checks the navigation, breadcrumbs, and tools. If the drawers API is used while all three of these are null then it will not be accessible in mobile viewports.
<details> …

fix: The AppBar should render when only drawers are present.

---

src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/internal.tsx
src/autosuggest/options-list.tsx
src/internal/components/dropdown-footer/index.tsx
src/internal/components/live-region/index.tsx
src/internal/components/options-list/index.tsx
src/multiselect/__tests__/multiselect.test.tsx
src/multiselect/internal.tsx
src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/property-filter-autosuggest.tsx
src/select/__tests__/select.test.tsx
src/select/internal.tsx

Associate dropdown footer with the actual list element using `aria-describedby` to give more persistent visibility of the message (it's currently aria-live announced, but then hard to re-discover).
Related links, issue #, if available: AWSUI-20604
New/updated tests
<details>
- _Changes …

feat: Associate dropdown footers with the dropdown list element

---

pages/app-layout/dashboard-content-type.page.tsx
pages/app-layout/utils/strings.ts
src/__tests__/__snapshots__/documenter.test.ts.snap
src/split-panel/interfaces.ts
src/split-panel/preferences-modal.tsx

When `hidePreferences` button is used, there is no point in passing strings for the modal, because it will never show. Additionally, when `closeBehavior` is `hide`, open button is also not displayed.
Updated the demo where we use this property to only include required strings
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/m …

fix: Allow to skip optional i18n strings on split panel

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/index.tsx
src/property-filter/interfaces.ts
src/property-filter/property-filter-autosuggest.tsx

PropertyFilter input can already accept these via FormFieldContext, so allow them also
to be overridden for custom use-cases.
Related links, issue #, if available: AWSUI-20256
Unit tests
<details> …

feat: Add labelling properties to PropertyFilter

---

pages/theming/integration.page.tsx
pages/theming/styles.scss
pages/theming/tokens.page.tsx
src/__a11y__/a11y-refresh-dark.test.ts
src/__a11y__/a11y-refresh-light.test.ts
src/__a11y__/run-a11y-tests.ts
src/theming/__integ__/index.test.ts
src/theming/__integ__/tokens.test.ts
src/theming/index.ts

Expose API introduced in https://github.com/cloudscape-design/theming-core/pull/37
Additional fix pending merge: https://github.com/cloudscape-design/theming-core/pull/39
- _Changes include appropriate documentation updates._ Not yet. Updates to website will be published at a later stage
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._ Confirmed …

feat: Expose runtime theming API for secondary themes

---

pages/app-layout/all-panels-open.page.tsx
pages/app-layout/with-drawers.page.tsx
src/app-layout/__tests__/mobile.test.tsx
src/app-layout/visual-refresh/navigation.tsx
src/app-layout/visual-refresh/tools.tsx

When both `navigationOpen` and `toolsOpen` are `true` same time, nothing is displayed.
This PR fixes it, making the tools taking precedence, same way as it works in Classic version
Related links, issue #, if available: AWSUI-20930
* Added extra unit tests
* Added dev page for manual testing of the new drawers feature
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/m …

fix: Fix app layout rendering when multiple drawers are open on mobile

---

src/s3-resource-selector/s3-modal/__tests__/main.test.tsx
src/s3-resource-selector/s3-modal/basic-table.tsx

S3 selector modal has inaccurate heading hierarchy in classic mode. Specifically, both modal header and table header are h2.
Go to [S3 selector page](https://d21d5uik3ws71m.cloudfront.net/components/05d92d1f7d46a94b73b3b88f92dcc5832ff80fd0/index.html#/light/s3-resource-selector/main/?visualRefresh=false), open modal, inspect Table heading.
<details> …

fix: Adjust heading hierarchy in s3 selector

---

pages/table/sticky-columns.page.tsx

Simplify sticky columns test page and make it configurable with url params.
<details>
- _If …

chore: Make sticky columns test page configurable

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/link/interfaces.ts

When link component used without `href` prop, `onFollow` fires on all keys even with modifiers. 
Add this behavior to the documentation
Doc only change
<details> …

chore: Update link API docs

---

pages/table/editable.page.tsx
pages/table/performance.page.tsx
src/table/__integ__/inline-editing.test.ts
src/table/__tests__/table.test.tsx
src/table/body-cell/index.tsx
src/table/body-cell/styles.scss
src/table/body-cell/td-element.tsx
src/table/use-table-focus-navigation.ts
src/test-utils/dom/table/index.ts

When a table has editable cells, it renders a few more elements in every cell to make them clickable and editable. These additional elements can cause performance regressions when compared to a table that doesn't have inline editing enabled.
This change attempts to improve the performance of editable tables by removing the amount and complexity of additional elements:
* The `<Button>` is replaced with a `<button>`
* The edit icon is rendered conditionally when the cell is hovered or focus
Related links, issue #, if available: Dry run build 6431111657.
This table contains some explorations to improve the rendering performance of tables with inline editing.
The measurements use a Cloudscape table with 100 columns and 100 rows, with all cells being editable. First time render performance is …

chore: Improve performance of table inline editing

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/cards/__tests__/cards.test.tsx
src/cards/index.tsx
src/cards/interfaces.tsx

Allow a custom label for cards group. The default behavior of aria-labelledby the header slot can be too verbose.
Related links, issue #, if available: AWSUI-20957
Unit tests
<details> …

feat: Allow cards list/group label to be overridden

---

pages/code-editor/base-props.ts
src/__tests__/__snapshots__/documenter.test.ts.snap
src/code-editor/__tests__/common.ts
src/code-editor/__tests__/preferences-modal.test.tsx
src/code-editor/index.tsx
src/code-editor/interfaces.ts
src/code-editor/preferences-modal.tsx

Ensure that all relevant Select props can be provided for the code editor theme picker 
New tests
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/acce …

fix: Pass through props for select in code editor preferences

---

pages/popover/text-align.page.tsx
src/expandable-section/expandable-section-header.tsx
src/popover/__tests__/popover.test.tsx
src/popover/internal.tsx
src/popover/styles.scss
src/side-navigation/__tests__/complex-side-navigation.test.tsx

Prevent block elements to appear inside inline
Related links, issue #, if available: AWSUI-20955
Added extra tests to affected components
<details> …

fix: Fix html validity in popover and expandable section

---

src/cards/index.tsx

Users can't place a div inside the card header because the wrapper is a span. Normally, it's designed to hold text (like a table), but it's being used in a situation with some layout elements. Given the scope of the change, we decided we might as well do it to unblock them.
Related links, issue #, if available: AWSUI-20694
I changed an element that already has `display: inline-block` styling. No tests. Sue me.
<details> …

fix: Allow placing semantic block elements inside card definition header

---

src/table/body-cell/styles.scss

The edit buttons for table inline editing are visually hidden (`opacity: 0`) but are exposed to assistive technology.
This makes it critical that focus outlines are displayed correctly when these cells receive focus. Unfortunately, our focus-visible polyfill doesn't detect screen reader users correctly, which means that edit buttons are not always displayed correctly when focused by a screen reader. For example, when focusing a edit using the VoiceOver rotor menu (VO+U).
To mitigate this problem, we're replacing the focus visible polyfill with a native `:focus-within` selector **for table inline editing only.** This is a special case and there is no need to apply these changes elsewhere.
Related links, issue #, if available: AWSUI-20149
Tested manually with Chrome, Firefox, Safari, and …

fix: Improve table inline editing focus highlighting for assitive technology

---

src/app-layout/visual-refresh/drawers.scss

This PR resolves an issue with the `AppLayout` `drawers` implementation regarding the stacking order of the contents and the close button. If `drawers` is used with contents other than a `HelpPanel` (such as a `Container`) the close button will be obscured and unusable. The resolution is to lift the stacking context of the close button similar to the original `tools` implementation.
Before:
https://user-images.githubusercontent.com/438181/233476013-6fc1fb12-557e-4083-aa79-1bf2a962648b.mov
After: 
https://user-images.githubusercontent.com/438181/233476047-f7f09c2e-2cf1-4d74-b900-8c66991b1a6e.mov
<details>
- _Changes are …

fix: Adjust the stacking order of drawers content

---

src/app-layout/visual-refresh/drawers.scss
src/app-layout/visual-refresh/drawers.tsx
src/app-layout/visual-refresh/navigation.scss
src/app-layout/visual-refresh/navigation.tsx
src/app-layout/visual-refresh/tools.scss
src/app-layout/visual-refresh/tools.tsx

This PR resolves an issue with the `AppLayout` `navigation`, `drawers`, and `tools` in mobile viewports when the deprecated `disableBodyScroll` property is enabled. Using `disableBodyScroll` sets the internal `offsetTop` value to `0` because sticky elements will be relative to the `AppLayout` root element and not the document `body`. However, `sticky` drawers are changed to `fixed` position in mobile viewports. This makes the `top` value incorrect because it is now relative to the document `body` and does not account for the height of the `header` element.
Before:
https://user-images.githubusercontent.com/438181/233471296-a49bc2a8-7402-43f6-960b-11a17fcce31c.mov
After:
https://user-images.githubusercontent.com/438181/233471331-e4bb9f81-5d31-4456-9b65-2d5be16ff133.mov
<details> …

fix: Adjust offsetTop value for drawers when disableBodyScroll is enabled

---

pages/modal/scroll-padding.page.tsx
src/modal/__integ__/modal.test.ts
src/modal/internal.tsx

A typical problem of sticky headers and footers is that they can cover other elements in an undesired way. In our modal component, the sticky footer can eventually cover focused elements when navigating with the keyboard:
https://user-images.githubusercontent.com/1257272/233566051-15abd309-b2ef-49a2-bae4-6c636de60e1c.mov
This PR fixes this by adding a bottom [scroll padding](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding) equivalent to the footer height.
Now the modal scrolls as needed as soon as the focused element meets the footer's position (not the modal's bottom):
https://user-images.githubusercontent.com/1257272/233566062-8c24c29d-5d71-4cee-876e-bce75f8c7e97.mov
- Added integration test
- Manually tested
<details>
_The following …

fix: Prevent modal sticky footer from hiding focused elements

---

src/code-editor/__integ__/code-editor.test.ts
src/code-editor/index.tsx
src/code-editor/pane.tsx
src/code-editor/status-bar.tsx

Looks like we did have this in the past, but broke it after a refactor. Added a couple of integ tests to prevent that. Also replaced 'react-focus-lock' with our simpler more predictable internal one.
Related links, issue #, if available: AWSUI-20678
Integration tests.
<details>
- …

fix: Restore focus to the code editor tab button when pane is closed

---

src/table/__tests__/table.test.tsx
src/test-utils/dom/table/index.ts

We have a test util function for `TextFilter` but we don't have any for `PropertyFilter` or any other filter like: `Select`. 
this PR adds a generic function `findFilterSlot` and a `PropertyFilter` specific one.
Related links, issue #, if available: AWSUI-20754
Added unit tests that uses these properties 
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBU …

chore: Add findFilterSlot and findPropertyFilter test utils

---

src/__a11y__/a11y-light.test.ts

Noticed that a11y tests were missing for classic light
Locally …

chore: Add a11y tests for classic light mode

---

src/attribute-editor/__tests__/attribute-editor.test.tsx
src/attribute-editor/row.tsx

A common accessibility violation is that the "Remove" buttons for the components have the same accessible text every time, which makes it confusing for assistive technology users. This adds an aria-labelledby pointing to the first input, exactly the same way each row is labelled. We made it less of an issue when we labelled each row, but the original issue is going to keep coming up, so...
Related links, issue #, if available: AWSUI-19472
Unit test added.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-a …

fix: Provide unique remove button label for each row in attribute editor and tag editor

---

src/attribute-editor/__tests__/attribute-editor.test.tsx
src/attribute-editor/row.tsx

Reverts cloudscape-design/components#975

revert: Revert "fix: Provide unique remove button label for each row in attribute editor and tag editor"

---

pages/top-navigation/integ.page.tsx
src/top-navigation/__integ__/top-navigation.test.ts
src/top-navigation/parts/utility.tsx

We broke this in a recent PR to update the click detail but borked it in the process.
Painstakingly integ tested.
<details> …

fix: Passthrough preventDefault on top navigation link utility clicks

---

src/table/thead.tsx

A minimal refactoring to support https://github.com/cloudscape-design/components/pull/918
<details> …

refactor: Table thead to render a single node for header selection cell

---

src/table/body-cell/styles.scss

The cell hover effect was using the wrong border radius in VR.
<details>
- _If the code …

chore: Improve border radius for table inline editing cells in refresh

---

src/top-navigation/__tests__/top-navigation-overflow-menu.test.tsx
src/top-navigation/parts/overflow-menu/menu-item.tsx

Before this fix, a button that has `variant: "primary-button"` and an `href` would not trigger a navigation when the viewport is small enough for the content to move to the overflow menu. It also only shows the "external" icon when in desktop view.
With this code change, the navigation is triggered correctly on all screen sizes.  
In addition, the "external" icon is also shown in the mobile view.
Related links, issue #, if available: **AWSUI-20976**
Manual local testing in the dev pages
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/bl …

fix: Primary button link in top navigation not firing in mobile view

---

src/internal/components/autosuggest-input/__tests__/autosuggest-input.test.tsx
src/internal/components/autosuggest-input/index.tsx
src/property-filter/__tests__/property-filter.test.tsx

When `disableFreeTextFiltering=true` the property filter can have no options matched and an empty dropdown is shown. We are still to decide if a dedicated no-match state is needed but for now the dropdown is to be hidden completely.
Updated tests for property filter and autosuggest input. Added new unit test for autosuggest input
<details> …

fix: Autosuggest input to not show dropdown when no content provided

---

src/expandable-section/expandable-section-header.tsx
src/expandable-section/styles.scss

There was a problem with visible focus outlines not displaying correctly for expandable section headers that didn't use the `container` variant.
Related links, issue #, if available: AWSUI-21024, AWSUI-21013
Tested manually.
<details> …

fix: Fixed visible focus outline for expandable section headers

---

src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/options-controller.ts
src/autosuggest/options-list.tsx
src/internal/components/options-list/utils/test-indexes.ts

The autosuggest items requires `data-test-index` and `data-in-group-index` attributes assigned to support test-utils (findOptionInGroup method). That didn't work because of a bug: the option parents comparison is done by reference but the references have been invalidated when writing the object's copy to the mapping.
Related links: AWSUI-20969
New unit tests
<details> …

fix: Fix autosuggest test indices to make findOptionInGroup work

---

src/collection-preferences/content-display/sortable-item.scss

Fixes warning:
```
autoprefixer: start value has mixed support, consider using flex-start 
instead
```
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles …

fix: Change `start` to `flex-start` in collection preferences.

---

src/table/__tests__/use-sticky-columns.test.tsx

Add test coverage for use-sticky-columns
<details> …

chore: Add unit tests for sticky columns

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/attribute-editor/__tests__/attribute-editor.test.tsx
src/attribute-editor/interfaces.ts
src/attribute-editor/row.tsx
src/tag-editor/__tests__/tag-editor.test.tsx
src/tag-editor/index.tsx
src/tag-editor/interfaces.tsx

The remove button has the same text for each row, which could end up confusing a lot of screen reader users, especially if we have many rows. We tried to do this automagically for everyone in #975, but that ended up breaking a lot of people's tests since many selected buttons by their accessible name, which changed from "Remove" to "Remove [tag name]".
This approach is a little more opt-in. It adds `removeButtonAriaLabel?: (item: T) => string` to i18nStrings for attribute editor and tag editor. This PR is small enough to act as the API proposal for itself :)
Related links, issue #, if available: AWSUI-19472
<details> …

feat: Add removeButtonAriaLabel to attribute editor and tag editor i18nStrings

---

src/table/selection-control/index.tsx

Kind of an edge-casey accessibility concern. The "select all" control for tables has a screen reader label, and the visual affordance is pretty clear without necessitating an actual text label, but we still need a visual text label of some kind. So this is the low-impact middle ground we've arrived at.
Related links, issue #, if available: AWSUI-20043
Manually, locally. No real way of testing "title" other than a unit test that tests the exact DOM structure I just added.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBU …

fix: Add "title" attribute to table multi selection control

---

pages/table/permutations.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/table/__tests__/table.test.tsx
src/table/body-cell/styles.scss
src/table/body-cell/td-element.tsx
src/table/interfaces.tsx
src/table/internal.tsx
src/test-utils/dom/table/index.ts

Allow individual columns to be marked as row headers for improved table semantics
Related links, issue #, if available: AWSUI-20031
New unit tests
<details> …

feat: Allow table columns to be specified as row headers

---

src/cards/index.tsx
src/container/__integ__/awsui-legacy-applayout-sticky.test.ts
src/container/internal.tsx
src/container/use-sticky-header.ts
src/table/__integ__/sticky-header.test.ts
src/table/internal.tsx

Description:
This PR updates the table component to make only the table header row sticky on mobile devices, instead of the entire header container. This improves the user experience on mobile devices by preserving the sticky behavior of the table header row, while allowing other header elements, such as title, filters or buttons, to scroll out of view.
Changes:
- Updated the sticky behavior in `src/container/internal.tsx` to take into account the new internal `__disableStickyMobile` prop.
- Added the prop to the sticky header in `src/container/use-sticky-header.ts` and made it disable the sticky feature on mobile devices by default (status-quo).
- Updated the sticky header test in `src/table/__integ__/sticky-header.test.ts` to reflect the new behavior on mobile devices.
- Added a …

feat: Make table header row sticky on mobile

---

pages/expandable-section/test.page.tsx
src/expandable-section/__integ__/expandable-section.test.ts
src/expandable-section/expandable-section-header.tsx

Expanding/collapsing the header seemed to remount the React tree around the header, which kicks focus back out to the body. I spent a while looking around for a `"key"`, and figured out what was actually happening. Of course, **[Boris got there first](https://github.com/cloudscape-design/components/pull/919#discussion_r1162554339)**  😛
Related links, issue #, if available: AWSUI-21024
Added an integration test (and a dev page to match).
<details>
- _Changes …

fix: Keep focus on header button after expanding/collapsing

---

src/container/internal.tsx

This PR fixes a regression caused by https://github.com/cloudscape-design/components/pull/1040, where the container would get the sticky styles (a box shadow) on mobile even though only the table header was sticky.
Existing screenshot tests.
<details> …

fix: Remove sticky styles from container on mobile

---

pages/wizard/wizard-screenshot.page.tsx
src/wizard/styles.scss

Long step title names overflow the wizard navigation. Refresh has the mixin correctly applied, but classic has its own component for navigation.
Related links, issue #, if available: AWSUI-21035
Updated screenshot test page.
<details> …

fix: Correctly break words in wizard navigation step title

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/side-navigation/__tests__/side-navigation.test.tsx
src/side-navigation/interfaces.tsx
src/side-navigation/internal.tsx

Add `info` slot for `SideNavigation` item of type `link-group`. 
there is already an `info` slot for items of type `link` so `link-group` should be treated the same 
added a unit test
<details> …

feat: Add info slot for link-group items in SideNavigation

---

src/__integ__/__snapshots__/themes.test.ts.snap
style-dictionary/visual-refresh/colors.ts

Update the VR resize handle color, to adhere to the new design decision.
Before:
After:
Related to https://github.com/cloudscape-design/components/pull/918
Visual regression tests in pipeline
<details> …

chore: Update VR resizable columns handle color

---

pages/table/full-page-variant.page.tsx
src/table/__integ__/table.test.ts
src/table/__tests__/a11y.test.tsx

While working on https://github.com/cloudscape-design/components/pull/918, an A11Y unit test has been showing some flakiness depending on the code changes. This PR moves the unit to an integration test.
After further investigation it seems like there a couple of problems (TL;DR: call order dependency & lack of identifying parameters):
- `mockSmallWrapper()` is mocking the return value of `useContainerQuery` using `mockReturnValueOnce()`. This means that the test will only work correctly if the call order of `useContainerQuery` within the tested code is consistent with the mocked order in the test. If the call order changes (like it happened on the https://github.com/cloudscape-design/components/pull/918), the test may fail, even if the actual functionality remains correct. This makes the …

chore: Move table A11Y unit test to integration test

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/modal/__tests__/modal.test.tsx
src/modal/index.tsx
src/modal/internal.tsx

When `closeAriaLabel` isn't provided, we're automatically defaulting to `""`, which isn't great. This messes with our i18n handler, makes it confusing for automated tools to check, and just feels wrong. Now the default is basically `undefined`, and it's even more clear when it's forgotten.
Changed a default value, so it was a manual check. Writing a test for this feels redundant.
<details> …

fix: Don't provide "" to modal closeAriaLabel by default

---

src/flashbar/__tests__/collapsible.test.tsx
src/flashbar/__tests__/flashbar.test.tsx
src/test-utils/dom/flashbar/index.ts

Added new test-util for flashbar to find flash items by type.
AWSUI-20204
New unit tests
<details> …

feat: Add findItemsByType to flashbar test-utils

---

src/app-layout/mobile-toolbar/index.tsx
src/app-layout/mobile-toolbar/styles.scss
src/app-layout/visual-refresh/drawers.scss
src/app-layout/visual-refresh/drawers.tsx

Our mobile touch targets for drawers are too small, and were called out during a Drawers design review. Updating them to be `40px`, which is what the current width is for the navigation and tools icons on mobile.
Note: We should follow-up on these targets, as we may want to expand these even further.
Before:
After:
<details> …

fix: Update mobile touch targets

---

pages/table/variants.page.tsx
pages/tabs/permutations.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/tabs/index.tsx
src/tabs/interfaces.ts

Adds `stacked` variant to tabs, so they can be used alongside other stacked containers, and maintain compatibility with classic.
In VR, we introduced stacked containers and tables. During tiger teams, we noticed a need for a backwards compatible version for stacked tabs as well.
Related links, issue #, if available: CR-90767732
Added stacked variant page to integ screenshot tests (CR-90767732).
<details> …

feat: Add stacked tabs variant

---

src/popover/__tests__/popover.test.tsx
src/popover/internal.tsx

We added a wrapper unsetting form field context around dialog components like modal and popover in #850. That was a little over-eager with popover and also reset it around the trigger, not just the dialog. This moves the context provider to wrap just the content.
Related links, issue #, if available: AWSUI-21042
One-time manual check. Not a use case I want to, uh, endorse.
<details> …

fix: Don't unset form field context around popover trigger

---

pages/table/sticky-columns-custom.page.tsx
pages/table/styles.scss
src/table/__tests__/use-sticky-columns.test.tsx
src/table/use-sticky-columns.ts

When the leading cells do not have paddings but the table does, the padding from the table should be applied to the first sticky column if it is stuck.
Refactored use-sticky-columns and proposed a solution for table padding. If applied on the table the padLeft property can be removed.
https://user-images.githubusercontent.com/20790937/236424385-ff4999f8-4a5b-4db6-b00a-e54402863c45.mov
<details>
- _Changes do not …

chore: Update custom page for sticky table columns to feature pad left

---

src/internal/components/options-list/__tests__/options-list.test.tsx
src/internal/components/options-list/index.tsx
src/property-filter/__integ__/async-loading.test.ts

Calling onLoadMore in an effect w/o dependencies can produce an infinite loop.
<details>
- …

fix: Make on-load-more stable

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/attribute-editor/internal.tsx
src/button/__tests__/button.test.tsx
src/button/index.tsx
src/button/interfaces.ts
src/button/internal.tsx

Pretty standard new property addition. I've seen this requested four or five times by this point, and the use cases get harder to push back each time. Developers can have a little custom attribute editor, as a treat.
New property description:
> **ariaDescribedby**: Adds `aria-describedby` to the button.
Related links, issue #, if available: AWSUI-21001
<details> …

feat: Add ariaDescribedby to button

---

src/flashbar/__tests__/flashbar.test.tsx
src/flashbar/flash.tsx

We allow JSX in header and content, but we do a string join to come up with the live region announcement. Don't you just hate it when [Object object]
Related links, issue #, if available: AWSUI-21045
Unit tests for LiveRegion content. The LiveRegion component takes it from there.
<details> …

fix: Improve announcement for flashbar content with JSX

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/checkbox/__tests__/common-tests.tsx
src/checkbox/base-checkbox.tsx
src/checkbox/internal.tsx
src/internal/components/abstract-switch/index.tsx
src/tiles/__tests__/tiles.test.tsx
src/tiles/interfaces.ts
src/tiles/internal.tsx
src/toggle/internal.tsx

Added aria-controls to Checkbox, Tiles and Toggle component APIs. The same has been previously added to the RadioGroup (see https://github.com/cloudscape-design/components/pull/659).
<details> …

feat: Add aria-controls to checkbox, toggle, and tiles

---

src/progress-bar/internal.tsx

Use only the standard HTML `progress` element attributes, as the additional `aria-` properties are not necessary.
(In the past it seems that these were necessary, for example in VO+Chrome, but testing now suggests the underlying Chrome issue has been resolved)
Related links, issue #, if available: AWSUI-21037
Local testing with VO+Chrome, VO+Safari, NVDA+Firefox
<details> …

fix: Remove unnecessary progress aria attributes

---

pages/app-layout/with-drawers.page.tsx

Fixes the following:
- Submitted messages by the user were actually not passed to the request
- The conversation was being initialized with a dummy "#hello world" message which was prompting generic answers. Pass a welcoming message from the assistant instead
- Reset the input field value to empty string after submitting
Manually tested
<details> …

fix: Pass new message when requesting new response

---

src/date-range-picker/styles.scss

Improve the wrapping of the "Cancel" and "Apply" buttons in the footer of the date ranger picker component.
Related links, issue #, if available: AWSUI-17098
<details> …

chore: Improve wrapping of buttons in the date range picker footer

---

pages/options-list/simple.page.tsx
src/autosuggest/internal.tsx
src/autosuggest/options-list.tsx
src/button-dropdown/internal.tsx
src/internal/components/options-list/__tests__/options-list.test.tsx
src/internal/components/options-list/index.tsx
src/multiselect/internal.tsx
src/property-filter/__integ__/async-loading.test.ts
src/property-filter/property-filter-autosuggest.tsx
src/select/__tests__/use-select.test.ts
src/select/internal.tsx
src/select/utils/use-select.ts

Fixes a bug introduced here: https://github.com/cloudscape-design/components/pull/1071
When dropdown is already open but the number of loaded options fits the screen height a second onLoadCall might be needed as can't rely on scroll.
Before:
https://github.com/cloudscape-design/components/assets/20790937/e1ee36c6-e9de-432a-bbbf-4321039238ec
After:
https://github.com/cloudscape-design/components/assets/20790937/fa1f616b-c2e4-4e02-874a-7583f1476fd1
Manual testing, a new unit test
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/C …

fix: Options list to call on-load-more when status changes to pending

---

src/app-layout/drawer/styles.scss

Outside of the Cloudscape testing environment, due to a difference in loading and bundling, CSS rules of the same specificity were being applied in a different order, causing unintended effects.
This PR increases the specificity of the correct CSS rules so that no matter what order the bundle is loaded, the correct styles are applied.
This was tested inside the management console using a local branch, so we know it works.

fix: Adds higher specificity to css properties in drawers

---

src/input/__tests__/input.test.tsx
src/test-utils/dom/input/base-input.ts
src/test-utils/dom/textarea/index.ts
src/textarea/__tests__/textarea.test.tsx

**Include a summary of the changes and the related issue:** This change introduces getters for `Input` & `TextArea` ElementWrappers to support string validation in unit tests.
**Also include relevant motivation and context:** This was motivated by an internal AWS discussion.
Related links, issue #, if available: AWSUI-21062
**How did you test to verify your changes?** I added unit tests.
**How can reviewers test these changes efficiently?** Running the unit tests locally or validating via an integration test.
<details> …

chore: Improve unit test APIs for Input & TextArea ElementWrappers by exposing getters for value property

---

.husky/commit-msg
.husky/pre-commit
.husky/prepare-commit-msg

The &> operator is a shorthand used in Bash and some other shells to redirect both stdout and stderr to the same location. However not all shells support this operator and the script can then fail. This change maintains the same functionality but improves compatibility. 
Reason for change is I was running into issues with my current shell where I have git-secrets installed but was unable to commit my changes due to these scripts failing.
I am now able to make commits again.
<details> …

chore: Improve shell compatibility in husky scripts

---

pages/content-layout/without-header.page.tsx

Adding a new page to be able to take screenshots of the current status, before making changes to the visuals in upcoming PRs.
Tested locally
<details> …

chore: Add page for ContentLayout without header

---

pages/app-layout/with-drawers.page.tsx
src/app-layout/__tests__/drawers.test.tsx
src/app-layout/drawer/interfaces.ts
src/app-layout/drawer/resizable-drawer.tsx
src/app-layout/index.tsx

Removed `controlled/uncontrolled` concept and allowed resize handling to be controlled, with a callback to provide the ability to persist the last value. Changing `size` to initialSize to indicate that we only use this value as... an initial size.
Tested locally using `with-drawers.page.tsx`, and included writing `onResize` value to local storage, and restoring to initialState. I also enabled, disabled drawers, added drawers dynamically and more!
It is correct.
It is secure.
It has been tested
---

fix: drawer widths

---

src/progress-bar/__tests__/progress-bar.test.tsx

This update replaces the previous approach in the ProgressBar test that could cause time outs and delays between assertions. By incorporating Jest's fake timers, we now simulate time passage more effectively, enhancing test predictability and reducing time out occurrences.
Unit test still passes.
<details> …

chore: Use fake timer in progress-bar unit test

---

src/app-layout/__tests__/desktop.test.tsx
src/app-layout/drawer/index.tsx
src/app-layout/drawer/styles.scss
src/app-layout/index.tsx

This PR fixes 3 issues:
1. Makes drawer items work like toggles (which they already do in VR), so that you can click to open and click again to close.
2. Expands the divider line to go across the entire trigger bar. This makes it consistent with mobile and also is from feedback from the stakeholder team.
3. Makes the focus state on selected items the same as non-selected items.
<details> …

fix: Makes drawers toggles and updates line

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/app-layout/interfaces.ts

We've had a number of situations in the past where people provided a react node (e.g. empty node or something) for split panel even when no content should be rendered - so we can't know when split panel is present. This makes it clear that it's either split panel or `null`.
Related links, issue #, if available: AWSUI-20807
Just a docs change.
<details> …

chore: Update app layout docs to recommend providing null to splitPanel

---

src/app-layout/__tests__/split-panel.test.tsx
src/app-layout/index.tsx
src/app-layout/split-panel-drawer/index.tsx
src/app-layout/visual-refresh/tools.tsx

Split Panel always takes width when `splitPanelOpen` and `splitPanelSize` are set even when no `splitPanel` is set.
Related links, issue #AWSUI-21104
Added unit tests. 
<details> …

fix: Split panel takes space even when no split panel is set

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/cards/__tests__/cards.test.tsx
src/cards/index.tsx
src/cards/interfaces.tsx

We added this to table but not cards, however the same functionality is useful there too.
New unit test.
<details> …

feat: Add `renderAriaLive` to cards component

---

src/app-layout/index.tsx

A follow up fix for regression caused by https://github.com/cloudscape-design/components/pull/1114.
Split Panel show not take space when it is closed or not set. 
Did not add more tests in this PR because it was caught be screenshot test.
<details> …

fix: Split panel takes space even when no split panel is closed

---

src/internal/analytics/__tests__/components/analytics-funnel.test.tsx
src/internal/analytics/__tests__/hooks/use-funnel-step.test.tsx
src/internal/analytics/__tests__/hooks/use-funnel-sub-step.test.tsx
src/internal/analytics/__tests__/hooks/use-funnel.test.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/context/analytics-context.ts
src/internal/analytics/hooks/use-funnel.ts
src/internal/analytics/index.ts
src/internal/analytics/interfaces.ts
src/internal/analytics/selectors.ts
src/internal/hooks/use-visual-mode/__tests__/use-visual-refresh-static.test.tsx

This change includes all the context providers, hooks and a stubbed implementation to orchestrate funnel based metrics within the components.
Design documentation: https://tiny.amazon.com/1190or99x/quipBBl9Tech
This Draft PR holds a all of the proposed changes to show how these will be used across the various components: https://github.com/cloudscape-design/components/pull/1115/files#diff-dbf7be64bedaf235736054490dfada45331ea33b255c3a27d8b1f5a9aeb0c83c
- A follow up PRs will replace the existing implementation in Wizard and introduce the context and hooks to the Form, Container, FormField, Alert, Flashbar and Button components.
- An additional follow up CR will be created to inject the relevant Analytics library to replace the stubbed implementation at build time.
Related links, issue #, …

chore: Add analytics components and hooks

---

pages/app-layout/with-drawers.page.tsx

A screenshot test that included tools wasn't working. Instead of toggling the tools toggle via click, we can do it with urlParams.
<details> …

fix: Updates tools to use UrlParams

---

pages/autosuggest/simple.page.tsx
pages/multiselect/multiselect.async.example.page.tsx
pages/multiselect/multiselect.sync.example.page.tsx
pages/select/select.async.example.page.tsx
pages/select/select.sync.example.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/autosuggest/interfaces.ts
src/autosuggest/internal.tsx
src/internal/components/dropdown-status/__tests__/dropdown-status.test.tsx
src/internal/components/dropdown-status/index.tsx
src/internal/components/option/utils/prepare-options.ts
src/multiselect/internal.tsx
src/property-filter/property-filter-autosuggest.tsx
src/select/__tests__/select.test.tsx
src/select/interfaces.ts
src/select/internal.tsx

Adds new property to select, multiselect and autosuggest components to specify number of matches while filtering.
Resulted text is displayed in status field of dropdown.
New unit test added.
Try in 
* [select.sync with auto filtering](https://d21d5uik3ws71m.cloudfront.net/components/7c23f4ac91871261a188e9ffddce994f18455889/index.html#/light/select/select.sync.example)
* [select.async](https://d21d5uik3ws71m.cloudfront.net/components/7c23f4ac91871261a188e9ffddce994f18455889/index.html#/light/select/select.async.example)
<details> …

feat: Add label with results of filtering in select and multiselect

---

pages/table/variants.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/table/interfaces.tsx
src/table/internal.tsx
src/table/utils.ts

This change adds a new variant (`borderless`) to the Table component. This variant removes any outer borders and shadows from the table, just like the `embedded` variant. However, unlike `embedded`, `borderless` works in both Classic and Visual Refresh.
The `borderless` variant is recommended for use-cases where the table shouldn't have any outer borders, regardless of theme or mode. For example, for tables inside dashboard widget containers. Previously, this required additional CSS to hide the shadows, see [embedded-table-wrapper/styles.module.scss](https://github.com/cloudscape-design/demos/blob/e5b10d2329593ab1f20613d7d45e6ff93d4721d7/src/pages/dashboard/components/embedded-table-wrapper/styles.module.scss).
Related links, issue #, if available: AWSUI-20338
<details> …

feat: Added `borderless` table variant

---

src/top-navigation/__tests__/top-navigation-overflow-menu.test.tsx
src/top-navigation/parts/overflow-menu/menu-item.tsx
src/top-navigation/parts/overflow-menu/views/submenu.tsx
src/top-navigation/parts/overflow-menu/views/utilities.tsx

Clicking on item in overflow menu should close the dropdown menu. It is how other dropdowns work(like ButtonDropdown). Moreover, we don't provide exposed functionality to close the menu dropdown to implement it from customer side. 
Related links, issue #AWSUI-21026
Add unit tests.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support) …

fix: Top navigation overflow menu does not close when clicking menu item

---

src/area-chart/__tests__/area-chart-initial-state.test.tsx
src/area-chart/elements/use-highlight-details.ts
src/area-chart/interfaces.ts
src/internal/components/cartesian-chart/bottom-labels.tsx
src/internal/components/cartesian-chart/interfaces.ts
src/internal/components/cartesian-chart/left-labels.tsx
src/internal/components/chart-filter/__tests__/i18n.test.tsx
src/internal/components/chart-filter/index.tsx
src/internal/components/chart-legend/__tests__/chart-legend.test.tsx
src/internal/components/chart-legend/index.tsx
src/internal/components/chart-plot/index.tsx
src/internal/components/chart-status-container/__tests__/chart-status-container.test.tsx
src/internal/components/chart-status-container/__tests__/i18n.test.tsx
src/internal/components/chart-status-container/index.tsx
src/internal/i18n/testing.tsx
src/pie-chart/__tests__/pie-chart.test.tsx
src/pie-chart/interfaces.ts
src/pie-chart/pie-chart.tsx
src/pie-chart/segments.tsx
src/pie-chart/utils.ts
src/popover/__tests__/popover.test.tsx
src/popover/body.tsx
src/popover/interfaces.ts

First batch of post-beta components for internationalization! The actual support addition is rather small; a lot of this PR is just tests. As before, we're continuing to add the integration as close to its use as possible, so a lot of chart subcomponents were updated. There are some additional things to consider:
- Simpler unit tests using an internal-only "TestI18nProvider"
- The addition of a new `@i18n` tag provided to interfaces
Unit testing. Generally each string is tested in unit tests. Also added a little test support provider so that we don't need to fake a locale and provide a full namespaced structure for each test case.
<details>
_The following items are to be evaluated by the author(s) and the …

chore: Add i18n support to chart components and popover

---

src/table/styles.scss

Fixes an unintentional regression in borderless tables in VR, introduced in https://github.com/cloudscape-design/components/pull/1095
<details> …

chore: Fix padding of borderless table in VR

---

src/table/__integ__/sticky-scrollbar.test.ts
src/table/__tests__/sticky-scrollbar.test.ts
src/table/styles.scss
src/table/use-sticky-scrollbar.ts

- Use `position: sticky` for sticky scrollbar of table. So that the scrollbar position moves together with the table. 
- Hide the real scrollbar but always use the fake one. Avoid the edge case that table start vibrating when scroll to the bottom, due to the cycle of fake scrollbar disappearing and reappearing.  
Related links, issue #AWSUI-21067
<details> …

fix: Table sticky scrollbar dangling when draging the table

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/cards/__tests__/cards.test.tsx
src/cards/index.tsx
src/code-editor/__tests__/code-editor.test.tsx
src/code-editor/index.tsx
src/code-editor/interfaces.ts
src/code-editor/pane.tsx
src/code-editor/preferences-modal.tsx
src/code-editor/status-bar.tsx

feat: Add i18n support to cards, code editor

---

pages/area-chart/example.tsx
pages/line-chart/permutations.page.tsx
pages/mixed-line-bar-chart/permutations.page.tsx
pages/pie-chart/permutations.page.tsx

#1135 made it so that recovery text is no longer displayed if the recovery click handler isn't provided. We don't that for permutation pages, so we had some visual test failures. This PR restores that link for visual testing.
<details>
- _Changes …

chore: Add recovery text back to chart permutation pages

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/collection-preferences/__tests__/collection-preferences.test.tsx
src/collection-preferences/content-display/index.tsx
src/collection-preferences/index.tsx
src/collection-preferences/interfaces.ts
src/collection-preferences/utils.tsx
src/split-panel/__tests__/split-panel.test.tsx
src/split-panel/index.tsx
src/split-panel/interfaces.ts
src/split-panel/side.tsx
src/table/__tests__/header-cell.test.tsx
src/table/body-cell/index.tsx
src/table/body-cell/inline-editor.tsx
src/table/header-cell/index.tsx

It's a lot of files, but it reads quick! Adds i18n string support to a batch of related components. The strings themselves will come in a later PR, so this PR itself will not change anything for users.
Codecov is yelling at me so I'll add a couple of tests before merging, but you can still take a look in the meantime :)
All i18n string additions are being tested with unit tests. As I'm sure you've noticed, there's a little internal test helper to make building test-specific i18n providers easy. Also, tests are most of the actual code in this PR.
<details>
- _Changes are …

feat: Add i18n support to table, split panel, collection preferences

---

pages/table/compact-mode.page.tsx
pages/table/simple-permutations.page.tsx
pages/table/sticky-header.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/s3-resource-selector/s3-modal/basic-table.tsx
src/table/interfaces.tsx

Following the addition of the new `borderless` variant in Table, we are now deprecating the old `embedded` variant. `borderless` and `embedded` currently have the exact same behavior in VR.
<details> …

feat: The `embedded` table variant is now deprecated in favor of `container` and `borderless`

---

src/header/styles.scss

A wrapping area around the heading in the Header component has `overflow: hidden` which causes any bit of overflowing content to be cut off.
This is most obvious with italics text:
But even without italics, the very tip of certain characters is also sometimes cut off (screenshot diffs below):
This overflow rule comes from a mixin (`text-flex-wrapping`) which is also used by components such as popover or alert, where it is applied at the outermost level of the component tree, so that eventually cutting off content seems justified (the content is really at the border of the component), but this is not the case here.
This is also relevant for #1143, since without this fix the focus ring around the new clickable area is cut off:
Ran against my …

fix: Prevent headings from being cut off in Header component

---

pages/modal/vertical-scroll.page.tsx
src/modal/__integ__/modal.test.ts
src/modal/styles.scss

Ensure that modal content can't overlap footer, even if it e.g. has a z-index set.
Related links, issue #, if available: AWSUI-21216
Updated integ and screenshot tests
<details> …

fix: Ensure that modal content can't overlap footer

---

pages/modal/vertical-scroll.page.tsx
src/modal/__integ__/modal.test.ts
src/modal/styles.scss

Reverts cloudscape-design/components#1139. We have an internal test that fails because of this, so this is a temporary rollback.

revert: Revert "fix: Ensure that modal content can't overlap footer"

---

pages/content-layout/dark-header-main.page.tsx
src/alert/internal.tsx
style-dictionary/visual-refresh/contexts/header-alert.ts
style-dictionary/visual-refresh/index.ts

Alert context overrides button styles. It results in using incorrect color palette in light mode when alert is inside content layout header.
This PR creates `alert-header` context, which uses dark mode state for color tokens. Context is applied to alerts inside `content-header` context.
Related links, issue #, if available: AWSUI-21158
<details> …

fix: Use content header context for alerts

---

src/app-layout/visual-refresh/layout.scss
src/content-layout/__tests__/content-layout.test.tsx
src/content-layout/internal.tsx
src/content-layout/styles.scss
src/internal/generated/custom-css-properties/list.js
src/wizard/styles.scss

- Add dark background to ContentLayout when header is not defined
- Align spacing below breadcrumbs across ContentLayout and Wizard
Locally, plus existing screenshot tests
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._ Confirmed …

feat: Add dark background to ContentLayout without header

---

src/internal/components/chart-plot/index.tsx

When focusing a bar chart, VoiceOver would announce "Chart of things, bar chart, empty". The focusable element is marked with role="application", but we still have inner elements marked up with "aria-*" properties. The empty announcement comes from a role="group" element directly below the chart plot. If marked as presentational (or not specially marked at all), the parent is not announced as empty.
We used to need the role="group" because we used to announce the vertical and horizontal axis labels under it, but we don't do that anymore, so there's really nothing outside of aria-hidden inside the bar chart anymore. So this is safe to do; for bar charts anyway, which are designed to fully rely on application-specific keyboard navigation.
Related links, issue #, if available: AWSUI-18682 …

fix: Prevent VoiceOver from announcing "empty" when focusing line/bar charts

---

src/tag-editor/__tests__/tag-editor.test.tsx
src/tag-editor/index.tsx

What it says on the tin. I didn't provide it because the string didn't use it, and my test string didn't either, but it's needed for pluralization inside the string still.
Modified the unit test.
<details> …

fix: Provide tagLimit value to tag editor's tagLimit i18n formatter

---

pages/expandable-section/container-variant.permutations.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/expandable-section/__tests__/expandable-section.test.tsx
src/expandable-section/__tests__/interactions.test.tsx
src/expandable-section/expandable-section-header.tsx
src/expandable-section/interfaces.ts
src/expandable-section/internal.tsx
src/expandable-section/styles.scss

Related links, issue #, if available: AWSUI-20024
- Added unit tests
- Added integration tests
- New permutations page for visual regression tests. Visual regression test will be added including focus states
BackstopJS tests are failing because a new page was added (`expandable-section/container-variant.permutations`) for which there is no reference.
<details> …

feat: Support interactive elements in Expandable section headers

---

src/split-panel/styles.scss

Although the SplitPanel sticky header has the z-index as 1. But its sibling, the content of the SplitPanel does not any z-index set. The items inside of the content of the SplitPanel can still overlap the header.
Related links, issue #AWSUI-20971
<details> …

fix: Content inside bottom split panel should not above the header

---

build-tools/tasks/generate-i18n-messages.js

```error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.```
News to me! Don't know how people used it just fine so far with this, but I assume it's a TypeScript version thing.
Changed it manually in the failing build and it worked. Also VS Code stopped yelling at me.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/bl …

fix: Fix generation of declaration files for i18n messages

---

src/expandable-section/__tests__/interactions.test.tsx
src/expandable-section/expandable-section-header.tsx
src/expandable-section/styles.scss
src/test-utils/dom/expandable-section/index.ts

After #1143, the clickable area to expand and collapse expandable sections is restricted to a subset of the header elements when interactive elements are present in the header. Therefore, clicking on the entire header with `ExpandableSection.findHeader().click()` is not reliable anymore to expand an expandable section in tests, and a new function `findExpandButton` is provided in test utils for this purpose, which returns only the clickable area.
Related documents:
- API proposal: kSXNASqTs3Sk
- More information about changes in the clickable area: 7SZJAvbhbznX
<details> …

chore: Add findExpandButton to Expandable section test utils

---

.github/workflows/bundle-size.yml
.github/workflows/bundle-size/.gitignore
.github/workflows/bundle-size/build.js
.github/workflows/bundle-size/index.html
.github/workflows/bundle-size/main-with-cloudscape.jsx
.github/workflows/bundle-size/main.jsx
.github/workflows/bundle-size/package-lock.json
.github/workflows/bundle-size/package.json

This PR adds a new Github Actions workflow, and an essentially empty Vite project that the workflow uses. The workflow measures the Javascript bundle size of the Cloudscape package for the PR's branch and the `main` branch. It then attaches a status message in the Checks section of the PR that describes the new Javascript bundle size, along with information on how the Javascript bundle size changed in this PR.
As a high-level overview, the workflow works like this:
1. We build the essentially empty Vite project. This generates a Javascript bundle file. We record the size of that file as the __baseline__ for the later calculations.
2. We checkout the code of __the base branch__ (i.e. `main`, usually), and build the components package from there. We add these components to the Vite project …

chore: Measure bundle size in pull requests

---

pages/form-field/permutations.page.tsx
src/form-field/internal.tsx
src/header/internal.tsx
src/internal/context/info-link-label-context.ts
src/link/__tests__/index.test.tsx
src/link/internal.tsx

Add additional labelling to "Info" links where it can be derived from the context.
Related links, issue #, if available: AWSUI-21219
New unit tests
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-princip …

feat: Auto-label info links where possible

---

src/modal/internal.tsx

Fun little fact I learned today: a tabindex on a generic element will often be interpreted by screen readers as having role="group". And if there is no accessible name associated with that element, it'll just read out the entire contents of the element (in this case, the modal).
In this case, when the modal is opened, the focus gets set into the close button, and since there's a "context switch", the screen reader reads the group "name", which ends up being the contents of the entire group.
Spelunking through commit history for this component, this tabIndex={-1} goes all the way back to the initial implementation of the modal where this div also had a ref (back when we set the focus to the whole modal instead of the close button), but after this ref was removed, this tabIndex stuck …

fix: Remove implicit unlabeled group around contents when focus is moved to modal

---

package-lock.json
package.json
src/internal/components/focus-lock/index.tsx
src/top-navigation/parts/overflow-menu/views/submenu.tsx
src/top-navigation/parts/overflow-menu/views/utilities.tsx

"Mom, can we use react-focus-lock?" "We have react-focus-lock at home"
Over the past year or so, we've mostly switched from react-focus-lock to using our own internal tab trap that's simpler to coordinate, and far less aggressive when it comes to focus management. This PR removes the final two components that still rely on the original focus lock and removes the dependency altogether. But I also couldn't resist a little refactor - moving things around so they read easier, mostly.
Related links, issue #, if available: AWSUI-18931
Added a new focus lock test for the return backoff logic thing, but other than that, existing tests should pass.
<details> …

chore: Remove dependency on react-focus-lock

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/s3-resource-selector/interfaces.ts
src/s3-resource-selector/s3-modal/basic-table.tsx
src/s3-resource-selector/s3-modal/index.tsx

Ensure that customers can set aria labels on components used
inside s3 resource selector.
(NB, we don't need to add internationalized versions, as they
will already be handled by the child components)
Related links, issue #, if available: AWSUI-21154
Tested locally
<details>
- _Changes …

fix: Add some missing aria label properties to S3 Selector

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/i18n/messages-types.ts
src/i18n/messages/all.de.json
src/i18n/messages/all.en-GB.json
src/i18n/messages/all.en.json
src/i18n/messages/all.es.json
src/i18n/messages/all.fr.json
src/i18n/messages/all.id.json
src/i18n/messages/all.it.json
src/i18n/messages/all.ja.json
src/i18n/messages/all.ko.json
src/i18n/messages/all.pt-BR.json
src/i18n/messages/all.zh-CN.json
src/i18n/messages/all.zh-TW.json
src/s3-resource-selector/interfaces.ts
src/tag-editor/interfaces.tsx

Synchronizes messages from the internal repo, picking up the translations since the last update (when we release i18n support). See #1189 for why we have a `messages-types.ts` file. This will be merged in on top of that PR.
Additionally, since we have strings for s3 resource selector and tag editor, this adds the `@i18n` marker to those components docs as well.
Fixes #1193.
Strings are strings. Docs have a documenter update.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING. …

chore: Synchronize i18n messages

---

src/i18n/messages-types.ts

These types are used in #1189 so they're not needed yet, but they're meant to be merged in with every message update so they made it in early. That's not a problem, but still, the naming needs to be changed, so this PR does just that.
<details>
- …

chore: Update generated interface name for i18n message types

---

src/internal/hooks/use-visual-mode/index.ts
src/internal/styles/utils/theming.scss
style-dictionary/utils/modes.ts

"Print" typically prints on a white background (and removes dark backgrounds),
so in general it's better to use light mode for this media.
Related links, issue #, if available: https://github.com/cloudscape-design/theming-core/pull/47
Tested in dev pipeline
<details> …

fix: Don't use dark mode for print media

---

src/expandable-section/__tests__/expandable-section.test.tsx
src/expandable-section/expandable-section-header.tsx
src/expandable-section/internal.tsx

Previously we had a workaround for VO+Safari that was causing problems
for other users (as the label & description were combined into one). This 
PR uses a more standard label/description approach.
Related links, issue #, if available: AWSUI-21215
New unit tests, local testing in VO+Chrome, NVDA+FF
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md …

fix: Use more standard aria-labels/descriptions in expandable section

---

src/help-panel/styles.scss
src/text-content/styles.scss

> Use primary links to help differentiate link text from surrounding text when interactivity is not implied by its context.
Text heavy components like the help panel and text content currently use secondary links, so we just rely on color to determine interactivity in those. This adds an additional bold link affordance.
~~Needs a design check before it's ready to merge.~~ All good to review!
Related links, issue #, if available: AWSUI-21173
Purely visual change.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#p …

fix: Use primary link visuals for anchors in HelpPanel and TextContent

---

src/i18n/provider.tsx

Self-explanatory, we can't use `useBaseComponent`, but we have this. The `AnnotationContext` component does the same thing.
<details> …

chore: Add metrics to I18nProvider

---

src/help-panel/styles.scss

Updated the help panel links to be primary links, but the footer that contains a list of links are not part of text content and should remain secondary.
Spotted during visual tests.
<details> …

fix: Use secondary links in help panel footers

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/button/__tests__/button.test.tsx
src/button/interfaces.ts
src/button/internal.tsx

Add ariaLabel as `title` to buttons as a visual hint.
This can help, for example, to give extra information about
icon-only buttons whose meaning may not be immediately clear to all users.
Related links, issue #, if available: AWSUI-21235
Unit tests & local testing in various browsers.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-sup …

feat: Add ariaLabel as `title` to buttons as a visual hint

---

src/autosuggest/__integ__/async-autosuggest.test.ts
src/autosuggest/virtual-list.tsx
src/internal/hooks/use-virtual/index.ts
src/select/parts/virtual-list.tsx

The useVirtual from react-virtual@2 might produce an infinite update loop caused by setting measured item sizes in the render cycle (as part of the `measureRef` assignment). The sum of all measured item sizes is returned as `totalSize` which is then set on the list container. Enforcing new container height might result in an items size change e.g. when the content wraps. 
The infinite update cycle causes React "Maximum update depth exceeded" error and can be additionally confirmed by logging the totalSize which should then bounce between two values. Empirically it has been found out that increasing the container size slightly (e.g. by 1px) - decreases the risk of items content wrapping in one size and not wrapping in the other that prevents the infinite loop.
Increasing the size does not …

fix: Document and mitigate infinite loop caused by react-virtual

---

pages/space-between/alignment.permutations.page.tsx
pages/space-between/styles.scss
src/__tests__/__snapshots__/documenter.test.ts.snap
src/space-between/interfaces.ts
src/space-between/styles.scss

As discussed, add more options to `alignItems` prop added in #1195: `start` and `end`.
**Why not include `stretch` as well?**
`stretch` is already the default behavior. According to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items#values), the initial value for `align-items` is `normal`, and this value:
> For flex items, the keyword behaves as `stretch`.
**Why not `flex-start` and `flex-end` instead of `start` and `end`?**
- Technically, the result would be the same. Whereas `flex-start` and `flex-end` are specific to the Flexbox, `start` and `end` are generic for all box models. [W3C docs](https://d21d5uik3ws71m.cloudfront.net/components/3489063170a9df7f7021c168aa0db3f2bf0e56ae/index.html#/light/space-between/alignment.permutations)
- As [this …

feat: Add support for aligning to start and end in SpaceBetween

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/code-editor/__tests__/code-editor.test.tsx
src/code-editor/index.tsx
src/code-editor/interfaces.ts

A couple of people have asked about providing screen reader `ariaLabel` properties to the code editor. Just like other form elements, we accept `ariaLabelledby` and `ariaDescribedby` on the component, but the code editor doesn't currently allow an `ariaLabel`.
Related links, issue #, if available: AWSUI-21273
Unit test (x1)
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components …

feat: Add ariaLabel property to code editor

---

src/property-filter/__tests__/utils.test.ts
src/property-filter/utils.ts

In trying to construct a `PropertyFilterOperatorExtended<string[]>` in a PropertyFilter, a token value type of `string[]` doesn’t actually work, but not until you try to edit. At token edit time, there’s a util that tries to manipulate the value as a string that fails (trying to call `toLowerCase()` on it). This wasn't caught by TypeScript because we don't have an ESLint rule for checking unsafe calls of `any` typed values.
This PR makes the handling logic in the util more robust by checking the type first. 
Related links, issue #, if available: AWSUI-21107
<details>
- _Changes are backward-compatible if not indicated, …

chore: Add check to ensure token value is string and add test

---

pages/expandable-section/permutations.page.tsx
src/expandable-section/__tests__/expandable-section.test.tsx
src/expandable-section/expandable-section-header.tsx
src/expandable-section/internal.tsx
src/expandable-section/styles.scss
src/expandable-section/utils.ts
src/header/internal.tsx

Reverts #1232 which reverted #1206, and adds fixes to default and footer variants when using the deprecated `header` prop.
- Same as in #1206 
- Added two new permutations
- Verified that BackstopJS fails only because of the newly added permutations
- Ran in my pipeline including visual regression tests against Examples, which originally surfaced the issue that motivated the revert, because the Tutorial panel component uses Expandable section internally with the deprecated `header` prop
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/bl …

feat: Support descriptions in Expandable section header for default variant

---

pages/app-layout/runtime-drawers.page.tsx
pages/app-layout/utils/external-widget.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/__tests__/warnings.test.tsx
src/app-layout/index.tsx
src/app-layout/runtime-api.tsx
src/internal/plugins/__tests__/drawers-controller.test.ts
src/internal/plugins/api.ts
src/internal/plugins/drawers-controller.ts
src/internal/plugins/index.ts
src/test-utils/dom/app-layout/index.ts

Adding new API for configuring app layout outside React tree. Detailed proposal: https://tiny.amazon.com/tjbskv2t/quipK3xL
* Added unit tests
* Tested on integration POC (links in the proposal)
<details> …

chore: Add app layout runtime API

---

src/expandable-section/expandable-section-header.tsx
src/expandable-section/styles.scss

Visual design review for #1206 surfaced that descriptions in expandable section headers should always be indented to match the header, for al variants, including container.
Related issue: AWSUI-21297
- Manually tested in Chrome, Firefox and Safari
- Reviewed that BackstopJS failures are as expected
- Visual regression tests are in place
<details> …

fix: Indent descriptions in headers of container variant Expandable sections

---

pages/expandable-section/permutations.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/expandable-section/__tests__/expandable-section.test.tsx
src/expandable-section/__tests__/interactions.test.tsx
src/expandable-section/expandable-section-header.tsx
src/expandable-section/interfaces.ts
src/expandable-section/styles.scss
src/expandable-section/utils.ts

After adding description for default variant (#1234), adding it to the footer variant too was a quite trivial change so we decided to follow up with it.
- Adapted unit tests
- Added unit tests to make sure `findExpandButton` works in all variants and with or without descriptions
- Added permutations to existing permutations page
- Manually reviewed permutations page
- Verified that BackstopJS failures are due to the newly added permutations and look as expected
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#pu …

feat: Support descriptions in Expandable section headers for footer variant

---

build-tools/tasks/themeable-source.js
src-themeable/internal/template/internal/generated/theming/index.cjs.d.ts
src-themeable/theming.ts
tsconfig.src-themeable.json

A step to support cloudscape-design/theming-core#35
This PR contains the same changes as already made in https://github.com/cloudscape-design/components/pull/1176 which got reverted because of a potential conflict about the `internalDir` path when generating the npm package artifacts. I verified successfully this wan't cause an issue by generating those artifacts and used them to generate a custom (build time) theme.
These changes:
- configures the `designTokensOutputDir` which holds the `package.json` which will be part of the generated build time theme artifacts.
- simplifies the way how we generate the themed components by generating the `buildThemedComponents` as part of the components build. It allows us to remove the ts build step in the theming package (which generates the build …

chore: Prepare design tokens template

---

pages/app-layout/utils/external-widget.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/runtime-api.tsx
src/app-layout/visual-refresh/trigger-button.tsx
src/internal/plugins/drawers-controller.ts

1. Accept svg content as a string in runtime API (because it has no access to JSX)
2. Fix `iconSvg` use in visual refresh mode
Updated dev page, checked that custom SVG renders correctly
<details> …

fix: Bug fixes in iconSvg feature in drawers

---

pages/line-chart/permutations.page.tsx
src/mixed-line-bar-chart/data-series.tsx

Extend clipping rectangle vertically by half the stroke width in each direction vertically, to prevent the line stroke from being clipped in segments where it has the maximum or minimum value of the domain for several times in a row.
Issue: AWSUI-21329
- Added permutation
- Manually tested with Chrome, Firefox and Safari
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/bl …

fix: Avoid cutting off half the stroke when line is at the edge of chart

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/attribute-editor/interfaces.ts

Fixes misalignment in documentation. Currently, [Attribute editor](https://cloudscape.aws.dev/components/attribute-editor/?tabId=api) has `i18nStrings` property marked as a part of built-in internationalization, but i18n [translation strings](https://github.com/cloudscape-design/components/blob/main/src/i18n/messages/all.en.json#L38C23-L38C23) contain `removeButtonText` only.
<details> …

fix: Correct i18n annotation of attribute editor

---

src/mixed-line-bar-chart/data-series.tsx

Because of existing borders in bars, #1224 had some unexpected changes in graphs which include bars. This addresses this issue by letting lines and bars have different clip paths.
Visual regression tests are in place.
Manually tested.
<details> …

fix: Prevent bars from covering baselines in graphs

---

pages/container/stacked-components.page.tsx
pages/expandable-section/container-variant.permutations.page.tsx
pages/expandable-section/stacked-variant.permutations.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/expandable-section/__tests__/expandable-section.test.tsx
src/expandable-section/expandable-section-container.tsx
src/expandable-section/interfaces.ts
src/expandable-section/internal.tsx

The variant is useful to group expandable sections with other stacked containers.
Additional unit and visual regression tests
<details>
- _Changes include appropriate documentation updates._ Yes
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._ 
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibi …

feat: Stacked variant for Expandable Section

---

src/internal/components/chart-popover/index.tsx

Currently the chart detail popover has `overflow: hidden` on its content, which means that focus outlines inside the popover are cut off. This change fixes it with the `overflowVisible` flag.
Requirement for https://github.com/cloudscape-design/components/pull/1124.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRI …

fix: Fix visible focus being cut off in chart detail popover

---

src/table/sticky-scrollbar/styles.scss

Increased the sticky scrollbar z-index to have it appear above the table sticky columns.
You can check it out here: https://d21d5uik3ws71m.cloudfront.net/components/120fe4afc191975697c3c9c4473d0ec3a19e108b/index.html#/light/table/sticky-columns/?stickyColumnsFirst=1&stickyColumnsLast=1
<details> …

chore: Increase sticky scrollbar z-index

---

style-dictionary/visual-refresh/metadata/colors.ts

The "non-current" breadcrumb link colors already can be changed via the colorTextLinkDefault token.
Exposing these tokens allow customers to adjust the remaining items in the breadcrumb group.
_Token description got reviewed._
Related links, issue #, if available: AWSUI-21309
<details>
- …

feat: Make design tokens for current breadcrumb item and breadcrumb icon public and themeable

---

src/table/__tests__/header-cell.test.tsx
src/table/header-cell/index.tsx
src/table/internal.tsx
src/table/thead.tsx
src/table/use-column-widths.tsx

A set of refactorings for resizable columns to remove the dependency on column indices and improve performance of the first rendering.
Existing tests, manual testing, lighthouse testing
<details> …

refactor: Table resizable columns remove dependency on indices

---

pages/container/media.page.tsx

Added a `SpaceBetween` to have the containers spaced out in the screenshots testing page.
Before: https://d1dnby8l05mrxs.cloudfront.net/polaris/index.html#/light/container/media/?density=compact&visualRefresh=true&motionDisabled=true&position=top&height=150px&content=4-3
After: https://d21d5uik3ws71m.cloudfront.net/components/9ed3141fcea1348d11b51a33865847a1717a7ce1/index.html#/light/container/media/?density=compact&visualRefresh=true&motionDisabled=true&position=top&height=150px&content=4-3
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/componen …

chore: Add SpaceBetween in the media page

---

src/wizard/__tests__/wizard.test.tsx
src/wizard/internal.tsx

Caused accessibility tests to fail in our pipeline; turns out a necessary string was missing and it came out after we adopted i18n strings in our own demos. Updated the component, updated the tests.
Updated i18n unit tests.
<details>
- _Changes …

fix: Accept i18nStrings.navigationAriaLabel in wizard through i18n provider

---

src/cards/styles.scss

`end` has good enough browser support, but old settings will issue a warning, which in turn can make builds fail.
Related PRs from the past: #1038, #1039
<details> …

fix: Add flex- prefix in Cards footer pagination for better backwards compatibility

---

pages/expandable-section/common.tsx
pages/expandable-section/container-variant.permutations.page.tsx
pages/expandable-section/focus.page.tsx

Add a separate page for Expandable section focus ring visual tests.
Until now, the container variant permutations page was being used for this and adding or removing permutations would make the focus ring tests fail unnecessarily.
This also allows us to test the focus rings much more thoroughly, across variants and features.
- Tested locally against new visual regression tests
- Verified BackstopJS failures
<details> …

chore: Refactor expandable section test pages

---

package-lock.json
package.json
pages/code-editor/controllable-height.page.tsx
pages/code-editor/simple.page.tsx
pages/code-editor/vertical-scroll.page.tsx
pages/code-editor/with-errors-no-warnings.page.tsx
src/code-editor/__integ__/code-editor.test.ts
src/code-editor/__tests__/code-editor.test.tsx
src/code-editor/__tests__/util.test.ts
src/code-editor/ace-editor.scss
src/code-editor/index.tsx
src/code-editor/pane.tsx
src/code-editor/setup-editor.ts
src/code-editor/util.ts

Ace recently released a flag to allow keyboard access to the gutter and code folding controls, and just improve keyboard accessibility in general (ajaxorg/ace#5146). This PR enables that option, and integrates it with the pane. Additionally, it simplifies the pane's focus management logic.
There are some changes around ace-builds 1.15.0 that breaks/changes how basePath is set, so I had to mess with the ace config in the dev pages, but following up on that shouldn't block this release. We use "ace-builds" in the component itself for the typings alone.
Related links, issue #, if available: AWSUI-19227
Tests have been changed where they were failing due to behavioral changes. The rest is visual.
<details> …

feat: Add keyboard accessibility to fold controls in code editor

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/text-filter/__tests__/text-filter.test.tsx
src/text-filter/interfaces.ts
src/text-filter/internal.tsx

Recently encountered a scenario where a user needed to pass in "usage instructions" for a text filter in the table tools. After some discussion, we felt that the constraint text UX was indeed the way to go. We support proper form fields in tables anyway (see [select filter](https://cloudscape.design/examples/react/table-select-filter.html)), so this isn't too far off.
We also discussed and felt it wouldn't be right to support the form field context by itself without also exposing the form field properties (`ariaLabelledby`, `ariaDescribedby`, `controlId`), so this adds them too.
Needs a review with the team before merging.
Related links, issue #, if available: AWSUI-21356
Unit tests!
<details>
_The following items are to be evaluated by the author(s) …

feat: Pass form field context to text filter

---

src/form-field/internal.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/interfaces.ts
src/internal/analytics/selectors.ts
src/link/internal.tsx
src/wizard/internal.tsx

With this change, we include the fields `stepName` and `subStepName` in the metrics event. Previously, we would only emit the selector to the elements containing those names. When a step is completed (i.e. at the point where `funnelStepComplete` is called), this selector does not point at the correct element anymore, because that element has been unmounted. To mitigate this, we save the name already at the start of the effect.
Related links, issue #, if available: nBvhAQL0oUIC , Line 33
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/bl …

fix: Include stepName and subStepName in events

---

src/table/body-cell/styles.scss

When the inline editing cells are on a sticky column, they lose their stickiness on hover / focus. This is due to the specificity of the `position` rule not being high enough in these cases. This PR fixes this.
Related links, issue #, if available: AWSUI-21418
<details> …

chore: Add higher-specificity rule for inline-editable sticky cell styles

---

src/area-chart/chart-container.tsx
src/area-chart/styles.scss
src/internal/components/cartesian-chart/chart-container.tsx
src/internal/components/cartesian-chart/styles.scss
src/mixed-line-bar-chart/chart-container.tsx
src/mixed-line-bar-chart/styles.scss

Introducing more reusable charts elements to support https://github.com/cloudscape-design/components/pull/1273
Existing tests
<details> …

refactor: Cartesian chart container

---

src/app-layout/visual-refresh/background.scss
src/app-layout/visual-refresh/layout.scss

The top offset was being calculated using a scaled variable, where it should be static. This PR fixes it.
Before: https://d1dnby8l05mrxs.cloudfront.net/polaris/index.html#/light/app-layout/with-table/?density=compact&visualRefresh=true&motionDisabled=true&stickyNotifications=true
After: https://d21d5uik3ws71m.cloudfront.net/components/159e004804283aadc52ec8652c1e273725c1bd63/index.html#/light/app-layout/with-table/?density=compact&visualRefresh=true&motionDisabled=true&stickyNotifications=true
Issue: AWSUI-21408
Run through my dev pipeline: `dev-v3-rucarva`.
<details>
- _Changes are backward-compatible if not indicated, …

fix: Height of dark header with sticky table in compact mode

---

pages/app-layout/utils/external-widget.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/runtime-api.tsx
src/internal/plugins/drawers-controller.ts

There is no guarantee that this iconName is going to be available in the receiving app layout, because it could be a different bundle.
Since we have no actual use-cases for `iconName` property it would be safer to unsupport the feature before it becomes problematic
1. Updated dev page to exclude built-in icons
2. Added a unit test
<details> …

chore: Unsupport iconName in runtime drawers api

---

pages/expandable-section/container-variant.permutations.page.tsx
pages/expandable-section/permutations.page.tsx
src/container/shared.scss
src/expandable-section/styles.scss

Currently the elements inside the header of Expandable sections don't behave as they should when wrapping. Heading and description are indented on the first line, but they don't align correctly when they wrap, and the action buttons are also not indented when wrapping below the description:
This is fixed here by indenting the entire header content, and then applying a negative margin to the element that contains the icon and the heading (which needs to be kept together in order to receive focus):
- Added permutations with long descriptions for all variants that support descriptions
- Ran in my pipeline
- Reviewed BackstopJS failures
- Reviewed by visual design
<details>
- …

fix: Correctly indent all header elements in expandable sections

---

pages/form/with-validation.page.tsx
pages/wizard/with-validation.page.tsx
src/form-field/__tests__/form-field-analytics.test.tsx
src/form-field/internal.tsx
src/form/__tests__/analytics.test.tsx
src/form/index.tsx
src/form/internal.tsx
src/internal/analytics/__tests__/hooks/use-funnel.test.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/context/analytics-context.ts
src/wizard/__tests__/analytics.test.tsx
src/wizard/internal.tsx

When a form is submitted (either in a Form component or in a page of a Wizard component), and an error is shown in one of the form fields, we emit the `funnelSubStepError` event. If a form-level error happens, we emit the `funnelError` event. When the user tries to submit the form again, and the same error happens, the error is not re-rendered. The result of this was that no new error event is emitted.
After this change, if there are errors after trying to submit a form (or a page, in the case of a Wizard), the error events are emitted again. This is achieved by applying a counter that is incremented on every attempt to submit the form, which causes the `useEffect` hooks to re-run.
Related links, issue #, if available: nBvhAQL0oUIC , Line 26
I have added two new testing pages, which I …

fix: Re-emit error metrics if an error persists after attempting to submit

---

src/expandable-section/__tests__/expandable-section.test.tsx
src/expandable-section/expandable-section-header.tsx
src/expandable-section/styles.scss
src/test-utils/dom/expandable-section/index.ts

Introduces two new test utils for expandable section that allows people to find the header text and descriptions, even when not using the container variant.
Related links, issue #, if available: AWSUI-21436
<details> …

feat: Add new test utils `findHeaderText` and `findHeaderDescriptions` to expandable section

---

src/table/sticky-scrollbar/styles.scss

This reverts commit 6f71624769d9164b35902c0dfbea81b0dd358aa2.
Some problems emerged with the scrollbar overlapping elements under some circumstances.
<details> …

revert: Revert "chore: Increase sticky scrollbar z-index (#1201)"

---

jest.unit.config.js

Make Jest to fail the build if the coverage numbers do not meet the threshold.
Replaces codecov reporting
PR build
<details> …

chore: Configure coverage thresholds in Jest

---

pages/multiselect/screenshot.page.tsx
pages/status-indicator/permutations.page.tsx
src/internal/components/dropdown-status/index.tsx
src/status-indicator/internal.tsx
src/status-indicator/styles.scss

The status indicator is a display-block component, for wrapping reasons. This also means we can't place any inline text next to it without it breaking to the next line if it takes up multiple lines. We can't switch the default to inline because it breaks wrapping in many circumstances (e.g. key-value pairs), so I'm adding this as an internal property for now.
Related links, issue #, if available: AWSUI-21388
Permutation tests. With `wrapText={false}`, it will overflow past the page (which is, I guess, expected), so I added a wrapper div that hides overflow past the page.
<details>
- _Changes are backward-compatible if …

fix: Prevent recovery button from wrapping to next line in dropdown footers

---

src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/index.tsx
src/property-filter/token-editor.tsx

`enteredTextLabel` is provided by autosuggest strings, which when they receive `undefined`, should use the built-in ones. Unfortunately, when property filter receives `undefined`, it provides a fallback value to autosuggest, which breaks this assumption.
Also I noticed a bunch of the buttons submit forms, so I fixed that as well while I was here.
The property filter, having been one of the beta components, lacked the GA component test suite. Added i18n tests to the component.
<details> …

fix: Fix enteredTextLabel message not being provided in property filter

---

src/input/internal.tsx

The color of the search icon in readonly input and autosuggest draws too much visual attention.
To make these more readable, especially in the context of Tag editor, we're changing the icon the "subtle" color variant in readonly state.
Related links, issue #, if available: AWSUI-20725
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-supp …

feat: Change search icon in readonly inputs to subtle variant

---

build-tools/tasks/package-json.js

We have a 2nd build for dev pages which now uses its own lock file. We can propagate this file and reuse.
We also used to do this before: https://github.com/cloudscape-design/components/pull/614, but this time the approach is safe, we publish it is a subfolder, not on the root
* PR build
* Push into dev-v3-serdiuk branch
<details> …

chore: attach package lock to dev-pages package

---

src/form-field/internal.tsx
src/internal/analytics/__tests__/hooks/use-funnel-step.test.tsx
src/internal/analytics/__tests__/hooks/use-funnel-sub-step.test.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/context/analytics-context.ts
src/internal/analytics/hooks/use-funnel.ts
src/link/internal.tsx

For funnel analytics, there are three different (nested) contexts: the funnel context, the funnel step context, and the funnel substep context. Each has a hook to retrieve the current value. Before this PR, the hooks for the inner contexts would also return properties from the "larger" context (e.g. `useFunnelSubStep` would also return the `stepNumber` from the step context).
However, this means that components that use a "lower-level" hook rely on that lower-level context to be present, in order to access values from a higher context. For example, if a form field is placed outside of a container (which provides the sub step context), there is no **sub**step context available, and the `useFunnelSubStep` hook would return an empty `stepNumber` (even though a **step** context might be …

fix: Unshare funnel hooks properties

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/property-filter/__tests__/common.ts
src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/index.tsx
src/property-filter/interfaces.ts

As signed off by the dev team, moving these situation-dependent labels out of `i18nStrings` and into the component proper. ~~Needs a content review though.~~ All done!
Updated unit tests, but that's about it.
<details> …

feat: Move filteringAriaLabel and filteringPlaceholder in property filter to top level

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/wizard/__tests__/wizard.test.tsx
src/wizard/interfaces.ts
src/wizard/internal.tsx
src/wizard/wizard-form.tsx

As signed off by the dev team, moving these situation-dependent labels out of `i18nStrings` and into the component proper. No new strings, we're all good on content review (unless `@deprecated` messages count?).
Updated unit tests, but that's about it.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#brow …

feat: Move i18nStrings.submitText in wizard to top level

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/attribute-editor/__tests__/attribute-editor.test.tsx
src/attribute-editor/interfaces.ts
src/attribute-editor/internal.tsx
src/attribute-editor/row.tsx

As signed off by the dev team, moving these situation-dependent labels out of `i18nStrings` and into the component proper. There's one new string that needs content review, but I'm going to get them reviewed in a big batch.
Updated unit tests, but that's about it.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBU …

feat: Move i18nStrings.removeButtonAriaLabel in attribute editor to top level

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/area-chart/__tests__/area-chart-initial-state.test.tsx
src/area-chart/chart-container.tsx
src/area-chart/interfaces.ts
src/area-chart/internal.tsx
src/internal/components/cartesian-chart/interfaces.ts
src/mixed-line-bar-chart/__tests__/mixed-chart.test.tsx
src/mixed-line-bar-chart/internal.tsx

As signed off by the dev team, moving these situation-dependent labels out of `i18nStrings` and into the component proper. No new strings, we're all good on content review (unless `@deprecated` messages count?).
Updated unit tests. I left a couple of original accesses in the tests just to be safe :)
<details> …

feat: Move xTickFormatter, yTickFormatter, and detailTotalFormatter in charts to top level

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/s3-resource-selector/__tests__/s3-in-context.test.tsx
src/s3-resource-selector/index.tsx
src/s3-resource-selector/interfaces.ts
src/s3-resource-selector/s3-in-context/index.tsx

As signed off by the dev team, moving these situation-dependent labels out of `i18nStrings` and into the component proper. Added a string, probably needs content review even if it's pretty simple.
<details> …

feat: Move i18nStrings.inContextInputPlaceholder in s3 resource selector to top level

---

src/container/__tests__/analytics.test.tsx
src/internal/analytics/__tests__/hooks/use-funnel-sub-step.test.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/context/analytics-context.ts
src/internal/analytics/hooks/use-funnel.ts

Before this change, when a container was placed inside another container, the inner container was treated as a new substep. This meant that focus or unfocusing an input element inside the inner container would emit each event twice: once for the inner container/substep, and once for the outer container/substep. Additionally, when tabbing from an input field in the outer container into an input field located in the inner container, a substep change metric would be emitted.
After this change, inner containers do not emit any events on their own, and they are treated as the same substep as their parent container when it comes to detecting a substep change. 
This PR needs to be applied after https://github.com/cloudscape-design/components/pull/1304 …

fix: Nested containers should not create a new subStep context

---

src/multiselect/__tests__/multiselect.test.tsx
src/select/__tests__/select.test.tsx
src/select/utils/use-select.ts

Fix an issue identified in pipeline testing (referenced ID is not in the DOM when popovers are closed)
Tested in dev pipeline
<details> …

fix: Only add aria-controls when dropdown is open

---

pages/funnel-analytics/with-error-alert-in-wizard.page.tsx
src/alert/__tests__/alert-analytics.test.tsx
src/alert/index.tsx

When an Alert is used to display an error, it now also emits `funnelError` or `funnelSubStepError` events, depending on whether it is placed inside a sub step (such as a container) or somewhere else in a funnel.
Added unit tests, and tested it manually on the new dev page
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/ …

feat: Emit error events for Alerts

---

src/form/__tests__/analytics.test.tsx
src/internal/analytics/__tests__/components/analytics-funnel.test.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/hooks/use-funnel.ts

`funnelStepComplete` should be emitted when the funnel is complete. This makes processing the events afterwards easier, since every step has a start and and end event now. The one exception is that no events should be emitted when the flow is cancelled.
Updated unit tests and manual testing in dev pages
<details> …

fix: Emit funnelStepComplete after completion, but not after cancellation

---

build-tools/tasks/styles.js
src/__tests__/design-tokens.test.ts

Adopt API introduced in https://github.com/cloudscape-design/theming-core/pull/55.
Built locally
<details>
- _Changes include appropriate documentation updates._ Will come later …

feat: Generate JSON schema for Design Tokens

---

src/app-layout/toggles/styles.scss

Fixing a regression introduced in #1343
* Locally
* Tests in my dev pipeline 
<details>
- _If …

chore: Fix focus outline on app layout triggers

---

pages/area-chart/fit-height.page.tsx
pages/mixed-line-bar-chart/fit-height.page.tsx
pages/pie-chart/fit-height.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/area-chart/__tests__/area-chart-initial-state.test.tsx
src/area-chart/chart-container.tsx
src/area-chart/internal.tsx
src/area-chart/model/index.ts
src/area-chart/model/use-chart-model.ts
src/internal/components/cartesian-chart/chart-container.tsx
src/internal/components/cartesian-chart/interfaces.ts
src/internal/components/cartesian-chart/styles.scss
src/internal/components/chart-plot/__tests__/chart-plot.test.tsx
src/internal/components/chart-plot/index.tsx
src/internal/components/chart-wrapper/index.tsx
src/internal/components/chart-wrapper/styles.scss
src/mixed-line-bar-chart/__tests__/mixed-chart.test.tsx
src/mixed-line-bar-chart/chart-container.tsx
src/mixed-line-bar-chart/internal.tsx
src/mixed-line-bar-chart/styles.scss
src/pie-chart/__tests__/utils.test.tsx
src/pie-chart/index.tsx
src/pie-chart/interfaces.ts
src/pie-chart/labels.tsx
src/pie-chart/pie-chart.tsx
src/pie-chart/segments.tsx
src/pie-chart/styles.scss
src/pie-chart/utils.ts

Re-introduction of https://github.com/cloudscape-design/components/pull/1273 reverted here: https://github.com/cloudscape-design/components/pull/1341
Updated the internal chart-wrapper and chart-container to have less performance impact on the charts not using the new property.
Tested in dev-pipeline.
<details> …

feat: Charts fit-height

---

src/internal/analytics/__tests__/mocks.ts
src/internal/analytics/index.ts
src/internal/analytics/interfaces.ts
src/wizard/__tests__/analytics.test.tsx

This PR adds the new event `funnelStepError`, which is used to emit a metric about an error that relates to a whole step, usually an Alert outside of a container. It differs from `funnelSubStepError`, which is for errors inside a substep like a container, and from `funnelError`, which is more generic.
Related links, issue #, if available: **CR-97002073**
<details> …

chore: Add `totalSubSteps` property and funnelStepError event

---

pages/popover/focus-test.page.tsx
src/popover/__integ__/popover.test.ts
src/popover/__tests__/popover.test.tsx
src/popover/internal.tsx

Ensure that if a custom popover trigger is used, the focus is returned
to it when the popover is dismissed.
Related links, issue #, if available: AWSUI-21509
New integ tests
<details> …

fix: Restore focus to custom popover triggers

---

src/cards/index.tsx
src/internal/analytics/__tests__/components/analytics-funnel.test.tsx

After this change, the Cards component is treated as a substep when it comes to funnel metrics, i.e. it is treated like a container.
Extended the unit test
<details> …

chore: Mark Cards component as a funnel substep

---

pages/autosuggest/form-submit.page.tsx
src/autosuggest/__integ__/form-submit.test.ts
src/autosuggest/internal.tsx
src/internal/components/autosuggest-input/index.tsx

Fixed disconnection between public onKeyDown handler and its internal counterpart
Related links, issue #, if available: AWSUI-21652
Added extra tests. Could not use JSDOM, because the default onKeyDown behavior is not supported there
<details> …

fix: Allow onKeyDown handler to prevent default behavior

---

src/table/__integ__/resizable-columns-misc.test.ts

Fixed tests by using the counter instead of the resize observer entry which caused issues with chromedriver
<details>
- _If the code …

chore: Fix flaky oscillating resize test

---

README.md

Hello, thanks for this useful software !
I copied and ran the basic example in the README and got an error.
```
Parsing error: Unexpected token, expected "("
```
I think there should be () after the JavaScript function.
<details> …

chore: fix README basic example

---

src/internal/components/abstract-switch/__tests__/abstract-switch.test.tsx
src/internal/components/abstract-switch/index.tsx

The auto-generated `aria-labelledby` would previously override any custom `ariaLabel`,
which basically means `ariaLabel` was a no-op. This prevents that override.
Updated tests
<details> …

fix: Don't override ariaLabel when explicitly set on switch components

---

pages/funnel-analytics/with-error-alert-in-wizard.page.tsx
src/wizard/wizard-form.tsx

Before this PR, the header area of the Wizard component was not included in the step context. This meant that when an info link inside the header was clicked, the resulting `helpPanelInteracted` event did not contain information about the current step. 
This PR moves the step context so that it contains the whole content area of the Wizard (i.e. without the navigation on the side).
Tested manually in dev page by inspecting the generated event
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/ …

chore: Include Wizard header in step context

---

README.md
src/internal/hooks/container-queries/use-height-measure.ts
src/mixed-line-bar-chart/chart-container.tsx

Refactored mixed chart axis props so that the bottom axis props are clearly decoupled from height.
Updated bottom labels height calculation to be synchronous so that the SVG height measurement does not have to wait until the bottom labels height is available.
The change also fixes the tick count number for horizontal bar charts - previously the tick count for Y was always measured against the plot height - now it runs against the correct dimension.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md …

fix: Fix tick count for horizontal bar charts and make bottom labels height measure synchronous

---

.eslintrc
src/i18n/index.ts
src/i18n/provider.tsx
src/i18n/testing.tsx

Noticed this was missing when messing with internal stuff and documenter. The named export has to stay, but we can have a default export on top as well.
And another thing I thought would be nice is the addition of a lint rule that stops us from transitively importing the modern ICU dependencies into TS 3.6+ supported component code.
If it builds, it's good.
<details> …

chore: Apply component export/displayName conventions to I18nProvider

---

src/internal/components/chart-popover/index.tsx
src/internal/utils/__tests__/dom.test.ts
src/internal/utils/dom.ts
src/pie-chart/__tests__/pie-chart.test.tsx
src/pie-chart/index.tsx
src/pie-chart/pie-chart.tsx
src/pie-chart/segments.tsx

Fixed two major issues
1. `event.relatedTarget` is not always a DOM node. Sometimes it is `window` and this breaks `node.contains(event.relatedTarget)`
2. There are two concurrent mouse leave handlers, for the SVG element and popover. When both fire same time, the second fails with an error, because the segment is already hidden. The new implementation is idempotent
Also did some additional refactoring, see the comments inline
Related links, issue #, if available: AWSUI-21557
1. Added more tests
2. Checked other chart components, they already use `nodeContains`, so we are good
<details>
- _Changes are backward-compatible …

fix: Merge mouseleave detection logic

---

src/flashbar/collapsible-flashbar.tsx

The focus ring of the notification bar button was almost-white (`grey-100`) because the `flashbar` visual context sets `colorBorderItemFocused` to this color. Since #1340 this context is set at the flash message level instead of the entire Flashbar component level, so this color token fell back to the default blue for this component.
This PR fixes it by applying (back) the `flashbar` visual context to the notification bar.
Manually tested against local server, for Classic and Visual Refresh, light and dark mode.
Visual regression tests exists are in place (that's why this was caught).
<details> …

fix: Restore notification bar button focus ring color

---

build-tools/tasks/generate-i18n-messages.js
build-tools/tasks/package-json.js
pages/alert/simple.page.tsx
pages/i18n/dynamic.page.tsx
pages/property-filter/hooks.page.tsx
pages/webpack.config.base.js
src/i18n/__integ__/i18n.test.ts
src/i18n/__tests__/dynamic.test.tsx
src/i18n/dynamic.d.ts
src/i18n/get-matchable-locales.ts
src/i18n/index.ts
src/i18n/provider.tsx

**This PR adds an `importMessages` export to `/i18n`**. All users have to do (on setups that work with dynamic imports) is:
```tsx
import { I18nProvider, I18nProviderProps, importMessages } from "@cloudscape-design/components/i18n";
const locale: string = getLocaleSomehow();
const messages: ReadonlyArray<I18nProviderProps.Messages> = await importMessages(locale);
ReactDOM.createRoot(rootElement).render(
<I18nProvider locale={locale} messages={messages}>
<App />
</I18nProvider>
);
```
`importMessages` returns an array if we ever need to give it additional functionality in the future, but I'm not super sure about it. But you can pass this array directly into the component (which expects an array anyway). The alternate option of statically importing strings as JS/JSON still exists for people …

feat: Provide loader function for dynamically imported i18n messages

---

src/table/internal.tsx
src/table/use-cell-editing.ts

A first step of refactoring for table's inline editing. The eventual goal is to distribute the state via context so that the table won't re-render when a cell state changes. For now, the cell editing state management is encapsulated in a dedicated hook.
Existing tests
<details>
- …

refactor: Table cell editing

---

src/button/index.tsx
src/internal/hooks/use-base-component/index.ts
src/select/index.tsx

This PR extends some components (Select, Button) with more metadata. This metadata is exposed in the `__awsuiMetadata__` property of the component's root node. More components are covered in https://github.com/cloudscape-design/components/pull/1398.
See also https://github.com/cloudscape-design/component-toolkit/pull/35
Related links, issue #, if available: document FZakAmaNW5fQ
Extended unit test
<details> …

chore: Expose component configuration in DOM metadata property

---

pages/alert/simple.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/alert/__tests__/alert.test.tsx
src/alert/index.tsx
src/alert/interfaces.ts
src/alert/internal.tsx
src/alert/styles.scss

This change adds a `focus` method to the alert component. This allows keyboard focus to be moved to the alert component, similar to how critical flashbar messages can receive focus. This is helpful when an alert with critical information appears dynamically and needs to grab the user's attention.
Related links, issue #, if available: AWSUI-8869
<details> …

feat: Add `focus` method to alert

---

.github/workflows/release.yml

This adds a special `release` task for the components repository that executes the three test types (unit, integ, a11y) in parallel. Execution time is almost halved, from ~60min to ~35min.
Tested in my dev branch: https://github.com/cloudscape-design/components/actions/runs/5781899944.
<details> …

chore: Parallel release action for components package

---

pages/cards/permutations.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/cards/interfaces.tsx

Update cards permutation to better match how we expect links
in cards to be implemented.
Tested locally
<details> …

chore: Update cards permutation to match expected usage

---

pages/app/index.tsx
pages/cards/selection.page.tsx
pages/tsconfig.json
src/__a11y__/run-a11y-tests.ts
src/__tests__/form-field-controls-integration.test.tsx
src/multiselect/__integ__/page-objects/multiselect-page.ts
src/test-utils/tsconfig.json
tsconfig.integ.json
tsconfig.json
tsconfig.unit.json

Bring them up to date with our supported browsers
Updated a few `indexOf` to `includes` to show that modern functions are supported
<details> …

chore: Upgrade tsconfigs

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/flashbar/__tests__/collapsible.test.tsx
src/flashbar/__tests__/flashbar.test.tsx
src/flashbar/collapsible-flashbar.tsx
src/flashbar/flash.tsx
src/flashbar/interfaces.ts
src/flashbar/non-collapsible-flashbar.tsx

Fall back to component-level i18nStrings if individual flash item labels aren't provided
New unit tests
<details> …

feat: Use i18nStrings as fallback flash icon labels

---

src/container/styles.scss
src/expandable-section/styles.scss
src/header/internal.tsx
src/header/styles.scss

We reduced header bottom padding in VR to improve info density in #1317, this introduced an inconsistency in the expandable section when it is closed, because heading vertical padding is no longer symmetrical. This PR increases the bottom padding of expandable section headers when it is closed so it looks more balanced.
https://github.com/cloudscape-design/components/assets/15003460/e86b4ce3-916a-4b15-ae7f-5e798cdedf28
Ideally, we would not add more space to the interface, however, we cannot reduce the top padding instead because we don't want a shift in the text between open and closed states. We also cannot have header text start at different heights because the board components use fixed alignment with the handles and settings buttons.
Related links, issue #, if available: AWSUI-21867 …

fix: Asymmetric header vertical padding in closed expandable section

---

pages/box/variants.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/box/__tests__/box.test.tsx
src/box/base-styles.scss
src/box/interfaces.ts

Add the new warning color to the Box component, to match with Alert, StatusIndicator etc.
Related links, issue #, if available: AWSUI-21899
Added new tests/permutations
<details> …

feat: Add text-status-warning color to Box

---

pages/button-dropdown/item-element.permutations.page.tsx
src/button-dropdown/item-element/styles.scss

Ensure inline-icon dropdown has active states
Related links, issue #, if available: AWSUI-21904
Updated visual regression tests
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/). …

fix: Ensure inline-icon dropdown has active states

---

src/file-upload/__tests__/file-upload-dropzone.test.tsx
src/file-upload/dropzone/index.tsx
src/file-upload/internal.tsx

Disallow dropping multiple files onto non-multiple FileUpload.
This ensures that drop behavior matches file selector behavior, 
and better matches with browser native inputs.
Related links, issue #, if available: AWSUI-21885
New unit tests & local testing
<details> …

fix: Disallow dropping multiple files onto non-multiple FileUpload

---

pages/app-layout/with-split-panel.page.tsx
src/split-panel/styles.scss

Allow long words in split panel header to be broken
Related links, issue #, if available: #1431
Local testing & updated screenshot test
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessib …

fix: Break words in split panel header

---

pages/alert/runtime-action.page.tsx
pages/flashbar/runtime-action.page.tsx
src/alert/__tests__/runtime-action.test.tsx
src/alert/actions-wrapper/index.tsx
src/alert/actions-wrapper/styles.scss
src/alert/internal.tsx
src/alert/styles.scss
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/runtime-api.tsx
src/flashbar/__tests__/runtime-action.test.tsx
src/flashbar/flash.tsx
src/flashbar/styles.scss
src/internal/plugins/api.ts
src/internal/plugins/controllers/__tests__/action-buttons.test.ts
src/internal/plugins/controllers/__tests__/drawers.test.ts
src/internal/plugins/controllers/action-buttons.ts
src/internal/plugins/controllers/drawers.ts
src/internal/plugins/helpers/index.ts
src/internal/plugins/helpers/runtime-content-wrapper.tsx
src/internal/plugins/helpers/use-discovered-action.tsx
src/internal/plugins/helpers/utils.ts
src/test-utils/dom/alert/index.ts
src/test-utils/dom/flashbar/flash.ts

Implement new runtime API
Added unit tests and dev pages for screenshot tests
<details>
- _If …

chore: Add runtime actions discovery to alert and flashbar

---

src/internal/keycode.ts
src/table/table-role/index.ts
src/table/table-role/use-grid-navigation.ts
src/table/table-role/utils.ts

Naive single tab stop mechanism for grid table
<details> …

Table grid navigation single stop

---

pages/autosuggest/virtual-resize.page.tsx
pages/select/virtual-resize.page.tsx
pages/tag-editor/simple.page.tsx
src/internal/__tests__/breakpoints.test.ts
src/internal/breakpoints.ts
src/internal/components/autosuggest-input/index.tsx
src/internal/components/dropdown/__integ__/alignment.test.ts
src/internal/components/dropdown/__tests__/dropdown-fit-handler.test.ts
src/internal/components/dropdown/dropdown-fit-handler.ts
src/internal/components/dropdown/index.tsx
src/internal/components/dropdown/interfaces.ts
src/internal/components/dropdown/styles.scss
src/multiselect/internal.tsx
src/select/internal.tsx

The main change in this PR is allowing the dropdowns of select, multiselect, and autosuggest to expand their width according to their content (up to a pre-defined maximum or 465px). Additionally, there are some other changes that support this new feature:
* Fixed a bug where dropdowns with `expandToViewport={true}` could expand beyond the trigger width (AWSUI-16369)
* Changed `getDropdownPosition` from using (9) positional arguments to using an object as argument
Related links, issue #, if available: AWSUI-19898, AWSUI-16369
<details> …

feat: Allow dropdowns of autosuggest, select, and multiselect to expand beyond their trigger width

---

src/alert/__tests__/alert-analytics.test.tsx
src/alert/index.tsx
src/form-field/__tests__/form-field-analytics.test.tsx
src/form-field/internal.tsx

When a form field with an error is inside an expandable section, it currently emits an error event, even though it is not visible to the user, i.e. the user has not actually encountered the error yet. With this PR, we suppress the error event in that case.
Tested manually in dev pages. This change is very difficult to test in a unit test, because it relies on the browser's layout calculation to determine whether the element is visible. Our simulated browser environment in the unit tests does not provide this information, and mocking that API would leave very little to actually test.
<details> …

chore: Don't report funnel errors for hidden errors

---

pages/progress-bar/with-updates.page.tsx
src/progress-bar/__tests__/progress-bar.test.tsx
src/progress-bar/index.tsx

Existing implementation of the progress assertion assumes that label is a string, which leads to incorrect announcement when ReactNode is passed. 
This fix uses inner text extraction build-in into LiveRegion utility to announce label text 
VO + Safari
Unit test added
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTR …

fix: Progress bar correctly announces text of a formatted label

---

pages/table/sticky-columns.page.tsx
src/table/internal.tsx
src/table/sticky-scrollbar/styles.scss

Follow up from https://github.com/cloudscape-design/components/pull/1305.
We actually want this treatment for all table variants of VR as well.
<details> …

chore: Offset sticky scrollbar when sticky columns are enabled for all table variants

---

src/form/__tests__/analytics.test.tsx
src/form/index.tsx
src/modal/internal.tsx

Before this PR, we only tracked primary button clicks in the `actions` slot of a Form. However, there are some creation flows where the primary button is not in the usual `actions` slot, but somewhere else in the Form.  
With this PR, we track primary buttons anywhere inside the Form. There is an exception for primary buttons in Modals, since that button usually only closes the Modal without submitting anything.
Added a unit test, and tested locally with a dev page.
<details> …

chore: Track primary buttons anywhere in funnels

---

pages/funnel-analytics/nested-funnels.page.tsx
src/alert/__tests__/alert-analytics.test.tsx
src/button/__tests__/internal.test.tsx
src/container/__tests__/analytics.test.tsx
src/expandable-section/__tests__/analytics.test.tsx
src/form-field/__tests__/form-field-analytics.test.tsx
src/form/__tests__/analytics.test.tsx
src/internal/analytics/__tests__/components/analytics-funnel.test.tsx
src/internal/analytics/__tests__/hooks/use-funnel-step.test.tsx
src/internal/analytics/__tests__/hooks/use-funnel.test.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/context/analytics-context.ts
src/link/__tests__/index.test.tsx
src/wizard/__tests__/analytics.test.tsx
src/wizard/index.tsx

This PR adds support for placing funnels inside other funnels (i.e. currently the Form and the Wizard components).
When a Form is placed inside another Form, the inner Form is now ignored.
When a Wizard is placed inside or around a Form, the Wizard now always takes precedence.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/ …

chore: Support nested funnels

---

src/breadcrumb-group/internal.tsx
src/button-dropdown/interfaces.ts
src/button-dropdown/internal.tsx
src/button-dropdown/styles.scss
src/internal/components/menu-dropdown/index.tsx
src/internal/components/menu-dropdown/interfaces.ts
src/test-utils/dom/button-dropdown/index.ts

Made some improvements, prepare to use this API in #1416 
1. Updated the API to make it more convenient to use
2. Added `testUtilsClass` to ensure that ButtonDropdown test-util keeps working even when rendering custom triggers
<details>
- …

refactor: Update customTriggerBuilder internal API

---

pages/table-fragments/grid-navigation-custom.page.tsx
src/table/internal.tsx
src/table/table-role/__tests__/table-role-helper.test.ts
src/table/table-role/table-role-helper.ts

Adding ARIA colcount to make table grid WAI compliant.
Accessibility tests in the pipeline.
<details> …

chore: Add aria-colcount to table grid

---

pages/property-filter/permutations.page.tsx
src/property-filter/index.tsx
src/property-filter/styles.scss

Recently, we made some changes to select filters to place them inside form fields ([see here](https://cloudscape.design/examples/react/table-select-filter.html)). Selects should always come with a visible label, and the placeholder or selected label isn't good enough.
In light of that, we also need to allow users to provide a label for the select inside the property filter's `customControl` slot.
Screenshot tested.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public- …

fix: Improve alignment for property filter custom controls

---

src/app-layout/visual-refresh/split-panel.scss
src/app-layout/visual-refresh/split-panel.tsx

Two fixes, basically:
- Bottom split panel scrolls out the page while it's opening: this was fixed by the suggestion in AWSUI-21941. Seems fair to me; that's what we do in the side panel. Speaking of which...
- Side split panel doesn't animate width: I found this while playing with the demo. Don't know if we accidentally broke this or if it ever worked, but... fixed!
Related links, issue #, if available: AWSUI-21941
Manually - through the Animations panel in Chrome's devtools. Not sure how I'd test animation transition state programmatically.
<details> …

fix: Fix split panel entry animations

---

pages/app-layout/runtime-drawers.page.tsx
pages/app-layout/with-drawers.page.tsx
src/app-layout/__tests__/desktop.test.tsx
src/app-layout/__tests__/drawers.test.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/__tests__/split-panel.test.tsx
src/app-layout/defaults.ts
src/app-layout/drawer/index.tsx
src/app-layout/drawer/interfaces.ts
src/app-layout/drawer/resizable-drawer.tsx
src/app-layout/index.tsx
src/app-layout/utils/use-drawers.ts
src/app-layout/utils/use-resize.tsx
src/app-layout/visual-refresh/context.tsx
src/app-layout/visual-refresh/drawers.tsx
src/app-layout/visual-refresh/mobile-toolbar.tsx
src/app-layout/visual-refresh/tools.tsx

refactor: Deduplicate drawers handling code between classic and refresh implementations

---

src/wizard/__tests__/analytics.test.tsx
src/wizard/index.tsx

When a Wizard emits its `funnelStart` event, that event contains information about which steps are optional. Currently this list uses zero-based indexing, which is inconsistent with e.g. the `stepNumber` property of the `funnelStepStart` event. This PR changes it to be 1-based indexing.
Updated unit test
<details> …

chore: Use 1-based indexing for optional funnel steps

---

src/header/__tests__/header.test.tsx
src/header/internal.tsx

Currently we're attaching the attribute `data-analytics-funnel="substep-name"` to every heading generated by the Heading component. However, these should only be applied to headings of Containers or container-like elements, i.e. second-level headings. This PR updates the Heading component to apply the attribute only on such headings.
Extended unit tests
<details> …

chore: Mark only h2-level headings as substep names

---

src/internal/analytics/__tests__/components/analytics-funnel.test.tsx
src/table/index.tsx

After this change, the Table component is treated as a substep when it comes to funnel metrics, i.e. it is treated like a container. This does not apply to the embedded variants of the Table, because those are expected to already have a container around them.
See also the equivalent change for Cards: https://github.com/cloudscape-design/components/pull/1362
Extended the unit test
<details> …

chore: Mark Table component as a funnel substep

---

pages/side-navigation/app-layout.page.tsx
src/app-layout/__tests__/common.test.tsx
src/app-layout/__tests__/mobile.test.tsx
src/app-layout/__tests__/utils.tsx
src/app-layout/index.tsx
src/app-layout/visual-refresh/context.tsx
src/expandable-section/expandable-section-header.tsx
src/side-navigation/internal.tsx

Reverts cloudscape-design/components#1434. We had some pipeline tests fail.

revert: Revert "fix: Refactor and fix AppLayout and side navigation panel state and behaviour"

---

src/app-layout/__tests__/common.test.tsx
src/app-layout/__tests__/desktop.test.tsx
src/app-layout/drawer/index.tsx
src/app-layout/mobile-toolbar/index.tsx
src/app-layout/toggles/index.tsx
src/app-layout/toggles/interfaces.ts
src/app-layout/visual-refresh/context.tsx
src/app-layout/visual-refresh/drawers.tsx
src/app-layout/visual-refresh/navigation.tsx
src/app-layout/visual-refresh/split-panel.tsx
src/app-layout/visual-refresh/tools.tsx
src/app-layout/visual-refresh/trigger-button.tsx
src/button-dropdown/interfaces.ts
src/button-dropdown/internal.tsx

We weren't properly using `aria-expanded` or `aria-controls` for the triggers in AppLayout. This adds those attributes to drawers, tools, navigation, and split panel when appropriate.
<details> …

fix: Fixes aria expanded and aria controls in AppLayout

---

src/table/internal.tsx
src/table/sticky-scrollbar/__tests__/sticky-scrollbar.test.tsx
src/table/sticky-scrollbar/sticky-scrollbar.tsx

Corrects a regression with the sticky scrollbar. The offset isn't just about the positioning, it's also about the z-index. We can never skip the "offset" for sticky scrollbars because otherwise, the scrollbar would go underneath the sticky columns.
We can separate the z-index and "offset" concerns, but also, we don't really need to. Let's just revert back to the known state. 
Another unit test!
<details>
- _Changes …

fix: Always offset sticky scrollbar if sticky columns are present

---

src/app-layout/visual-refresh/drawers.tsx
src/app-layout/visual-refresh/trigger-button.scss
src/app-layout/visual-refresh/trigger-button.tsx

Quick follow-up to this: https://github.com/cloudscape-design/components/pull/1416
Adding the clip-path removed the box-shadow from drawer triggers.
Before:
After:
<details> …

fix: Adds box shadow back to trigger buttons in drawers

---

src/table/__integ__/inline-editing.test.ts
src/table/body-cell/index.tsx
src/table/body-cell/inline-editor.tsx

When editing a table cell and clicking somewhere outside, the edit mode ended and the edited cell kept focus by purpose. 
Now, if a focusable element got clicked outside during an edit, editing get cancelled and the outside clicked element  receives focus - the focus handling does not get intercepted anymore.
In case of some change are made during editing, the customer is able to intercept and display a modal about unsaved changes.
Related links, issue #, if available: AWSUI-21967
- Added integration test to cover change.
- Verify the changes on the /table/editable page at the recent PR deployment.
<details>
- _Changes …

fix: Click outside focus handling on table inline edit

---

src/table/__tests__/header-cell.test.tsx
src/table/header-cell/index.tsx
src/table/header-cell/th-element.tsx
src/table/header-cell/utils.ts
src/table/internal.tsx
src/table/resizer/index.tsx
src/table/selection-control/index.tsx
src/table/sticky-header.tsx
src/table/thead.tsx

Introduce an element to be shared for all header cells including selection cell needed for the upcoming change: https://github.com/cloudscape-design/components/pull/1480.
<details> …

refactor: Introduce table th element

---

pages/table-fragments/grid-navigation-custom.page.tsx
src/table/__tests__/a11y.test.tsx
src/table/internal.tsx
src/table/table-role/__integ__/grid-navigation.test.ts
src/table/table-role/__tests__/use-grid-navigation.test.tsx
src/table/table-role/grid-navigation.md
src/table/table-role/interfaces.ts
src/table/table-role/table-role-helper.ts
src/table/table-role/use-grid-navigation.ts
src/table/table-role/utils.ts

Made changes to the table grid navigation based on an integration attempt (see https://github.com/cloudscape-design/components/pull/1480).
The main changes are:
* Moving from focused cell to a cell containing one focusable element focuses the element and not the cell itself.
* When focus is inside a widget cell the Tab/Shift+Tab can be used to move focus back to the table.
* The navigation now works when the first data row index is other than 1.
* Updated existing integ test
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/componen …

chore: Table grid nav updates

---

src/date-picker/index.tsx
src/date-range-picker/index.tsx
src/internal/focus-tracker.ts
src/internal/hooks/use-focus-tracker.ts
src/internal/utils/node-belongs.ts

`nodeBelongs` utility already contains check for portals, no need for custom implementation via `viewportId`
This PR is a preparation for `containsOrEqual` removal https://github.com/cloudscape-design/components/pull/1465
PR build ([this test suite](https://github.com/cloudscape-design/components/blob/main/src/date-range-picker/__integ__/events.test.ts) in particular covers the focus tracker functionality)
<details> …

refactor: Reuse nodeBelongs in focus tracker utility

---

src/internal/utils/__tests__/dom.test.ts
src/internal/utils/dom.ts
src/internal/utils/node-belongs.ts

Remove a duplicate of a utility which already exists in the toolkit
PR build
<details>
- _If …

chore: Repalce containsOrEqual with utility from the toolkit

---

pages/app-layout/utils/external-widget.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/utils/use-drawers.ts
src/internal/plugins/controllers/drawers.ts

Support `awsuiPlugins.appLayout.registerDrawer({ defaultActive: true })` to allow opening it on the initial rendering
<details> …

chore: Allow runtime drawers to be open by default

---

src/internal/utils/node-belongs.ts
src/mixed-line-bar-chart/__tests__/mixed-chart.test.tsx

In JSDOM, when calling `element.blur()`, `event.relatedTarget` can be `Document` instance, which has no `dataset` property. 
In real browsers, it is `null` in this case, and works as expected
Related links, issue #, if available: AWSUI-22179
Added an extra unit test
<details>
- _Changes …

fix: JSDOM compatibility in mixed line bar chart

---

src/internal/analytics/hooks/use-funnel.ts

This PR fixes incorrect names in the `funnelSubStepComplete` event.
The names are incorrect when the user has focused a text field and then clicks the button to proceed to the next step. In this situation, the `funnelSubStepComplete` event is emitted after the step transition has happened, and thus the element selectors point to wrong elements now.
To mitigate this, we save the names already at the point where we emit the corresponding start event. This matches the approach we're already taking for the `funnelStepComplete` event: https://github.com/cloudscape-design/components/blob/df04533aa56157985792e1ceb8aaf965a77a193d/src/internal/analytics/components/analytics-funnel.tsx#L231-L255
Manually tested in dev pages
<details> …

chore: Fix names in funnelSubStepComplete event

---

pages/table-fragments/grid-navigation-custom.page.tsx
src/table/table-role/__integ__/grid-navigation.test.ts
src/table/table-role/__tests__/use-grid-navigation.test.tsx
src/table/table-role/grid-navigation.md
src/table/table-role/interfaces.ts
src/table/table-role/table-role-helper.ts
src/table/table-role/use-grid-navigation.ts
src/table/table-role/utils.ts

Updated the grid navigation based on the team's feedback. The "widget" cells are no longer explicitly present, instead - the focus handling is now done uniformly for all cells and elements.
Whenever there is a need to support cell content requiring arrow-based navigation the consumer must ensure the content only becomes fully interactive upon activation, same as the built-in inline editing feature works. The table no longer interferes when the focused element or one of its parents has role="dialog" or data-awsui-table-suppress-navigation="true".
Updated the docs and the test page accordingly.
Updated unit- and integration tests.
<details> …

chore: Table grid navigation replace widget with dialog

---

pages/funnel-analytics/dynamic-multi-page-flow.page.tsx
pages/funnel-analytics/dynamic-single-page-flow.page.tsx
src/form/__tests__/analytics.test.tsx
src/internal/analytics/__tests__/hooks/use-funnel-step.test.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/context/analytics-context.ts
src/internal/analytics/interfaces.ts
src/internal/analytics/selectors.ts
src/wizard/__tests__/analytics.test.tsx

This PR emits the `funnelStepChange` event whenever a funnel step is modified, i.e. when the substeps of the step change.
The events have been added in https://github.com/cloudscape-design/components/pull/1507.
Added unit tests and tested manually in new dev pages.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIB …

chore: Emit `funnelStepChange` events

---

src/table/__integ__/resizable-columns.test.ts
src/table/__tests__/resizable-columns.test.tsx
src/table/resizer/index.tsx

Made resize handles buttons that require activation with Space/Enter before accepting further keyboard input.
Fixed a bug with controlled mode when onWidthChange handler was never called - now it is called upon resize commit with Space/Enter. The operation can also be discarded with Escape.
Updated existing and added new unit- and integration tests. Screenshot tests, dry-run.
<details> …

feat: Table resize handler requires keyboard activation

---

src/__tests__/__snapshots__/design-tokens.test.ts.snap
style-dictionary/visual-refresh/metadata/typography.ts

This change publishes base typography tokens (font size, line height, font weight) for body, heading, and display text styles. These tokens will also be themeable.
Related links, if available: Website: CR-100498948, Demos: CR-10050128, theming-core [#58](https://github.com/cloudscape-design/theming-core/pull/58)
Issue #: [#1330](https://github.com/cloudscape-design/components/issues/1330)
Ran through dev pipeline: AwsUi-v3-katiegeo
<details>
- _Changes do …

feat: Publish themeable typography design tokens

---

pages/table/sticky-columns.page.tsx
src/table/__tests__/body-cell.test.tsx
src/table/body-cell/td-element.tsx
src/table/sticky-columns/__tests__/use-sticky-columns.test.tsx
src/table/sticky-columns/use-sticky-columns.ts

The missing subscription cleanup function caused a memory leak.
ref: AWSUI-22191
New unit test added.
<details> …

fix: Cleanup sticky columns listeners when table cells unmount

---

pages/app/index.tsx
src/app-layout/__integ__/awsui-applayout.test.ts
src/internal/hooks/use-visual-mode/__tests__/use-visual-mode.test.tsx
src/internal/hooks/use-visual-mode/index.ts

When window[Symbol.for('awsui-visual-refresh-flag')] returns true, renders page in VR.
GlobalStyles: 100722878
Updating Dashboard...
<details> …

chore: Add vr class from window symbol value

---

src/internal/components/masked-input/__tests__/masked-input.test.tsx
src/internal/components/masked-input/keyboard-handler.ts

Masked inputs such as date input autocomplete the value basked on the defined mask when the field is blurred or the user presses Enter. However, the input should not autocomplete when its value is empty. This change fixes a bug where pressing Enter in an empty date input would change the value to "2000-01-01".
Related links, issue #, if available: AWSUI-17211
<details> …

fix: Fix date input to no longer autocomplete when it's empty

---

.eslintrc

This PR creates the basic code for using ESLint to check for unsafe usages of the `any` type. It does _not_ enable this rule for any files yet, this will come in later PRs.
<details> …

chore: Add basic linting rules for unsafe `any` usages

---

.eslintrc

Add the `no-explicit-any` rule to the newly added rules of making safe typings.
We'll incrementally add to the files array as we fix the typings for each sub path, like for example, the `src/cards/**`
<details> …

chore: Use no-explicit-any rule

---

pages/container/common.tsx
pages/container/media-side-permutations.page.tsx
pages/container/media-top-permutations.page.tsx
src/__a11y__/axe.ts
src/__tests__/__snapshots__/documenter.test.ts.snap
src/container/interfaces.ts
src/container/styles.scss

We'd like to support automatically scaling the `<iframe>` element as a direct child of the media container. For youtube embeds and such.
Related links, issue #, if available: AWSUI-22100
There are screenshot tests for this styling on images already. ~~Don't know if it's worth adding iframe-specific screenshot tests and scenarios for just `width: 100%; height: 100%`.~~ iframes now have custom styling (removing the border), so added some permutations.
<details> …

feat: Support iframes in container media content

---

pages/funnel-analytics/dynamic-multi-page-flow.page.tsx
pages/funnel-analytics/dynamic-single-page-flow.page.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/wizard/__tests__/analytics.test.tsx
src/wizard/internal.tsx

This PR emits the funnelChange event whenever a funnel is modified, i.e. when the steps of the funnel change.
The events have been added in https://github.com/cloudscape-design/components/pull/1507.
See also https://github.com/cloudscape-design/components/pull/1509 for the related funnel**Step**Change event, which handles changes in substeps rather than in steps.
Manually tested in updated dev page, and added unit tests
<details> …

chore: Emit `funnelChange` events

---

src/app-layout/__tests__/drawers.test.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/index.tsx
src/app-layout/utils/use-drawers.ts
src/app-layout/visual-refresh/context.tsx
src/app-layout/visual-refresh/drawers.tsx

Fixing the case when app layout uses `toolsOpen` controlled mode together with drawers.
It was possible to have double drawers content
Added extra unit tests
<details> …

fix: Handle toolsOpen properly when drawers API is used

---

.eslintrc.js

This PR disables the ESLint rule `react/forbid-component-props`. The rule produces a large amount (479 instances) of warnings that reduce the visibility of more relevant warnings.
<details> …

chore: Disable `react/forbid-component-props` ESLint rule

---

src/internal/components/portal/index.tsx
src/table/__tests__/resizable-columns.test.tsx
src/table/header-cell/index.tsx
src/table/internal.tsx
src/table/resizer/index.tsx
src/table/thead.tsx

When asserting column headers text content is must not include anything but the header text.
Ref: AWSUI-22297
Added a new unit test to secure the property.
<details> …

fix: Resizable columns text content to not include column width

---

src/app-layout/visual-refresh/context.tsx

Fixing a regression from the past PR: https://github.com/cloudscape-design/components/pull/1527/files?w=1#r1319041557
* Locally
* Screenshot tests in my dev pipeline (where this issue was originally found)
<details> …

fix: Update right content gap activation logic

---

src/app-layout/drawer/resizable-drawer.tsx
src/i18n/messages-types.ts
src/i18n/messages/all.de.json
src/i18n/messages/all.en-GB.json
src/i18n/messages/all.en.json
src/i18n/messages/all.es.json
src/i18n/messages/all.fr.json
src/i18n/messages/all.id.json
src/i18n/messages/all.it.json
src/i18n/messages/all.ja.json
src/i18n/messages/all.ko.json
src/i18n/messages/all.pt-BR.json
src/i18n/messages/all.zh-CN.json
src/i18n/messages/all.zh-TW.json
src/internal/components/drawer/__tests__/drawer.test.tsx
src/internal/components/drawer/index.tsx
src/internal/components/drawer/interfaces.ts
src/internal/components/drawer/styles.scss

This is the first step to creating a Drawer component, which will release along with the public release of the drawers changes to the AppLayout. The goal of this PR is to get the code reviewed so that when the time comes to release the component publicly, it is mostly a "flip of a switch" to move the component out of the `internal` folder.
The purpose of the Drawer component is to provide a wrapper for the contents of a drawer, similar to the HelpPanel in the current tools slot or the SplitPanel in the splitPanel slot. It is built as a clone of the HelpPanel component, without the style overrides.
<details> …

chore: Creates internal drawer component

---

src/header/styles.scss

The previous PR for header wrapping improvements (https://github.com/cloudscape-design/components/pull/1386) caused some unexpected regressions in compact mode. This change fixes that.
<details> …

chore: Follow-up fixes for the header wrapping update in compact mode

---

src/app-layout/__tests__/common.test.tsx
src/app-layout/__tests__/desktop.test.tsx
src/app-layout/__tests__/drawers.test.tsx
src/app-layout/__tests__/main.test.tsx
src/app-layout/__tests__/mobile.test.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/drawer/index.tsx
src/app-layout/mobile-toolbar/index.tsx
src/app-layout/utils/use-drawers.ts
src/app-layout/visual-refresh/drawers.tsx

Fixing merge logic between separate tools slot and drawers.
Behavior in the current public API
```js
<AppLayout /> // renders empty tools drawer [1]
<AppLayout tools="content" /> // renders tools drawer with content [2]
<AppLayout toolsHide={true} /> // hides tools drawer
```
How this will change when `drawers` public property is introduced
```js
<AppLayout drawers={[]} /> // renders one drawer for the tools (looks identical to [1] from above)
<AppLayout tools="content" drawers={[]} /> // same as [2] from above
<AppLayout tools="some tools" drawers={[drawer]} /> // renders two drawers, the first one is "tools"
```
Updated existing unit tests and added a few extra ones for corner-cases
<details>
_The following …

chore: Update tools-to-drawer treatment

---

src/form/__tests__/analytics.test.tsx
src/internal/analytics/__tests__/components/analytics-funnel.test.tsx
src/internal/analytics/__tests__/mocks.ts
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/selectors.ts
src/wizard/__tests__/analytics.test.tsx
src/wizard/__tests__/common.tsx
src/wizard/__tests__/wizard.test.tsx
src/wizard/analytics.ts
src/wizard/index.tsx
src/wizard/internal.tsx

Previously, we've included the `stepConfiguration` and `subStepConfiguration` properties in the `funnelChange` and `funnelStepChange` events (https://github.com/cloudscape-design/components/pull/1509, https://github.com/cloudscape-design/components/pull/1511).
With this PR, we also include these properties in the corresponding start event, so that they can be used as a reference when the change events are emitted (otherwise it is difficult to figure out what changed).
Extended unit tests
<details> …

chore: Include stepConfiguration and subStepConfiguration properties in start events

---

src/wizard/styles.scss

Global `li` styles can override styles of the Wizard `li`. this can happen when using different major versions of Cloudscape versions in the same app.
no screenshot failures.
<details> …

fix: reset list item padding in Wizard

---

src/table/__tests__/resizable-columns.test.tsx
src/table/resizer/index.tsx

The resize handle width is set to the element's ARIA label and should be available before the element receives focus as otherwise it reads as `0`.
See 6oM9A1dINc3m
Added new unit test
<details> …

fix: Make resize handle width available before it gets focused

---

pages/app-layout/runtime-drawers.page.tsx
src/app-layout/__integ__/runtime-drawers.test.ts
src/app-layout/__tests__/drawers.test.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/utils/use-drawers.ts
src/app-layout/visual-refresh/drawers.tsx

When drawers API is used `toolsOpen` is ignored. This introduced an issue for controlled mode, which is commonly used to integrate with help panel.
Added extra unit and integration tests
<details> …

fix: Fix controlled tools mode when drawers API is used

---

.github/workflows/release.yml

This extends our existing test sharding to also apply during the release workflow.
See https://github.com/cloudscape-design/.github/pull/57 for the existing sharding.
n/a
<details> …

chore: Shard a11y tests during release workflow

---

src/internal/analytics/__tests__/components/analytics-funnel.test.tsx
src/internal/analytics/components/analytics-funnel.tsx

Add 'cloudscape-creation-flow-done' event when funnelComplete or funnelCancelled. 
<details> …

chore: Emit event when funnelComplete or funnelCancelled

---

src/table/sticky-columns/__tests__/use-sticky-columns.test.tsx
src/table/sticky-columns/utils.ts

The sticky columns feature of the table requires cell references stored in a record. When the table un-mounts, those references are removed. In the`updateCellOffsets` utility the null-check was not implemented correctly: `element.getBoundingClientRect().width ?? 0` instead of `element?.getBoundingClientRect().width ?? 0`. As result, the function is failing when table cells un-mount.
The issue was not observed until the resent fix https://github.com/cloudscape-design/components/pull/1508 for cell references assignment. Before the fix the cleanup never happened so upon un-mounting the record retained all references.
Added a unit test to secure regression.
<details>
- _Changes …

fix: Make table sticky columns util support columns unmount

---

pages/table/resizable-columns.page.tsx
src/table/__integ__/resizable-columns.test.ts
src/table/__tests__/resizable-columns.test.tsx
src/table/header-cell/index.tsx
src/table/internal.tsx
src/table/resizer/index.tsx
src/table/thead.tsx

This change essentially reverts https://github.com/cloudscape-design/components/pull/1492 due to unexpected changes to the columnheader element in the accessibility tree causing failures of those tests querying columns by role.
The original change is to be reintroduced once it is figured out how to make it safer.
See 6oM9A1dINc3m
Added a test featuring getByRole selector.
<details> …

revert: Make table resize handles no longer requiring activation with keyboard

---

src/cards/index.tsx
src/container/__tests__/analytics.test.tsx
src/container/index.tsx
src/container/internal.tsx
src/expandable-section/expandable-section-container.tsx
src/expandable-section/index.tsx
src/expandable-section/internal.tsx
src/internal/analytics/__tests__/components/analytics-funnel.test.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/hooks/use-funnel.ts
src/modal/internal.tsx
src/table/index.tsx
src/table/internal.tsx

chore: Fix funnel support for modals

---

src/table/__tests__/resizable-columns.test.tsx
src/table/header-cell/index.tsx
src/table/resizer/__tests__/resizer-lookup.test.tsx
src/table/resizer/index.tsx
src/table/resizer/resizer-lookup.ts

Fixed the following issues of the table column resizer:
* VO click (VO+Space) triggers is-dragging mode which is not ending as there is no follow-up mouse-up event.
* When resizing with keyboard the aria-valuenow of the separator can be set to below the min-width and become inconsistent with the actual column width value which is validated correctly. 
Besides, removed the non-null assertion operators from the queries done inside the resizer element. 
Added a new unit test to cover the resize below min-size issue.
<details> …

fix: Fix table resizer issues with screen-reader

---

pages/dropdown/min-width.page.tsx
pages/dropdown/width.page.tsx
src/internal/components/dropdown/__integ__/width.test.ts
src/internal/components/dropdown/__tests__/dropdown-fit-handler.test.ts
src/internal/components/dropdown/dropdown-fit-handler.ts
src/internal/components/dropdown/index.tsx
src/internal/components/dropdown/styles.scss
src/internal/generated/custom-css-properties/list.js
src/internal/utils/scrollable-containers.ts

After #1423, dropdowns of the autosuggest, select and multiselect components expand beyond the trigger width, like this:
The problem is, that doesn't account for the available space, so in a narrow viewport or in a narrow container with hidden overflow the dropdown will be cut off:
This is fixed here by opting out of that behavior if it was detected that the the dropdown overflows. So if that would happen, it will _not_ stretch beyond the trigger:
Issue: AWSUI-22328
Added new test page, which I used for both running manual testing and for writing new integration tests.
<details> …

fix: Constrain dropdown width to viewport

---

pages/dropdown/width.page.tsx
src/internal/components/dropdown/__integ__/width.test.ts

A leftover `useEffect` was interfering with tests, causing flakiness.
Also, correctly set `loading` back to `asyncLoading` instead of `false` when closing the dropdown, so that it the page state is correctly reset to its initial state also when `asyncLoading` is `true`.
- Ran the integration tests 3 times, all successfully
- Manually tested the page to make sure it keeps behaving as expected.
<details> …

chore: Fix test page and flaky test

---

pages/button-dropdown/permutations-main-action.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/button-dropdown/__tests__/button-dropdown.test.tsx
src/button-dropdown/interfaces.ts
src/button-dropdown/internal.tsx

Instead of only allowing main actions for primary button dropdown, it can now also be used for the "normal" variant.
<details> …

feat: Allow button dropdown with "normal" variant to define a main action

---

src/table/sticky-scrollbar/sticky-scrollbar.tsx
src/table/sticky-scrollbar/styles.scss
src/table/sticky-scrollbar/use-sticky-scrollbar.ts

When toggling the sticky columns preference back and forth, the sticky scrollbar disappears. 
This fixes it.
Related issue: AWSUI-22340
<details> …

fix: Make useStickyScrollbar hook react to offset prop

---

src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/internal.tsx
src/internal/components/dropdown/index.tsx
src/internal/components/dropdown/styles.scss

When focusing the autosuggest input field on the ["No suggestions" example](https://cloudscape.design/components/autosuggest/?tabId=playground&example=no-suggestions) without an `empty` text, you can see the undesired collapsed border. This is because even when there is no suggestions and no empty text, we still render the dropdown content. This is a regression from Classic.
Customers need this to use Autosuggest to build a search experience. We want to support this use case, extending the component's guidelines to reflect it.
This PR adds an `shouldRenderDropdownContent` condition to the autosuggest component. This was needed because there were empty wrapper nodes passed on to the dropdown, even though there was no actual content inside of them.
This allows us to apply the correct …

fix: Don't display dropdown border when there is no content on autosuggest in VR

---

src/app-layout/__tests__/desktop.test.tsx
src/app-layout/drawer/index.tsx
src/app-layout/drawer/styles.scss
src/app-layout/index.tsx

A single drawer acted slightly different than tools - the entire bar was not clickable (only the icon), and it would keep the trigger bar visible when opened. This PR adjusts those two features so that a single drawer now acts the same as tools. 
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-s …

feat: Mimics tools behavior when there is only one drawer

---

src/table/sticky-scrollbar/styles.scss

Re-added the margin that was necessary for avoiding sticky scrollbar overlap with interactive elements on a VR compact mode table.
This regression was introduced here: https://github.com/cloudscape-design/components/pull/1554/files#diff-b75a1d7e7c07f45b0c5b02301c632dc0cd30bc15c824eb2d951d1f697cd22803L41-L43 and caught on visual regression tests.
dev-v3-rucarva pipeline screenshot tests
<details> …

chore: Re-add margin for VR sticky-scrollbar when offset

---

pages/autosuggest/recovery-test.page.tsx
src/autosuggest/__tests__/i18n.test.tsx
src/autosuggest/internal.tsx
src/internal/components/dropdown-status/__tests__/dropdown-status.test.tsx
src/internal/components/dropdown-status/index.tsx
src/multiselect/__tests__/i18n.test.tsx
src/multiselect/__tests__/multiselect.test.tsx
src/multiselect/internal.tsx
src/property-filter/property-filter-autosuggest.tsx
src/select/__tests__/i18n.test.tsx
src/select/internal.tsx

We missed couple of properties when implementing i18n 
Related links, issue #, if available: AWSUI-22320
New `i18n` unit tests added
<details> …

fix: Use recoveryText from i18n provider in Select

---

src/pie-chart/__tests__/__snapshots__/utils.test.tsx.snap
src/pie-chart/__tests__/utils.test.tsx
src/pie-chart/labels.tsx
src/pie-chart/utils.ts

Distributes pie charts labels to better occupy available space by:
- Positioning them in a circle around the chart, as opposed to aligning them on the right/left
- Pushing them as much as possible to the top or bottom of the chart, were there is more horizontal space to display the labels
Locally and through internal pipeline
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/componen …

feat: Optimize space occupation of pie charts titles

---

pages/autosuggest/permutations-async.page.tsx
pages/multiselect/screenshot.page.tsx

We changed the logic of rendering retry button because of i18n fallback. Assuming that retry button should always have a callback, it should now be provided in order to render a button.
This PR adds missing callbacks to permutation pages
Related links, issue #, if available: -
<details> …

test: Add recovery handler to fix screenshots

---

pages/property-filter/split-panel-app-layout-integration.page.tsx
src/internal/components/autosuggest-input/index.tsx
src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/property-filter-autosuggest.tsx

The empty state of the property filter must be shown when no properties are available. The issue was in autosuggest-input not showing the dropdown when there is no content while the empty state is defined in a footer instead.
New unit tests
<details> …

fix: Property filter empty state visible when no properties

---

src/autosuggest/internal.tsx

Fixes a merge issue between https://github.com/cloudscape-design/components/pull/1574 and https://github.com/cloudscape-design/components/pull/1567 changes.
The dropdown footer must not render when its content is null. This is used by the autosuggest-input internal component to not show the dropdown.
Existing unit tests capture the change
<details> …

fix: Do not render autosuggest dropdown footer when it is empty

---

pages/property-filter/permutations.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/index.tsx
src/property-filter/interfaces.ts
src/property-filter/styles.scss
src/test-utils/dom/property-filter/index.ts

Add new `customFilterActions` slot for property filter. This is necessary for the new saved filter set pattern.
Related links, issue #, if available: `p5G3AYbjkFXK`, AWSUI-19066
<details> …

feat: Add `customFilterActions` slot to property filter

---

src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/__tests__/utils.tsx
src/app-layout/mobile-toolbar/index.tsx

Fixing a bug where `jest.mock` did not mock `useMobile` and `useVisualRefresh` properly
Added an acid test to ensure that the mocks apply correctly
<details> …

chore: Fix incorrect mock application in app layout tests

---

src/app-layout/visual-refresh/drawers.scss
src/app-layout/visual-refresh/drawers.tsx

The slider of drawers didn't line up vertically with the slider of split panel.
Before:
After:
Also, the drawer was animated both in and out, which didn't match the navigation on the other side. This removes the animation out so that the two match. There is a separate issue with the animation that creates lag in certain scenarios, but since that is a more complex fix, this is a holdover for the launch of drawers until that bug can be fixed.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/ma …

fix: Aligns drawers slider to split panel and matches side nav animation

---

pages/app-layout/with-drawers.page.tsx

Adds Split Panel url params so that we can add a screenshot test with an open split panel and open drawers.
See https://github.com/cloudscape-design/components/pull/1587 for additional context.
<details> …

fix: Adds split panel url params

---

pages/app-layout/with-drawers-empty.page.tsx
src/app-layout/__tests__/drawers.test.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/drawer/index.tsx
src/app-layout/index.tsx
src/app-layout/mobile-toolbar/index.tsx
src/app-layout/utils/use-drawers.ts
src/app-layout/visual-refresh/context.tsx
src/app-layout/visual-refresh/drawers.tsx
src/app-layout/visual-refresh/layout.tsx
src/app-layout/visual-refresh/mobile-toolbar.tsx
src/app-layout/visual-refresh/tools.tsx

Implement this proposal: ZuAXAsmOsora
* Updated related tests and added new dev pages for discovered corner-case
* Run screenshot tests in my dev pipeline
<details> …

chore: Disable implicit tools integration into drawers list

---

pages/app-layout/with-drawers.page.tsx

Follow up for #1581. With that change, tools are now ignored on this page.
Opened the page locally, it works
<details> …

chore: Remove tools from drawers page

---

pages/app-layout/utils/external-widget.tsx
src/app-layout/__integ__/runtime-drawers.test.ts
src/app-layout/__tests__/desktop.test.tsx
src/app-layout/__tests__/drawers.test.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/__tests__/utils.tsx
src/app-layout/utils/use-drawers.ts

Fixing a bug where `drawerItem.onResize` was not called
Added extra tests
<details>
- _If the …

chore: Fix missing drawer resize handler

---

src/date-range-picker/__tests__/date-range-picker.test.tsx
src/date-range-picker/index.tsx

The form field wrapper should only auto-label the trigger, and not indiscriminately extend out to every input inside the dropdown. This cancels out the form field context around the dropdown.
Related links, issue #, if available: AWSUI-22471
Added tests.
<details> …

fix: Don't pass through form field context to inputs in date range picker dropdown

---

src/header/internal.tsx
src/header/styles.scss

The issue raised was that double-clicking on the last word of the heading also selects an adjacent info link. This happens because there's no text node space between the two words, only a margin. If we just "break" the inline flow with something like `inline-flex`, it's a quick hack to easily resolve this without visual differences or even worse hacks.
Related links, issue #, if available: AWSUI-22380
Browser heuristic thing (sorta), so as long as it works once and doesn't affect screenshots, no JS tests are needed.
<details> …

fix: Exclude info link when double-clicking header for selection

---

src/app-layout/__integ__/app-layout-drawers.test.ts
src/app-layout/__integ__/runtime-drawers.test.ts
src/app-layout/__tests__/desktop.test.tsx
src/app-layout/__tests__/drawers.test.tsx
src/app-layout/__tests__/mobile.test.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/drawer/index.tsx
src/app-layout/mobile-toolbar/index.tsx
src/app-layout/test-classes/styles.scss
src/app-layout/visual-refresh/drawers.tsx
src/test-utils/dom/app-layout/index.ts

As part of moving drawers from beta to public, we made the decision to change the name of `findDrawersSlider` to `findActiveDrawerResizeHandle`. We also decided `findDrawersDesktopTriggersContainer` and `findDrawersMobileTriggersContainer` were unnecessary and added bloat, so I removed the instances of those and refactored the tests that used them.
<details> …

chore: Updates drawers tests

---

src/date-range-picker/index.tsx

Warn about this being missing only if relative ranges are actually enabled
Related links, issue #, if available: AWSUI-22546
Tested locally
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/acce …

fix: Warn about missing `formatRelativeRange` only when relevant

---

pages/app-layout/with-drawers.page.tsx
src/app-layout/__tests__/drawers.test.tsx
src/app-layout/__tests__/utils.tsx
src/app-layout/drawer/index.tsx
src/app-layout/drawer/interfaces.ts
src/app-layout/index.tsx
src/app-layout/mobile-toolbar/index.tsx
src/app-layout/utils/use-drawers.ts
src/app-layout/visual-refresh/context.tsx
src/app-layout/visual-refresh/drawers.tsx

During the Drawers Bug Bash, it was discovered that the overflow drawer button does not communicate it's badged state. In order to communicate this, a small API change was required to add an additional aria label in this case.
<details>
- …

fix: Adds aria label for badge on overflow drawers

---

src/input/__tests__/input.test.tsx
src/input/internal.tsx

Currently when using Input inside FormField, `aria-labelledby` is always being set from FormField context. Because `aria-labelledby` has precedence over `aria-label` in accessible name calculation, it's not possible to use `aria-label` on Input to add additional context.
Related links, issue #, if available: AWSUI-22502
New tests added
<details> …

feat: Make Input aria-label available when using FormField

---

src/app-layout/__tests__/desktop.test.tsx
src/app-layout/__tests__/mobile.test.tsx
src/app-layout/drawer/index.tsx
src/app-layout/mobile-toolbar/index.tsx
src/app-layout/visual-refresh/drawers.tsx

Part of Drawers Bug Bash. 
`role=toolbar` and `aria-orientation` were added to the desktop versions of drawers, but not mobile. This adds them to mobile, and makes sure all 4 versions (classic / vr, mobile / desktop) match:
```
<aside aria-label="Drawers" role="region">
<div role="toolbar" aria-orientation="horizontal/ vertical">
...
</div>
</aside>
```
The `role="region"` was a suggestion by the accessibility team, since asides should not be children of `main`s without it.
<details> …

fix: Adds correct toolbar aria label to mobile and matches desktop

---

src/app-layout/__tests__/mobile.test.tsx
src/app-layout/index.tsx
src/app-layout/visual-refresh/context.tsx

Fixed a bug where open drawer allowed to focus and scroll the main page content rendered underneath 
Replicated existing tests we had for the same feature in tools 
<details> …

chore: Apply no-focus and no-scroll classes when drawer opens on mobile

---

src/app-layout/__integ__/app-layout-drawers.test.ts
src/app-layout/visual-refresh/drawers.tsx

From Drawers Bug Bash.
No min-width on drawers caused situations like this on small screens:
Added a min-width of 290 for feature parity with tools.
It should be noted that situations like this can still happen, which isn't ideal, but should be handled holistically:
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRI …

fix: Adds min-width to drawer

---

pages/table/sticky-header-with-actions.page.tsx
src/table/sticky-scrollbar/styles.scss

The table's sticky header, which houses elements with a dropdown (e.g.: Select or ButtonDropdown), has a `position: sticky` and a `z-index: 800`. This conflicts with the horizontal scrollbar's z-index (also 800), causing the dropdown options to hide behind the scrollbar.
Related links, issue #, if available: AWSUI-22618
Added screenshot tests: CR-103247561
<details> …

chore: Update sticky-scrollbar z-index to avoid conflict with sticky header

---

src/split-panel/side.tsx
src/split-panel/styles.scss

Replace an `hr` with borders for improved consistency across different split panel variants/positions.
Related links, issue #, if available: AWSUI-22580
Visual regression tests
<details> …

fix: Remove unnecessary <hr> in split panel

---

pages/app-layout/with-drawers.page.tsx
src/app-layout/__integ__/app-layout-drawers.test.ts
src/app-layout/visual-refresh/main.scss
src/app-layout/visual-refresh/main.tsx

From Drawers Bug Bash.
An open drawer wasn't pushing over the content when `disableContentPaddings` was true. This updates the logic in the main file and adds an appropriate integration test.
<details> …

fix: Pushes content over when drawer opens, and adds test

---

pages/app-layout/runtime-drawers.page.tsx
pages/app-layout/with-drawers.page.tsx
src/app-layout/__integ__/runtime-drawers.test.ts
src/app-layout/visual-refresh/context.tsx

From Drawers Bug Bash.
With both tools and drawers, having both tools and a side split panel open simultaneously was not allowing for adequate resize of split panel.
This merges the variables into a single variable when calculating the max width of the split panel, so that the two function the same.
<details> …

fix: Fixes scroll discrepencies between drawer and tools

---

pages/table/sticky-header-with-actions.page.tsx

There was a missing `.screnshot-area` on the test page.
<details> …

chore: Add ScreenshotArea to table sticky-header test page

---

src/form/__tests__/analytics.test.tsx
src/form/index.tsx
src/internal/analytics/components/analytics-funnel.tsx
src/internal/analytics/context/analytics-context.ts
src/internal/analytics/hooks/use-funnel.ts
src/internal/analytics/interfaces.ts
src/modal/internal.tsx

We saw two issues with the funnel names reported by some customers that were either 1. reporting incorrectly due to asynchronously render their breadcrumbs for various reasons or 2. using a modal with an embedded form would use the breadcrumb as its funnel name which might be unrelated to the modal contents (e.g. Feedback dialogs). 
This PR tries to improve this for Forms by allowing it to rather prefer using the Form Header slot instead of the breadcrumb and for Modals it introduces a new context where it can provide the preferred funnel name selector to the Funnel.
New behaviour:
- Forms will now default to the Form Header slot instead of Breadcrumb
- Forms inside a Modal will default to the Modal Header instead of Breadcrumb
Updated unit tests …

chore: Change default Funnel Name selector for Forms and Modals

---

src/container/internal.tsx
src/expandable-section/expandable-section-container.tsx
src/expandable-section/index.tsx
src/expandable-section/internal.tsx
src/internal/context/modal-context.ts
src/modal/internal.tsx
src/table/internal.tsx

Additional div around the modal was initially used to associate the HTML node used by the Portal which would later be used to check from funnel step focus by checking if a focussed element is a descendant of this node. This information is useful to understand if a user is still on the same step when opening a modal from a form element in that given step, e.g. an s3 resource selector. However the additional div caused a layout shift. 
We do not have a strong use case for embedded funnels inside a modal as they are primarily either a Form or Wizard and so we can ignore further interactions in this and change if new data is presented.
This change:
- Reverts/refactors some code made in [1494](https://github.com/cloudscape-design/components/pull/1494)
- Adds a modal context so that funnel …

chore: Remove additional div from Modal

---

pages/app-layout/with-drawers.page.tsx
src/app-layout/visual-refresh/drawers.scss
src/app-layout/visual-refresh/drawers.tsx

From Drawers Bug Bash.
The Drawers slider was scrolling up with long content, instead of being sticky like the split panel. This moves the slider out of the scrollable content area and reworks the grid.
This also adds scrolling content to the test page.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#bro …

fix: Positions drawer slider so that it does not scroll with content

---

pages/pie-chart/fit-height.page.tsx
src/pie-chart/constants.scss
src/pie-chart/styles.scss
src/pie-chart/utils.ts

Adjusted the min size calculation for the pie chart when fit-height is used to achieve better responsiveness.
Currently, the min-height is set for the pie chart to give enough space for the labels to render. More often than not, the labels take much less space which results in lots of empty space around the chart and despite that empty space a scrollbar is added if the container content height is below 196px.
The adjusted values to calculate the min-height neglect the labels and allow for the radius to shrink but not below the hard limit of 30px. That allows to fit the charts much better (can now fit into 140px w/o adding a scrollbar while previously it couldn't fit into 180px).
Screenshot tests
<details> …

fix: Pie chart is better optimised for fit-height

---

src/split-panel/styles.scss

Fix some small alignment issues between split panel and help panel/other drawers
Related links, issue #, if available: Follow-up to #1620
Tested locally
<details> …

fix: Ensure split panel heading styling matches other drawers

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/property-filter/__tests__/property-filter.test.tsx
src/property-filter/controller.ts
src/property-filter/index.tsx
src/property-filter/interfaces.ts

Added new operator "^" (starts with) to the list of supported operators. Added a new translation label for it.
Related links: AWSUI-20384
New tests for applied translations. The actual filtering is performed by the collection-hooks.
<details> …

feat: New operator 'starts-with' in property filter

---

pages/date-range-picker/common.ts
src/__tests__/__snapshots__/documenter.test.ts.snap
src/date-range-picker/__tests__/date-range-picker.test.tsx
src/date-range-picker/__tests__/i18n-strings.ts
src/date-range-picker/interfaces.ts
src/date-range-picker/mode-switcher.tsx

Mode switcher in Date range picker is a toolbar and, therefore, should have an accessible name that describes it. We need to pass a string to `label` property of the segmented control used for the mode switcher
Related links, issue #, if available: AWSUI-22536
new unit test added
<details> …

feat: Add accessible name to mode switcher in Date range picker

---

pages/app-layout/runtime-drawers-imperative.page.tsx
pages/app-layout/runtime-drawers.page.tsx
src/app-layout/__integ__/runtime-drawers-controllability.test.ts
src/app-layout/__integ__/runtime-drawers.test.ts
src/app-layout/__tests__/main.test.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/drawer/index.tsx
src/app-layout/drawer/interfaces.ts
src/app-layout/drawer/resizable-drawer.tsx
src/app-layout/index.tsx
src/app-layout/utils/use-drawers.ts
src/app-layout/visual-refresh/context.tsx
src/app-layout/visual-refresh/drawers.scss
src/app-layout/visual-refresh/drawers.tsx

In a single-drawer (tools only) mode, app layout renders `tools` slot content even when it is closed. Some teams are relying on this. When rendering multiple drawers we tried to render only the active one, but this broke compatibility.
This PR restores compatibility, we now always keep the tools content in the DOM, only hide it when it is closed
Added a dev page `pages/app-layout/runtime-drawers-imperative.page.tsx` to reproduce this case and added several unit tests to capture this behavior
<details> …

fix: Render a hidden copy of tools drawer for compatibility when drawers are used

---

src/anchor-navigation/use-scroll-spy.tsx
src/table/internal.tsx
src/table/sticky-columns/use-sticky-columns.ts
src/table/thead.tsx
src/table/use-column-widths.tsx

Moving column width related logic loser together. It is a step towards resolving the issue visible with React 18 when containerWidth changes in an effect causing the auto width to be calculated one render too late. As result the last column can be resized below its min width for a short while.
<details> …

refactor: Column auto width is set in column widths utils

---

pages/expandable-section/common.tsx
pages/expandable-section/container-variant.permutations.page.tsx
pages/expandable-section/simple.page.tsx
src/header/internal.tsx
src/header/styles.scss

When an element with a height smaller than button's height is provided to `headerActions` slot, it makes header vertical padding asymmetric.
Related links, issue #, if available: AWSUI-22377
New permutation added, waiting for screenshots in dev pipeline 
<details> …

fix: Fix alignment for header with non-interactive elements in actions

---

src/anchor-navigation/use-scroll-spy.tsx
src/table/internal.tsx
src/table/sticky-columns/use-sticky-columns.ts
src/table/thead.tsx
src/table/use-column-widths.tsx

This reverts commit 26a79cebae573b14e95fd6953aba60f63b4f52d7.
Reverting as causing regression in screenshot tests
<details> …

revert: Column auto width is set in column widths utils (#1638)

---

src/breadcrumb-group/__integ__/breadcrumb-group.test.ts
src/breadcrumb-group/__tests__/breadcrumb-group.test.tsx
src/breadcrumb-group/__tests__/breadcrumb-item.test.tsx
src/breadcrumb-group/internal.tsx
src/breadcrumb-group/item/item.tsx

Desktop viewport breadcrumbs has a data attribute for to identify a potential funnel name. In a mobile viewport a different node is rendered and this data attribute was missing.
Changes made:
- Small refactor to name these at attributes related to funnels. This is done as the attributes are applied to the inner most text span instead of the root breadcrumb item element and it might have been confusing to not find your data attributes there.
- These specific funnel data attributes are now applied to both desktop and mobile versions of the breadcrumbs
- Updated unit test
<details> …

chore: Apply funnel name data attribute to mobile breadcrumbs

---

src/autosuggest/__tests__/autosuggest.test.tsx
src/autosuggest/internal.tsx
src/multiselect/__tests__/multiselect.test.tsx
src/multiselect/internal.tsx
src/select/__tests__/select.test.tsx
src/select/internal.tsx

Include warning to make it clearer that `recoveryText` is only displayed if an `onLoadItems` function is provided
Tested locally
<details> …

chore: Add dev warning if recovery text provided without function

---

src/__tests__/__snapshots__/documenter.test.ts.snap
src/progress-bar/__tests__/progress-bar.test.tsx
src/progress-bar/index.tsx
src/progress-bar/interfaces.ts
src/progress-bar/internal.tsx

Does what it says on the tin. People could provide visual labels through the `label` property, but it turns out in some contexts, like inside a table cell, the visual label itself doesn't provide enough context. So additional programmatic context needs to be added. This allows for that.
Related links, issue #, if available: AWSUI-22557
Unit tests!
<details> …

feat: Add ariaLabel and ariaLabelledby to progress bar

---

src/button-dropdown/styles.scss

The padding for the button dropdown with main action looked a little bit unbalanced. This change fixes that problem.
Related links, issue #, if available: AWSUI-22498
<details> …

chore: Update padding for button dropdown with main action

---

.github/workflows/build-lint-test.yml
.github/workflows/bundle-size.yml
.github/workflows/dry-run.yml
.github/workflows/lint-pr.yml
.github/workflows/release-gh-notes.yml
.github/workflows/release.yml
.github/workflows/visuals.yml

This PR switches to the new shared repository for GitHub workflows and actions: https://github.com/cloudscape-design/actions.
For the most recent changes to the shared workflows, see https://github.com/cloudscape-design/actions/pull/1. The new configuration was successfully tested in this Draft PR: https://github.com/cloudscape-design/components/pull/1672.
<details> …

chore: Switch to new actions repo for workflows

---

src/internal/components/dropdown/index.tsx

Alternative fix to https://github.com/cloudscape-design/components/pull/1669, without caching anything.
Ticket: AWSUI-22613
Note: dropdowns do not expand beyond the trigger width when virtual scroll is enabled. This is a known issue: AWSUI-22357
- Successful dry-run build to same failing package as in https://github.com/cloudscape-design/components/pull/1669. The build time is similar (11m 47s then, 12m 35s now)
- Manually tested against existing page `dropdown/width` (which also has [integration tests](https://github.com/cloudscape-design/components/blob/main/src/internal/components/dropdown/__integ__/width.test.ts))
<details>
- _Changes include appropriate documentation …

fix: Adjust dropdown width only on resize

---

src/date-range-picker/__tests__/date-range-picker.test.tsx
src/date-range-picker/index.tsx

The trigger for the date range picker doesn't include the selected value. So screen reader users will be unable to tell what the selected date is. This is also something we do in other components like selects.
Related links, issue #, if available: AWSUI-22616
Unit tests!
<details>
- …

fix: Add currently selected value to date range picker's trigger label

---

pages/status-indicator/permutations.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/status-indicator/internal.tsx
src/status-indicator/styles.scss

Fixes #1643.
Since warning yellow was added to the system in #1340, it only makes sense that this color can be used as color override for status indicators.
- Added permutation to existing permutations page, verified the result visually
- Verified that the BackstopJS failures are as expected
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browse …

feat: Add yellow value to status indicator colorOverride prop

---

pages/table/resizable-columns-rounding.page.tsx
pages/table/resizable-columns.page.tsx
src/table/__integ__/resizable-columns.test.ts
src/table/internal.tsx
src/table/styles.scss
src/table/thead.tsx

In VR styles container can have paddings (those are actually applied to the table element). The paddings must be considered when compared container width against table width - otherwise the isScrollable state is applied 40px later. It also causes the last column resizer to not auto-scroll the container.
Before fix (see how the last column is getting smaller than its min-width before container scroll applies):
https://github.com/cloudscape-design/components/assets/20790937/d7808de6-1a73-478a-bf50-fbcf7380ebbf
After fix:
https://github.com/cloudscape-design/components/assets/20790937/3e08a81d-6412-46d4-b995-0ba10e684a53
Added an integration test for regression.
<details>
- …

fix: Consider container paddings in table calculations

---

pages/funnel-analytics/mock-funnel.ts
pages/funnel-analytics/static-single-page-flow.page.tsx
pages/s3-resource-selector/main.page.tsx
pages/s3-resource-selector/shared.tsx
src/internal/analytics/__integ__/static-single-page-flow.test.ts

This adds tests for the existing behaviour. It includes some fix mes that were found while writing and is intended as a start to testing.
<details> …

chore: Add integ tests for single page funnels

---

pages/table/resizable-columns-rounding.page.tsx
pages/table/resizable-columns.page.tsx
src/table/__integ__/resizable-columns.test.ts
src/table/internal.tsx
src/table/styles.scss
src/table/thead.tsx

This reverts commit 03b08a68756aada14d3a3cb2066b2f9515e53658.
Reverting as of causing regression on sticky empty state placement.
<details> …

revert: Consider container paddings in table calculations (#1650)

---

src/flashbar/collapsible-flashbar.tsx
src/flashbar/common.tsx
src/flashbar/non-collapsible-flashbar.tsx

The class `flash-with-motion` makes a flashbar flash enter or leave with animations, based on `.enter` and `.leave` suffixes that React Transition adds when the element enters or leaves: see https://github.com/cloudscape-design/components/blob/main/src/flashbar/motion.scss.
In #1656, I merged the logic to apply this class in the collapsible and non-collapsible versions of the flashbar but it turns out, there is a subtle difference:  in the non-collapsible flashbar these animations only play in Visual Refresh, but in the collapsible flashbar they are supposed to play not only in Visual Refresh but also in Classic, and it should stay like that.
Disabling React-Transition-based enter and leave animations for Classic had the following unintended consequences in Classic:
1. The enter animation …

fix: Fix last item of collapsible flashbar not being dismissible

---

pages/funnel-analytics/mock-funnel.ts
pages/funnel-analytics/static-multi-page-flow.page.tsx
src/internal/analytics/__integ__/static-multi-page-create.test.ts
src/internal/analytics/__integ__/static-single-page-flow.test.ts

Similar to this [PR](https://github.com/cloudscape-design/components/pull/1671) to add for integ tests for single page.
This adds tests for the existing behaviour. It includes some fix mes that were found while writing and is intended as a start to testing.
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md …

chore: Add integ tests for multi page create funnel metrics

---

pages/table/resizable-columns-rounding.page.tsx
pages/table/resizable-columns.page.tsx
src/table/__integ__/resizable-columns.test.ts
src/table/empty-state-cell.tsx
src/table/internal.tsx
src/table/node-data-cell.tsx
src/table/styles.scss
src/table/thead.tsx

This is the re-introduction of https://github.com/cloudscape-design/components/pull/1650 that was reverted due to a regression in empty state.
The sticky empty state cell requires its width to be explicitly set as container width plus table paddings. Previously the paddings were always included and not those are have to be taken care of explicitly.
<details> …

fix: Consider container paddings in table calculations (2)

---

pages/app-layout/with-drawers.page.tsx
src/app-layout/__tests__/desktop.test.tsx
src/app-layout/__tests__/drawers.test.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/__tests__/utils.tsx
src/app-layout/drawer/__tests__/drawers-helpers.test.ts
src/app-layout/drawer/drawers-helpers.ts
src/app-layout/drawer/index.tsx
src/app-layout/drawer/interfaces.ts
src/app-layout/drawer/overflow-menu.tsx
src/app-layout/drawer/resizable-drawer.tsx
src/app-layout/index.tsx
src/app-layout/interfaces.ts
src/app-layout/mobile-toolbar/index.tsx
src/app-layout/runtime-api.tsx
src/app-layout/utils/use-drawers.ts
src/app-layout/utils/use-resize.tsx
src/app-layout/visual-refresh/context.tsx
src/app-layout/visual-refresh/drawers.tsx
src/internal/plugins/controllers/drawers.ts

Preparing to make `<AppLayout drawers={[...]}>` API public. The final api shape is different than our beta version, so this PR updates all internal usage of this object and adds a converter step to support two APIs same time to give beta consumers some time to migrate
* PR build
* Preview deployment for manual testing
* Screenshot tests in my dev pipeline
<details> …

chore: Update drawers object shapes to public API

---

pages/token-group/index.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/token-group/interfaces.ts
src/token-group/internal.tsx
src/token-group/styles.scss

The token group component comes with some top padding by default, which is going against general expectations from components in the system. This was an oversight during the development of the component. However, simply removing the padding now would be a breaking change. Instead, we're adding a new property, `disableOuterPadding`, which removes the outer padding so that Token group becomes a more flexible building block.
Related links, issue #, if available: AWSUI-22994
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBU …

feat: Add `disableOuterPadding` property to Token group component

---

src/mixed-line-bar-chart/chart-container.tsx

The mixed line-bar chart goes through a few render cycles in order to make some necessary calculations: only once it has rendered once it knows the container width, which is needed for calculating the maximum space available for the left labels. And after one more render we know the space that the left labels actually take.
Before the first render, the container width has a fallback assigned width of 500. If the actual size after render is smaller, this can lead to a situation where the calculated size for the plot (`plotWidth`) is negative until `leftLabelsSize` is updated in the next render. This does not produce visible artifacts but renders errors in the console for one render cycle.
This is fixed here by using the minimum of `leftLabelSize` and `maxLeftLabelSize`, as we already know …

fix: Improve space management logic in mixed line-bar chart

---

pages/token-group/index.page.tsx

Add missing ScreenshotArea wrapper for a token group screenshot testing page.
<details>
- _If …

chore: Add missing ScreenshotArea

---

src/app-layout/visual-refresh/context.tsx

Removing an unnecessary effect fixes the issue.
Ticket: AWSUI-22632
- Ran through my pipeline, including Lighthouse tests
- Manually tested the "Delete modal" example page. I can only reproduce the issue on the old host and not in the new one, even with CPU throttling at 6x
<details>
- …

fix: Prevent notifications slot in App layout from flickering in React 18

---

src/area-chart/__integ__/area-chart.test.ts
src/area-chart/__integ__/page-objects/area-chart-page.ts
src/area-chart/chart-container.tsx
src/area-chart/elements/chart-popover.tsx
src/area-chart/model/use-chart-model.ts
src/internal/components/chart-popover/index.tsx
src/mixed-line-bar-chart/__integ__/mixed-line-bar-chart.test.ts
src/mixed-line-bar-chart/chart-container.tsx
src/mixed-line-bar-chart/chart-popover.tsx
src/pie-chart/__integ__/pie-chart.test.ts
src/pie-chart/pie-chart.tsx

Since custom content is supported in chart popovers via `detailPopoverFooter`, it is possible to insert interactive elements, such as links and buttons, in a chart popover. In such a case, it is possible to navigate into a chart popover with the keyboard, even without necessarily pinning it. However, there were a couple issues when navigating inside the popover without pinning it:
- In bar, line, mixed line-bar and pie charts, the popover would stay open when navigating away. This can be especially problematic if the popover is tall, since it could be covering focused legend items below.
- In area charts, it was not possible to navigate inside the popover by tabbing. When doing so, the popover would close.
This PR fixes these two issues and establishes one single behavior for all graphs …

fix: Close chart popover when focus moves away

---

pages/cards/selection.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/cards/__tests__/selection.test.tsx
src/cards/index.tsx
src/cards/interfaces.tsx

This change introduces a new property for Cards that allows the entire card to be clickable to make a selection. This is helpful when selection is a main use-case for this instance of Cards, and there are no other interactive elements in the cards sections.
Related links, issue #, if available: AWSUI-14894, `InohAwVWe3aI`
<details>
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/b …

feat: Allow Cards selection by clicking anywhere on the card with `entireCardClickable` property

---

pages/app-layout/runtime-drawers.page.tsx
pages/app-layout/utils/drawers.tsx
pages/app-layout/with-beta-drawers.page.tsx
pages/app-layout/with-drawers-empty.page.tsx
src/__tests__/__snapshots__/documenter.test.ts.snap
src/app-layout/__tests__/common.test.tsx
src/app-layout/__tests__/desktop.test.tsx
src/app-layout/__tests__/drawers.test.tsx
src/app-layout/__tests__/main.test.tsx
src/app-layout/__tests__/mobile.test.tsx
src/app-layout/__tests__/runtime-drawers.test.tsx
src/app-layout/__tests__/utils.tsx
src/app-layout/drawer/index.tsx
src/app-layout/drawer/interfaces.ts
src/app-layout/drawer/overflow-menu.tsx
src/app-layout/index.tsx
src/app-layout/interfaces.ts
src/app-layout/mobile-toolbar/index.tsx
src/app-layout/runtime-api.tsx
src/app-layout/utils/use-drawers.ts
src/app-layout/utils/use-resize.tsx
src/app-layout/visual-refresh/context.tsx

Moving Drawers from beta to public. Beta API is still supported via `convertBetaApi` and `as any` type cast on consumers' end. Once the teams using the beta drawers fully migrate, we can delete that part of the code.
This also converts some tests for drawers to the public API whenever it was 1-line change, and adds several new tests, including breaking up `with-drawers` and `with-beta-drawers` test pages.
It adds 3 new AppLayout properties: 
```
drawers?: Array<AppLayoutProps.Drawer>;
activeDrawerId?: string | null;
onDrawerChange?: NonCancelableEventHandler<{ activeDrawerId: string | null }>
```
And 3 new AppLayout ariaLabels:
```
drawers?: string;
drawersOverflow?: string;
drawersOverflowWithBadge?: string;
```
In a separate PR …

feat: Public Drawers

---

src/attribute-editor/styles.scss
src/breadcrumb-group/item/styles.scss
src/internal/components/token-list/styles.scss
src/internal/styles/links.scss
src/link/constants.scss
src/link/styles.scss
src/tag-editor/styles.scss

Check the internal research doc, the people love a heavy offset. This won't fit into the existing variant map, so I had to create a font-size map. And to prevent `text-decoration` from overriding all the little sub-properties, I switched to `text-decoration-line` which is supported by every browser in our support matrix.
Related links, issue #, if available: AWSUI-22009
It's a styling change, and I expect the one big permutation page to collect all the differences.
<details>
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.m …

chore: Increase offset between link text and underline

---

pages/modal/with-dropdowns.page.tsx
src/button-dropdown/utils/use-button-dropdown.ts
src/date-picker/index.tsx
src/date-range-picker/index.tsx
src/internal/components/autosuggest-input/index.tsx
src/internal/components/options-list/__tests__/use-keyboard.test.ts
src/internal/components/options-list/utils/use-keyboard.ts
src/modal/__tests__/modal.test.tsx
src/popover/body.tsx
src/popover/internal.tsx

Prevent Modal from closing on ESC, if there is a dropdown / popover opened inside the modal.
Related links, issue #, if available: AWSUI-22988
New unit test added
<details> …

fix: Do not dismiss modal on ESC if dropdown is opened

---

pages/app-layout/runtime-drawers.page.tsx
pages/app-layout/utils/drawers.tsx
pages/app-layout/utils/external-widget.tsx

Now that Drawer is released, we can update the test pages to use the correct component.
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/ …

chore: Updates test pages to use drawer instead of help panel

---

src/app-layout/__integ__/app-layout-drawers.test.ts
src/app-layout/drawer/index.tsx
src/app-layout/drawer/styles.scss

In classic, the drawer resize handle was scrolling up with the content. This fixes that, and adds a test to avoid regressions in the future.
<details> …

fix: Fixes drawer resize handle scrolling with content

---

src/date-range-picker/__tests__/date-range-picker-absolute.test.tsx
src/date-range-picker/utils.tsx
src/internal/utils/date-time/join-date-time.ts

Normalizes returned value when timeInput is of the format hh
<details> …

fix: DateRangerPicker with hh timeInputFormat

---

src/date-range-picker/__tests__/date-range-picker-absolute.test.tsx
src/date-range-picker/__tests__/date-range-picker-relative.test.tsx
src/date-range-picker/__tests__/date-range-picker.test.tsx
src/date-range-picker/calendar/__tests__/calendar.test.tsx

Remove usage of act as test utils now wrap with act by default.
All tests still pasing
<details> …

chore: Clean up date range picker unit tests

---

src/multiselect/internal.tsx
src/multiselect/styles.scss

Make sure multiselect uses new `disableOuterPadding` property now, as well as adjusting the spacing between multiselect and token group to use a scaled token.
Related links, issue #, if available: AWSUI-23613
<details> …

chore: Use new disableOuterPadding property for Multiselect and update spacing

---

src/table/__integ__/selection.test.ts
src/table/body-cell/styles.scss

Before this change, when selecting the last row on a table in VR
there has been a 1px jump. Caused by the last row which had the same
default border-bottom-height of 2px as all remaining rows.
So when selecting the last row, the padding-bottom got reduced (as for all remaining rows) when selecting to make the available space for increasing the border-bottom-width from 1px to 2px. This caused the jump.
With this change, when selecting the last row it does not adjust the padding-bottom as it’d be needed for all remaining rows. This keeps the table at the same height in VR.
_⚠️ Failing Table permutation tests are expected: Previous state includes the 1px jump when the last row is selected._
**Recording of the changes (focus on the changes in the computed box model when interacting with the …

fix: Table has same height when last row is selected
